### ISSUE TITLE
Componente que pode armazenar multiplos textos semelhante ao <po-multiselect>

### ISSUE THREAD

**Issue by yanric2000** [po-ui/po-angular#1008]
#### Descrição da melhoria
A ideia da feature seria criar um componente semelhante ao <po-multiselect> porem com a capacidade de guardar valores inseridos pelo usuário sem os ter armazenados em uma lista pré-definida, como é o caso do Gmail(em anexo) quando queremos anexar mais de uma pessoa em uma mesma mensagem.

#### Caso de uso
No projeto que estou desenvolvendo um dos parâmetros que podem ser usados para realizar a busca de registros é a "versao". Nela podemos filtrar registros que possuem desde a versão 1(primeira de todas) até a versão N. O controle é feito por baixo dos panos e é inviável tentar mapear qual o maior número que o usuário poderia digitar. Com esse novo componente o usuário poderia dizer que deseja buscar registros com versões específicas, digitando o número que deseja e logo em seguida apertando a tecla Enter.
Outra feature que seria muito bem vinda nesse componente seria um controle feito por regex, idêntico ao que existe no componente <po-input>, assim antes de salvar quaisquer valor poderia ser verificado se o texto digitado pelo usuário é válido, e caso não for exibir uma mensagem de erro.

#### Informações adicionais
Segue abaixo em anexo o exemplo do Gmail:

![exemplo](https://user-images.githubusercontent.com/32688319/133678945-eebf7767-9a95-40e2-b022-0e734d79b313.png)

**Comment by yanric2000** [comment]
Oba boa noite @jhonyeduardo 

Então, o que não me agrada nessa estratégia são dois pontos, o primeiro é a onda de requisições disparadas por parte do usuário. Por exemplo, se forem escolhidas 3 versões diferentes(1,2,3), vão ser disparadas 3 requisições e mais uma quarta que seria para de fato buscar os registros com o filtro aplicado. E o segundo ponto seria que o problema deixaria de ser apenas uma questão de Front(como está sendo tratada atualmente) e passaria a depender de implementações extras do Back, que além do filtro precisariam disponibilizar um endpoint para ser encontrada a versão.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
