### ISSUE TITLE
MENU: Padding entre label e ícone

### ISSUE THREAD

**Issue by alexandreandradeTotvs** [po-ui/po-angular#1018]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Acessar um menu qualquer e retraí-lo.

#### Qual o comportamento atual?

Olá, boa tarde!

Atualizamos recentemente para a versão 5.13.0 para utilizar um novo recurso na Tabela. No entanto, percebemos que o Menu ficou um pouco desconfigurado, como pode ser observado na imagem:
![image](https://user-images.githubusercontent.com/56031606/134406911-ef17894d-455a-4841-bdb9-f231ddcb52b7.png)

Comportamento anterior:
![image](https://user-images.githubusercontent.com/56031606/134407252-500e944f-4626-4fd8-bb2f-d21e937cb1df.png)

Aparentemente não existe padding entre o ícone e a label.

#### Que comportamento você esperava ver?

Um espaçamento entre o ícone e a label do Menu.

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x ] Chrome
  - [x ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @alexandreandradeTotvs, consegue simular este problema em nosso ambiente? https://stackblitz.com/edit/po-ui (atualize as dependencias caso necessario)

Outra situação, a versão do po-style ta de acordo com o po-angular?

Fico no aguardo.

**Comment by alexandreandradeTotvs** [comment]
Olá @jhonyeduardo , muito obrigado. De fato meu po-style estava incorreto.
