### ISSUE TITLE
METODO OU MODO DE ALTERAR CSS DOS COMPONENTS

### ISSUE THREAD

**Issue by wiliammd** [po-ui/po-angular#1022]
#### Descrição da melhoria
Se tivesse como utilizar a classe css que vcs passam para o front 
se tivesse como fazer isso e ele ver a propriedade e sobrescrever seria otimo :D
#### Caso de uso
ex: po-table-column --> por padrão é rigth gostaria de escolher estes tipos de propriedades
.po-table-column {
align-item:center!important
}
#### Informações adicionais
se existe tem como me passar uma doc ou me mandar um email por favor, obrigado! att wiliam.depiro@hotmail.com

**Comment by jhonyeduardo** [comment]
Boa tarde @wiliammd 

Qual seria a situação a resolver? Valores numéricos ficam a direita por uma orientação de UX.

**Comment by wiliammd** [comment]
ok, obrigado pelo feedback

**Comment by jhonyeduardo** [comment]
Qualquer dúvida estou a disposição
