### ISSUE TITLE
Incluir componentes dinamicamente em Table

### ISSUE THREAD

**Issue by fabianofss** [po-ui/po-angular#1025]
**Descrição da melhoria**
Tenho situações onde exibo ordens de serviço em um box (cada box é uma row na table), existe uma forma de tornar cada ordem um button ou um link usando componente po.ui ou HTML?

**Caso de uso**
Hoje minha table está assim:
![Captura2021-09-27 112602](https://user-images.githubusercontent.com/17128503/134928146-b1987e53-860c-4ad9-a314-fd0894cc70b5.png)

Gostaria de tornar algo mais parecido com isso:
![Captura2021-09-27 112713](https://user-images.githubusercontent.com/17128503/134928333-575191bf-9803-4ab2-b51d-c92943f44328.png)

**Comment by jhonyeduardo** [comment]
Bom dia @fabianofss 

Temos a diretiva [PoTableCellTemplate](https://po-ui.io/documentation/po-table-cell-template), na qual você terá liberdade de incluir o que deseja.

Veja também nos exemplos do PoTable: https://po-ui.io/documentation/po-table

Qualquer dúvida estou a disposição.

**Comment by fabianofss** [comment]
> Bom dia @fabianofss
> 
> Temos a diretiva [PoTableCellTemplate](https://po-ui.io/documentation/po-table-cell-template), na qual você terá liberdade de incluir o que deseja.
> 
> Veja também nos exemplos do PoTable: https://po-ui.io/documentation/po-table
> 
> Qualquer dúvida estou a disposição.

A customização deu certo,
muito obrigado.

**Comment by jhonyeduardo** [comment]
Qualquer dúvida estou a disposição.
