### ISSUE TITLE
<po-decimal>: <demora para mais de um minuto para executar (p-change)>

### ISSUE THREAD

**Issue by wiliammd** [po-ui/po-angular#1032]
Projeto muito extenso para executar...

#### Qual o comportamento atual?
<po-decimal> (p-change) demora mais de um minuto para executar minha função após sair do campo

#### Que comportamento você esperava ver?
quando sair do campo executar a função...

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @wiliammd 

Consegue simular pra gente?

Fiz um teste no stackblitz e esta disparando normalmente: https://stackblitz.com/edit/po-ui-alrcbk?file=src%2Fapp%2Fapp.component.ts

**Comment by wiliammd** [comment]
você tem skype ou email para eu dar acesso a minha maquina pra te mostrar o projeto?

**Comment by wiliammd** [comment]
eu resolvi com utilizando o p-blur ja que o p-change realmente demora muito tempo para executar a função

**Comment by jhonyeduardo** [comment]
Olá @wiliammd 

Tudo bem.

Como resolveu seu problema e não encontramos a evidencia do problema, fecharemos a issue, Obrigado!

**Comment by wiliammd** [comment]
beleza, porém o p-change está com problemas
po version 5.8.0
angular version 12.2.0

**Comment by jhonyeduardo** [comment]
Boa tarde @wiliammd 

Por favor, nos enviar a simulação para que possamos corrigir a situação.

Temos um ambiente montado para auxilia-lo: https://stackblitz.com/edit/po-ui-alrcbk?file=src%2Fapp%2Fapp.component.html
