### ISSUE TITLE
Campo de pesquisa do po-page-dynamic-table utiliza o parâmetro search que não é previsto no guia de API 

### ISSUE THREAD

**Issue by raphasoares** [po-ui/po-angular#1035]
#### Descrição da melhoria
Atualmente o campo de pesquisa do componente po-page-dynamic-table inclui na url de pesquisa o campo search, que não é previsto no guia de API totvs. 
Sugiro que, em vez de incluir o parâmetro automáticamente, seja possivel relacionar uma propriedade da table ao campo de pesquisa, desta forma, gerando uma url que é prevista no guia.

#### Caso de uso
Atualmente a url gerada é: https://20660202-2a26-45b0-9aba-aee013b692c2.mock.pstmn.io/servers?page=1&pageSize=10&search=teste. Desta forma, seria necessário um tratamento especifico no endpoint para a tela. Na proposta a url passaria a ser: https://20660202-2a26-45b0-9aba-aee013b692c2.mock.pstmn.io/servers?page=1&pageSize=10&name=teste, onde 'name' é uma das propriedades do modelo do endpoint. Desta forma não haverá a necessidade de um tratamento especifico para o componente, considerando que o guia de API já preve que todas as APIs devem atender a esse filtro. 

#### Informações adicionais
A sugestão é baseada no documento https://tdn.totvs.com/display/public/INT/Guia+de+implementacao+das+APIs+TOTVS#GuiadeimplementacaodasAPIsTOTVS-Par%C3%A2metrosexpans%C3%ADveis

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
