### ISSUE TITLE
Inclusão da propriedade e dos campos para configuração do intervalo de execução de tarefas do JobScheduler v1.1

### ISSUE THREAD

**Issue by raphasoares** [po-ui/po-angular#1036]
#### Descrição da melhoria
Implementar a propriedade 'rangeExecutions' à estrutura do modelo da API JobScheduler e permitir a configuração do intervalo no componente po-page-job-scheduler

#### Caso de uso
Permitira a utilização do novo componente da API JobScheduler na V1.1

#### Informações adicionais
Conforme documentação disponível em https://api.totvs.com.br/apidetails/JobScheduler_v1_100.json

**Comment by alinelariguet** [comment]
Funcionalidade já disponibilizada no componente. Verifique o changelog.
