### ISSUE TITLE
Permitir a utilização do componente po-page-job-scheduler mesmo sem o endpoint 'process'

### ISSUE THREAD

**Issue by raphasoares** [po-ui/po-angular#1037]
#### Descrição da melhoria
Permitir que seja passado como parâmetro para o componente po-page-job-scheduler o objeto com as configurações do step Parametrização. Quando informado o objeto de parâmetro, sugiro que o campo processo deixe de ser exibido. 

#### Caso de uso
No caso ERP Datasul, utilizamos diferentes telas para cada um dos processos. Desta forma o componente não atende a necessidade do ERP porque a lista de processos será extensa e obrigará os clientes a saberem exatamente o nome do relátorio, não apenas o 'caminho no menu' de onde ele se encontra. 
Com a modificação, caso o objeto de parâmetros seja informado, não haverá a necessidade do usuário informar o processo, assim sendo possível criar telas especificamente para 1 único processo.

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

**Comment by alinelariguet** [comment]
Funcionalidade já disponibilizada no componente. Verifique o changelog.
