### ISSUE TITLE
page-dynamic-detail: exibir propriedades disponíveis na interface PoPageDynamicTableDetailField

### ISSUE THREAD

**Issue by jhonyeduardo** [po-ui/po-angular#1042]
**Descrição:**
Atualmente a interface `PoPageDynamicTableDetailField` não exibe todas as propriedades disponíveis na documentação do portal.

https://po-ui.io/documentation/po-page-dynamic-detail

**Especificação:**
Alterar documentação da interface, adicionando as tags que faltam para todas as propriedades serem exibidas.

Adicionar as tags @docsExtends e @ignoreExtendedDescription, conforme a documentação de [HOW TO DOCUMENT](https://github.com/po-ui/po-angular/blob/master/HOW_TO_DOCUMENT.md#extends)

Exemplo de implementação:
```
/**
 * @docsExtends PoDynamicViewField
 * 
 * @usedBy PoPageDynamicDetailComponent
 *
 * @ignoreExtendedDescription
 * 
 * @description
 *
 * Interface dos fields usados para compor o template `po-page-dynamic-detail`.
 */
```
  
    
  **Critérios de aceite:**
  - [Commits no padrão](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md);
  - Documentação;

**Comment by mauromattos00** [comment]
Fala @jhonyeduardo! Posso ficar com essa task, pls?

**Comment by jhonyeduardo** [comment]
Bom dia @mauromattos00, fique a vontade em contribuir conosco :)

**Comment by mauromattos00** [comment]
@jhonyeduardo, pelo que eu entendi, essa interface é estendida de outras que já possuem outras propriedades. A intenção aqui é inserir somente as linhas que você especificou ali no exemplo?

**Comment by jhonyeduardo** [comment]
@mauromattos00 Exato, falta apenas as tags mencionadas no item, pois as propriedades ja existem.
