### ISSUE TITLE
PO-TABLE: Consumo de CPU ao utilizar Table Row Template 

### ISSUE THREAD

**Issue by alexandreandradeTotvs** [po-ui/po-angular#1049]
#### Reprodução
https://po-ui-swzyea.stackblitz.io

Passos para reproduzir:
1.  Foi criado no exemplo (https://po-ui-swzyea.stackblitz.io) uma tabela com uma row template, a qual utiliza o método (getTexto ) para realizar o tratamento de um determinado dado.
2. Expanda o primeiro item da tabela (mantenha ele expandido até o fim do teste)
3. Role o scroll para o fim da página
3. Passe o cursor do mouse sobre qualquer informação em qualquer coluna.
4. Verifique no console que o método getTexto é executado.
5. Verifique por meio do gerenciador de tarefas do Windows o consumo de CPU enquanto move o mouse sem parar nas informações de qualquer coluna.

#### Qual o comportamento atual?

Um alto consumo de CPU, levando o navegador a travar.

#### Que comportamento você esperava ver?

Verificar a possibilidade de baixar o consumo de CPU para viabilizar a utilização de templates.

#### Ambiente

- PO UI: 5.13.0
- Angular: 12.0.1
- Browser(s):
  - [x ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @alexandreandradeTotvs 

Obrigado pela abertura desta issue, vamos analisar a situação a fim de melhorar performance do componente.

**Comment by jhonyeduardo** [comment]
Entendemos que componente PoTable é um componente complexo e possui alguns situações a serem melhoradas, mas como curto prazo, veja a sugestão para resolver este problema:

Para melhorar a situação apliquei estrategia de OnPush, com isso melhora muito a execução desnecessária da função 'getTexto'.

https://stackblitz.com/edit/po-ui-odabvr?file=src%2Fapp%2Fapp.component.html

**Comment by alinelariguet** [comment]
Boa noite @alexandreandradeTotvs,

Deu certo? Podemos encerrar essa issue?

**Comment by alinelariguet** [comment]
Como não tivemos mais resposta estou fechando esta issue.
Att.
