### ISSUE TITLE
Toolbar

### ISSUE THREAD

**Issue by bessajonathan** [po-ui/po-angular#1050]
#### Descrição da melhoria
Possibilitar a inclusão de dados/descrições no toolbar.
Principalmente a inclusão de TAG

#### Caso de uso
![image](https://user-images.githubusercontent.com/54686186/136109230-d0630972-7634-4228-921b-b3533eae1b2d.png)

#### Informações adicionais
Seria interessante se o PO permitisse a personalização da toolbar.
Hoje as opções existentes são poucas.

Segue abaixo um exemplo:
Ali na opção do plano eu não consigo adicionar uma tag

![image](https://user-images.githubusercontent.com/54686186/136109175-60702c1c-779e-4776-8c4f-fd5deb54a448.png)

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
