### ISSUE TITLE
Navbar

### ISSUE THREAD

**Issue by bessajonathan** [po-ui/po-angular#1052]
#### Descrição da melhoria
Gostaria que fosse possível usar o profile da toolbar juntamente com a navbar.

#### Caso de uso
Isso possibilitaria outra opção de menu.Pois nem sempre a opção lateral é a melhor.
Também seria interessante se fosse possível adicionar um grupo na navbar e os sub-links abaixo

#### Informações adicionais
Segue exemplo da navbar disponível hoje
![image](https://user-images.githubusercontent.com/54686186/136208582-0cfa50e8-51c6-45ba-9907-3029b59bd994.png)
Segue exemplo da toolbar
![image](https://user-images.githubusercontent.com/54686186/136208729-29b68697-ad3b-4719-805c-9d418bd15705.png)

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
