### ISSUE TITLE
po-combo: Labels iguais com Value diferente não sendo exibido

### ISSUE THREAD

**Issue by RBalconi** [po-ui/po-angular#1065]
#### Reprodução

https://stackblitz.com/edit/po-ui-4qvxe4?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/18688446/137983421-cc3e7e8e-7c3c-48a4-a515-4293f9047ab7.png)

Passos para reproduzir:
1. Crie um ``po-combo``
2. Nesse ``po-combo``, insira um ``p-options`` com o ``value`` unico e o ``label`` repetido
``` 
    [p-options]="[
      { value: 'Foo', label: 'Bar' },
      { value: 'Foo1', label: 'Bar' }
    ]"
```

#### Qual o comportamento atual?
O ``po-combo`` exibe apenas um option, mesmo os ``value`` sendo unicos.

#### Que comportamento você esperava ver?
O ``po-combo`` exibisse os options corretamente.

#### Ambiente

- PO UI: 5.16.0
- Angular: 12.1.1
- Browser(s):
  - [x] Chrome
  - [x] Firefox
- Operating System:
  - [x] Windows
  - [x] Mint

**Comment by RBalconi** [comment]
Bom dia @jhonyeduardo 

Estávamos tentando utilizar de uma forma parecida, unica diferença que os dados vinha do banco de acordo com os registros que o usuário fizer na tabela X.

Imagina o seguinte: O usuário fez uma inserção na tabela ``receipt`` de duas receitas, as duas com o **nome** "macarrão", porem a **descrição** de cada uma são diferente, no po-combo só aparecerá um "macarrão" para selecionar (mesmo o ``value`` sendo único, no caso o ``id`` do banco).

**Comment by alinelariguet** [comment]
Boa noite @RBalconi,
Obrigada pelas informações, porém nesse caso não haveria um problema para o usuário que não saberia qual das duas opções escolher? Do ponto de vista da acessibilidade eu acho que permitir 2 opções com labels iguais pode gerar problemas. Não seria o caso de usar o componente po-lookup onde é possível ver outros dados do registro para selecioná-lo?

**Comment by dycorrales** [comment]
No meu caso estou com o mesmo problema, o questionamento que @alinelariguet fez é pertinente, mas eu por exemplo estou mostrando as opções dentro de um template, sendo que tenho um nodo pai diferente para um grupo de opções, podemdo repetir a opção por cada nodo pai diferente, neste caso o comportamento do componente segue sendo de mostrar a opção com mesmo label uma vez só :(

**Comment by alinelariguet** [comment]
Corrigido e entregue na v6.10.0 liberada hoje. :)
