### ISSUE TITLE
<po-combo>: <Quero popular o meu p-field-label e p-field-value usando um array>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#1066]
#### Reprodução

https://stackblitz.com/edit/po-ui-nxdg14?file=src%2Fapp%2Fapp.component.ts

Passos para reproduzir:
1. 
2. 

#### Qual o comportamento atual?
Quero popular o meu p-field-label e p-field-value usando um array do p-options, porém não consigo fazer isso diretamente, apenas usando o array nativo com label e value.

#### Que comportamento você esperava ver?
Conseguir colocar em prática os exemplos que estão na documentação, de poder acessar meu array com os valores originais da varável que são retornados da API.

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Funcionalidade liberada no componente. Verificar changelog.
