### ISSUE TITLE
Tree View Customizável

### ISSUE THREAD

**Issue by ricmello** [po-ui/po-angular#1069]
#### Descrição da melhoria
Permitir a utilização de templates para customizar os itens do componente Tree View.

#### Caso de uso
Com isso, poderíamos criar árvores editáveis e/ou com conteúdo personalizado (ex.: po-tag com o status em cada nó) para interfaces mais ricas.

#### Informações adicionais
O comportamento seria similar ao do [Angular Material](https://material.angular.io/components/tree/examples)

**Comment by jhonyeduardo** [comment]
Boa tarde @ricmello 

Obrigado pela sugestão, vamos adicionar em nosso backlog.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
