### ISSUE TITLE
Duvida subItems do componente menu não tem propriedade icon?

### ISSUE THREAD

**Issue by wiliammd** [po-ui/po-angular#1073]
Duvida subItems do componente menu não tem propriedade icon?
não tem como adicionar icones nos subItems do menu po-ui?

**Comment by jhonyeduardo** [comment]
Boa tarde @wiliammd 

Quando tiver duvidas, por favor utilizar o [Github Discussions](https://github.com/po-ui/po-angular/discussions).

Atualmente os ícones são exibidos apenas no primeiro nível de menus, por uma decisão de UX, conforme informado na propriedade icon do PoMenuItem.
