### ISSUE TITLE
<po-page-edit>: <bug ao escrever um html no Rich Text>

### ISSUE THREAD

**Issue by Feeh03114** [po-ui/po-angular#1080]
#### Reprodução

https://po-ui-bmytsq.stackblitz.io
https://stackblitz.com/edit/po-ui-6cqatb?file=src/app/etiqueta/etiqueta-form.component.html

Passos para reproduzir:
1. 
html
`
<po-page-edit p-title="Etiqueta" (p-save)="save()" (p-cancel)="cancel()" (p-save-new)="saveNew()">
    <po-tabs p-small>
        <po-dynamic-form #dynamicForm [p-value]="model" [p-fields]="fields">
        </po-dynamic-form>
        <po-rich-text name="Etiqueta" [(ngModel)]="txt" [p-height]="height" p-label="Etiqueta Layout" p-readonly
            (p-change)="changeEvent('p-change')" (p-change-model)="changeEvent('p-change-model')">
        </po-rich-text>
        <div class="po-row">
            <po-textarea class="po-md-6" name="HLTML Etiqueta" [(ngModel)]="txt" p-label="HLTML Etiqueta" p-rows="18"
                p-required>
            </po-textarea>
            <po-textarea class="po-md-6" name="Aviso" [(ngModel)]="Aviso" p-readonly p-label="Aviso" p-rows="18">
            </po-textarea>
        </div>
    </po-tabs>
</po-page-edit>
`
.ts
`
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Component, OnInit, ViewChild } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { PoDialogService, PoDynamicFormComponent, PoNotificationService } from '@po-ui/ng-components';

import { PoPageDynamicEditActions, PoPageDynamicEditField } from '@po-ui/ng-templates';
import { concat, EMPTY, Observable, Subscription } from 'rxjs';
import { map, tap } from 'rxjs/operators';

const actionInsert = 'insert';
const actionUpdate = 'update';

const headers = new HttpHeaders({
  'X-PO-SCREEN-LOCK': 'true',
});

@Component({
  selector: 'app-etiqueta-form',
  templateUrl: './etiqueta-form.component.html',
  styleUrls: ['./etiqueta-form.component.css']
})
export class EtiquetaFormComponent implements OnInit {
  @ViewChild(PoDynamicFormComponent, { static: true })
  dynamicForm: PoDynamicFormComponent;

  formAction = actionInsert;
  modalAction = actionInsert;
  readonly subscriptions: Subscription[] = [];
  model: any = {};
  fields = [];
  errorMessage: string;
  event: string;
  help: string;
  height: number=500;
  label: string;
  placeholder: string;
  properties: Array<string>;
  txt: string;
  modelo:string = `<html><style>*{margin: 0;padding: 0;}</style><body>{#####}</body></html>`;
  Aviso:string = `
  No HTML coloque
  #price# = preço,
  #code# = código do produto,
  #url#  = url da imagem,
  #description# = descrição do prodtuo
  ` ;
  
  

  constructor(
    private readonly http: HttpClient,
    private readonly activatedRoute: ActivatedRoute,
    private readonly poDialog: PoDialogService,
    private readonly poNotification: PoNotificationService,
    private readonly router: Router
  ) { }

  ngOnInit() {
    this.loadDataFromApi();
    this.restore();
  }

  changeEvent(event: string) {
    console.log(event)
    this.event = event;
  }

  get isUpdateOperation() {
    return this.formAction === actionUpdate;
  }

  restore() {
    this.txt = '';
  }

  cancel(){
    if (this.dynamicForm && this.dynamicForm.form.dirty) {
      this.poDialog.confirm({
        message: 'Tem certeza que deseja cancelar esta operação?',
        title: 'Cancelar',
        confirm: () => this.router.navigate(['/etiqueta']),
      });
    } else {
      this.router.navigate(['/etiqueta']);
    }

  }

  saveNew(){
    this.saveOperation();
    /* const saveOperation$ = this.saveOperation();

    this.subscriptions.push(
      saveOperation$.subscribe((message) => {
        this.poNotification.success(message);
        this.router.navigate(['/documento-entrada/new']);
      })
    ); */
  }
  
  save(){
    this.saveOperation();
     /*const saveOperation$ = this.saveOperation();

    this.subscriptions.push(
      saveOperation$.subscribe((message) => {
        this.poNotification.success(message);
        this.router.navigate(['/documento-entrada']);
      })
    ); */
  }

  private loadDataFromApi() {
    const { serviceApi } = this.activatedRoute.snapshot.data;
    const { id } = this.activatedRoute.snapshot.params;
    if (serviceApi) {
      const fields$ = this.getFields(serviceApi, id);

      const data$ = this.loadData(serviceApi, id);

      this.subscriptions.push(
        concat(fields$, data$).subscribe()
      );
    }
  }
  private saveOperation(){//: Observable<any> {
    const { serviceApi } = this.activatedRoute.snapshot.data;
    const { id } = this.activatedRoute.snapshot.params;

    const successMsg = id
      ? 'Recurso atualizado com sucesso.'
      : 'Recurso criado com sucesso.';

    const html_etiqueta = this.modelo.replace('{#####}', this.txt)

    const model = {
      ...this.model,
      html_etiqueta: html_etiqueta
    };
    console.log(model)
    /* const saveOperation$ = this.isUpdateOperation
      ? this.http.put(serviceApi + `/${id}`, model, {
          headers,
        })
      : this.http.post(serviceApi, model, {
          headers,
        });

    return saveOperation$.pipe(map(() => successMsg)); */
  }

  private loadData(serviceApi: string, id: number): Observable<any> {
    if (!id) {
      this.model = {};
      this.formAction = actionInsert;
      return EMPTY;
    }

    this.formAction = actionUpdate;

    return this.http
      .get(serviceApi + `/${id}`, {
        headers,
      })
      .pipe(tap((response) => (this.model = response)));
  }

  private getFields(serviceApi: string, id: number): Observable<any> {
    const metadataType = id ? 'edit' : 'create';
    return this.http
      .get(`${serviceApi}/metadata?type=${metadataType}`, { headers })
      .pipe(
        tap((response) => {
          this.fields = response.fields;
        })
      );
  }

}

`
2. 
escrever um html no Textarea

#### Qual o comportamento atual?
[Video mostrando o comportamento atual](https://youtu.be/sGrEkRZVlW4)

#### Que comportamento você esperava ver?
Que quando mudasse a fonte ou html não afetasse na janela do sistema

#### Ambiente

- PO UI: 5.4.0
- Angular: 12.2.9
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @Feeh03114 

Obrigado por abrir esta issue, vamos avalia-lo e retornar assim que possível.

**Comment by alinelariguet** [comment]
Bom dia ,
Se você usar dessa forma aqui `<span style=“font-size: 30px;”>Felipe</span>` ocorre o mesmo problema?

**Comment by Feeh03114** [comment]
Contornei isso usando o Code Editor
