### ISSUE TITLE
[po-table] Suporte para objetos aninhados

### ISSUE THREAD

**Issue by afucher** [po-ui/po-angular#1081]
#### Descrição da melhoria
Hoje só conseguimos usar no `po-table` objetos simples, gostaria de ter suporte para mostrar valores de propriedades de objetos aninhados

#### Caso de uso
Ao começar a trabalhar com dados mais complexos, fica muito ruim ter que ficar transformando os dados para um objeto mais simples. 

#### Informações adicionais
Fiz um exemplo de como imagino que poderia ser: https://stackblitz.com/edit/po-ui-nggbvm?file=src/app/app.component.ts
```
colunas = [
    { property: 'prop1', label: 'Prop1' },
    { property: 'obj.prop2', label: 'Prop2' },
  ];

  items = [{ prop1: 'prop1', obj: { prop2: 'prop2' } }];
 ```

**Comment by jhonyeduardo** [comment]
Boa tarde @afucher 

Obrigado pela sugestão,
Hoje já temos a #132 para realizar esta melhoria, vamos verificar para incluir nas próximas versões, visto que é uma funcionalidade já solicitada.

Qualquer dúvida, estamos a disposição.

**Comment by alinelariguet** [comment]
Boa noite, esta funcionalidade foi incluída e publicada na v6.0.0.
Att.
