### ISSUE TITLE
po-page-list: valor incoreto no p-container

### ISSUE THREAD

**Issue by MarcosEllys** [po-ui/po-angular#1083]
#### Reprodução

Utilize o repositório (https://github.com/MarcosEllys/poui-page-list) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Iniciar um novo projeto Angular
2. Adicionar o PO UI Components -> ng add @po-ui/ng-components
3. Adicionar PO UI Templates -> ng add @po-ui/ng-templates
4. Adicionar o Schematics do PO Page List -> ng generate @po-ui/ng-components:po-page-list
5. Selecionar **PO Table     [ https://po-ui.io/documentation/po-table     ]**
6. Inciar a aplicação com npm ou yarn

#### Qual o comportamento atual?

No template src\app\page-list\page-list.component.html
```html
[p-container]="true"
```

#### Que comportamento você esperava ver?

No src\app\page-list\page-list.component.html o p-container recebendo uma variável
```html
[p-container]="container"
```

No src\app\page-list\page-list.component.ts a variável **container** especificando os tipos aceitos conforme a documentação com literal types.

```typescript
container: 'border' | 'shadow' = 'border';
```

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by MarcosEllys** [comment]
Se for planejado alguma mudança/melhoria eu me habilito para implementa-la 😁.

Uma sugestão também seria tipar container em PoTableBaseComponent:391, caso o container fosse tipado, esse tipo poderia ser exportado e teriamos o tipo correto do container centralizado.

**Comment by alinelariguet** [comment]
Olá @MarcosEllys ,
A funcionalidade seria desenvolvida sim no po-table, observe que o ng generate utilizado simplesmente inclui um po-table dentro do componente po-page-list. Porém eu não entendi o bug em si. Houve uma limitação no componente?
