### ISSUE TITLE
Permitir mensagens de erro no componentes de input baseado em outros critérios

### ISSUE THREAD

**Issue by vrrafael** [po-ui/po-angular#1084]
#### Descrição da melhoria
O componente _input_ permite definir uma mensagem de erro (_p-error-pattern_) que é exibida quando o atributo _pattern_ ou _mask_ não são satisfeitos. Seria interessante permitir uma lista _[{mensagem: criterio}]_ para cobrir outras situações.

#### Caso de uso
Imagine dois campos IP para definir uma faixa para DHCP que devem obedecer as seguintes regras:
- Valor entre 1 e 254 (considerando classe C). Ex: 192.168.100.25
- O valor deve estar na mesma faixa que o gateway. Ex. gateway 192.168.100.1 e DHCP 192.168.200.20:192.168.200.60 resulta em erro.

Atualmente não é possível exibir mensagens de erro quando uma das regras é quebrada.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
