### ISSUE TITLE
Lookup: Não remove valores quando utilizado multi-select

### ISSUE THREAD

**Issue by bessajonathan** [po-ui/po-angular#1086]
#### Qual o comportamento atual?
![image](https://user-images.githubusercontent.com/54686186/139961866-16d66dfa-4ffd-4674-8730-9ef1c511c4cd.png)

Após selecionar mais de um valor no lookup e setar a váriavel como null ou [] o campo não é limpo.

#### Que comportamento você esperava ver?
Após setar o valor do ngModel como null deveria limpar os items selecionados.
![image](https://user-images.githubusercontent.com/54686186/139961832-9b8123f5-08e3-436a-8d24-879ceefc7afb.png)

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [ x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @bessajonathan 

Obrigado pela abertura dessa issue, vamos atuar para resolver o problema.

**Comment by alinelariguet** [comment]
Já foi corrigido e foi publicado na v5.21.0.
