### ISSUE TITLE
Possibilitar incluir hint no título do po-widget

### ISSUE THREAD

**Issue by alvarocamillont** [po-ui/po-angular#109]
Bom dia,

No componente po-widget (https://portinari.io/documentation/po-widget) eu preciso poder colocar um hint quando o usuário fizer um hover sobre o titulo do card.
Esse hint pode ser padrão (propriedade title do html) ou customizado (https://www.w3schools.com/css/css_tooltip.asp)

Grato

**Comment by samir-ayoub** [comment]
Boa tarde, Álvaro,

Vamos adicionar este item em nosso backlog e o PO irá avaliar sua sugestão,
qualquer dúvida nos acione!

PS: Você pode paliativamente incluir um tooltip no próprio card se isso não atrapalhar seu projeto.

**Comment by alvarocamillont** [comment]
Sem problemas!

**Comment by renanarosario** [comment]
Devido à falta de interação e ao fato de ser uma issue antiga, estamos encerrando esta issue.
