### ISSUE TITLE
[po-page-dynamic-table] Duvida infinite-scroll

### ISSUE THREAD

**Issue by PauloPenalva** [po-ui/po-angular#1092]
Como ativar o infinite-scroll da po-table no componente po-page-dynamic-table ?

**Comment by alinelariguet** [comment]
No momento essa funcionalidade não foi repassada ainda para o componente po-page-dynamic-table.

**Comment by alinelariguet** [comment]
Nesse caso, você deseja manter essa issue em aberto para solicitação da funcionalidade? Também incentivamos contribuições, se for do seu interesse, estamos a disposição.

**Comment by wsteixeira** [comment]
Boa noite,

@alinelariguet, gostaria de contribuir neste issue.
