### ISSUE TITLE
po-field: Permitir que a aplicação controle quando importar HttpClientModule

### ISSUE THREAD

**Issue by siegklenes** [po-ui/po-angular#1093]
#### Descrição da melhoria
Na base de código, alguns módulos, como po-field, po-i18n, importam o módulo junto HttpClientModule. Como mais de um HttpClientModule é fornecido como efeito colateral de import dos módulos citados, mais de uma instância de HttpClient acaba sendo fornecida pela aplicação, o que para a maioria dos cenários, apenas uma única configuração de HttpClient com interceptors no AppModule é suficiente . Como efeito colateral de importar o PoFieldModule ou PoI18nModule, fica obrigatório para a aplicação repetir o import de módulos que fornecem interceptors de amplo uso, como interceptor para injeção de token de autenticação.
O efeito colateral é descrito também na documentação do angular https://angular.io/guide/http#provide-the-interceptor

#### Caso de uso
Permite um código mais limpo(Interceptors e HttpClientModule declarado apenas em um ponto, remove necessidade de um módulo compartilhado para evitar duplicação)
Permite um controle maior da aplicação, apenas se ela necessitar de mais de uma contexto de HttpClientModule ela importa.
Menos contextos para manter, menor consumo geral da aplicação.

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

**Comment by yantotvs** [comment]
+1
