### ISSUE TITLE
MultiSelectService no dynamicForm e no Multiselect

### ISSUE THREAD

**Issue by Feeh03114** [po-ui/po-angular#1098]
### Discussed in https://github.com/po-ui/po-angular/discussions/1097

<div type='discussions-op-text'>

<sup>Originally posted by **Feeh03114** November 16, 2021</sup>
Estou criando um Multiselect usando um request mas ficou muito sobrecarregado por se tratar de muitas linhas, então queria sugerir essa melhoria se possível de ter essa função direto no metadata ou no componente com o recurso de paginação, assim não deixa lento o recurso.

Html - Multiselect
`
<po-multiselect class="po-md-12" [name]="name_multselect" [(ngModel)]="model.multselect"
    [p-label]="name_View" [p-options]="items_multselect" p-optional [p-disabled]="!Hasmultselect">
</po-multiselect>
`

request dos items- Multiselect
`
 items_multselect: Array<PoCheckboxGroupOption> = [{value: '00', label: 'test'}]
 private getitems(optionsService: string): Observable<any> {
    return this.http.get(optionsService).pipe(
      map((res: Array<PoCheckboxGroupOption>) => {
        this.items_multselect = res;
      })
    );
  }
`</div>

**Comment by alinelariguet** [comment]
Estamos implementando a funcionalidade do multiselect com serviço no componente po-dynamic-form, será publicado na próxima release

**Comment by Feeh03114** [comment]
Olá, vi que foi colocado o multiselect com serviço, porém não tem paginação, isso deixa o multiselect muito lento e sobrecarregado.

**Comment by h2danilo** [comment]
Boa Tarde,

Também notei problema acima!

**Comment by alinelariguet** [comment]
Obrigada por reportar, vamos analisar e em breve daremos um retorno.
