### ISSUE TITLE
PO Upload: Problema ao arrastar arquivo

### ISSUE THREAD

**Issue by cmregazzo** [po-ui/po-angular#1100]
#### Reprodução

Passos para reproduzir:
1. Arraste de forma rápida, um arquivo para a pagina conde consta o po-upload.

#### Qual o comportamento atual?
Dependendo da "velocidade" que o arquivo é arrastado para dentro do po-upload, o arquivo em vez de ir para área de Upload, é aberto no navegador. Só consegui reproduzir tal problema no Chrome.

Segue o link demonstrando o problema utilizando a página padrão de demonstração de componentes do PO-UI:

https://drive.google.com/file/d/1cLXldEyxFYBalzgKt8_Dyyn7C6LtCWju/view?usp=sharing

#### Que comportamento você esperava ver?
O comportamento esperado é o arquivo ir para área de upload ou a mensagem informando que o arquivo não foi inserido em local correto.

#### Ambiente

- PO UI: 5.5.0
- Angular: 12.1.3
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
