### ISSUE TITLE
po-combo: Não aceita a instrução ngModel no HTML

### ISSUE THREAD

**Issue by thiagosantostotvs** [po-ui/po-angular#1103]
Passos para reproduzir:
1. Criar um projeto angular com PO-UI conforme o guia com os primeiros passos.
2. Adicionar no app.component.html um po-combo ou po-select apontando no ngModel para uma variável do componente.

#### Qual o comportamento atual?
Apresenta o erro abaixo ao executar a instrução "ng build" ou "ng serve".
_Error: src/app/app.component.html:6:16 - error NG8007: The property and event halves of the two-way binding 'ngModel' are not bound to the same target._

#### Que comportamento você esperava ver?
Compilar o projeto sem problemas.

#### Ambiente

- PO UI: 5.21.0
- Angular: 12.0.1
- Browser(s):
  Problema na compilação antes de apresentar a tela do browser.

- Operating System:
  Problema na compilação

Segue abaixo o projeto criado para simular o problema.
[my-po-project.zip](https://github.com/po-ui/po-angular/files/7571770/my-po-project.zip)
.

**Comment by pedroballona** [comment]
Problema ocorrendo também com o seguinte na seguinte versão:

- PO UI: ^5.22.0
- Angular: ^12.0.1

**Comment by alinelariguet** [comment]
Esta issue está em análise e logo publicaremos uma correção. Uma forma paliativa de contornar a situação é alterar o arquivo tsconfig.json:
"angularCompilerOptions": { "strictTemplates": false }

**Comment by pedroballona** [comment]
> Esta issue está em análise e logo publicaremos uma correção. Uma forma paliativa de contornar a situação é alterar o arquivo tsconfig.json: "angularCompilerOptions": { "strictTemplates": false }

obrigado pelo retorno

**Comment by alinelariguet** [comment]
Bom dia, 
Identificamos que não se trata de um bug, é somente uma melhoria na nossa documentação. Já fizemos o ajuste e a documentação já está disponível no nosso portal conforme abaixo:

Na versão 12.2.0 do Angular a verificação strictTemplates vem true como default. Portanto, para utilizar two-way binding no componente deve se utilizar da seguinte forma:

```
<po-select ... [ngModel]="selectModel" (ngModelChange)="selectModel = $event"> </po-select>

**Comment by quaresma-cq** [comment]
> [ngModel]="selectModel"

Boa noite,

Na documentação do po-select aparece como  **[(ngModel)]="select"**. Nesse caso está desatualizado também?

![Image](https://github.com/user-attachments/assets/c2f4abb8-e43a-423e-b6f9-b2addd8012e1)
