### ISSUE TITLE
Alteração no filtro do po-page-dynamic-table

### ISSUE THREAD

**Issue by haidicarolina** [po-ui/po-angular#1105]
#### Descrição da melhoria
Atualmente não é possível alterar o place-holder do filtro rápido ao utilizar po-page-dynamic-table, dessa forma o usuário não sabe por qual campo a pesquisa rápida fará a busca. Além disso, a pesquisa rápida sempre envia uma requisição com o queryParam no formato "search=ValorPesquisado", este formato não esta previsto no guia de api da totvs, 
Sugestões:
- Ser possível informar qual campo será utilizado para o filtro rápido e ser enviado a requisição com o 'property' do campo ao invés da palavra genérica 'search'.
- Ser configurável algo como um "beforeSearch" que será executado antes da realização da pesquisa permitindo manipular a requisição que será enviada. Sobre esta opção, seria interessante se também contemplasse o filtro avançado.

#### Caso de uso
Filtro rápido atendendo as api's existentes.

**Comment by alinelariguet** [comment]
Boa tarde @haidicarolina,
Obrigada pela sugestão. Vamos incluir essa issue no nosso backlog.
Att.
