### ISSUE TITLE
Alteração para atualizar em mais momentos os dados da po-page-dynamic-table 

### ISSUE THREAD

**Issue by haidicarolina** [po-ui/po-angular#1106]
#### Descrição da melhoria
Possibilidade de atualizar os dados do po-page-dynamic-table a qualquer momento, exemplo: que pudesse ser feita uma nova requisição a qualquer momento e que ao fazer, atualizasse os dados da tabela. Atualmente, os dados da tabela só são atualizados por meio da utilização dos filtros. 

#### Caso de uso
Implementar uma ação customizada que remove ou adiciona uma nova linha na tabela.
Implementar um botão customizado de "Atualizar" que faz uma nova requisição com intuito de atualizar os dados da tabela. 
Nestes casos as funcionalidades não atualizam os dados da tabela e por isso o usuário não possui certeza que sua ação 'funcionou'

#### Informações adicionais
Não há

**Comment by alinelariguet** [comment]
Boa tarde @haidicarolina
Obrigada pela sugestão. Vamos incluir essa issue no nosso backlog.
Att.

**Comment by alinelariguet** [comment]
Boa tarde @wsteixeira está issue já está em desenvolvimento internamente. Obrigada pela disposição.

**Comment by wsteixeira** [comment]
olá @jcorrea97,

A PR #1224 não fechou a issue.

**Comment by alinelariguet** [comment]
Boa tarde @haidicarolina e @wsteixeira ,
esta funcionalidade foi entregue na versão 6.6.0
