### ISSUE TITLE
Possibilitar customização do componente po-chart

### ISSUE THREAD

**Issue by guilhermebc** [po-ui/po-angular#111]
Boa tarde,

Estou usando o **po-chart**  (https://portinari.io/documentation/po-chart) e me deparei com alguns detalhes que eu gostaria de customizar no gráfico para um projeto. Segue a lista de funcionalidades que atualmente estou precisando.

Setar cores particulares para cada dado no gráfico.
Escolher mostrar ou não a parte de legendas.
Definir a label de cada elemento do gráfico dentro ou fora.
Definir largura do gráfico tipo "Donut".

Segue em anexo um exemplo de gráfico.

Obrigado desde já!

![Screenshot from 2019-10-04 14 49 50](https://user-images.githubusercontent.com/14234175/66228657-5f5ede80-e6b6-11e9-957a-24f995aac1d6.png)

**Comment by samir-ayoub** [comment]
Boa tarde, Guilherme,

Os itens serão adicionados no backlog e o PO avaliará a entrega conforme a demanda. Porém, há itens conflitantes conforme abaixo. Pode me dizer se interpretamos corretamente?

**_Definir a label de cada elemento do gráfico dentro ou fora.:_** 
O time de UX estipulou como padrão de definição de labels através de tooltip e também nas legendas. 
A sugestão de exibição de label associada com um fio na área externa colide com uma funcionalidade futura que é a listagem de itens que contem um percentual ínfimo. Portanto, para implementarmos isso, precisaríamos de uma estudo prévio que corrobore com sua sugestão e que não conflita com as demais definições do estudo.

**_Definir largura do gráfico tipo "Donut"._**
A que você se refere aqui, à espessura do gráfico ou à largura total?

**Comment by guilhermebc** [comment]
Boa tarde, @samir-ayoub,

Sim, foram plenamente interpretados. Sobre definir as labels dentro ou fora do gráfico, consigo utilizar através de tooltip mesmo, mas ainda posso fazer um estudo prévio para uma possível implementação sem conflitos com futuras implementações.

Obrigado desde já e fico no aguardo :)

**Comment by samir-ayoub** [comment]
E com relação à largura é referente a espessura? Pois você pode definir a altura do gráfico e, consequentemente, a largura.

**Comment by guilhermebc** [comment]
Além da largura e altura total do gráfico, precisaria definir a espessura do arco para uma melhor UX e melhor categorização para cada gráfico de acordo com os dados que ele representa.

**Comment by samir-ayoub** [comment]
Ok, perfeito, sugestões encaminhadas com exceção do item 3 :)
Atenciosamente

**Comment by jhonyeduardo** [comment]
Olá,
Itens solicitados foram liberados, sendo o ultimo, a possibilidade de aumentar o raio do donut que será lançado na v4.10.0, 
Obrigado.
