### ISSUE TITLE
Polookup não aceita coluna do tipo dateTime

### ISSUE THREAD

**Issue by haidicarolina** [po-ui/po-angular#1111]
#### Descrição da melhoria
Polookup aceitando coluna do tipo dateTime

#### Caso de uso
Coluna do polookup com data e hora.

#### Informações adicionais
Atualmente os tipos aceitos pelo polookup para as colunas são: string, number, date e currency, seria interessante adicionar o tipo 'dateTime' seguindo inclusive o padrão de outros componentes.

**Comment by alinelariguet** [comment]
Obrigada pela sugestão,
Vamos incluir este item no nosso backlog.
Att.

**Comment by wsteixeira** [comment]
Olá @alinelariguet,

Esta issue ficou aberta apesar de já ter sido disponibilizada na PR #1201
