### ISSUE TITLE
<po-page-dynamic-table>: <No multi select>

### ISSUE THREAD

**Issue by Feeh03114** [po-ui/po-angular#1119]
Passos para reproduzir:
1.  
html
`<idx-po-page-dynamic-table [p-page-custom-actions]="pageActions">
</idx-po-page-dynamic-table>`

metadata
`{
      property: 'pessoa_id',
      label: 'Fornecedor',
      optional: true,
      optionsMulti: true,
      optionsService: '/api/pessoas/multi-select',
      gridColumns: 12,
      gridSmColumns: 12,
      divider: 'Parametros',
    }
`

#### Qual o comportamento atual?
![WhatsApp Image 2021-11-29 at 11 06 49](https://user-images.githubusercontent.com/58147419/144614193-b7e17843-88f4-46d5-9272-5e84a6939df0.jpeg)

#### Que comportamento você esperava ver?
quando o texto não coubesse ele aparecesse "outros #" , sendo o # o numero de itens a mais.

#### Ambiente

- PO UI: 5.22.0
- Angular: 12.1.3
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Boa tarde @Feeh03114,

Por favor, entre na pasta node_modules > @po-ui > style e verifique a versão que está na propriedade version dentro do arquivo package.json, ela deve ser a mesma do pacote @po-ui/ng-components que como informado acima é a v5.22.0.

**Comment by Feeh03114** [comment]
![image](https://user-images.githubusercontent.com/58147419/145202811-6aed9d0f-a2fd-4251-aabe-d3610a3cb1a3.png)
a mesma versão

**Comment by alinelariguet** [comment]
Obrigada por reportar! Vamos analisar e retornaremos o contato.

**Comment by alinelariguet** [comment]
Consegue simular pelo stackblitz? Montei o ambiente aqui e não consegui reproduzir o erro.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
