### ISSUE TITLE
po-decimal com configurações diferente de valores

### ISSUE THREAD

**Issue by thiagogoncalves** [po-ui/po-angular#113]
Estou criando uma tela onde tenho dois componentes do tipo "po-decimal", um é em reais e o outro em dólar.  Meu projeto está todo configurado para utilizar com o LOCALE "pt-BR".

Como eu faço para definir que o campo com valores em outras moedas são de outro LOCALE ?

**Comment by samir-ayoub** [comment]
Olá Thiago, boa tarde,

No Portinari não há um tratamento customizado para locales, teria que implementar. 

De qualquer forma, não vemos isso como uma atribuição de responsabilidade do componente, ainda mais porque o `po-decimal` não faz distinção de valores do tipo moeda e sim para valores decimais genéricos.

Para analisar melhor peço que envie uma exemplificação mais detalhada da sua necessidade, se por exemplo seu interesse é trocar vírgulas por pontos  ou então trocar quantia de casas decimais por exemplo.

**Comment by thiagogoncalves** [comment]
Olá Samir,

Eu gostaria de ter um campo decimal com o padrão monetário em reais e o outro em dólar por exemplo:

R$ 1.999,99 o separados é uma vírgula
U$ 1,999.99 o separados é um ponto

É possível ?

**Comment by samir-ayoub** [comment]
Imagino que, para esse caso específico, você poderia tentar utilizar o CurrencyPipe e definir o currency code assim como a representação decimal conforme convier. Porém, teria que optar pelo `<po-input>` e tratar uma diretiva para aceitação de digitação apenas para números.

**Comment by samir-ayoub** [comment]
Iremos analisar duas possibilidades:

- melhoria no componente **po-decimal** para que seja possível alterar os separadores de decimal e milhar;
- novo componente destinado à campos monetários

Este item será adicionado em nosso backlog e o PO irá avaliar a viabilidade de cada proposta.

Qualquer dúvida estou a disposição!

**Comment by thiagogoncalves** [comment]
Boa tarde!

Como está essa melhoria, tem uma data para este desenvolvimento?

Att.
Thiago Gonçalves dos Santos

**Comment by jhosefmarks** [comment]
Ainda não temos previsão, mas aceitamos colaborações no projeto #ficadica. :P

**Comment by jhonyeduardo** [comment]
Boa tarde Pessoal

Na versão 3.10.0 lançamos o p-locale dentro do componente [PoDecimal](https://po-ui.io/documentation/po-decimal)


Por padrão, o locale será capturado através do PoI18n mas também será possível especificar por componente através do p-locale.
