### ISSUE TITLE
po-page-dynamic-detail - atributo do tipo label

### ISSUE THREAD

**Issue by TecoAvila** [po-ui/po-angular#1140]
Temos em nosso modelo um atributo do tipo "**label**", onde o valor é uma campo numérico (exemplo: 1, 2, 3), mas ao usuário, apresentamos uma string (exemplo: Ativo, Inativo, Bloqueado).
Conseguimos trabalhar muito bem com este atributo nos componentes **po-page-dynamic-table** (table e busca avançada) e no **po-page-dynamic-edit**. Onde, enviamos a partir do Backend o valor numérico, mas ao usuário é apresentado a string. O componente realiza o de-para através da propriedade "**options**".
Mas, o componente **po-page-dynamic-detail** não suporta este tipo de atributo.
Ele apresenta na tela o conteúdo "**puro**" do atributo (1, 2 ou 3), ao invés da string.
O componente deveria identificar que foi enviada a propriedade "**options**" e realizar o de-para do conteúdo.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
