### ISSUE TITLE
Melhorar funcionalidade de customActions no po-page-dynamic-table

### ISSUE THREAD

**Issue by haidicarolina** [po-ui/po-angular#1156]
Descrição da melhoria
O atributo de ações customizadas do po-page-dynamic-table não tem a opção de 'visible' disponível em outros componentes que define se a ação será apresentada ou não. 

Caso de uso
Determinada ação que só será apresentada para um determinado tipo de usuário, ou que dependa de determinado valor do registro em questão vinculado a ação.

**Comment by jcorrea97** [comment]
Obrigado pela sugestão, vamos analisar e daremos um retorno.

**Comment by wsteixeira** [comment]
Boa noite,

Posso fazer esta contribuição?
