### ISSUE TITLE
po-table/po-page-dynamic-table: PoTableActions, prop "visible": boolean | Function

### ISSUE THREAD

**Issue by PedCoelho** [po-ui/po-angular#1158]
### Descrição da melhoria
Nas interfaces ``PoTableAction``, ``PoPageDynamicTableActions``, ``PoPopupAction`` e afins, relativas aos componentes ``po-table`` seria interessante que a implementação da propriedade ``visible`` acompanhasse a implementação de ``disabled``, com a possibilidade de se passar uma função com retorno de ``boolean``.

![image](https://user-images.githubusercontent.com/40411622/148812883-bbce71e1-89e6-4a04-aef0-ab89a3d9560f.png)
![image](https://user-images.githubusercontent.com/40411622/148812913-3cf75f84-fe23-483e-a180-4c19357885a6.png)

### Caso de uso
Controlar dinâmicamente a ``visibilidade`` de Actions no popup de acordo com propriedades da linha da tabela. Assim como é possível com a propriedade ``disabled``.

### Informações adicionais
Exemplo de implementação desejada
![image](https://user-images.githubusercontent.com/40411622/148813502-4dcc5106-4cd2-4f7e-a821-4cc6791d8908.png)

**Comment by wsteixeira** [comment]
Boa tarde,

O atributo visible já está sendo tratado na issue #1156 na propriedade p-table-custom-actions, mas está faltando o tratamento na propriedade p-page-custom-actions, onde gostaria de fazer uma contriubuição.
