### ISSUE TITLE
Page Dynamic Table - p-actions-right

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1160]
### Discussed in https://github.com/po-ui/po-angular/discussions/1133

<div type='discussions-op-text'>

<sup>Originally posted by **wsteixeira** December 15, 2021</sup>
Não consegui colocar o "actions" do lado direito, o portal também ainda não tem o "p-actions-right".</div>

**Comment by wsteixeira** [comment]
Eu gostaria de contribuir nesta issue, não tenho muita experiência, mas já consegui ajustar a coluna do lado direito, agora falta os próximos passos, teste, portal, documentação e etc.

**Comment by alinelariguet** [comment]
Bom dia @wsteixeira, tudo bem?
Vou entrar em contato para combinarmos melhor a contribuição.

**Comment by wsteixeira** [comment]
Bom dia,

Ok, vou aguardar, mas já está pronto, já rodei o build do portal e já testei.

**Comment by alinelariguet** [comment]
Bom dia @wsteixeira você pode abrir a PR pra gente então dai seguimos com as orientações na própria PR.

**Comment by wsteixeira** [comment]
Boa tarde @alinelariguet, PR gerada!

**Comment by alinelariguet** [comment]
Obrigada @wsteixeira ,
Assim que possível vamos revisá-la. 
Obrigada por contribuir!

**Comment by Kleger** [comment]
Boa tarde @alinelariguet, td bem?
Não sei se há alguma forma de votar nas issues, então estou deixando esse comentário pra informar que também estou precisando dessa propriedade.
Alguma previsão de quando será liberada?
