### ISSUE TITLE
lookup: Não encontra registro após click em Carregar mais resultados

### ISSUE THREAD

**Issue by leonardomachadopereira** [po-ui/po-angular#1166]
Problema no componente lookup (Busca Avançada), eu fiz uma simulação do problema no próprio portal e usei o exemplo PO Lookup - Hero, segue abaixo as instruções para a simulação:

1. Clique em Busca Avançada, e digite Peter Parker no Name;
2. Na tabela mostra os dados corretamente;
3. Limpar o filtro, e após clicar em Carregar mais resultados;
4. Repetindo a consulta, o registro não é encontrado.

Notei que a requisição após clicar em Carregar mais resultados está com o page=2 no filter:
https://po-sample-api.herokuapp.com/v1/heroes?filter=&page=2&pageSize=10&name=Peter%20Parker
Após limpar o filtro novamente, ele carrega os 10 próximos registros a partir da página 2.

**Comment by brunoromeiro** [comment]
Bom dia, @leonardomachadopereira .

Estamos analisando, e em breve daremos retorno.

**Comment by brunoromeiro** [comment]
Conforme análise estamos incluindo essa issue no nosso backlog.

Obrigado por reportar.

**Comment by wsteixeira** [comment]
Olá @brunoromeiro

Esta issue ficou aberta apesar de já ter sido disponibilizada na #1220

**Comment by alinelariguet** [comment]
Esta issue foi concluída e liberada na v6.5.1 em 14/03/22.
