### ISSUE TITLE
<po-accordion-item>: <meu componente externo perde as configurações ao ser adicionado dentro do Accordion>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#1168]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.
**https://stackblitz.com/edit/po-ui-sz5dr7?file=src%2Fapp%2Fcard%2Fcard.component.html**

Passos para reproduzir:
1. Adiciono o accordion na minha página;
2. Adiciono meu componente externo dentro do accordion-item

#### Qual o comportamento atual?
O Componente externo perde toda a estilização

#### Que comportamento você esperava ver?
**Que o componente externo mantivesse a estilização definida, adicionei o exemplo em vermelho de como está dentro do accordion e de preto como está corretamente.**

#### Ambiente

- PO UI:  5.4.0
![Sem título1](https://user-images.githubusercontent.com/58361652/151040363-3767d501-e7ea-4ca6-a58b-a89a8dbd47ab.png)
![Sem título](https://user-images.githubusercontent.com/58361652/151040368-ae24a422-049f-4c67-9f4c-f9bba5409ff6.png)

- Angular: 12.1.2
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [x] Opera
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by brunoromeiro** [comment]
Bom dia, @EduardaDalmas .

Estamos analisando, e em breve daremos retorno.

**Comment by brunoromeiro** [comment]
Bom dia @EduardaDalmas .

O nosso componente tem um `line-height: 24px` para o corpo do `accordion` que foi definido pelo UX. 
Para contornar esta sua situação, verificamos que basta você definir no estilo do seu componente card um `line-height: initial`.

Atenciosamente.

**Comment by EduardaDalmas** [comment]
Boa tarde!

Perfeito, agradeço o auxílio.

Uma sugestão para evitar mais issues sobre isso é adicionar algum rodapé na documentação, isso vai ajudar bastante. 

Ótima semana!
