### ISSUE TITLE
propriedade visible das actions do component po-page-default

### ISSUE THREAD

**Issue by jeterson** [po-ui/po-angular#117]
```
actions: PoTableAction[] = [
    { label: 'Avançar', action: () => { }, visible: false },

  ];
```

A propriedade `visible`do `PoTableAction` para o component `PoPageDefault` não tem efeito no componente.
Olhando no repo do component, parece que não a definição do comportamento dessa propriedade.

Se o problema for alguma definição a mais da minha parte, por favor me avise.

Desde já obrigado.
Att.

**Comment by samir-ayoub** [comment]
Olá Jeterson, bom dia,

A interface para lista de ações do componente **po-page-default** é a **PoPageAction** e a evidência enviada contém a _PoTableAction_.
Ainda assim, na documentação do componente há esta especificação para a interface: 

> As propriedades selected, separator, type e visible serão vistas a partir da terceira ação e somente quando definir quatro ações ou mais.
[po-page-default](https://portinari.io/documentation/po-page-default)

Me diga por favor se sua aplicação se enquadra nessa premissa e se o comportamento é adequado.
Qualquer dúvida estou a disposição

**Comment by jeterson** [comment]
Desculpe, acabei digitando a interface errada:
```
 actions: PoPageAction[] = [
    { label: 'Avançar', action: this.next.bind(this), visible: false, disabled: this.nextActionDisabled.bind(this) },
    { label: 'Concluir', action: this.done.bind(this), visible: false, disabled: this.doneActionVisible.bind(this) },
    { label: 'Voltar', action: this.back.bind(this), visible: false, disabled: this.backActionDisabled.bind(this) },

  ];
```
Peguei o trecho do código direto do projeto agora, e uma screen dos botoes na tela que to fazendo
![portinari](https://user-images.githubusercontent.com/23269618/66652752-7779b500-ec04-11e9-9107-d12d87c708f2.PNG)

**Comment by jeterson** [comment]
Mas entendi, pra funcionar, só se definir mais de 4 acoes, mas seria interessante eu poder, assim como o `disabled`, poder definir o `visible` independente da quantidade de ações.

Obrigado pelo esclarecimento

**Comment by samir-ayoub** [comment]
Vamos adicionar este item em nosso backlog e o PO irá avaliar sua sugestão,
qualquer dúvida estou a disposição!

**Comment by jeterson** [comment]
Muito obrigado, por hora, vou usar só o `disabled` mesmo para impedir cliques ao botão

**Comment by jhonyeduardo** [comment]
Bom dia @jeterson  

Item resolvido na release 4.2.0, veja nosso [CHANGELOG](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md)

Obrigado
