### ISSUE TITLE
po-page-dynamic-detail: Exemplo com erro

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1175]
#### Qual o comportamento atual?
No exemplo do componente **Page Dynamic Detail** está aparecendo a mensagem '**Registro não encontrado**'.

#### Que comportamento você esperava ver?
Que o exemplo do componente **Page Dynamic Detail** apresente a interface com os dados.

#### Ambiente

- PO UI: 6.20
- Angular: 13.0.2

**Comment by alinelariguet** [comment]
Boa tarde @wsteixeira, tudo bem?
Obrigada por reportar, porém esse comportamento não se trata de um bug. O po-page-dynamic-detail utiliza o identificador enviado como path parameter para poder realizar a busca do registro e nesse caso o nosso portal não está redirecionando para essa página de exemplos com um identificador, por esse motivo que não aparece nenhum registro.
Favor verificar o funcionamento do componente independente do portal.
Att.

**Comment by wsteixeira** [comment]
Bom dia,

@alinelariguet, obrigado pelo retorno.

     Eu entendi, você tem razão, mas eu gostaria de contribuir na issue #1140 e desta forma eu precisaria do exemplo funcionando para demonstrar a funcionalidade.

     Eu até alterei o exemplo incluindo:
- TAG
 `<router-outlet></router-outlet>`

- Codigo 
```
  constructor(
    private router: Router) { }

  ngOnInit() {
    this.router.config.push({ path: 'people/:id', component: SamplePoPageDynamicDetailUserComponent });
    this.router.navigate(['people', '0148093543698']);
  }
```

     Até funcionou na minha maquina, mas depois do build do portal, a TAG deve ter ficado duplicada e quando seleciono o componente "Page Dynamic Detail" o portal redireciona para home.

     Estou tentando usar o 'Auxiliary Routes' '<router-outlet name="section1"></router-outlet>', mas ainda não tive sucesso!

     Tem alguma outra ideia para me ajudar?

Obrigado.
