### ISSUE TITLE
Po-Accordion-Item

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#1180]
#### Descrição da melhoria
Opção de chamar alguma função no click do accordion item.

#### Caso de uso
Ao clicar no item do Accordion, chamar uma função específica do conteúdo informado.

#### Informações adicionais
Pode ser uma chamada no (p-change) ou no (p-click)
![imagem_2022-02-04_173725](https://user-images.githubusercontent.com/58361652/152599697-6d37883c-bdb3-41b5-80fe-e8885e095016.png)

**Comment by EduardaDalmas** [comment]
Olá, tudo bem? Preciso de um retorno o quanto antes. Se puderem me apresentar alguma alternativa para o problema.

**Comment by jribeiroo** [comment]
Boa tarde @EduardaDalmas obrigado pela sugestão, vamos incluir esta issue no nosso backlog. SE você quiser você pode contribuir com essa funcionalidade também.

Att.
