### ISSUE TITLE
É possível realizar formatação customizada no conteúdo de uma coluna do po-table?

### ISSUE THREAD

**Issue by nicocelli** [po-ui/po-angular#1181]
Gostaria de mascarar o valor apresentado em determinada coluna do po-table.

**Exemplo:**
Tenho uma coluna que é o número do telefone:
Valor apresentado: 47 992624595
Valor que eu gostaria: 47 99*****95

Como se eu aplicasse um format que chamasse uma função minha, isso é possível? Ou através de um pipe?

**Comment by jribeiroo** [comment]
Boa tarde @nicocelli você precisa tratar os dados antes de exibir na tabela. Veja se isto resolve pra você. 

Att.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
