### ISSUE TITLE
po-table: exception ao carregar componente com p-height definida

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#1188]
Passos para reproduzir:
1- Entrar em uma rota que tenha uma po-table com p-height na declaração definida.

#### Qual o comportamento atual?

Surge um erro de `TypeError: Cannot read properties of undefined (reading 'find')`
![image](https://user-images.githubusercontent.com/29649474/153005238-74f7d432-8abb-470e-93f7-2cb0058ce553.png)

Obs.: Ja notei outros bugs relacionado ao p-height da tabela, bugando a movimentação horizontal, etc etc.

#### Ambiente

- PO UI: 4.10
- Angular: 11.2
- Browser(s):
  - [ ] Chrome
  - [ ] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by brunoromeiro** [comment]
Olá @guiworks, obrigado pelo contato.

Consegue simular por aqui https://stackblitz.com/edit/po-ui-kfub3g ?

Fico no aguardo.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
