### ISSUE TITLE
Lookup - Esconder ícone de lupa

### ISSUE THREAD

**Issue by TecoAvila** [po-ui/po-angular#1193]
Atualmente, quando um lookup é desabilitado, ele fica com o fundo cinza como o padrão dos fill's. 
Mas, continua apresentando o ícone de lupa, isto dá a falsa impressão que ele pode ser clicado.

O ideal é que, ao ser desabilitado, o ícone seja escondido. 
Ou, exista a possibilidade do desenvolvedor esconder o ícone quando necessário.

Segue anexo o print exemplificando a solicitação.
<img width="344" alt="Lookup-Icon" src="https://user-images.githubusercontent.com/65685116/153497457-4d46dd3e-732c-48ac-9a2f-4b1b83ad7ee3.png">

**Comment by alinelariguet** [comment]
Boa noite @TecoAvila,
Consultamos o time de UX Lab e eles não indicaram esta alteração. Caso necessário você pode substituir o po-lookup por um po-input quando estiver desabilitado.
Att.

**Comment by TecoAvila** [comment]
Olá @alinelariguet , bom dia,

Gostaríamos de saber porque o UX Lab não recomenda esta alteração.
Aproveitando, sempre que tivermos este cenário, saberia nos dizer qual seria o Canal para o nosso UX Local entrar em contato com o UX Lab's ?

**Comment by brunoromeiro** [comment]
Olá @TecoAvila, bom dia. Tudo bem?
Vou te mandar o contato do Douglas coordenador do UX Labs.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
