### ISSUE TITLE
Table - Gerenciador de Colunas do mesmo lado das Ações

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1194]
#### Descrição da melhoria
Depois que passou a ser possível trocar o lado do `p-actions` o `columns-manager` não acompanha `p-actions` e quando os dois ficam em lados opostos, creio que a usabilidade não fica boa.

#### Caso de uso
Melhor aproveitamento do espaço no caso do mobile, caso o `p-actions` o `columns-manager` ficassem do mesmo lado.

#### Informações adicionais
Gostaria de colaborar nesta melhoria.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
