### ISSUE TITLE
po-table: table com infinite-scroll nao exibindo as colunas

### ISSUE THREAD

**Issue by RBalconi** [po-ui/po-angular#1198]
#### Reprodução

Passos para reproduzir:
1. Crie uma `po-table`;
2. Adicione as configuraçoes necessarias para usar o infinite-scroll:
```
(p-show-more)="showMore()"
[p-infinite-scroll]="true"
p-infinite-scroll-distance="80"
p-height="450"
```
#### Qual o comportamento atual?

A tabela "encolhe" as colunas, no desktop aparentemente comportou normal, porém no mobile/tablet ficam deformada.
Segue prints de exemplo:

PrintScreen em Desktop - Exibindo normal
![image](https://user-images.githubusercontent.com/18688446/154065638-346f839e-95f4-4152-92c1-793d80f710a8.png)
PrintScreen em Mobile - Exibindo com as colunas "encolhidas"
![image](https://user-images.githubusercontent.com/18688446/154066042-692a2ea8-c288-41fe-b7ef-544f549f70a1.png)

Ambas sao a mesma tabela.

Obs.: Ao remover a opçao `p-height="450"` do HTML esse problema é corrigido, porem o infinite-scroll nao funciona.

#### Que comportamento você esperava ver?

Deveria manter o tamanho das colunas e adicionas em scroll horizontal, como é feito nas tabelas sem o infinite-scroll:
Segue um PrintScreen de exemplo:
![image](https://user-images.githubusercontent.com/18688446/154068105-9cda8d4c-1ca3-4b8e-9ee1-582c23e61f3a.png)

#### Ambiente

- PO UI: 6.0.0
- Angular: 13.1.1
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [x] Ubuntu
  - [ ] Outros

**Comment by brunoromeiro** [comment]
Bom dia @RBalconi, 

Estamos analisando, e em breve daremos retorno.

**Comment by brunoromeiro** [comment]
@RBalconi já tentou utilizar a propriedade ´p-columns´? 
Criei um exemplo aqui para ver se te ajuda no curto prazo, https://stackblitz.com/edit/po-ui-jk3vxj?file=src%2Fapp%2Fapp.component.html.

Fico no aguardo.

**Comment by RBalconi** [comment]
> @RBalconi já tentou utilizar a propriedade ´p-columns´? Criei um exemplo aqui para ver se te ajuda no curto prazo, https://stackblitz.com/edit/po-ui-jk3vxj?file=src%2Fapp%2Fapp.component.html.
> 
> Fico no aguardo.

Sim sim, usamos a `[p-columns]`, percebi que passa valor em pixel no seu exemplo, aqui usamos porcentagem. Mas de resto tudo igual.

```
      <po-table
        #tableTest
        id="tableTest"
        p-selectable
        p-hide-select-all="false"
        p-sort="true"
        p-striped="true"
        [p-columns]="columns"
        [p-items]="dataFiltered"
        [p-literals]="customLiterals"
        (p-change-visible-columns)="columnsManager($event)"
        (p-show-more)="showMore()"
        [p-infinite-scroll]="true"
        p-infinite-scroll-distance="80"
        p-height="450"
      >
      </po-table>
```

**Comment by RBalconi** [comment]
Confirmei aqui, ao trocar no seu exemplo de px para % ocorreu o mesmo, problema, vou sugerir essa alteraçao no projeto ate ser resolvido. Obrigado :)

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
