### ISSUE TITLE
Seletor de idioma

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#120]
Gostaria de sugerir uma opção para no template Page Login, podermos definir se o combo de seleção do idioma irá aparecer ou não, pois em alguns casos a aplicação poderá ser feita exclusivamente em um idioma apenas.

**Comment by RafaellyG** [comment]
Ola Anderson!

Sugestão de melhoria encaminhada para análise.

**Comment by joao-arthur-moreira** [comment]
Aguardando esta funcionalidade! não vejo necessidade de exibir o seletor de idioma a não ser que a aplicação necessite operar com mais de um idioma ai fica a critério do desenvolvedor mostrar ou não o seletor.

**Comment by jhosefmarks** [comment]
Feito! PR #607 

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#360-2020-09-14
