### ISSUE TITLE
PoPageAction propriedades não funcionam como esperado

### ISSUE THREAD

**Issue by rmarmitt** [po-ui/po-angular#121]
O componente PoPageAction não respeita algumas propriedades, por exemplo:

label: 'Remover',
icon: 'po-icon-delete',
type: 'danger'

O botão em questão não fica em vermelho, tampouco aparece o ícone esperado.

Estas ações estão sendo utilizadas em uma < po-page-default >

StackBlitz: https://portinariui-skj7yn.stackblitz.io

- Portinari: 1.12.0
- Angular: 8.0.6
- Browser(s): Chrome 77
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by RafaellyG** [comment]
Ola Rafael!

Este comportamento está na [documentação do `po-page-default`](https://portinari.io/documentation/po-page-default), na interface `PoPageAction` informa que o `type` atualmente só será respeitado quando definir quatro ações ou mais, o mesmo acontece com o ícone (nesse caso falta documentar).

Vou encaminhar essa issue para análise como uma sugestão de melhoria para os botões do `po-page-default`

Qualquer dúvida estou a disposição.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. Caso seja necessário, uma nova issue será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
