### ISSUE TITLE
po-table - PoTableAction - Nova propriedade: color

### ISSUE THREAD

**Issue by TecoAvila** [po-ui/po-angular#1222]
Solicitamos a inclusão da propriedade "color" na interface "PoTableAction" do componente "po-table".
Segue anexo uma imagem com o exemplo da aplicabilidade.
![color-action-table](https://user-images.githubusercontent.com/65685116/157869063-68c3105b-1252-46d5-8b38-92dc1dcd2dd7.png)

**Comment by lucas-pollus** [comment]
+1

**Comment by jribeiroo** [comment]
A necessidade seria somente a cor vermelha como no caso do remover ? Teria a necessidade de mais alguma cor ?

**Comment by TecoAvila** [comment]
Olá @jribeiroo , verificamos que, através da propriedade "type" é possível mudar a cor do item para vermelho (danger).
A ideia aqui é ter mais flexibilidade para mudar a cor do item de menu.

**Comment by alinelariguet** [comment]
Boa tarde @TecoAvila existe também a questão de usabilidade onde a cor auxilia o usuário para melhor entendimento. Você poderia verificar esta sugestão com a equipe de UX?

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
