### ISSUE TITLE
configuração inicial do po-ui: Could not resolve dependency

### ISSUE THREAD

**Issue by maikiperin** [po-ui/po-angular#1226]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: requi@0.0.0
npm ERR! Found: rxjs@7.5.5
npm ERR! node_modules/rxjs
npm ERR!   rxjs@"~7.5.0" from the root project
npm ERR!   peer rxjs@"^6.5.3 || ^7.4.0" from @angular/core@13.2.6
npm ERR!   node_modules/@angular/core
npm ERR!     @angular/core@"~13.2.0" from the root project
npm ERR!     peer @angular/core@"^13.0.2" from @po-ui/ng-components@6.5.1
npm ERR!     node_modules/@po-ui/ng-components
npm ERR!       @po-ui/ng-components@"6.5.1" from the root project
npm ERR!     6 more (@angular/animations, @angular/common, @angular/forms, ...)
npm ERR!   3 more (@angular/common, @angular/forms, @angular/router)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer rxjs@"~7.4.0" from @po-ui/ng-components@6.5.1
npm ERR! node_modules/@po-ui/ng-components
npm ERR!   @po-ui/ng-components@"6.5.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\Maiki\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Maiki\AppData\Local\npm-cache\_logs\2022-03-15T12_31_51_195Z-debug-0.log
× Package install failed, see above.

Passos para reproduzir:
1. Execução do comando: ng add @po-ui/ng-components

#### Ambiente
- Browser(s):
  - [X ] Chrome
- Operating System:
  - [X ] Windows

**Comment by alinelariguet** [comment]
Boa tarde @maikiperin, tudo bem?
Você está seguindo o nosso [guia de primeiros passos](https://po-ui.io/guides/getting-started)?
Verifique a sua versão do npm, deve ser utilizada a v6.

**Comment by maikiperin** [comment]
Boa tarde @alinelariguet,

Utilizando o Node versão LTS e realizando o downgrade no NPM para v6, deu certo.

Obrigado.
