### ISSUE TITLE
Table: O `p-infinite-scroll` somente funciona até um determinado valor no `p-height`.

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1228]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-rrdsan?file=src/app/app.component.html) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Use sempre a opção **"Open in New Window"** ou faça direto no Vscode.
2. Eu fiz a primeira simulação em um monitor de 14'' de um notebook.
3. Na a propriedade `p-height` até o valor `320` funciona o `p-infinite-scroll`.
4. Na a propriedade `p-height`  com valor acima de `320` não funciona o `p-infinite-scroll`, aparece o **"Carregar mais resultados"**.
5. Eu fiz a segunda simulação em um monitor de 24''.
6. Na a propriedade `p-height` até o valor `440` funciona o `p-infinite-scroll`.
7. Na a propriedade `p-height`  com valor acima de `440` não funciona o `p-infinite-scroll`, aparece o **"Carregar mais resultados"**.
8. Se o teste for feito em um equipamento de dois monitores, faça a atualização da pagina no navegador.

#### Qual o comportamento atual?
A propriedade `p-height` parece funcionar até uma valor limite de 320 para monitor de 14'' e 440 para monitor de 24'', para que o  `p-infinite-scroll` funcione.

#### Que comportamento você esperava ver?
Que o  `p-infinite-scroll` funcione independente do valor do `p-height`, já que a documentação não menciona limites.

#### Ambiente

- PO UI: V6.5.1
- Angular: V13.0.2
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by visued** [comment]
+1

**Comment by wsteixeira** [comment]
Boa tarde,

Não fiz nada não.

Atenciosamente,

**Comment by renanarosario** [comment]
O erro nas versão mais novas não ocorre. 
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
