### ISSUE TITLE
Po-Table: Adicionar formatação do pais dentro da tabela em um coluna do tipo numérico.

### ISSUE THREAD

**Issue by DautPavan** [po-ui/po-angular#1229]
#### Descrição da melhoria
Bom dia, 
Trabalhando usando o PO-UI, tenho uma tabela com uma coluna do tipo "number", onde iramos tratar um valor para o usuário. Mesmo utilizando o pipeline para formata o valor a ser exibido com a quantidade de casas decimais (format: '1.3-5'), tenho a necessidade que essa valor seja apresentado no formato 'BRL' (X.XXX,XXX), atualmente esse valor é sempre exibido no formato 'USD' (Padrão)

#### Caso de uso
Melhoria permitira que os valores em uma tabela do tipo number seja apresentados no formato necessário de cada pais. Diferenciado a do formato "currency", pois não contem o tipo da moeda na frente (R$:1.000,00)

#### Informações adicionais
**Sugestão** desse recurso seria dentro a interface PoTableColumn, quando informamos a propriedade 'format' para number, seja possível incluir também o 'locale'. Exemplo :
( 
 {
   label: 'Custo Nota', 
   property: 'custoNota', 
   width: "150px", 
   type:'number',
   format: '1.3-5|BRL' //Informado o valor em casa decimal, após um separador (por exemplo: ' | ' ) para informa o locale
 }
)
![image](https://user-images.githubusercontent.com/47869279/158612505-4996a0f5-9c5c-49b3-a9a7-6c17f5c77122.png)

Dentro do método de exibir o numero na tabela "formatNumber", seja passado esse valor informa após o PIPE na interface (BRL).
![image](https://user-images.githubusercontent.com/47869279/158612175-7f26a793-cc6d-469d-9096-2157b1d4be41.png)
![image](https://user-images.githubusercontent.com/47869279/158612228-5364a812-6fba-4ebc-bc8a-4ed4964a3457.png)

Usando o  DecimalPipe passando no metodo "transform" esse valor a mais.
![image](https://user-images.githubusercontent.com/47869279/158612793-c575c172-1d73-4a63-b383-44850185134c.png)

**Comment by wsteixeira** [comment]
Olá @DautPavan,

Eu normalmente coloco a configuração abaixo no `app.module.ts` e consigo o resultado que você está esperando.
```
import { DEFAULT_CURRENCY_CODE, LOCALE_ID, NgModule } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import ptBr from '@angular/common/locales/pt';

...

registerLocaleData(ptBr);

@NgModule({
  ...
  providers: [
    { provide: LOCALE_ID, useValue: 'pt' },
    { provide: DEFAULT_CURRENCY_CODE, useValue: 'BRL' },
  ],
  ...
})
export class AppModule { }
```

**Comment by wsteixeira** [comment]
Olá @DautPavan,

Eu normalmente coloco a configuração abaixo no `app.module.ts` e consigo o resultado na moeda local que você está esperando.

```
import { DEFAULT_CURRENCY_CODE, LOCALE_ID, NgModule } from '@angular/core';
import { registerLocaleData } from '@angular/common';
import ptBr from '@angular/common/locales/pt';

...

registerLocaleData(ptBr);

@NgModule({
  ...
  providers: [
    { provide: LOCALE_ID, useValue: 'pt' },
    { provide: DEFAULT_CURRENCY_CODE, useValue: 'BRL' },
  ],
  ...
})
export class AppModule { }
```

**Comment by wsteixeira** [comment]
Olá @DautPavan,

Nesta situação eu não informar, já que esta configuração fixa a localidade! Vou pesquisar um pouco, pois também fiquei curioso e se encontra eu informo.
