### ISSUE TITLE
po-table - Lentidão e travamento na tabela quando possui muitas linhas e colunas.

### ISSUE THREAD

**Issue by tapiarona** [po-ui/po-angular#1230]
Projeto para reprodução no STACKBLITZ:
https://stackblitz.com/edit/po-ui-ftkguu?file=src/app/app.component.html

Passos para reproduzir:
1. Criar uma tabela com 500 linhas e 31 colunas;
2. Veja que há uma lentidão e alguns travamentos na tela.

#### Qual o comportamento atual?
Lentidão no po-table ao utilizar 500 linhas e 31 colunas na tabela.

#### Que comportamento você esperava ver?
Comportamento normal do po-table, sem lentidão e travamentos.

Temos um projeto no qual necessita que seja apresentado no po-table diversas informações, sendo assim, temos um grande número de colunas e linhas. As linhas são carregadas através de requisição a uma API utilizando o conceito de sroll infinito. No exemplo citado no STACKBLITZ veja que na primeira tabela temos 31 colunas e na segunda 23. Há uma diferença de performance entre as duas... Precisamos que o componente seja performático independente do número de linhas e colunas na tela.

Obrigado.

#### Ambiente

- PO UI:  5.22.2
- Angular:  12.2.0
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Boa noite @tapiarona, obrigada por reportar! Vamos implementar o virtual-scroll no po-table. Acredito que isso ajude na performance. Assim que a funcionalidade for liberada daremos um retorno.

Att.,

**Comment by alinelariguet** [comment]
Liberamos o virtual scroll na v6.12.0. Importante lembrar que esta funcionalidade só é atribuída para tabelas com a propriedade p-height habilitada.
Att.
