### ISSUE TITLE
Reordenação e redimensionamento de colunas dinâmico

### ISSUE THREAD

**Issue by fabionaspolini** [po-ui/po-angular#1238]
#### Descrição da melhoria

Não localizei uma opção que torna-se possível meu usuário reordenar e nem redimensionar as colunas no grid em tempo de execução.

![image](https://user-images.githubusercontent.com/8163004/159841335-73d71cce-f454-47f9-bc0b-f221d372164f.png)

#### Caso de uso

As vezes a coluna corta informações do final do texto que são uteis do cliente e um simples redimensionamento melhoria a experiência dele com o sistema. 

O mesmo para reordenação de colunas, tem cenários que o mesmo consulta serve para avaliar coisas diferentes e seria util essa flexibilidade.

**Comment by jribeiroo** [comment]
Olá bom dia @fabionaspolini 
Você poderia alterar a propriedade "width" no retorno da sua API , como exemplificado no sample da Table - Airfare no portal do PO UI.

Att.

**Comment by alinelariguet** [comment]
Boa tarde @fabionaspolini, a funcionalidade de ordenação já está disponível a partir da v6.13.0

**Comment by fabionaspolini** [comment]
Obrigado @alinelariguet , achei a opção dentro do gerenciador de colunas dos exemplos, mas não achei muito intuitivo. Geralmente temos essa feature clicando a arrastando no título da coluna.

O redimensionamento de colunas pelo usuário final no frontend ainda não tem alternativa.

**Comment by alinelariguet** [comment]
Boa tarde @fabionaspolini, entendemos que o drag drop não é a melhor saída tratando-se de acessibilidade, mas de qualquer maneira esta funcionalidade será reestudada pela equipe de UX. Sobre o redimensionamento também será estudado.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
