### ISSUE TITLE
Sugestão de Melhoria em POPageLogin

### ISSUE THREAD

**Issue by dovalgomes** [po-ui/po-angular#124]
Adicionar EventEmmiter na Seleção de idioma do componente po-page-login, para externalizar o valor do idioma selecionado (pt-BR, en-US) ...

**Comment by RafaellyG** [comment]
Ola Doval!

Sugestão de melhoria encaminhada para análise.

**Comment by jhosefmarks** [comment]
Feito! PR #607 

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#360-2020-09-14

**Comment by jhosefmarks** [comment]
Feito! PR #607 

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#360-2020-09-14
