### ISSUE TITLE
PO-PageLogin: Não permite a utilização do po-combo com uma url de serviço

### ISSUE THREAD

**Issue by dovalgomes** [po-ui/po-angular#1250]
#### Reprodução
https://stackblitz.com/edit/po-ui-8kabhl?file=src/app/app.component.html

Passos para reproduzir:
1. Tente selecionar o combo com o personagem

#### Qual o comportamento atual?

Não lista os registros de um array em po-combo na utilização do po-page-login

#### Que comportamento você esperava ver?

Exibição de uma lista de personagens de acordo com o serviço passado

#### Ambiente

- PO UI: latest
- Angular: latest
- Browser(s):
  - [ X ] Chrome
  - [ X ] Firefox
  - [ X ] Edge
  - [ X ] Safari
  - [ X ] IE 11
  - [  ] Outros
- Operating System:
  - [X] Windows
  - [X] macOS
  - [X ] Ubuntu
  - [ ] Outros

**Comment by dovalgomes** [comment]
Pessoal, dei uma analisada no código fonte do POPageLogin e o 'problema' está ocorrendo por que aparentemente a parametrização para a utilização do POCombo com campo personalizado não é atendida.

![image](https://user-images.githubusercontent.com/29559080/162449338-501410da-e682-4ae1-9b4e-ab0b45a4f586.png)

**Comment by dovalgomes** [comment]
no trecho 
![image](https://user-images.githubusercontent.com/29559080/162449458-1292d3a4-6062-4ace-a873-48b82ad973b0.png)'

` if (isTypeof(value, 'object') && !Array.isArray(value) && value['property']) {`

a condição só é atendida se o retorno do serviço não for um array... mas no caso da utilização do PoCombo o retorno do serviço é um array. talvez seja o caso de implementar um else if para retornos com array.

**Comment by jribeiroo** [comment]
Bom dia @dovalgomes 

O retorno da sua API não esta no padrão de utilização de APIs da TOTVS [](https://po-ui.io/guides/api)
Caso você teste com a API disponibilizada no sample do PO-COMBO irá funcionar
https://po-sample-api.herokuapp.com/v1/heroes 

Att

**Comment by dovalgomes** [comment]
> Bom dia @dovalgomes
> 
> O retorno da sua API não esta no padrão de utilização de APIs da TOTVS https://po-ui.io/guides/getting-started Caso você teste com a API disponibilizada no sample do PO-COMBO irá funcionar https://po-sample-api.herokuapp.com/v1/heroes
> 
> Att
> 
> <img alt="po-combo" width="722" src="https://user-images.githubusercontent.com/50326350/162459665-9d0d481c-3b53-4648-af08-f09bf20aac9f.PNG">

Beleza, realizei um teste aqui e funcionou... muito obrigado!
