### ISSUE TITLE
po-page-dynamic-table: O modal está com problemas responsivos

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1253]
#### Reprodução

https://stackblitz.com/edit/po-ui-1jnqyd?file=src/app/app.component.html

Passos para reproduzir:
1. Defina alguns campos para o filtro avançado;
2. Defina as opções opções para estes campos;
3. Durante a execução altere o tamanho da interface

#### Qual o comportamento atual?
O modal para seleção do filtro avançado esta com problema responsivo e quanto maior a tela maior é o problema e isso dificulta a visibilidade das opções.

#### Que comportamento você esperava ver?
O modal para seleção do filtro avançado deve ser responsivo e dificulte a visibilidade das opções.

#### Ambiente

- PO UI: 6.11.0
- Angular: 13,0,2
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Seguem abaixo alguns prints com a simulação do problema:**

![image](https://user-images.githubusercontent.com/36740857/163284373-65693120-91e6-4951-b267-4cf469da1d43.png)
![image](https://user-images.githubusercontent.com/36740857/163284623-b3dbb909-f948-4a77-bd67-a23827ab49f4.png)
![image](https://user-images.githubusercontent.com/36740857/163284645-81c4b49e-0c3c-4979-afcd-b5e88e1735ea.png)
![image](https://user-images.githubusercontent.com/36740857/163284709-e88fca65-6c04-4a06-9da8-1d7673344da9.png)

**Comment by wsteixeira** [comment]
Olá @alinelariguet, existe alguma previsão de correção a exibição dos "radio buttons"?

**Comment by alinelariguet** [comment]
Ainda não temos @wsteixeira, houve reclamação dos usuários sobre esse comportamento?

**Comment by wsteixeira** [comment]
olá, @alinelariguet,

Sim houve, não é critico, mas quanto maior for a tela pior fica a visualização e parte do rotulo vai desaparecendo.

**Comment by renanarosario** [comment]
Comportamento já existe hoje nas versões mais atuais do PO-UI. Conforme doc abaixo:
https://po-ui.io/documentation/po-page-dynamic-table
