### ISSUE TITLE
ListView: action visible não aceita função

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#1265]
#### Reprodução
Adicionar uma ListView e em qualquer action colocar uma função para determinar o valor da propriedade visible.

#### Qual o comportamento atual?
A função não é chamada e a action sempre é exibida.

#### Que comportamento você esperava ver?
Chamar a função informada aguardando o seu valor retornado para exibir ou não a action.
Uma sugestão seria passar o item da listview que está sendo renderizada para permitir exibir ou não uma action por item e não de forma geral.

#### Ambiente

- PO UI: 6.9.0
- Angular: 13.3.0
- Browser(s):
  - [X] Chrome

- Operating System:
  - [X] Windows

**Comment by wsteixeira** [comment]
Olá @likid,

Eu fiz uma simulação e existem comportamentos diferentes com duas e três ações:

- Com duas ações não está funcionando. Quando se clica em `Change` o  `actionValue' troca o valor booleano, que funciona para o `disabled`, mas não funciona para o `visible`.
- Com três ações está funcionando. Quando se clica em `Change` o  `actionValue' troca o valor booleano, e funciona para todas a ações
[Simulação](https://stackblitz.com/edit/po-ui-fwdabz?file=src/app/app.component.ts)
