### ISSUE TITLE
Primeiros passos: Desatualizado

### ISSUE THREAD

**Issue by thiagogoncalves** [po-ui/po-angular#1267]
Precisei iniciar um novo projeto em angular e seguindo os passos conforme a documentação do site, o projeto não funciona. Ocorrem erros ao acessar a página. 

Para conseguir fazer funcionar o meu projeto, precisei ajustar o meu package.json conforme o arquivo abaixo.

`{
  "name": "my-project-app",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^13.3.4",
    "@angular/common": "^13.3.4",
    "@angular/compiler": "^13.3.4",
    "@angular/core": "^13.3.4",
    "@angular/forms": "^13.3.4",
    "@angular/platform-browser": "^13.3.4",
    "@angular/platform-browser-dynamic": "^13.3.4",
    "@angular/router": "^13.3.4",
    "@po-ui/ng-components": "^6.9.0",
    "@po-ui/ng-templates": "^6.9.0",
    "rxjs": "~7.4.0",
    "tslib": "^2.3.1",
    "zone.js": "~0.11.5"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~13.1.3",
    "@angular/cli": "~13.1.3",
    "@angular/compiler-cli": "^13.3.4",
    "@types/jasmine": "~2.8.8",
    "@types/node": "^8.9.4",
    "jasmine-core": "~3.10.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.1.0",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "~1.7.0",
    "typescript": "~4.5.2"
  }
}`

Fica como sugestão, em toda a apresentação da release do PO-UI, fazer um projeto do zero adicionando o o framework, colocando para rodar durante a apresentação.

Att.
Thiago G. dos Santos

**Comment by brunoromeiro** [comment]
Oi @thiagogoncalves consegue me informar os erros?
Fiz o processo aqui novamente do zero e não consegui simular.
Se puder me enviar o retorno do terminal/cmd ou da tela e console do navegador agradeçemos.

**Comment by totvsLiessem** [comment]
Bom dia, tambem estou com problemas de realizar o "Primeiros Passos".
Ao tentar adicionar o @po-ui/ng-components apresenta alguns erros.

Segue abaixo o print do erro e o .log gerado.

![image](https://user-images.githubusercontent.com/101
[2022-04-26T13_46_49_898Z-debug-0.log](https://github.com/po-ui/po-angular/files/8563726/2022-04-26T13_46_49_898Z-debug-0.log)
411097/165313752-c0d712ca-df07-4c36-bb5d-e3c30d442ba5.png)

**Comment by brunoromeiro** [comment]
@totvsLiessem Qual a versão do NPM que você está usando?

**Comment by thiagogoncalves** [comment]
Eu estou na 8.7.0

Em ter., 26 de abr. de 2022 15:43, Bruno Romeiro ***@***.***>
escreveu:

**Comment by totvsLiessem** [comment]
> @totvsLiessem Qual a versão do NPM que você está usando?

Package Manager: npm 8.7.0.


![Versões](https://user-images.githubusercontent.com/101411097/165508387-ceab3b57-dbc6-4ee7-bd9c-29d43b9f736b.png)
![packageJSON](https://user-images.githubusercontent.com/101411097/165508658-dd3c98de-fcbc-4dff-b2fc-c8f2d09cddfd.png)
[2022-04-27T11_29_09_412Z-debug-0.log](https://github.com/po-ui/po-angular/files/8571582/2022-04-27T11_29_09_412Z-debug-0.log)

**Comment by totvsLiessem** [comment]
Consegui identificar o erro que ocorria para mim, alterei a versão da dependência "rxjs" para a versão 7.4.0 aí tudo funcionou.
Alteração realizada na linha 23 do meu arquivo package.json
De: "rxjs": "~7.5.5"
Para "rxjs": "~7.4.0"

**Comment by brunoromeiro** [comment]
Esse erro se dá exatamente por conta dessa peerDependencia do pacote `@angular/core` com o `rxjs`, que pode ser verificado no [package.json](https://github.com/angular/angular/blob/f3eb7d9ecb9a82e7396cca658e3250e47c853153/packages/core/package.json#L19) do projeto deles.
E acontece apenas em versões do `npm` superiores à versão 6. Por este motivo sugerimos usar o `npm i -g npm@6`  e o `npm i --legacy-peer-deps`.

Mas estamos vendo uma melhor forma de resolver esse warn.

**Comment by wsteixeira** [comment]
Bom dia,

Eu uso o npm 7 e faço a instalação da dependências com `npm install --legacy-peer-deps` e funciona normalmente, já tive alguns problemas com o npm 8.

**Comment by alinelariguet** [comment]
Estamos atuando nesse ajuste porém nossa documentação atual já orienta a utilizar usar o `npm i -g npm@6` e o `npm i --legacy-peer-deps` para fazer a instalação sem erros, conforme comentário acima do @brunoromeiro.
