### ISSUE TITLE
habilitar/desabilitar escolha de idioma na po-page-login

### ISSUE THREAD

**Issue by joao-arthur-moreira** [po-ui/po-angular#127]
Propriedade para habilitar ou desabilitar a escolha do idioma na page login e fixar um idioma default

**Comment by RafaellyG** [comment]
Ola João, encaminhei sua sugestão de melhoria para análise.

Atualmente o idioma default é sempre o do navegador.

Qualquer dúvida estou a disposição.

**Comment by jhosefmarks** [comment]
Duplicate of #120

**Comment by jhosefmarks** [comment]
Feito! PR #607 

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#360-2020-09-14
