### ISSUE TITLE
<PO-DATEPICKER>: Set automático de data ao pressionar enter

### ISSUE THREAD

**Issue by lucasm16GC** [po-ui/po-angular#1279]
Segue vídeo da demonstração do BUG:
https://user-images.githubusercontent.com/96486981/168312120-3062c55a-6e79-496e-81aa-64972fcef418.mp4

Passos para reproduzir:
1. Crie um formulário com po-datepicker e po-input
2. Adicione um form group a esse formulário
3. Pressione "ENTER" em qualquer input

##############################
Ao pressionar "ENTER " em qualquer po-input
O primeiro datepicker do formlário set a data automaticamente
Não importa em qual po-input você esteja posicionado

##############################
Ao pressionar "ENTER" no input ele não sair do campo e nao set a data do primeiro datepicker automaticamente

#### Ambiente

- PO UI: 6.0.0
- Angular: Angular 13.1.1
- Browser(s):
  - [x ] Chrome
- Operating System:
  - [x ] Windows

**Comment by jcorrea97** [comment]
Olá @lucasm16GC, esse bug foi corrigido na versão 6.5.1
