### ISSUE TITLE
Usar Datepicker Range e Lookup no filtro avançado 

### ISSUE THREAD

**Issue by RomuloSRamos** [po-ui/po-angular#1288]
#### Descrição da melhoria
Possibilidade de utilizar o Datepicker range e Lookup no filtro avançado em Page Dynamic Search 

#### Caso de uso
Em tabelas com muitos dados e/ou com colunas de classificação com mais de 10 opções ou quando a coluna é referente a uma dimensão com vários campos de busca.
Ex.: Coluna produto, seria possível buscar por: nome, Código, fabricante....

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
