### ISSUE TITLE
Quebra de Linha na Notificação

### ISSUE THREAD

**Issue by danielscatigno-ncpc** [po-ui/po-angular#1294]
Estou tentando gerar uma quebra de linha na Notificação, mas não funciona
já tentei \r\n e tbm <BR>

this.poNotification.error('Erro ao cadastrar: \r\n'+ 'descrição teste');

**Comment by renanarosario** [comment]
Realizando teste internos não á quebra de linha no po-notification. E após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
