### ISSUE TITLE
po-page-dynamic-table - Adicionar parâmetros para renomear Botões

### ISSUE THREAD

**Issue by Kinsuyo** [po-ui/po-angular#1321]
Boa tarde, 

#### Descrição da melhoria
Utilizando o componente po-page-dynamic-table , surgiu a necessidade de renomear os botões para outros tipos de Ações. Lendo as documentações não consegui localizar um parâmetro para que essa mudança de nome seja feita.

#### Caso de uso
Aqui na empresa utilizamos uma tela em MVC que faz diversas manutenções na Tabela do Contas a Pagar, a exemplo da alteração em massa da data de vencimento de alguns títulos, como na encontrei a possibilidade de renomear os botões o componente neste momento não nos atende, tivemos que montar a tela componente por componente.

#### Informações adicionais
Acredito que esta melhoria possa ser aplicada a todos os componentes que tenha botões embarcados. Abaixo uma imagem ilustrando a necessidade:
 
![image](https://user-images.githubusercontent.com/42854292/176248651-1951c823-0b21-4202-80e6-d6697cf58ef1.png)

**Comment by gabrielibarbosa** [comment]
Bom dia!
Obrigada pela sugestão, iremos incluir essa issue no nosso backlog para desenvolvimento e sua priorização será avaliada pelo P.O. do projeto.
Atenciosamente.

**Comment by wsteixeira** [comment]
Olá @Kinsuyo, @gabrielibarbosa e @jribeiroo, 

Eu fiz uma contribuição que atende está sugestão!

**Comment by gabrielibarbosa** [comment]
Olá @wsteixeira, agradecemos sua contribuição!
A PR está na fila de priorização da PO para que possamos realizar a revisão e publicar.
