### ISSUE TITLE
po-breadcrumb: Action não é executada quando breadcrumb longo

### ISSUE THREAD

**Issue by JuAintablian** [po-ui/po-angular#1325]
#### Reprodução
[https://po-ui-afwku9.stackblitz.io/page-2](https://po-ui-afwku9.stackblitz.io/page-2)

Passos para reproduzir:
1. No primeiro breadcrumb, quando são exibidos os 3 pontinhos, a action setada não é executada
2. 
![image](https://user-images.githubusercontent.com/26873436/176755581-fe554c72-18ff-4454-8285-b4e2f405f2a5.png)
![image](https://user-images.githubusercontent.com/26873436/176757471-3cfaf1db-0ae0-4424-aa61-0a12da6eaf18.png)

3.  O link inicio deveria abrir a /page-0

#### Qual o comportamento atual?
Ao clicar em início, a função não é executada.

#### Que comportamento você esperava ver?
Executar a função configurada nos itens do breadcrumb

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [x] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Olá @JuAintablian, não consegui abrir o link do stackblitz porém consegui simular no labs do breadcrumb no nosso portal. Obrigada por reportar! Vamos incluir esse item no nosso backlog para correção.

**Comment by alinelariguet** [comment]
Esta correção foi liberada na v14.3.0.
