### ISSUE TITLE
po-table: Não exibe coluna do tipo `array` em `detail` e problema de alinhamento também em `detail`

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1328]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-ugdsbi?file=src/app/app.component.ts) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Carregue a aplicação de simulação;
2. Escolha um "Pedido";
3. Clique no ícone de detalhes para exibir os itens do pedido;

#### Qual o comportamento atual?
- O componente não está a "Descrição do Produto", apesar de estar presente no objeto `product.productName`;
- O componente não está alinhando a direita as colunas do tipo `number` e `currency` 

#### Que comportamento você esperava ver?
- Que o componente exiba a coluna "Descrição do Produto";
- Que o componente alinhe a direita as colunas do tipo numero e monetária; 

#### Ambiente

- PO UI: 6.14.0
- Angular: 13.0.3
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

![image](https://user-images.githubusercontent.com/36740857/177196300-c263116d-7fe1-4583-9cd1-aec6cec1d56e.png)

**Comment by jribeiroo** [comment]
Bom dia @wsteixeira como vai ? 
Obrigado por reportar, iremos atuar como melhoria pois o componente ainda não é tratado. 

Att

**Comment by jribeiroo** [comment]
Bom dia @wsteixeira ! 

Criamos essa issue no nosso issue manager interno, mas de qualquer forma estamos reabrindo, obrigado.

Att
