### ISSUE TITLE
Erro _angular_core__WEBPACK_IMPORTED_MODULE_1__.ɵɵelementStart

### ISSUE THREAD

**Issue by MarcosEllys** [po-ui/po-angular#1330]
#### Reprodução

Ao iniciar um novo projeto Angular na versão 13.1.0 e incluir o po-ui recebo erros de compilação no console e ainda parece indicar a falta de uma função

![image](https://user-images.githubusercontent.com/6751242/177399488-ef82a6ad-8e56-44ea-876b-5fe06c680eda.png)

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-u1qbhv?file=src%2Fapp%2Fapp.module.ts) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Crie um novo projeto: npx -p @angular/cli@13.1.3 ng new Angular13App
2. Adicione o po-ui: ng add @po-ui/ng-components
3. Adicione o template:  ng add @po-ui/ng-templates
4. Rode a aplicação: ng serve
5. Veja o erro :)

Ps: mesmo após incluir o angular/material (ng add @angular/material) para incluir o cdk o erro continua existindo

#### Qual o comportamento atual?

Erro de compilação no template apresentado no console.

#### Que comportamento você esperava ver?

Ver uma aplicação limpa com um scaffold de po-toolbar, po-menu e po-page-default

![code](https://user-images.githubusercontent.com/6751242/177400363-fc0e1c38-2ce6-4b77-9183-13f6e27212b5.png)

#### Ambiente

- PO UI: ^6.14.0
- Angular: ~13.1.0
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

![code](https://user-images.githubusercontent.com/6751242/177400654-f0c6ef95-ab77-4b59-a8dc-9f39be172848.png)

**Comment by jribeiroo** [comment]
Olá bom dia @MarcosEllys, não consegui reproduzir da forma que descreveu , mas olhando teus arquivos vi que a versão do seu 'typeScript' esta divergente. Eu segui os primeiros passos [https://github.com/po-ui/po-angular/blob/v6.14.0/docs/guides/getting-started.md](url) e consegui realizar com sucesso. Tente segui os passos do getting started.
