### ISSUE TITLE
Projeto não iniciado

### ISSUE THREAD

**Issue by ericfpaula** [po-ui/po-angular#1336]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. 
2. Realizada a instalação conforme primeiros passos. Não finaliza a inclusão dos componentes. Erro na imagem!

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros
![image](https://user-images.githubusercontent.com/108842806/178151539-446479ab-bd0f-4e45-92f8-d7f7b45998dc.png)

**Comment by jribeiroo** [comment]
Bom dia @ericfpaula tudo bem ? 

Vi que esta tentando adicionar o pacote do PO UI na v.14 do angular , para adicionar na v.14 é necessário rodar `ng add @po-ui/ng-components@next` com @next, ou se preferir instale a versão `npm i -g @angular/cli@13` e seguir os primeiros passos.

**Comment by ericfpaula** [comment]
Obrigado.
