### ISSUE TITLE
po-page-dynamic-table: Erro na propriedade `forceOptionsComponentType`

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1345]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-k9t8w2?file=src/app/app.component.ts) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Apenas abrir o link  (https://stackblitz.com/edit/po-ui-k9t8w2?file=src/app/app.component.ts)

#### Qual o comportamento atual?
O componente não está conseguindo importar  `ForceOptionComponentEnum`

#### Que comportamento você esperava ver?
Que componente consiga importar  `ForceOptionComponentEnum`

#### Ambiente

- PO UI: 14.0.0
- Angular: 14.0.2
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Olá @wsteixeira, vamos analisar, porém eu já peguei esse erro no stackblitz anteriormente, acredito que não tenha a ver com a nova propriedade e sim com a configuração do stackblitz, vamos verificar e logo daremos retorno.

**Comment by wsteixeira** [comment]
Olá @alinelariguet, obrigado pelo retorno!

Eu também não consegui fazer ele funcionar no Vscode!

Ele importa de:
`import { ForceOptionComponentEnum } from '@po-ui/ng-components/lib/components/po-dynamic/po-dynamic-field-force-component.enum';`

Erro:
`./src/app/registration/product/product-list/product-list.component.ts:1:0-128 - Error: Module not found: Error: Package path ./lib/components/po-dynamic/po-dynamic-field-force-component.enum is not exported from package C:\Projetos\Angular\po-sample-app\node_modules\@po-ui\ng-components (see exports field in C:\Projetos\Angular\po-sample-app\node_modules\@po-ui\ng-components\package.json)`

![image](https://user-images.githubusercontent.com/36740857/180263463-f4ac1eca-35e6-4793-b73d-d44b7c8d61e8.png)

**Comment by alinelariguet** [comment]
manda print do seu package.json por favor pra eu analisar as versões.

**Comment by wsteixeira** [comment]
Olá @alinelariguet ,

Segue conforme solicitado.
![image](https://user-images.githubusercontent.com/36740857/180310192-9e6bc131-23b4-4c0f-948b-f0b38ba0f095.png)

**Comment by alinelariguet** [comment]
Bom dia @wsteixeira,
Obrigada por reportar! Vamos analisar o problema em questão e colocá-lo no nosso backlog para correção, mas identifiquei que se for utilizado dessa forma está funcionando: [stackblitz](https://stackblitz.com/edit/po-ui-nywk6n?file=src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,package.json).
Att.

**Comment by wsteixeira** [comment]
Olá @alinelariguet,

No `stackblitz` de fato funciona, mas no Vscode não funcionou!
![image](https://user-images.githubusercontent.com/36740857/180789665-65ab1208-d34a-4b02-9117-98e83948727d.png)
![image](https://user-images.githubusercontent.com/36740857/180789530-9dd777a4-d1a2-47c8-b8cb-b8f4b4d522d6.png)

**Comment by alinelariguet** [comment]
Bom dia @wsteixeira para funcionar igual ao stackblitz é necessário colocar o tipo Array<any> nos fields. Como falei vamos realizar a correção, porém momentaneamente podemos usar dessa forma.

**Comment by alinelariguet** [comment]
Boa tarde @wsteixeira , corrigido e liberado na v14.1.0 :)
