### ISSUE TITLE
po-page-dynamic-search: initValue não funciona com mais de 1 item

### ISSUE THREAD

**Issue by flaviosrc** [po-ui/po-angular#1373]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-w2zuyz?file=src/app/app.service.ts) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Defina um campo poPageDynamicSearchFilters no poPageDynamicSearch.
2. O campo deve estar configurado com optionsMulti, optionsService e initValue.
3. Preencha o initValue com uma lista, contendo mais de 1 item.
4. Na interface, clique em Busca avançada.
5. O campo não é preenchido com os valores definidos anteriormente.

Exemplo do campo:
```
{
      property: 'hero',
      label: 'Hero name',
      optionsMulti: true,
      optionsService: 'https://po-sample-api.herokuapp.com/v1/heroes',
      initValue: ['Robert Bruce Banner', 'Steve Rogers']
}
```

#### Qual o comportamento atual?
Quando configurado um campo com multiselect e options service, o initValue não funciona com mais de 1 item.

![image](https://user-images.githubusercontent.com/47234386/185237705-fd44a2c0-16d2-48d5-92f1-be0b36663867.png)
![image](https://user-images.githubusercontent.com/47234386/185237967-f00600c5-2a01-42ca-b1f6-d6c19a4e87cf.png)

#### Que comportamento você esperava ver?
Quando configurado um campo com multiselect e options service, funcionar com mais de 1 item no initValue.

![image](https://user-images.githubusercontent.com/47234386/185238113-1deb1da9-a227-429f-b121-14ca9b5dd769.png)
![image](https://user-images.githubusercontent.com/47234386/185238160-0ce57de5-3780-46ae-a29c-1846e6f7c764.png)

No exemplo de código, aplico um método para salvar no localStorage do navegador, os filtros selecionados pelo usuário. Se o usuário selecionar apenas um item e recarregar a página, no evento onLoad normalmente é restabelecido os filtros anteriores na propriedade initValue de cada filtro. Quando o usuário seleciona mais de um item e recarrega a página, os itens da tabela continuam filtrados, os disclaimers continuam listados, porém ao clicar em Busca avançada, o campo em questão fica vazio.

#### Ambiente

- PO UI: 14.0.0
- Angular: 14.0.7
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [X] Outros

**Comment by gabrielibarbosa** [comment]
Bom dia @flaviosrc! 

Estamos analisando o cenário reportado logo lhe daremos um retorno!

Atenciosamente

**Comment by wsteixeira** [comment]
Olá @flaviosrc e @gabrielibarbosa,

Eu fiz um exemplo mais simples  e atualizei o StaclBlitz para 14.2.1 e funcionou.
[https://stackblitz.com/edit/po-ui-jwcs2a?file=src/app/app.component.ts](https://stackblitz.com/edit/po-ui-jwcs2a?file=src/app/app.component.ts)
![image](https://user-images.githubusercontent.com/36740857/185641278-39b8cb79-0f87-462f-828f-2fce2acc9042.png)

**Comment by flaviosrc** [comment]
@wsteixeira 
O problema ocorre quando usado o optionsService ao invés do options.
https://stackblitz.com/edit/po-ui-ccqd7w?file=src/app/app.component.ts

![image](https://user-images.githubusercontent.com/47234386/185655263-07b7af38-5c78-426a-9798-b614a5bab23c.png)

**Comment by wsteixeira** [comment]
Olá @gabrielibarbosa e @flaviosrc,

O problema está na requisição enviada para o backend:
- Quando é solicitado dois heróis `hero: ['Robert Bruce Banner', 'Steve Rogers']` é gerado a seguinte URL `https://po-sample-api.herokuapp.com/v1/heroes?name=Robert%20Bruce%20Banner,Steve%20Rogers` e não retorna nada:
![image](https://user-images.githubusercontent.com/36740857/185713683-c3aa230c-4e6f-47b6-8665-9414e4f56aa5.png).
- Quando é apenas um herói: `hero: ['Robert Bruce Banner']` é gerado a seguinte URL `https://po-sample-api.herokuapp.com/v1/heroes?name=Robert%20Bruce%20Banner` e retorna o herói:
![image](https://user-images.githubusercontent.com/36740857/185713898-95153fb5-6cc1-42e4-9675-f78fac1619fb.png)

**Comment by flaviosrc** [comment]
Bom dia @wsteixeira, sendo assim, acho que o problema então está resolvido.
Na documentação do Page Dynamic Search, é tratado sobre isso com a propriedade advancedFilters.
![image](https://user-images.githubusercontent.com/47234386/185810831-f17f50e5-81f5-4b7c-9521-37ac54023f14.png)

Fiz outro exemplo de implementação usando PoComboFilter (https://stackblitz.com/edit/po-ui-rp66ur?file=src/app/hero-combo.service.ts), que funcionou perfeitamente, com exeção para um detalhe, implementando a interface PoComboFilter padrão, tive um erro no console (na imagem abaixo), onde exige o método getObjectsByValues, que é implementado pela interface PoMultiselectFilter, se implementando esse método no PoComboFilter, tudo funciona sem problemas.
![image](https://user-images.githubusercontent.com/47234386/185810593-9aac82a5-c2fd-49a6-8ad6-d07e100cbd14.png)

Agradeço pela ajuda, pessoal!

**Comment by wsteixeira** [comment]
Olá @flaviosrc e @gabrielibarbosa,

Creio que o problema seja mesmo na API do PO-UI , eu ajustei novamente o exemplo [https://stackblitz.com/edit/po-ui-igcamd?file=src/app/app.component.ts](https://stackblitz.com/edit/po-ui-igcamd?file=src/app/app.component.ts) e fiz um novo teste em uma [API](https://nestjs-sample-api.herokuapp.com) que eu desenvolvi para teste mesmo e funcionou conforme esperado.

![image](https://user-images.githubusercontent.com/36740857/185814156-812b07eb-a3d6-40fd-9821-7e1c3408fcb6.png)

**Comment by gabrielibarbosa** [comment]
Olá @wsteixeira e @flaviosrc!

Agradeço a interação de vocês, ficamos muito felizes quando a comunidade interage!

Sobre o problema relatado, irei criar uma issue para nosso backlog de desenvolvimento para que possamos corrigir o erro da nossa API que vocês apontaram na aqui.

**Comment by alinelariguet** [comment]
Como visto que o problema não é um bug no componente e sim um ajuste necessário na nossa api de exemplo que fica em outro repositório vou encerrar esta issue.
