### ISSUE TITLE
<po-dynamic-form>: O evento `change` não dispara quando o combo é o primeiro campo a ser tocado e alterado

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1378]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-fmgh9f?file=src/app/app.component.ts) para reproduzir o bug relatado na issue. Este exemplo foi extraído do próprio portal. 

Passos para reproduzir:
1. Execute o StackBlitz;
2. Click diretamente no campo `State` e selecione um estado;
3. Observe que o campo `City` não habilitou conforme o esperado;
4. Click no campo `Country` e depois click no campo `State` e selecione um estado;
5. Observe que o campo `City` habilitou conforme o esperado;
6. Recarregue o StackBlitz para um novo teste;
7. Click diretamente no campo `Country` e depois click no campo `State` e selecione um estado;
8. Observe que o campo `City` habilitou conforme o esperado;
9. Conclusão, o evento `change` não dispara quando o combo é o primeiro campo a ser tocado e alterado;

#### Qual o comportamento atual?
O evento `change` não dispara quando o combo é o primeiro campo a ser tocado e alterado

#### Que comportamento você esperava ver?
O evento `change` deve disparar quando o combo for tocado e alterado independente da ordem de alteração dos campos.

#### Ambiente

- PO UI: V14.0.0
- Angular: V14.0.7
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by gabrielibarbosa** [comment]
Bom dia @wsteixeira!

Obrigada por reportar esse cenário! Irei incluir uma issue de manutenção no nosso backlog para que possamos realizar a correção no nosso componente.

Atenciosamente

**Comment by wsteixeira** [comment]
Olá @gabrielibarbosa,

Eu fiz uma contribuição para corrigir este problema e coloquei a referencia também a issue **`DTHFUI-6477`**.

**Comment by gabrielibarbosa** [comment]
Olá @wsteixeira!

Ficamos muito felizes com a sua contribuição! 
Ela está em nosso backlog para realizar o code review conforme priorização da PO do projeto.

Atenciosamente
