### ISSUE TITLE
PO-Upload: Problema 

### ISSUE THREAD

**Issue by cmregazzo** [po-ui/po-angular#1380]
#### Reprodução

Segue a reprodução do problema no Stackblitz: https://stackblitz.com/edit/po-ui-1knfjb?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts

Passos para reproduzir:
1. Adicione o componente PO-Upload no projeto;
2. Tenta alterar os métodos status, percent, etc. da "barra de progresso" de carregamento do arquivo.

#### Qual o comportamento atual?
Ao alterar os valores dos métodos status e percent, a barra de progresso de Uploado do Arquivo do PO-Upload, não é carrega em tempo de excução. Só é alterada quando se clica no Drag and Drop do PO-Upload

#### Que comportamento você esperava ver?
Quando estava utilizando a versão 5.5.0 do PO-UI e a versão 12.1.3 do Angular, ao alterar os valores de status e percent da barra de progresso do PO-Upload, a barra "corria" normalmente em tempo de execução.

Segue o video mostrando como era o funcionamento:

https://www.dropbox.com/s/c11tsbh2umnfn8z/Upload%20Arquivo%20PO-UI%20Barra%20de%20Progresso%20OK.wmv?dl=0

Segue o video mostrando como esta agora:

https://www.dropbox.com/s/delln3c824yva21/Upload%20Arquivo%20PO-UI%20Barra%20de%20Progresso%20Problema.wmv?dl=0

#### Ambiente

- PO UI: 14.3.0

- Angular: 14.1.3

- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [x] Outros
  
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by gabrielibarbosa** [comment]
Olá @cmregazzo!

Analisando o código que disponibilizou para nós no Stackblitz, pude perceber que você está acessando variáveis, que apesar de públicas, não estão disponíveis na nossa documentação. 

Sugerimos que para que você faça as adaptações que deseja no componente Po Upload utilizando as propriedades, métodos e interfaces disponíveis na documentação.
`[https://po-ui.io/documentation/po-upload]
`

**Comment by cmregazzo** [comment]
Boa tarde @gabrielibarbosa,

Muito obrigado pelo feedback, mas eu havia verificado a documentação do PO-Upload não achei nenhum método e interface disponível para atualização da Barra de Progresso de carregamento do Arquivo, por isso fiz a manipulação das variáveis diretamente no objeto.

Você pode, por favor, me informar quais seriam as propriedades, métodos, interfaces, etc., que devo usar para manipular a Barra de Progresso de Arquivo do PO-Upload?

Obrigado.

**Comment by cmregazzo** [comment]
Bom dia @gabrielibarbosa,

Continuo no aguado de uma solução para o meu problema.

Obrigado.

**Comment by cmregazzo** [comment]
Boa Tarde @gabrielibarbosa ,

Continuo no aguardo de uma solução pro meu problema.

Obrigado.

**Comment by wsteixeira** [comment]
Olá @cmregazzo,

Não sei se esta questão já foi resolvida, mas de qualquer forma se um exemplo onde a barra de progresso está funcionando https://stackblitz.com/edit/po-ui-7qnqc1?file=src/app/app.component.ts.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
