### ISSUE TITLE
po-table: p-selected / p-unselected sendo executados simultaneamente

### ISSUE THREAD

**Issue by tapiarona** [po-ui/po-angular#1392]
https://stackblitz.com/edit/po-ui-gg6np1?file=src/app/app.component.html

Passos para reproduzir:
1. Crie um componente po-table e habilita o p-selected / p-unselected, verifique que está sendo chamada as duas propriedades ao mesmo tempo, tanto a p-selected  como a p-unselected.
2. Observe o console.log que foi adicionado no exemplo do STACKBLITZ

#### Qual o comportamento atual?
Na clicar numa linha do po-table e seleciona-la é disparada as propriedades p-selected / p-unselected juntas.

#### Que comportamento você esperava ver?
Ao marcar uma linha somente a propriedade p-selected deve ser executada.
Ao desmarcar uma linha somente a propriedade p-unselected deve ser executada.

#### Ambiente

- PO UI: 14.3.1
- Angular: 14.2.0
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by tapiarona** [comment]
Issue aberta no Jira:
https://jiraproducao.totvs.com.br/browse/DTHFUI-6545

**Comment by alinelariguet** [comment]
Correção entregue e publicada na v14.6.0.
