### ISSUE TITLE
PO-Upload - Parâmetros do payload

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1395]
#### Descrição da melhoria
Estou trabalhando em um projeto de integração com o TAE(Totvs Assinatura Eletrônica) e preciso fazer um upload de arquivos, porem o `payload` gerado é incompatível com a API da aplicação. 

#### Caso de uso
Payload esperado:
![image](https://user-images.githubusercontent.com/36740857/189904994-a7cdaa8e-6e06-41dc-b542-8e4b2f76bc7e.png)

Payload gerado pelo po-upload:
![image](https://user-images.githubusercontent.com/36740857/189905203-a735915f-2e10-4d9b-806e-93ec41879456.png)

#### Informações adicionais
Seria interessante que no evento `p-upload` tivesse um atributo booleano para informar se o objeto `data` deve ser desestruturado ou não, ou criar um objeto extra se seria automaticamente desestruturado, assim seria possível passar parâmetros no mesmo nível do parâmetro `fileList'

**Comment by jkozima** [comment]
Wanderley, Boa Tarde,
Obrigado por reportar, vamos avaliar a sua solicitação em conjunto com a PO.

Abraço,

**Comment by wsteixeira** [comment]
Olá @jkozima e @alinelariguet, 

Eu posso fazer uma contribuição, mas preciso saber qual solução seria mais adequada:

- Atributo booleano para desestruturar o objeto `data`;
- Parâmetro extra com desestruturação automática;
- Outra solução;

**Comment by wsteixeira** [comment]
Olá,

Na verdade minha sugestão de encaixa mais em uma extração de atributos do objeto `data` ou de um novo objeto, objetivamente seria criar uma interação para extrair os atributos do objeto e deixar no mesmo nível do `fileList` no `payload`.

**Comment by alinelariguet** [comment]
Bom dia @wsteixeira, nesse caso seria uma quebra para quem já utiliza hoje certo? Vou dar uma olhada no padrão de API's e logo darei um retorno.

**Comment by wsteixeira** [comment]
Olá @alinelariguet,

Eu acredito que não quebra, porque a ideia seria acrescentar no objeto gerado pelo evento do `(p-upload)="uploadEvent($event)"` uma das duas opções:

- Opção 1: Acrescentar um atributo booleano opcional por exemplo `extractData`, que se informado e for igual a `true`, será feito a extração dos atributos do objeto `data` e manterá o objeto `data` vazio;
- Opção 2: Acrescenta uma tratativa para um objeto adicional e opcional por exemplo `extraParams`, que se informado, será feito a extração automática dos atributos do mesmo.

As APIs do TAE estão no link https://totvs-sign.readme.io.

**Comment by wsteixeira** [comment]
Olá @alinelariguet,

Eu me antecipei e fiz uma contribuição, caso não seja a melhor saída ,por favor me informe.
