### ISSUE TITLE
Carregar mais do PO-TABLE não funciona após ordenar uma coluna manualmente

### ISSUE THREAD

**Issue by luisfsm** [po-ui/po-angular#1410]
```
<po-page-dynamic-search  [p-title]="tituloPaginaDinamica"  [p-filters]="filters" [p-literals]="filtroAvancado"
        [p-keep-filters]="true"  (p-change-disclaimers)="filtroPorTag($event)" (p-quick-search)="buscaMonitor($event)"
        (p-advanced-search)="buscaAvancada($event)"
      >
        <po-table
          p-single-select 
          p-sort="true"
          p-striped="true"
          [p-columns]="monitorColumns"
          [p-items]="dados"
          [p-loading]="carregandoDadosGrid"
          [p-show-more-disabled] ="!habilitaBotaoCarregarMais"
          (p-show-more)="carregarConferenciaPreco(true, null)"
        >
        </po-table>
 </po-page-dynamic-search>
```

#### Qual o comportamento atual?
Ao clicar em alguma coluna para fazer a ordenação, após isso clicar em "carregar mais", não é exibido os dados novos da request. 

#### Que comportamento você esperava ver?
Aparecer os novos dados.

#### Ambiente

- PO UI:  14.5.0
- Angular: 14.1.0
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jkozima** [comment]
Boa Tarde!

@luisfsm obrigada por nos reportar, nosso time de desenvolvimento irá analisar esse comportamento.
Retornaremos assim que possível.
Abraço.

**Comment by jkozima** [comment]
Boa Tarde!

@luisfsm solicito a gentileza nos enviar uma simulação do erro reportado via stackblitz, não conseguimos reproduzir esse comportamento no componente.

Ficamos no aguardo.
Abraço.

**Comment by renanarosario** [comment]
Nas versões mais atuais já está corrigido o problema. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.
Agradecemos pela compreensão.
