### ISSUE TITLE
switch: permitir customizar os valores do model (true/false)

### ISSUE THREAD

**Issue by brunoromeiro** [po-ui/po-angular#1423]
#### Descrição da melhoria
**História:** Como usuário gostaria de ter uma opção para atribuir o valor do model do componente po-switch com o valor atribuído nas propriedades p-label-off e p-label-on.

**Especificação:** 

- criar nova propriedade p-format-model: boolean com valor default=false;
- repassar para o componente po-dynamic-form a propriedade criada no componente po-switch e verificar o validate se continua funcionando corretamente.
- obs: utilizar decorator @InputBoolean

**Critérios de aceite:**

- Testes Unitários
- Codificação (CDN e UI)
- Documentação
- Validar nos navegadores suportados
- Sample no Portal

**Comment by wsteixeira** [comment]
Olá @brunoromeiro, contribuição finalizada!
