### ISSUE TITLE
docs(modal-password-recovery): atualiza url base da API

### ISSUE THREAD

**Issue by alinelariguet** [po-ui/po-angular#1429]
#### Descrição da melhoria
Alteramos o servidor do projeto po-sample-api do heroku para o fly.io, portanto se faz necessário a troca da url base das API's.

#### Especificação
No arquivo `sample-po-modal-password-recovery-request.component.ts` é necessário alterar o valor da propriedade `urlRecovery` de: `https://po-sample-api.herokuapp.com/v1/users` para: `https://po-sample-api.fly.dev/v1/users`.

#### Informações adicionais
Necessário utilizar o prefixo docs no commit do ajuste conforme [documentação](https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md#regras-para-cria%C3%A7%C3%A3o-de-commits).

**Comment by caio-bernardo** [comment]
Oi, claro. Sobre o que seria?

> Oi @caio-bernardo, tudo bem?
> 
> Você teria um tempinho para a gente trocar uma idéia sobre essa issue?

Oi, claro. Sobre o que seria?

**Comment by brunoromeiro** [comment]
> Oi, claro. Sobre o que seria?
> 
> > Oi @caio-bernardo, tudo bem?
> > Você teria um tempinho para a gente trocar uma idéia sobre essa issue?

Faço parte do Core Team do PO UI. E queria te dar umas sugestões sobre essa issue, apesar de ser simples.
Conseguimos entrar numa call? E qual seria o melhor horário na parte da tarde?

**Comment by caio-bernardo** [comment]
> > Oi, claro. Sobre o que seria?
> > > Oi @caio-bernardo, tudo bem?
> > > Você teria um tempinho para a gente trocar uma idéia sobre essa issue?
> 
> Faço parte do Core Team do PO UI. E queria te dar umas sugestões sobre essa issue, apesar de ser simples. Conseguimos entrar numa call? E qual seria o melhor horário na parte da tarde?

Claro, 17h30 seria possível?

**Comment by brunoromeiro** [comment]
> Claro, 17h30 seria possível?

Seria sim! Me passa um email para te colocar no Invite.

**Comment by caio-bernardo** [comment]
> > Claro, 17h30 seria possível?
> 
> Seria sim! Me passa um email para te colocar no Invite.

Aqui esta: caio.2004vb@gmail.com
