### ISSUE TITLE
poTable - propriedade "tooltip" do PoTableColumn

### ISSUE THREAD

**Issue by TecoAvila** [po-ui/po-angular#1443]
Temos a necessidade de incluir uma pequena observação para uma determinada coluna da Table, com o objetivo de um melhor entendimento para o usuário da informação que está sendo apresentada.
Gostaríamos de utilizar um "tooltip" para apresentar esta observação.
Verificamos que o componente "PoTableColumn" já possui este propriedade, mas ela só é apresentada quando a coluna é do tipo "link".
Gostaríamos que o tooltip fosse apresentado independente do tipo de coluna.

**Comment by vieirawilliam** [comment]
Já passei por esse mesmo problema também. Seria mesmo interessante ter um tooltip para todos os tipos de colunas. Pois muitas das vezes, o nome da coluna precisa ser abreviado por conta da quantidade de colunas.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
