### ISSUE TITLE
PO-TABLE colspan e rowspan

### ISSUE THREAD

**Issue by danielsilvalima1996** [po-ui/po-angular#145]
#### Qual o comportamento atual?

PO-TABLE com colunas e linhas criando apenas uma célula na junção, não suportando colspan e rowspan.

#### Que comportamento você esperava ver?

mesclar linhas e colunas através do rowspan e colspan, para unir células conforme a necessidade.

#### Ambiente

- Portinari: 1.12
- Angular: 8.2.0
- Browser(s): Google Chrome
- Operating System (Ubuntu 18.04.3 LTS):

**Agradeço desde já, obrigado!**

**Comment by alinelariguet** [comment]
Boa tarde danielsilvalima1996,
Esta issue será adicionada ao nosso backlog e o P.O planejará sua entrega.
Qualquer dúvida estamos a disposição.

**Comment by danielsilvalima1996** [comment]
Boa Tarde @alinelariguet !

Obrigado pelo feedback, irei aguardar as próximas atualizações.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
