### ISSUE TITLE
PoI18nModule: ao deletar as variáveis do localStorage quebra-se o comportamento padrão

### ISSUE THREAD

**Issue by guilnorth** [po-ui/po-angular#1457]
#### Reprodução
https://stackblitz.com/edit/po-ui-kaz2dz?file=src/app/app.component.ts

Passos para reproduzir:
1. Selecione um idioma no select
2. Com as versões do PO 14.7.0 o problema ocorrerá (package.json)

#### Qual o comportamento atual?
A linguagem após refresh não é mantida pois a configuração foi apagado do localStorage (PR #1343 Issue #1331), nunca aplicando a linguagem escolhida.

#### Que comportamento você esperava ver?
Após selecionar a linguagem no select, é feito um refresh da aplicação através do próprio PoI18nService no método **setLanguage** passando a propriedade **reload** como **true**. O  refresh é necessário para aplicar a linguagem em todo o sistema (https://po-ui.io/documentation/po-i18n#setLanguage).

Como essa informação não é salva em banco de dados, somente utilizando o comportamento já existente de buscar do localStorage (feito pelo próprio processo do module/service do PO) acaba nunca alterando o idioma para o desejado.

A exclusão das variáveis **PO_DEFAULT_LANGUAGE** e **PO_USER_LOCALE** no localStorage não deveria ser feito de modo arbitrário e sim através de algum parâmetro ou método onde a aplicação desejada pudesse escolher o comportamento (se pega o idioma via browser ou via localStorage caso já exista).

Quando duas aplicações PO-UI rodam no mesmo browser isso não afeta os idiomas de cada, pois cada uma tem seu contexto de storage separado por domínio.

#### Ambiente

- PO UI: 14.7.0
- Angular: 14
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by gabrielibarbosa** [comment]
Bom dia @guilnorth!

Obrigada por reportar o erro! O @wsteixeira já abriu uma PR com os ajustes e será adicionado na nossa fila de revisão.

Obrigada @wsteixeira por contribuir com o nosso projeto :D

Atenciosamente

**Comment by alinelariguet** [comment]
Foi mergeado já o ajuste e deve ser liberado na próxima segunda-feira na v14.10.1
