### ISSUE TITLE
Multiplos retornos no Lookup

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#147]
Estou utilizando no meu projeto o componente Lookup através do componente Dynamic Form e percebi que no Lookup é possível retornar os valores apenas para um campo. Eu gostaria de sugerir uma alteração neste componente para que possa ser passado um array ou uma marcação nas columns para informar quais campos serão retornados porém não de forma concatenada como é atualmente e sim retornando cada valor para um campo.
Ex: Consulta padrão de cliente retornando o código no campo que chamou a consulta padrão e a loja no campo que estivesse na sequencia.
Isso deixaria o componente mais parecido com a funcionalidade da consulta padrão já existente no Protheus.

**Comment by alinelariguet** [comment]
Bom dia likid,
Para que possa ficar um pouco mais claro, você poderia anexar mais algum exemplo sobre a sua sugestão?
Att.

**Comment by likid** [comment]
Aline, veja o gif abaixo, é de um sistema que tenho em html5 com bootstrap onde criei uma consulta padrão, nos mesmos moldes do lookup, utilizando datatables para exibir os dados. Note que no início os campos estão em branco, exceto o estado, quando eu seleciono o registro, todos os campos são preenchidos e estes valores são preenchidos a partir da linha selecionada, é isso que estou sugerindo para o lookup.
![ezgif com-add-text](https://user-images.githubusercontent.com/10984007/68025541-d2467f80-fc8b-11e9-99a2-51c3baf4df5c.gif)

**Comment by nicoleoliveira** [comment]
Boa tarde @likid 
Atualmente no po-lookup, nós temos um evento chamado `p-selected`  que será disparado quando ocorrer alguma seleção e será passado por parâmetro o objeto com o valor selecionado.

Isso já não te ajudaria nesta funcionalidade que você nos mostrou no gif?

**Comment by likid** [comment]
Olá @nicoleoliveira , eu ainda não explorei a fundo o lookup porque estou usando ele encapsulado no dynamic form, porém se no evento p-selected ele me trouxer os dados da linha selecionada, isso me ajudaria sim, porém provavelmente terei que deixar de usar o dynamic form e terei que fazer manualmente a criação dos campos de forma dinâmica, pois o dynamic form é um ótimo template mas ele acaba limitando as funcionalidades dos componentes utilizados dentro dele.

**Comment by nicoleoliveira** [comment]
Olá @likid 
Esta issue será adicionada ao nosso banco de ideias e será analisado pelo nosso time a viabilidade da implementação.
Qualquer dúvida estamos a disposição.

**Comment by vieirajean** [comment]
Olá @likid 

 Você chegou a avaliar o comportamento do lookup no dynamic form?

 Olhando o título da sugestão, imaginei que a necessidade seria a múltipla seleção de itens no lookup. Caso concorde, podemos solicitar ao time do PO-UI para que avalie esta sugestão olhando para o requisito de múltipla seleção de registros.

Att.

**Comment by likid** [comment]
@vieirajean essa issue eu abri para que quando seja selecionado uma opção no lookup, seja possível retornar mais de um valor da mesma linha, de colunas diferentes, semelhante ao que temos na consulta padrão do Protheus. Veja o GIF que deixei acima, ao selecionar o cliente eu retorno o código, loja e nome.

**Comment by alinelariguet** [comment]
Boa noite @likid a funcionalidade de múltipla seleção no lookup foi implementada e já foi publicada nas ultimas versões, você conseguiu fazer o que era necessário com o evento p-selected comentado acima?

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
