### ISSUE TITLE
po-select: O label do option selecionado não é exibido quando o value é um enum com 0 

### ISSUE THREAD

**Issue by Closedbc** [po-ui/po-angular#1473]
#### Reprodução
O label do option selecionado não é exibido quando o value do option é um enum com 0.

https://po-ui-fp6hgi.stackblitz.io/

Passos para reproduzir:
-Coloca um po-select no html e cria um enum com dois itens, sendo um no valor 0 no value de um option do (Array<PoSelectOption>).

Ex.:

`<po-select [p-options]="options"></po-select>`

`import { Component, OnInit, VERSION } from '@angular/core'; 
import { PoSelectOption } from '@po-ui/ng-components';
import { TestesEnum } from './testeEnum.enum';`

`@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent implements OnInit {
  options: Array<PoSelectOption> = new Array<PoSelectOption>;
  ngOnInit(): void {
    this.options.push({ value: TestesEnum.teste0, label: 'Teste 0' });
    this.options.push({ value: TestesEnum.teste1, label: 'Teste 1' });
  }
}
export enum TestesEnum {
  teste0 = 0,
  teste1 = 1,
}`

#### Qual o comportamento atual?
O label do item selecionado com 0 não aparece quando se intercalar a seleção com outro.

#### Que comportamento você esperava ver?
O label deveria aparecer.

#### Ambiente

- PO UI: 14.8.0
- Angular: 14.0.2
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jkozima** [comment]
Bom dia!

@Closedbc  obrigada por nos reportar, vamos avaliar a sua solicitação.
Em breve lhe daremos um retorno.

Abraço.

**Comment by jkozima** [comment]
@Closedbc Tudo bem?

Tentamos reproduzir o cenário mencionado em nosso em nossa portal e a principio parece que esta ok. 
O link do dtackblitz enviado esta com erro e não conseguimos executa-lo, consegue nos enviar o link sem erro?
![image](https://user-images.githubusercontent.com/102690426/198704921-c6387511-5b1f-4659-8990-316366b38d73.png)

No aguardo.

**Comment by Closedbc** [comment]
Prezados, 

Acabei de abrir o link reportado anteriormente e ele está ok.

https://po-ui-fp6hgi.stackblitz.io/

**Comment by wsteixeira** [comment]
Olá @jkozima,

Para simular o problema você deve seguir os sequentes passos:

1. Selecione primeiramente a opção "Teste 1";
2. Depois selecione a opção "Teste 0", você poderá observar que a opção selecionada não aparece;

Conclusão:

1. Quando a alteração é de "branco" para "Teste 0", funciona;
2. Quando a alteração é de "Teste 1" para "Teste 0", não funciona;

Observação:
    No portal funciona porque o `value` é `string` e o problema só aparece quando o `value` é `number`.

```
<po-page-default p-title="PO UI">

  <po-select
    name="select"
    [(ngModel)]="select"
    [p-options]="options"
    (p-change)="changeEvent($event)"
  >
  </po-select>

  <hr />

  <div class="po-row">
    <po-info class="po-md-6" p-label="Model" [p-value]="select"> </po-info>

    <po-info class="po-md-6" p-label="Event" [p-value]="event"> </po-info>
  </div>


</po-page-default>
```
