### ISSUE TITLE
po-page-dynamic-search Acionando o método de busca avançada automaticamente ao preencher o objeto de filtros

### ISSUE THREAD

**Issue by thiagogoncalves** [po-ui/po-angular#1480]
Stackblitz: https://stackblitz.com/edit/po-ui-emq7en?file=src/app/app.component.ts

Passos para reproduzir:
1. Ao carregar a tela, observe no console do stackblitz a mensagem "loadData".

#### Qual o comportamento atual?
Eu tenho uma tela construída da mesma forma que no exemplo do stackblitz. Ao carregar a tela, a mesma chama 2x o método "loadData" do exemplo fazendo a chamada por 2x no back-end.

Isto ocorre porque eu defini um valor inicial para um campo qualquer da busca avançada, porém eu preciso que ao abrir a tela não execute esta busca avançada, porque estou apenas abrindo a tela e fazendo o carregamento inicial de forma manual.

#### Que comportamento você esperava ver?
Gostaria que o componente "po-page-dynamic-search" não acionasse o método advancedSearch de forma automática ao preencher a propriedade "p-filters". Somente quando fosse aplicado na modal do componente.

#### Ambiente

- PO UI: 14.0.0
- Angular: 14.0.0

**Comment by jkozima** [comment]
Bom dia!

@thiagogoncalves obrigada por nos reportar, vamos avaliar a sua solicitação.
Em breve lhe daremos um retorno.

Abraço.

**Comment by felipepetuco** [comment]
Olá @thiagogoncalves obrigado pelo contato, conforme conversamos, trazer os termos "pesquisados" sem que a consulta tenha sido realizada pode gerar um problema para a experiência do usuário, pois estaria vendo os termos que em tese teriam sido consultados porém com os dados ainda não atualizados. 

Por hora estamos encerrando esta issue  contudo caso a necessidade persistir entre em contato conosco novamente.

Atenciosamente,
Time PO-UI
