### ISSUE TITLE
Suporte a template na parametrização do componente de PoPageJobScheduler

### ISSUE THREAD

**Issue by guilnorth** [po-ui/po-angular#1491]
#### Descrição da melhoria
Permitir template customizável para o componente de PoPageJobScheduler, na etapa de **parametrização**.

Observações:
- Possibilitar uma maneira de repassar as alterações realizadas no componente de template ao `executionParameter` model do componente de PoPageJobScheduler para envio dos dados a Api.

#### Caso de uso
Temos processos em que a etapa de parametrização foge muito do suportado hoje pelo componente (suporta dynamic-form). Para esses casos, seria ideal dar a possibilidade de customizar através de template.

#### Informações adicionais
- Ao avançar para conclusão, deve pegar os dados do template e inserir no model do componente de PoPageJobScheduler .

**Comment by jkozima** [comment]
Boa Tarde!

@guilnorth  obrigada por nos reportar, vamos avaliar a sua solicitação.
Em breve lhe daremos um retorno.

Abraço.

**Comment by guilnorth** [comment]
Boa tarde @jkozima, já estou trabalhando nessa melhoria e vou abrir um PR em breve.

**Comment by alinelariguet** [comment]
Boa tarde @guilnorth essa [issue aqui](https://github.com/po-ui/po-angular/issues/1468) a ver com a sua solicitação?

**Comment by guilnorth** [comment]
Boa tarde @alinelariguet. Em parte, no caso de "adicionar parâmetros dentro do executionParameter".
Porém, nessa melhoria a alteração do 'executionParameter ' se dá quando utilizada a diretiva para template (PR #1493).

No caso da issue #1468, acredito que seria um 'beforeSend'. Também seria possível utilizar o 'p-value', alterando a função `convertToJobSchedulerInternal` para que permitisse mais alterações.
