### ISSUE TITLE
Sugestão de nova fucionalidade ao PoTab

### ISSUE THREAD

**Issue by jeterson** [po-ui/po-angular#150]
Seria muito legal e interessante, conectar o component PoTab a uma rota (router)
Por exemplo, o component PoTab teria uma propriedade `url` ou `link` de uma rota configurada.
Quando eu abrisse essa `PoTab`, o conteúdo da rota renderizaria dentro do `PoTab`

Por exemplo:
```
<po-tabs>
       <po-tab *ngFor="let tab of tabs" [p-title]="tab.title" [url]="tab.url">       
</po-tabs>
```

Adicionalmente, o tab poderia ter um botão de fechar a aba
Obs: Ao invés do *ngFor para adicionar tab ao `PoTabs`, também poderia ter uma propriedade `tabs` no `PoTabs`:
`<po-tabs tabs="PoTabsInterface"></po-tabs>`

**Comment by jeterson** [comment]
Esse framework em vuejs (que é muito bom por sinal) possui um comportamento semelhante ao que estou sugerindo:
[https://quasar.dev/vue-components/tabs#Usage](url)
ver seção Connecting to vue router

**Comment by alinelariguet** [comment]
Bom dia jeterson, 
Esta issue será adicionada ao nosso backlog e o P.O avaliará e planejará sua entrega.
Qualquer dúvida estamos a disposição.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
