### ISSUE TITLE
Sugestão de melhoria: p-clean no PoCombo

### ISSUE THREAD

**Issue by rmarmitt** [po-ui/po-angular#152]
Sugestão de melhoria

Adicionar a propriedade p-clean, que coloca o 'X' para limpar o campo, ao componente po-combo

Esta propriedade é encontrada em demais inputs, e seria bem útil no combo.

**Comment by alinelariguet** [comment]
Boa tarde rmarmitt, 
Esta issue será adicionada ao nosso backlog e o P.O planejará sua entrega.
Qualquer dúvida estamos a disposição.

**Comment by jhosefmarks** [comment]
Finalizado!
