### ISSUE TITLE
po-widget: Inputs dentro do widget nao aceitam espaço.

### ISSUE THREAD

**Issue by rodrigomagalha** [po-ui/po-angular#1526]
#### Reprodução

https://stackblitz.com/edit/po-ui-axqt5g?file=src/app/app.component.html

Passos para reproduzir:
1. Digite no imput letras e espacos

Acredito que o problema esteja no metodo em marcado em vermelho.
![image](https://user-images.githubusercontent.com/26638952/201429581-af4a07c9-272a-4239-96a0-46af63130417.png)

#### Qual o comportamento atual?
Ao digitar dentro de um INPUT qualqer, (po-input, po-text, etc..) quando se preciona a tecla SPACO nada acontece.

#### Que comportamento você esperava ver?
Espaço deveria aparecer no input

#### Ambiente

- PO UI: 14.9.0
- Angular: 14.2.1
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [x] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [x] macOS
  - [ ] Ubuntu
  - [ ] Outros

Obrigado

**Comment by alinelariguet** [comment]
Boa tarde @rodrigomagalha, obrigada por reportar. Este ítem já está no nosso backlog para correção. 
Att.

**Comment by rafaellmarques** [comment]
Situação corrigida e publicada na versão 14.11.0.
