### ISSUE TITLE
<po-decimal>: o comando de focus() não posiciona no campo correto

### ISSUE THREAD

**Issue by silvana-torres** [po-ui/po-angular#1528]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

https://stackblitz.com/edit/po-ui-zu5tvb?file=src/app/app.component.html

Passos para reproduzir:
1. Incluir um campo do tipo decimal na última posição do formulário
2. Incluir o comando para dar nome ao campo no TS
3. Incluir o nome no HTML do campo
4. Ao inserir uma validação e executar o comando this.nomeDoCampo?.focus(); o cursor não é posicionado no campo. A mesma regra funciona se o campo a ser selecionado não seja o último do formulário

#### Qual o comportamento atual?
O comando focus não funciona quando o campo é o último da tela

#### Que comportamento você esperava ver?
O comando focus funcionar em qualquer campo da tela

#### Ambiente

- PO UI: 14
- Angular: 14.0.2
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Boa tarde @silvana-torres, eu testei no stackblitz incluído e tanto o focus quanto o cursor são posicionados corretamente, inverti as ordens e funcionou certinho também, você poderia fazer um vídeo do comportamento reportado?

**Comment by anabye** [comment]
Comentário para encerramento da issue.

Após análise do código fornecido, verificamos que o método público focus() está funcionando conforme esperado, aplicando o foco no componente de acordo com a condição definida.

Evidência:
[Descrição: focus aplicado no combo peso 2, quando seu value for maior que a do peso 1]
![issue-1528](https://github.com/user-attachments/assets/3b7f9fb4-6291-4123-87b1-39b545284018)


Entendemos que o comportamento ocorre conforme o esperado e por isso a issue será encerrada. Caso precise de um novo apoio, basta abrir uma nova issue, que estaremos a disposição.
