### ISSUE TITLE
<po-combo>:  lista não é recarregada após limpar o campo

### ISSUE THREAD

**Issue by dgo-angelo** [po-ui/po-angular#1529]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

https://stackblitz.com/edit/po-ui-6vaw3t?file=src/app/app.component.html

Passos para reproduzir:
1. Preencher o valor no campo
2. Limpar o valor do campo através do botão "Limpar" ou pela opção de limpeza do próprio po-combo. 

#### Qual o comportamento atual?
Após limpar o campo e clicar novamente no combo a lista não é carregada (não é feita uma nova requisição à api), sendo necessário clicar 2 vezes no campo.

Este comportamento foi detectado nos cenários abaixo:
- Quando p-infinite-scroll é igual a true
- Quando  a api retorna o hasNext igual a false

#### Que comportamento você esperava ver?
Que após a limpeza do campo a lista fosse preenchida (que seja feita uma nova requisição à api) corretamente, sem a necessidade clicar 2 vezes no campo.

#### Ambiente

- PO UI: 14
- Angular: 14.0.2
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Boa tarde @dgo-angelo, obrigada por reportar, vamos incluir esta issue no nosso backlog para correção.
Att.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada analisado que já houve conclusão da solicitação.
