### ISSUE TITLE
Sugestão de melhoria para DynamicForm

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#154]
Ao configurar os campos a serem exibidos no DynamicForm, é possível informar a um determinado campo o seu searchService para que seja criado um campo do tipo lookup, porém, observando o componente lookup é possível ver que nele é possível enviar parametros junto a requisição (p-filter-params), mas no dynamicform não temos a opção de informar este parametro do lookup. Parametros na requisição feita pelo lookup são extremamente importantes pois em muitos casos é possível que os dados solicitados precisam ser filtrados por algum valor do formulário, exemplo: escolher um estado e no lookup para escolher os municípios trazer somente os municípios do estado selecionado. 
Sem esta opção eu não vejo outra forma de filtrar a consulta feita.

**Comment by likid** [comment]
Eu fiz uma alteração local no fonte do portinari e consegui criar esse recurso que sugeri nesta issue. Alterei apenas 2 arquivos e inclui uma linha em cada um. Como eu poderia contribuir para o projeto? Posso criar um PR com esta minha alteração?

**Comment by rmarmitt** [comment]
> Eu fiz uma alteração local no fonte do portinari e consegui criar esse recurso que sugeri nesta issue. Alterei apenas 2 arquivos e inclui uma linha em cada um. Como eu poderia contribuir para o projeto? Posso criar um PR com esta minha alteração?

Crie uma pull request!

**Comment by nicoleoliveira** [comment]
Olá @likid 

Você pode criar uma PR para contribuição :)
E então será analisado pelo nosso time a viabilidade da implementação para este componente.
Qualquer dúvida estamos a disposição.

**Comment by jhosefmarks** [comment]
Será tratado na issue #161.

**Comment by jhosefmarks** [comment]
Resolvido na issue #161

Changelog: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#1230-2020-01-17
