### ISSUE TITLE
Po-Chart: Hook afterDraw

### ISSUE THREAD

**Issue by cleitontb** [po-ui/po-angular#1541]
#### Descrição da melhoria
Gostaria de ter a possibilidade de chamar uma determinada função após o término do desenho do gráfico em tela

#### Caso de uso
Migrar projetos que usam outras libs de gráficos e utilizam desses hooks (Ex: ChartJS).

Exemplo: 

```
chartOptions: PoChartOptions = {
  legend: true,
  axis: {
    minRange: 0,
    maxRange: 100,
    gridLines: 5,
  },
  hooks: [
    { "afterDraw": this.handleAfterDraw }
  ]
};
```

#### Informações adicionais
Se já existe não encontrei na documentação

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
