### ISSUE TITLE
po-rich-text: Comportamento incorreto dos botões 

### ISSUE THREAD

**Issue by charlesreitz** [po-ui/po-angular#1551]
Pessoal, o rich-text-text teve seu comportamento alterado, os botões ficaram fora e está gerando um posicionamento incorreto do componente, poderia verificar? 

![image](https://user-images.githubusercontent.com/1248135/204092288-7b52241e-255f-41c5-95fc-3a2933b6555a.png)

https://po-ui.io/documentation/po-rich-text

**Comment by rafaellmarques** [comment]
Bom dia @charlesreitz , obrigada por reportar, vamos incluir esta issue no nosso backlog para correção.
Att.
