### ISSUE TITLE
diversos componentes: inconsistencia no uso de string e String

### ISSUE THREAD

**Issue by dfelippa** [po-ui/po-angular#1566]
Em diversos componentes é utilizado String bem como string. Especilamente:
Array\<String\>
bem como 
Array\<string\>

#### Qual o comportamento atual?

A utilização de String não é indicada.

#### Que comportamento você esperava ver?

Substituir o uso de String por string

#### Ambiente

- PO UI: 14.12.1

**Comment by rafaellmarques** [comment]
Boa tarde @dfelippa , tudo bem?
Obrigado por reportar, vamos analisar e assim que possível lhe daremos um retorno.

Att.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
