### ISSUE TITLE
<po-lookup>: não aplica disclaimer ao digitar valor manualmente

### ISSUE THREAD

**Issue by gabriesgomes** [po-ui/po-angular#1575]
#### Qual o comportamento atual?
Ao digitar um id existente e pressionar tab, deveria aplicar o format com os dados do objeto retornado pela requisição.
Mas após finalizar a requisição o campo é limpo tendo o comportamento de como se não tivesse encontrado o objeto.

<img width="438" alt="Screenshot_77" src="https://user-images.githubusercontent.com/55770651/207450014-53481dd7-66de-4d05-9304-bba267eb7a45.png">
<img width="414" alt="Screenshot_78" src="https://user-images.githubusercontent.com/55770651/207450262-bfa97f35-d2ee-467a-a10a-4850d0506e97.png">

#### Que comportamento você esperava ver?

Ao finalizar a requisição com evento da tecla tab o componente deveria aplicar o disclaimer com os dados do objeto encontrado de acordo com a propriedade format definida no mesmo. Imagem abaixo é um exemplo que foi preciso abrir a modal e selecionar o objeto com o mouse.
![image](https://user-images.githubusercontent.com/55770651/207450718-bf4b2a6a-d309-4f52-99a0-c49801403a9f.png)

#### Ambiente

- PO UI:  14.12.0 
- Angular:  14.0.2 
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by rafaellmarques** [comment]
Boa tarde @gabriesgomes , tudo bem?
Obrigado por reportar, vamos analisar e assim que possível lhe daremos um retorno.
Você poderia disponibilizar um cenário próximo do que tem através do `stackblitz` para simularmos?

Att.

**Comment by rafaellmarques** [comment]
A issue está sendo encerrada pois o relator já solucionou a questão.
