### ISSUE TITLE
po-tab: String fixo "Mais" em portugues

### ISSUE THREAD

**Issue by eternauta123** [po-ui/po-angular#1577]
Acessar um po-tabs que tenga mais tabs dos que suportados pelo largo da janela
Mostra o botao "Mais" sem traducao
- PO UI: 14.12.2
- Angular: 14
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [x] Safari
  - [x] IE 11
  - [x] Outros
- Operating System:
  - [x] Windows
  - [x] macOS
  - [x] Ubuntu
  - [x] Outros

**Comment by yantotvs** [comment]
Aproveitando a issue, o botão "Mais" não foi projeto para funcionar com o evento de click? só consigo ver as opções no dropdown quando dou foco e aperto "enter"

**Comment by jcorrea97** [comment]
@yantotvs em qual versão você não está conseguindo apertar o "Mais" com evento de click?

**Comment by yantotvs** [comment]
@jcorrea97 como meu projeto está usando o Angular 13 estamos na versão 6.9

**Comment by wsteixeira** [comment]
Olá, 

Segue uma simulação da situação reportada pelo @yantotvs.
[Link simulação](https://stackblitz.com/edit/po-ui-yocgwn?file=src/app/app.component.html)

**Comment by jcorrea97** [comment]
@wsteixeira obg pela simulação. @yantotvs não sei se entendi direito o problema, quando eu aperto o "mais" com o click ou via teclado (tab e enter) o dropdown aparece normalmente. 

No link do @wsteixeira e no exemplo do portal também funciona via click : https://po-ui.io/documentation/po-tabs

**Comment by wsteixeira** [comment]
Olá @jcorrea97,

Eu fiz uma contribuição para a tradução da palavra "Mais" quando o navegador estiver em outro idioma.
