### ISSUE TITLE
po-dynamic-form: Campos iniciados com disabled = true não iniciam desabilitados

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#1584]
#### Reprodução
Criar um array com um conjunto de campos marcados como desabilitados para serem utilizados no dynamic-form e verificar que nenhum campo será iniciado como disabled.

https://stackblitz.com/edit/angular-ivy-2bnfak?file=src/app/app.component.html

#### Qual o comportamento atual?

Os campos não inicializam desabilitados

#### Que comportamento você esperava ver?

Campos desabilitados na inicialização

#### Ambiente

- PO UI: 14.12.2
- Angular: 14 e 15
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jcorrea97** [comment]
Olá @likid, na versão 15 do angular houve uma alteração na forma como é tratado internamente o estado de "disabled" dos componentes customizados. 
Para resolver esse problema você pode inserir a seguinte configuração no import do seu app.module:
```
FormsModule.withConfig({
      callSetDisabledState: 'whenDisabledForLegacyCode',
    }),
```
Alterei o seu stackblitz caso queira testar novamente: 
https://stackblitz.com/edit/angular-ivy-d6u2ua?file=src%2Fapp%2Fapp.module.ts

**Comment by likid** [comment]
@jcorrea97 com esta configuração no import funcionou o carregamento com os campos em disabled, porém, seria possível isso já funcionar de forma padrão no dynamic-form ou sempre terá que ser feito este import na aplicação?

**Comment by jcorrea97** [comment]
@likid vamos analisar pra por internamente quando disponibilizarmos a próxima versão

**Comment by MarcosEllys** [comment]
Alguma novidade @jcorrea97 ?

**Comment by jcorrea97** [comment]
@MarcosEllys as próximas releases serão a partir da segunda semana de janeiro.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
