### ISSUE TITLE
po-upload: ScrollBar

### ISSUE THREAD

**Issue by cmregazzo** [po-ui/po-angular#1587]
Após atualizar o PO-UI 14.12.2, as ScrollBar de componentes como po-upload, po-widget, etc., criada na tela pelo PO-UI quando os objetos ultrapassam a altura determinada, não estão seguindo o padrão de cores e modelos.

Segue print da ScrollBar no componente po-upload com a versão 14.12.2 do PO-UI:

https://www.dropbox.com/s/bm3ccl2eu4m5doz/PO-UI_ScrollBar_14_12_2.png?dl=0

Segue link do StackBlitz para repodução:

https://stackblitz.com/edit/po-ui-phkj2a

Na versão do PO-UI 14.0.0, as ScrollBars dos componente po-upload, po-widget, etc., estavam seguindo corretamente as cores e padrão do PO-UI.

Segue print da ScrollBar no componente po-upload com a versão 14.0.0 do PO-UI:

https://www.dropbox.com/s/j3g91id1req3cug/PO-UI_ScrollBar_14_0_0.png?dl=0

Segue link do StackBlitz para repodução:

https://stackblitz.com/edit/po-ui-26emvp

#### Passos para reproduzir:
1. Crie um projeto PO-UI com a ultima versão;
2.  Inclua um componente do tipo po-upload;
3. Selecione vários arquivos até que seja ultrapassa a área de arquivos selecionados e seja criado a ScrollBar

#### Qual o comportamento atual?

A ScrollBar de componentes como po-upload, não está seguindo o padrão de modelo e cor do PO-UI

#### Que comportamento você esperava ver?

A ScrollBar do po-upload, deveria estar igual a ScrollBar do po-page-default.

#### Ambiente

- PO UI: 14.12.2
- Angular: 15.0.4
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros

- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jcorrea97** [comment]
Boa tarde @cmregazzo.
Vamos analisar e assim que possível lhe daremos um retorno.

**Comment by rafaellmarques** [comment]
Boa tarde @cmregazzo , tudo bem?
O componente `po-upload` utiliza o componente interno `po-container`, esse componente teve sua aparência remodelada seguindo as definições de estilo e acessibilidade do Animalia DS e por isso a scrollbar está seguindo o modelo padrão de cada navegador. O mesmo ocorre com o componente `po-widget` e outros componentes que já tiveram suas aparências alteradas.
Att.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
