### ISSUE TITLE
Componente Po Grid 

### ISSUE THREAD

**Issue by aksilvaa** [po-ui/po-angular#159]
#### Reprodução

https://portinariui-jcqdn4.stackblitz.io/

Passos para reproduzir:
1. Realizar o Double Click ou apertar a tecla enter na célula desejada.

#### Qual o comportamento atual?
Tentei reproduzir o componente e  após a seleção do campo escolhido é apresentado o Erro 'nativeElement' no console, após isso decide verificar a documentação e está apresentando o mesmo erro conforme print abaixo:
![image](https://user-images.githubusercontent.com/50679891/68213390-3c2b9580-ffba-11e9-8d01-8385a2379ad0.png)

#### Que comportamento você esperava ver?

Permitir  a edição e confirmação da linha conforme documentação.

#### Ambiente

Portinari: 1.12
Angular: 8.2.0
Browser(s): Google Chrome
Operating System : Windows

**Poderiam me instruir se a utilização do componente esta correta?**

**Comment by nicoleoliveira** [comment]
Boa tarde @aksilvaa  
Conseguimos simular este bug.
Esta issue será adicionada ao nosso backlog e o P.O. planejará sua entrega.
Qualquer dúvida estamos a disposição.

**Comment by danielsilvalima1996** [comment]
## Boa tarde! ##

#### Ambiente

Portinari: 1.26.0
Angular: 8.0.0
Browser(s): Google Chrome
Operating System : Linux Ubuntu

Eu estava com o mesmo problema, o componente quebrava ao apertar o enter ou clicar duas vezes. Eu dei um fork no projeto e modifiquei, creio que tenha resolvido esse erro.

Como devo proceder para que vocês avaliem se foi resolvido?

Desde já agradeço!

**Comment by jhosefmarks** [comment]
Pode seguir nosso guia de contribuição: https://github.com/po-ui/po-angular/blob/master/CONTRIBUTING.md

**Comment by leonardoquintania** [comment]
Bom dia, efetuei o teste hoje e estou com o mesmo erro.

core.js:6210 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at PoGridCellComponent.onEditCell (po-ui-ng-components.js:28862)
    at PoGridCellComponent.dblclick (po-ui-ng-components.js:28828)
    at PoGridCellComponent_ng_template_2_Template_div_dblclick_0_listener (po-ui-ng-components.js:2920)
    at executeListenerWithErrorHandling (core.js:21888)
    at wrapListenerIn_markDirtyAndPreventDefault (core.js:21930)
    at HTMLDivElement.<anonymous> (platform-browser.js:976)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
    at Object.onInvokeTask (core.js:41709)
    at ZoneDelegate.invokeTask (zone-evergreen.js:398)
    at Zone.runTask (zone-evergreen.js:167)

Gostaria de saber uma previsão para correção, fiz um teste no exemplo disponibilizado no site e está com o mesmo erro. 

https://po-ui.io/documentation/po-grid

**Comment by jhonyeduardo** [comment]
Bom dia,

Item resolvido na PR https://github.com/po-ui/po-angular/pull/711, será liberado na próxima versão.
