### ISSUE TITLE
po-list-view: Dificuldade em visualizar inicio e fim do componente

### ISSUE THREAD

**Issue by matiasdanielz** [po-ui/po-angular#1594]
#### Descrição da melhoria
Ao utilizar o componente po-list-view com 02 ou mais itens, há uma dificuldade em perceber quando começa e quando termina o componente, resultando em dificuldades para diferenciar os "cards" numa lista com dezenas de itens, segue imagem de exemplo:

![image](https://user-images.githubusercontent.com/91097480/211871524-d8d67418-ac7e-4f15-98f4-c88a7a50dc82.png)

Acredito que será útil adicionar uma opção de usar bordas ou sombreamento nos cards da po-list-view.

#### Caso de uso
Lista de po-list-view com dezenas de items

**Comment by rafaellmarques** [comment]
Boa tarde @matiasdanielz , tudo bem?
Muito obrigado pela sugestão, incluiremos essa issue em nosso backlog.

Att.
