### ISSUE TITLE
Adicionar a propriedade "readonly" ao componente po-switch

### ISSUE THREAD

**Issue by matiasdanielz** [po-ui/po-angular#1604]
#### Descrição da melhoria
Gostaria que o botão po-switch recebesse a propriedade readonly, principalmente para utilizar no po-dynamic-form.

#### Caso de uso
Apresentar diversos dados de uma tabela em formato somente visualização.

#### Informações adicionais
Visto que desejo apresentar os dados com a "borda input" do po-dynamic-form, nao gostaria de utilizar o po-dynamic-view nesse caso.

Utilizei um "po-modal" para apresentar diversos itens de uma tabela em formato somente leitura, porém, o unico tipo de campo que ainda é possivel alterar é o po-switch.

#### Imagem de exemplo
![image](https://user-images.githubusercontent.com/91097480/213706565-ff8e312b-89bc-46d0-88ca-9ac383830591.png)

**Comment by rafaellmarques** [comment]
Boa tarde @matiasdanielz , tudo bem?

Muito obrigado pela sugestão, iremos avaliar e assim que possível lhe daremos um retorno.

Att.

**Comment by wsteixeira** [comment]
Boa tarde,

@matiasdanielz a propriedade `p-disabled` não ajudaria neste caso?

Att.

**Comment by matiasdanielz** [comment]
Bom dia,

@wsteixeira, realmente, parece que vai atender a minha necessidade, agradeço pela sugestão.

att,

**Comment by felipepetuco** [comment]
Como houve retorno positivo, estamos encerrando a issue.
