### ISSUE TITLE
[Dynamic Form] - Opção para pular linha

### ISSUE THREAD

**Issue by DavidMarques1331** [po-ui/po-angular#1606]
Implementar a opção "newLine" ao "PoDynamicFormField" para a possibilidade de trabalhar melhor o layout de um formulário

![image](https://user-images.githubusercontent.com/71023291/213951456-b18d353c-1949-4602-b0c1-2c94333c0adf.png)

**Comment by rafaellmarques** [comment]
Bom dia @DavidMarques1331 , tudo bem?

Para organizar o layout do formulário dessa maneira você pode utilizar uma das seguintes propriedades para controlar o espaçamento de cada componente, [ `gridSmPull`, `gridMdPull`, `gridLgPull`, `gridXlPull`]. Essas propriedades adicionam ao componente uma margem a direta preenchendo o espaço restante da tela e movendo o próximo componente para a  linha seguinte.

Por exemplo:
```
...
{ property: 'email', divider: 'CONTACTS', gridColumns: 6, icon: 'po-icon-mail', gridXlPull: 6 },
{ property: 'phone', mask: '(99) 99999-9999', gridColumns: 6 },
{ property: 'address', gridColumns: 6 },
...
```

Fico no aguardo pra saber se isso te ajuda, qualquer dúvida estamos a disposição.

Att.

**Comment by felipepetuco** [comment]
Issue encerrada por não haver interação do autor nos últimos 35 dias.
