### ISSUE TITLE
Filtro do Lookup

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#161]
Pessoal,
estou analisando ainda o uso do filtro no componente lookup e a forma que está desenvolvido o componente, se levar em consideração que em um projeto cria-se um componente para gerar o formulário de forma dinâmica e através de metadados como o dynamic-form, ao tentar informar o filtro para o lookup utilizando um valor do model, não é possível fazer utilizando um valor vindo de um metadados.
Ex: se eu passar para o [p-filter-params] o valor "{estado:dados.CAMPO_DO_ESTADO}" de forma chumbada no template, o lookup vai buscar o valor do meu model toda vez que fazer a requisição, porém não é dessa forma que deveria funcionar, pois eu quero no meu metadados retornar as expressões de filtro que eu gostaria pois a geração do form é dinamica e para cada form eu posso ter diferentes lookups com parametros de filtros diferentes.
Dito isso acima eu gostaria de saber como é possível fazer isso, receber a expressão de uma string ou um object e passar para o lookup, pois estou tentando de todas as formas e só funciona quando é hardcoded. Será que a forma de passagem de filtros não deveria ser alterada para facilitar, podendo por exemplo chamar uma função para nela possa ser retornado um objeto contendo os parametros para filtro?

**Comment by jhosefmarks** [comment]
@likid você pode usar o https://stackblitz.com/fork/portinariui para exemplificar melhor o que você está tentando fazer?

Não ficou muito claro para mim.

**Comment by likid** [comment]
@jhosefmarks , eu não consigo criar um exemplo prático no stackblitz porque eu não tenho um backend para simular a dificuldade que eu tive, mas imagine fazer a criação dos campos de um form dinamicamente como é feito com o dynamic form que recebe os dados dos campos de um json que poderá vir de um banco de dados e nestes dados se for necessário informar um filtro para o componente lookup, retornando uma string no json e esta informação do filtro for um dado de outro campo, ele não interpreta a string como um objeto como se fosse colocado no p-filter-param da forma que eu exemplifiquei na abertura da issue.

Na aplicação que estou fazendo eu resolvi chamando uma função e passando a expressão nela e na função eu vou um eval() para buscar os valores do model, porém eu não sei como poderia ser melhorado isso no portinari para não ser desta forma ou se fazendo um eval() seria a única forma (apesar de que deve-se evitar o uso do eval).

**Comment by jhosefmarks** [comment]
@likid entendi o que você quer, e realmente hoje não tem como você fazer isso direto pelo componente.

Estamos trabalhando na melhoria desse componente e vamos incluir sua necessidade no "pacote" de implementações que estamos pensando para o mesmo.

Obrigado pela contribuição.

**Comment by jhosefmarks** [comment]
Issue duplicada #154.

**Comment by jhosefmarks** [comment]
Resolvido na issue #161

Changelog: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#1230-2020-01-17
