### ISSUE TITLE
<po-page-dynamic-search>: <diversos bugs ao utilizar po-page-dynamic-search + po-table dentro de po-modal>

### ISSUE THREAD

**Issue by matiasdanielz** [po-ui/po-angular#1613]
#### Reprodução
Utilizar "po-page-dynamic-search" + "po-table" dentro de po-modal

StackBlitz
https://stackblitz.com/edit/po-ui-947ahh?file=src/app/app.component.html

Passos para reproduzir:
1. Criar po-modal
2. Criar Botão chamando a abertura do po-modal
3. Criar po-page-dynamic-search
4. Inserir uma po-table

#### Qual o comportamento atual?
1. Segundo a documentação do "po-page-dynamic-search" a propriedade "p-title" seria opcional, porém, ao tentar usar o componente sem a propriedade "p-title", ele simplesmente nao renderiza.
2. Visto que nao consigo deixar a propriedade "p-title" do po-page-dynamic-search vazia, costumo deixar assim: p-title=" ", porém, ao tentar fazer isso dentro do po-modal, a renderização do "po-page-dynamic-search" fica zoada, conforme foto:
![image](https://user-images.githubusercontent.com/91097480/215167829-6e0b000b-0ad4-4916-a2c2-635f9aa884f7.png)
3. Por algum motivo que nao compreendi, ao utilizar o "po-page-dynamic-search" + "po-table" dentro do "po-modal", o "po-modal" aumenta drasticamente o height do componente de forma desnecessaria, conforme foto:
![image](https://user-images.githubusercontent.com/91097480/215168434-83c88e2f-8ff2-4904-a6ff-242b4de09a23.png)

#### Ambiente

- PO UI: 14.12.1
- Angular:  14.2.10
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jkozima** [comment]
Boa tarde!

@matiasdanielz Tudo bem?
Todos os componentes do tipo PO-Page não foram desenvolvidos para serem utilizados dentro de outras páginas ou modal, justamente por impactar em questões de usabilidade e acessibilidade.
Indicamos a montagem do template com componentes usados separadamente
podemos ajudar em mais alguma coisa?
