### ISSUE TITLE
look-up: Exibir modal quando houver mais de um registro quando pesquisa realizada por input

### ISSUE THREAD

**Issue by GuilhermeLopesTotvs** [po-ui/po-angular#1624]
#### Descrição da melhoria
A melhoria seria para quando digitar no campo do Look-up e realizar a pesquisa, que seja aberto o modal e apresente dentro do mesmo, o resultado da pesquisa.

#### Caso de uso
Preciso realizar a pesquisa de um cliente/fornecedor, utilizando o componente de look-up, ao digitar no campo do look-up sem realizar a abertura do modal. Ao terminar de digitar no campo e mandar realizar a pesquisa, caso haja, mais de um resultado, deve abrir o modal do look-up, já com os resultados da pesquisa quando digitad.

#### Informações adicionais
![image](https://user-images.githubusercontent.com/101195334/216130966-33c51ba4-955e-445d-bd35-28e232caab76.png)

Caso haja apenas um registro:
![image](https://user-images.githubusercontent.com/101195334/216131604-2e570007-bede-4f85-9d6e-7c5826b628c4.png)

Caso haja mais de um registro, abrir o modal com o resultado da pesquisa:
![image](https://user-images.githubusercontent.com/101195334/216131939-852a65fa-58cc-4dd6-8987-3ec81564b7cf.png)

**Comment by gabrielibarbosa** [comment]
Bom dia @GuilhermeLopesTotvs! 

Estamos analisando o cenário reportado e assim que possível iremos lhe dar um retorno.

Atenciosamente

**Comment by gabrielibarbosa** [comment]
Bom dia @GuilhermeLopesTotvs!

Analisamos a melhoria proposta e entendemos que o comportamento que você deseja reproduzir não convém com o uso do componente Lookup.
Uma sugestão que deixamos é que você utilize o componente Combo e quando selecionado o item abra um modal e apresente a tabela conforme descrito na sua issue.

Atenciosamente

**Comment by felipepetuco** [comment]
Issue encerrada por não haver interação do autor nos últimos 35 dias.
