### ISSUE TITLE
Comportamento do search do po-page-list para evitar múltiplos disparos

### ISSUE THREAD

**Issue by kalelchavestotvs** [po-ui/po-angular#1629]
#### Descrição da melhoria
Hoje no po-page-list temos uma busca rápida que quando disparada não possui nenhum comportamento padrão para evitar que uma nova pesquisa seja disparada novamente quando a tecla enter fica pressionada. Isso poderia vir a ser uma melhoria do componente evitando que algum serviço seja congestionado e até mesmo derrubado por conta de uma tecla "enter" pressionada.

**Comment by gabrielibarbosa** [comment]
Bom dia @kalelchavestotvs!

Agradecemos o contato conosco, iremos analisar a melhoria sugerida no componente PO Page List e lhe daremos um retorno!

Atenciosamente

**Comment by jkozima** [comment]
Boa tarde @kalelchavestotvs!
Tudo bem?
Entendemos que o componente hoje já permite esse tratamento do lado da aplicação.
É possível verificando o valor emitido e não executando a chamada do serviço, caso o valor emitido seja repetido.
Isso resolve a sua questão?

Ficamos no aguardo.
Abraço.
