### ISSUE TITLE
Lookup: Clique em botões não dispara a validação do lookup/atualização do campo de valor e seu estado final fica desabilitado

### ISSUE THREAD

**Issue by fpetuco** [po-ui/po-angular#1647]
Temos uma page list contendo um disclaimer e o botão de busca avançada que abre um componente filho com os campos de filtros avançados.
O componente filho envia e recebe os parâmetros de filtros avançados para o componente pai.
1 - Envia quando o usuário preenche o respectivo campo;
2 - Recebe, quando há alguma mudança no disclaimer;

Porém se for informado algum valor em um lookup da pesquisa avançada e em seguida clicar em um botão, não será emitido ao componente pai o objeto que contém os parâmetros de pesquisa atualizados. Vimos que nesse cenário, os eventos (ngModelChanges) e (p-change) do lookup são lidos após o evento de click do botão.

Para resolver esse problema aplicamos um tratamento no evento (change) do lookup, desta forma foi possível pegar o valor do elemento do DOM e atualizar o objeto antes do click no botão: 
"this.filter = {...this.filter, [attribute]: e.srcElement.value}"

O quê está sendo observado agora é que o evento (p-change) do lookup está sendo executado duas vezes e seu estado final está sendo sempre como desabilitado. 
Isso deve estar ocorrendo porque o objeto é retornado para o componente pai, que consequentemente, atualiza o disclaimerGroup. 
No disclaimerGroup há um tratamento no change dele que atualiza a relação dos parâmetros que compõem os filtros avançados e desta forma já atualiza o respectivo objeto no componente filho, porém, como mencionei, está resultando na passagem pelo (p-change) do lookup uma segunda vez deixando o estado final do componente como desabilitado.

Deixei o p-disabled dinâmico com a ideia de forçar então seu estado final para desabilitado, mas não teve efeito, o estado final permanece como desabilitado.

#### Resumindo: 
Se informar um valor no lookup e clicar em outro elemento como um input de outro lookup, o uso da diretiva [(ngModel)] será suficiente para atualizar o objeto a ser retornado ao componente pai.
Se informado um valor no lookup e clicar em um botão, não há leitura do (p-change) do lookup, sendo necessário customizar no evento (change) do componente. Porém, nesse caso, quando o componente recebe o valor por [(ngModel)] o seu estado final está ficando como desabilitado.

Qual seria o evento correto para aplicar a mudança de estado do respectivo componente deixando-o habilitado?

#### Qual o comportamento atual?
Clique em botões não dispara a validação do lookup/atualização do campo de valor e seu estado final fica desabilitado.

#### Que comportamento você esperava ver?
Que o evento (p-change) do componente fosse observado já na perda do foco do elemento.

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by alinelariguet** [comment]
Bom dia @fpetuco, tudo bem?
Segue stackblitz com sugestão de implementação, caso não atenda nos envie por favor o fonte para que possamos analisar melhor a situação.
https://stackblitz.com/edit/po-ui-r4necb?file=src%2Fapp%2Fapp.component.html,src%2Fapp%2Fapp.component.ts
PS: a modal do lookup não está abrindo no stackblitz, mas abre normalmente no app local.
Att.

**Comment by fpetuco** [comment]
Olá @alinelariguet obrigado pelo retorno, estou disponibilizando um exemplo do nosso cenário em https://stackblitz.com/edit/angular-sr2jvq?file=src%2Fapp%2Fapp.component.ts
A sua proposta resolve o problema de habilitar novamente o lookup contudo voltamos ao problema inicial de o usuário ter que clicar em algum lugar na modal para habilitar o campo e então clicar no botão Aplicar.
A necessidade é: Ao informar um valor no lookup e em seguida clicar no botão Aplicar, o lookup precisa estar com seu valor atualizado antes de ser processado o evento de click do botão.
