### ISSUE TITLE
po-number: Remover alteração dos valores através do scroll

### ISSUE THREAD

**Issue by kalelchavestotvs** [po-ui/po-angular#1650]
#### Descrição da melhoria
Remover alteração dos valores do po-number através do scroll evitando erros que podem passar desapercebido pelos usuários.

#### Caso de uso
Adicionar o po-number em tela, informar um valor, colocar o mouse em cima e rolar o scroll do mouse.

#### Informações adicionais
No nosso sistema em questão, há processos extremamente críticos onde o usuário irá informar um range de valores o qual aquele processo será executado.
Como são processos complexos e críticos é muito comum que a tela possua campos suficientes para gerar um scroll vertical a tela onde normalmente o usuário irá utilizar o scroll do mouse para interagir.
Caso o mouse passe por algum campo po-number esse valor pode ser alterado para mais ou menos conforme for o scroll do momento. Somando essa situação a diversos parâmetros que a tela poderá ter, poderá ocorrer um erro de processo por engano.
Em alguns momentos ocorre agendamento do processo e caso esse erro ocorra o usuário terá o trabalho adicional de desfazer todos os agendamentos que ele cadastrou.
Com isso solicito a possibilidade de removermos essa característica do po-number.
Junto estou anexando uma tela exemplo para melhor entendimento.

![image](https://user-images.githubusercontent.com/82214796/222137064-c4d2b75b-316c-4ab7-96c4-06fa6ff00d68.png)

**Comment by alinelariguet** [comment]
Boa tarde @kalelchavestotvs, tudo bem?
qual versão do PO UI? tentamos simular aqui e não conseguimos simular o comportamento reportado.
Att.

**Comment by kalelchavestotvs** [comment]
Oi @alinelariguet esqueci de mencionar o problema ocorre no Firefox e pode ser simulado no portal do po-ui mesmo.
No chrome, brave... está ok

**Comment by jkozima** [comment]
Boa Tarde @kalelchavestotvs 

Tudo bem?
Conseguimos reproduzir essa ocorrência no navegador firefox, incluiremos a issue em nosso backlog para correção.

Abraço.

**Comment by kalelchavestotvs** [comment]
Bom dia, ótimo!
Vocês tem uma previsão para a correção? Ela é um pouco crítica para nós.
