### ISSUE TITLE
Componentes Time e DateTime

### ISSUE THREAD

**Issue by ghost** [po-ui/po-angular#1651]
#### Descrição da melhoria
1 - Novo componente, estilo Datepicker, para informar o horário
2 - Novo componente, estilo Datepicker, para informar a data e o horário

#### Caso de uso
Necessidade de informar a hora da execução ou data e hora de execução

#### Adicional
Criar um novo componente ou então adicionar um parâmetro ao Datepicker para a exibição da seleção de hora

**Comment by jkozima** [comment]
@DavidMarques1331 boa tarde!

Tudo bem?
Obrigada pela sua solicitação de melhoria.
Hoje já temos um estudo definido por UX para implementar o horário timepicker, essa solicitação consta em nosso backlog para implementação futura.
Mas ainda não temos definição sobre de estudo para informar data e horário, encaminharemos para UX avaliar.

Abraço.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.

Será tratado na issue [DTHFUI-7811] (https://jiraproducao.totvs.com.br/browse/DTHFUI-7811).
