### ISSUE TITLE
Table: Erro no posicionamento do tooltip de um elemento dentro da tabela.

### ISSUE THREAD

**Issue by LeandroLBBernardes** [po-ui/po-angular#1654]
**Descrição:** 
Ao passar o mouse por cima de um item na tabela que possui o atributo [p-height] é definido no html, o posicionamento do tooltip fica fora de posição. Ele aparece muito a baixo de onde deveria aparecer, segue abaixo um exemplo, onde meu mouse estava posicionado no segundo item da tabela:

**Evidencia do problema:**
![ERRORPOUI](https://user-images.githubusercontent.com/49132764/223716919-7e6d2415-a5ce-47ce-8529-2293bf2d2de2.png)

**OBS:** Esse erro só aparece quando setamos no html o atributo [p-height], em tabelas que não possuem esse atributo esse erro não acontece.

**Comment by jkozima** [comment]
Boa Tarde @LeandroLBBernardes 

Tudo bem? 
Para conseguir te ajudar nesse apoio, precisamos das informações abaixo:
- PO UI: 
- Angular: 
- Browser(s):
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

No aguardo, abraço.

**Comment by LeandroLBBernardes** [comment]
Bom dia, segue abaixo as informações solicitadas

Versão PO UI: 14.4.0
Versão Angular: 14.2.3
Browser(s): Edge
Operating System: Windows

**Comment by anabye** [comment]
Uma breve correção: a correção foi disponibilizada na versão 14.7.1 do PO-UI. Agradecemos a todos pelas contribuições.
