### ISSUE TITLE
Possibilidade de desabilitar cache no po-combo

### ISSUE THREAD

**Issue by yantotvs** [po-ui/po-angular#1656]
#### Descrição da melhoria
Gostaria que existisse uma forma de não guardar em cache as opções do componente po-combo quando ele estiver utilizando um serviço.

#### Caso de uso
No meu projeto existe uma diretiva que integra a API do Google com o componente de combo. Quando uma das opções ficam salvas em cache como não é feita a busca novamente dessas informações os valores ficam incompletos e causa inconsistência.

**Comment by jkozima** [comment]
Boa Tarde @yantotvs 

Tudo bem?
No componente PO-Combo não existe cache configurado, esse componente foi desenvolvido para sempre realizar uma nova requisição.
Nesse caso, é necessário limpar o cache do próprio navegador.

**Comment by yantotvs** [comment]
E essas linhas fazem o que exatamente?

https://github.com/po-ui/po-angular/blob/08cddee24d6f8b2219a6e46d9dbe5318cc53b848/projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts#L262

https://github.com/po-ui/po-angular/blob/08cddee24d6f8b2219a6e46d9dbe5318cc53b848/projects/ui/src/lib/components/po-field/po-combo/po-combo-base.component.ts#L243

**Comment by yantotvs** [comment]
Link para o stackblitz: https://angular13-bootstrap-zgwmtt.stackblitz.io/

Evidencia no vimeo: https://vimeo.com/808475745/128da80cce

Mostrei ao vivo pro Jorge Nicholas Ribeiro também via gmail.
