### ISSUE TITLE
po-modal: warning na build

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#1660]
Esta issue é referente ao po-style, mas como o pessoal não olha muito as issues lá, resolvi abrir aqui.

nas classes `po-modal-footer` e `po-modal-footer-basic` a propriedade `justify-content` está `end` e ao efetuar a build do angular, é emitido um warning dizendo para alterar para `flex-end`. Fiz a alteração diretamente no node_modules e o warning sumiu, portanto acredito que basta fazer esta alteração no repositório po-style para solucionar este warning.

#### Ambiente

- PO UI: 15.3.0
- Angular: 15.2.2
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

**Comment by rafaellmarques** [comment]
Boa tarde @likid , tudo bem?

Estamos encerrando essa issue pois a correção foi publicada na versão 15.7.1.

Att.
