### ISSUE TITLE
Table Row Template - Sugestão

### ISSUE THREAD

**Issue by danielsilvalima1996** [po-ui/po-angular#167]
**Table Row Template - Sugestão de melhoria**

#### Qual o comportamento atual?
Ao adicionar um Table Row Template é possível apresentar informações adicionais, clicando e abrindo o tanto que for necessário, e para fechar clicando nas que estão abertas.

#### Que comportamento você esperava ver?
Um sugestão de melhoria seria abrir apenas uma por vez, e ao clicar em outra linha, a que estivesse abertura seria fechada automaticamente.

#### Ambiente

- Portinari: 1.15.0
- Angular: Angular 8
- Browser(s): Chrome
- Operating System (Ubuntu):

**Comment by jhosefmarks** [comment]
@danielsilvalima1996 sugestão anotada!

**Comment by danielsilvalima1996** [comment]
@jhosefmarks obrigado!

fico no aguardo.

**Comment by jhonyeduardo** [comment]
Bom dia @danielsilvalima1996 

Item entregue na release 4.0.0-rc.1
