### ISSUE TITLE
page-dynamic-table: Botão de Detalhe não está funcionando

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1677]
#### Reprodução funcionando na versão 15.1.0
https://stackblitz.com/edit/po-ui-6x2pmq?file=src/app/app.component.html

Passos para reproduzir:
1. Entre no portal
2. Selecione o componente Page Dynamic Table
3. Selecione o exemplo "PO Page Dynamic Table - Users"
4. Click no botão "Details"

#### Qual o comportamento atual?
Componente não exibe o modal detalhe, creio que depois que houve a mudança no componente "Popup".

#### Que comportamento você esperava ver?
Componente deve exibir o modal de detalhe.

#### Ambiente

- PO UI: 15.5.1
- Angular: 15.0.3
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by rafaellmarques** [comment]
Bom dia @wsteixeira , tudo bem?

Obrigado por reportar, vamos analisar e assim que possível daremos um retorno.

Att.
