### ISSUE TITLE
po-lookup: Componente de loading não aparece na modal de busca ao acionar o enter

### ISSUE THREAD

**Issue by thiagosantostotvs** [po-ui/po-angular#1679]
Passos para reproduzir:
1. Abrir o site do po-ui e exibir os exemplos do lookup.
2. Pressionar o F12 e clicar na aba de Rede/Network.
3. Selecionar a velocidade da internet para "Conexão 3G Lenta"
4. Posicionar no exemplo "PO Lookup - Hero Reactive Form"
5. Clicar na lupa do campo "Hero".
6. Buscar no campo de pesquisa rapida por "Peter Park" e pressione o botão "enter".
7. Buscar no campo de pesquisa rapida por "Peter Park" e clique na lupa de pesquisa.

#### Qual o comportamento atual?
Ao realizar a pesquisa através do botão "enter", a tela de loading/carregando não aparece, para o usuário final parece que o sistema não está realizado a busca.

#### Que comportamento você esperava ver?
Preciso que seja exibida a tela de loading/carregando sempre assim como acontece quando voce clica na lupa de pesquisa.

#### Ambiente

- PO UI: 15.5.0
- Angular: 15
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [X] macOS
  - [X] Ubuntu
  - [x] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by rafaellmarques** [comment]
Bom dia @thiagosantostotvs , tudo bem?

Obrigado por reportar, vamos analisar e assim que possível daremos um retorno.

Att.
