### ISSUE TITLE
Melhoria PO-Menu

### ISSUE THREAD

**Issue by zinum11** [po-ui/po-angular#1684]
#### Descrição da melhoria
No PO Menu quando você altera o estado de esconder `p-collapse="true"` para expandir `p-collapse="false"` não desalinhar os elementos do menu.

#### Caso de uso
Ao analisar o CSS dos itens `.po-menu-item` do menu percebi que eles não estavam respeitando os dimensionamentos realizados nos mesmos, isso deve-se por causa dos textos (_label_) dos próprios itens. Para solucionar isso apenas acrescentei ao CSS do item o propriedade `white-space: nowrap;`

`.po-menu-item {
    white-space: nowrap;
}`

Se possível, por favor adicionar a propriedade `white-space: nowrap;` ao CSS para funcionar mais limpo e fluído.

Obrigado

**Comment by rafaellmarques** [comment]
Bom dia @zinum11 , tudo bem?

Muito obrigado pela sugestão de melhoria, vamos analisar e assim que possível lhe daremos um retorno.

Att.

**Comment by renanarosario** [comment]
Após uma análise detalhada das versões mais recentes do PO-UI, confirmamos que o desalinhamento informado não ocorre mais. Sendo assim, a issue de apoio do GIT será finalizada.

Agradecemos pela compreensão.
