### ISSUE TITLE
DatePicker: Quando o formato é iso8601 Extended é acrescido um segundo a mais

### ISSUE THREAD

**Issue by CarlosPhilippe** [po-ui/po-angular#1725]
#### Reprodução
StackBlitz: https://stackblitz.com/edit/po-ui-krznzv

Passos para reproduzir:
1. Escolher a data pelo componente Datepicker
2. Verificar o ngModel, estará com o 1 segundo a mais

#### Qual o comportamento atual?
Quando configurado o formato iso8601 Extended, é adicionado 1 segundo na data disponível no ngModel do componente.
Valor atual: 2023-05-26T00:00:01-00:00
Timestamp: 1685059201

#### Que comportamento você esperava ver?
Quando configurado o formato iso8601 Extended, não deveria ser adicionado nenhum segundo a mais ou retirado segundo algum da data passada pelo componente
Valor esperado: 2023-05-26T00:00:00-00:00
Timestamp: 1685059200

No TReports a data é trafegada sempre em iso8601 e a hora é levada sempre em consideração, por isso qualquer segundo faz a diferença tanto nas listagens, quanto nos filtros.

Observação
Na versão 15.8.0, ainda persiste o comportamento.
No Site do PO-UI é reproduzivel.
No Github https://github.com/po-ui/po-angular/blob/master/projects/ui/src/lib/components/po-field/po-datepicker/po-datepicker-base.component.ts linha 120 está provavelmente o motivo da falha
protected hour: string = 'T00:00:01-00:00';

#### Ambiente

- PO UI: 14.4.0 
- Angular: 14.1.0
- Browser(s):
  - Chrome
  - Firefox
  - Edge
  - Opera
- Operating System:
  - Windows

**Comment by CSimoesJr** [comment]
Bom dia, @CarlosPhilippe, tudo bem?

Agradecemos por reportar, nosso time estará analisando e responderemos o mais breve possível!
 

Att.

**Comment by rafaellmarques** [comment]
Boa tarde @CarlosPhilippe , tudo bem?

Vamos incluir essa issue em nosso backlog.

Att.

**Comment by CarlosPhilippe** [comment]
Ok Rafael, agradecido...
