### ISSUE TITLE
Page Dynamic Table: opções do Outras Ações sem estilo

### ISSUE THREAD

**Issue by gtrabach** [po-ui/po-angular#1729]
#### Qual o comportamento atual?
Ao criar mais de três botões em uma Page Dynamic Table, os mesmos estão perdendo o estilo e ficando com um tamanho menor do que o normal.

![image](https://github.com/po-ui/po-angular/assets/46979335/de7b5b8e-4f44-4c62-a272-d713f441102a)

#### Que comportamento você esperava ver?
Que fosse idêntico ao da documentação, com os estilos dos botões permanecendo o mesmo:

![image](https://github.com/po-ui/po-angular/assets/46979335/86596894-711a-4a85-b421-5e971811eeb3)

#### Ambiente
- PO UI: 15.9.0
- Angular: 15.2.9
- Browser(s):
  - [ ] Chrome
  - [ x ] Firefox
  - [ x ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações
Tentei simular via StackBlitz mas retornou o seguinte erro:

![image](https://github.com/po-ui/po-angular/assets/46979335/20509f81-bd7e-46ea-acc4-45c0aa4275e0)

Nunca usei essa ferramenta e sou iniciante em Abgular, então não consegui entender o motivo: https://stackblitz.com/edit/po-ui-unftp2?file=src%2Fapp%2Fapp.component.html

**Comment by jcorrea97** [comment]
Boa tarde @gtrabach esse erro ocorre quando o HttpClientModule não está sendo importado no módulo do seu componente.
Criei um exemplo simples utilizando a ultima versão do po-ui e a aparência está normal. Se puder passar as versões do seu package.json podemos te ajudar melhor.

https://stackblitz.com/edit/po-ui-1jnj6h?file=src%2Fapp%2Fapp.module.ts

**Comment by gtrabach** [comment]
Ei @jcorrea97, obrigado pela ajuda mas foi uma noobada minha. Esqueci de instalar a @po-ui/style. Instalei aqui e deu tudo certo.
