### ISSUE TITLE
page-login: p-environment alinhado com alinhamento a esquerda

### ISSUE THREAD

**Issue by danilosalve** [po-ui/po-angular#1743]
#### Reprodução
Ao atualizar o PO-UI para a versão 15.9.1 a "tag" utilizada na propriedade **p-environment** do componente **po-page-login** esta com alinhamento a esquerda.

O problema também é reproduzido no portal do po-ui.

![image](https://github.com/po-ui/po-angular/assets/42416870/d9f0c157-e593-4047-9d5c-5044cb18fc4a)

Passos para reproduzir:
1. No portal selecionar o componente po-page-login
2. Na aba de exemplos, preencher o campo enviroment.

#### Qual o comportamento atual?
alinhamento do enviroment a esquerda

#### Que comportamento você esperava ver?
alinhamento do enviroment a centralizado.

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by felipepetuco** [comment]
Olá @danilosalve vimos que você abriu a issue no Jira também. Vamos dar andamento ao atendimento por lá e havendo novidades atualizo a issue.
Atenciosamente,
