### ISSUE TITLE
Ocultar label <po-button>

### ISSUE THREAD

**Issue by dudamesacasa** [po-ui/po-angular#1771]
#### Descrição da melhoria
Ocultar label do <po-button> quando o tamanho do p-icon + p-label for maior que o tamanho do conteúdo do botão para que o label não fique para fora do botão conforme exemplo abaixo:
![image](https://github.com/po-ui/po-angular/assets/117955293/ea9d7c9b-27ef-46ed-be1c-127ca34aeb5d)

#### Caso de uso
Descreva os casos de uso que a melhoria permitiria.

#### Informações adicionais
Link exemplo StackBlitz: https://stackblitz.com/edit/po-ui-hvow5s?embed=1&file=src%2Fapp%2Fapp.component.html

**Comment by anliben** [comment]
Boa Tarde @dudamesacasa, tudo bem?

Iremos analisar sua solicitação, caso seja do seu interesse também podes enviar uma contribuição para nossa biblioteca

Attr.

**Comment by rafaellmarques** [comment]
Boa tarde @dudamesacasa , tudo bem?

Muito obrigado pela sugestão, vou levar a issue para o nosso backlog e analisar.

Att.

**Comment by anliben** [comment]
Boa Tarde @dudamesacasa, tudo bem?

Não seguimos nosso fluxo de desenvolvimento nesta issue, pois analisado pelo PO não coincide com o produto!

Attr.
