### ISSUE TITLE
Page Dynamic Table: remover gerenciador de colunas

### ISSUE THREAD

**Issue by gtrabach** [po-ui/po-angular#1782]
Bom dia!

Existe alguma forma de remover o botão de gerenciador de colunas de um Page Dynamic Table? Objetivo: não exibir o botão, assim, não permitindo o usuário alterar a visibilidade e ordem dos campos.

![gerenciador_colunas_poui](https://github.com/po-ui/po-angular/assets/46979335/935f358f-f52c-4d40-baa9-037c565f7d33)

Na discussão a seguir https://github.com/po-ui/po-angular/discussions/1781, o Jhosef informou para utilizar a propriedade `p-hide-columns-manager`, mas ela não surte efeito na Dynamic Table, apenas na Table convencional.

**Comment by felipepetuco** [comment]
Boa tarde, obrigado pelo seu contato, é sempre bom e muito importante a sua interação frente às mudanças e avanços que o po-ui está buscando. Vamos encaminhar essa issue para nosso backlog para estendermos o recurso de ocultar o gerenciador da tabela também para o Page Dynamic Table.

Atenciosamente,

**Comment by jkozima** [comment]
Bom dia!
A correção foi aplicada na versão 16.3.0 do PO UI.
Obrigada.
