### ISSUE TITLE
protheus-lib-core: falta de documentação

### ISSUE THREAD

**Issue by dabraga** [po-ui/po-angular#1788]
Boa tarde ,

Falta de informação para uso do protheus-lib-core .
Segui a documentação desses links:
- https://tdn.totvs.com.br/display/public/framework/Protheus-lib-core
- https://tdn.totvs.com.br/display/public/framework/FwCallApp+-+Abrindo+aplicativos+Web+no+Protheus
Porém o exemplo não mostra o uso de cada função disponivel no framework . Poderiam enviar um documentação mais detalhada , ou um git de exemplos com as funcionalidade do framework

**Comment by felipepetuco** [comment]
Olá obrigado pelo contato :D ! 
O time que mantém estas páginas é o time de framework Protheus e não o PO-UI, então o quê você pode fazer é entrar em contato com o fremework Protheus solicitando mais informações para esclarecer suas dúvidas.

Atenciosamente.

**Comment by felipepetuco** [comment]
Entendi. Não atuamos sob o uso de cada função disponível no framework. Atuamos apenas nos componentes PO-UI.

**Comment by dabraga** [comment]
@felipepetuco  obrigado
