### ISSUE TITLE
Sugestão Rich Text

### ISSUE THREAD

**Issue by JoseCamilo** [po-ui/po-angular#179]
#### Melhoria
Adicionar na barra de ferramentas uma opção de formato de texto.
Nesta opção, o usuário posiciona o cursor em uma linha, e informa se ela é um Titulo, subtitulo 1 2 3, paragrafo, citação e outros.

#### Caso de uso
Com essa melhoria teremos uma formatação de texto mais rica :) 
Quando enviamos via javascript uma string já com essa formatação, o Rich Text aceita e formata muito bem isto. A melhoria iria divulgar isto.

**Comment by jhosefmarks** [comment]
Sugestão anotada!

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
