### ISSUE TITLE
<po-menu>: Problema shortLabel

### ISSUE THREAD

**Issue by cmregazzo** [po-ui/po-angular#1790]
Boa tarde,

Fiz a atualização do meu projeto PO-UI para versão 15.15.0, e após tal atualização, o menu não está exibindo o descritivo informado no Short Label, quando o mesmo está "fechado".

Segue link de reprodução no StackBlitz: https://po-ui-y6jzea.stackblitz.io

Passos para reproduzir:
1. Criei um projeto padrão PO-UI;
2. Insira o <po-menu> com os icones e os respectivos Shorts Label.

Qual o comportamento atual?
O comportamento atual é que o Short Label não está sendo exibido no menu "fechado".

Que comportamento você esperava ver?
O comportamento que esperava acontecer, é exibir o Short Label com o meu "fechado".

O problema pode ser reproduzido no próprio exemplo utilizado na página oficial do PO-UI, já que tal problema também está ocorrendo no site oficial:

https://po-ui.io/documentation/po-menu

Ambiente:

- PO UI: 15.15.0
- Angular: 15.1.2
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [x] Outros

- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

Att,

Cristian Regazzo

**Comment by rafaellmarques** [comment]
Bom dia @cmregazzo , tudo bem?
A shortLabel não tem mais uso quando o menu está recolhido.
Recentemente o componente foi ajustado com as definições do AnimaliaDS e o comportamento está previsto em handoff.

Qualquer dúvida estamos a disposição.

Att.

**Comment by cmregazzo** [comment]
Boa tarde,

Obrigado pelo feedback.

Ficou bem "estranho" esse comportamento padrão.

Obrigado.
