### ISSUE TITLE
Table: Problemas com a ordenação das colunas

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1793]
#### Reprodução

Passos para reproduzir:
1. Usar o portal do PO-UI
2. Selecionar um exemplo do componente Table

#### Qual o comportamento atual?
Ao clicar na coluna da tabela a mesma não esta ordenando.

#### Que comportamento você esperava ver?
Ao clicar na coluna da tabela a mesma deve realizar a ordenação conforme as setas.

#### Ambiente

- PO UI: V15.15.0
- Angular: Versão do Portal
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by MaiconPutton87** [comment]
Também identifiquei o mesmo problema.  Caso ajude na analise o problema só ocorre quando não definida a propriedade "**p-height**", caso esteja definida o **p-sort** funciona corretamente.

**Comment by jkozima** [comment]
Bom dia!
Correção liberada na versão 16.1.0
https://jiraproducao.totvs.com.br/browse/DTHFUI-7608
