### ISSUE TITLE
po-table: Opção de ocultar o botão excluir ao selecionar linhas

### ISSUE THREAD

**Issue by gtrabach** [po-ui/po-angular#1799]
#### Descrição da melhoria
Ao utilizar a versão mais recente do POUI, no componente Po Table com seleção de linhas, está sendo exibido um botão Excluir e está permitindo excluir linhas da tabela.

Porém na documentação não existe nada especificando como fazer para não exibir este botão.

#### Caso de uso
Determinadas tabelas, onde o intuito é apenas para exibição de dados, perdem o sentido visto que o usuário pode manipular as informações sem permissão.

#### Informações adicionais
Anteriormente (versão 15.12.1) essa opção não era exibida. Na documentação, exemplo PO Table - Airfare (https://po-ui.io/documentation/po-table), é possível simular essa situação.

![261096928-81765cbe-2386-4509-a026-6c37f82ad17b](https://github.com/po-ui/po-angular/assets/46979335/fe908b09-64e8-405b-beb6-b70683e8c2c1)

**Comment by CSimoesJr** [comment]
Boa tarde @gtrabach, tudo bem?

Você pode utilizar a propriedade [p-hide-batch-actions]="true" para esconder essa ação da sua tabela.
Qualquer dúvida estamos à disposição!

Att.
