### ISSUE TITLE
Sugestão Rich Text Tabelas

### ISSUE THREAD

**Issue by MoisesOsti** [po-ui/po-angular#180]
Melhoria
Adicionar na barra de ferramentas uma opção de edição de tabelas.
Nesta opção, o usuário consegue incluir tabela, linhas ou colunas em tabelas existentes.

Caso de uso
Quando enviamos via javascript uma string já com uma tabela, o Rich Text aceita e formata muito bem isto. A melhoria iria divulgar isto.

**Comment by jhosefmarks** [comment]
Sugestão anotada!

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
