### ISSUE TITLE
po-table: alinhamento de colunas do tipo number

### ISSUE THREAD

**Issue by lucas-pollus** [po-ui/po-angular#1801]
#### Reprodução
Utilizar o Labs da própria documentação

Passos para reproduzir:
1. Para reproduzir, fui na Documentação da Table 
2. Na parte da Po Table Labs
3. Marquei o checkbox Number

#### Qual o comportamento atual?
Observei que as colunas da tabela quando utilizado o tipo 'number' o alinhamento do label fica na direita, porém o valor da coluna está alinhado a esquerda. No própria documentação é possível notar esse comportamento. Esse é o comportamento padrão ou se trata de bug? Porque quando se tem várias colunas seguidas do tipo 'number' fica um pouco confuso entender as informações.

#### Que comportamento você esperava ver?
Esperava que tanto o label como o valor da coluna estivessem alinhados a direita.

#### Ambiente

- PO UI: 15.15
- Angular: 15
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by rafaellmarques** [comment]
Bom dia @lucas-pollus , tudo bem?

Obrigado por reportar, vamos analisar e incluir uma issue em nosso backlog.

Att.

**Comment by jkozima** [comment]
Bom dia!
Correção liberada na versão 16.2.1
https://jiraproducao.totvs.com.br/browse/DTHFUI-7668

**Comment by lucas-pollus** [comment]
Muito obrigado!
