### ISSUE TITLE
po-lookup-modal: Erro na traducao russo

### ISSUE THREAD

**Issue by eternauta123** [po-ui/po-angular#1810]
Abrir o lookup em russo e verificar que a traducao do botao CONFIRMAR nao esta correta em russo. Além de nao comecar com maiuscula.

Passos para reproduzir:
1. Abrir o lookup em russo e verificar que a traducao do botao CONFIRMAR nao esta correta em russo. Além de nao comecar com maiuscula.

#### Ambiente

- PO UI: Any
- Angular: Any
- Browser(s):
  - [x ] Chrome
  - [ x] Firefox
  - [ x] Edge
  - [ x] Safari
  - [ x] IE 11
  - [ x] Outros
- Operating System:
  - [ x] Windows
  - [ x] macOS
  - [ x] Ubuntu
  - [ x] Outros

**Comment by felipepetuco** [comment]
Obrigado por reportar, vamos análisar e dar o retorno o mais breve possível.
