### ISSUE TITLE
Table: Propriedade `width` está se comportando apenas como largura mínima.

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1824]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-3chsnb?file=src%2Fapp%2Fapp.component.html) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Reproduza o exemplo sem a propriedade `p-items`
2. Reproduza o exemplo com a propriedade `p-items`

#### Qual o comportamento atual?
A propriedade `width` está se comportando como largura mínima da coluna.

#### Que comportamento você esperava ver?
A propriedade `width` deveria se comportar como largura da coluna, independente do conteúdo, pois a documentação não especifica largura mínima. No caso do conteúdo superar a largura definida o mesmo deve apresentar reticências, caracterizando conteúdo incompleto.

#### Ambiente

- PO UI: 15.0.0
- Angular: 15.0.4
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

![image](https://github.com/po-ui/po-angular/assets/36740857/576a8bd9-4fe9-4f9b-b3fb-9fb3844066ee)

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by CSimoesJr** [comment]
Boa tarde @wsteixeira, tudo bem?

Criaremos uma issue em nosso backlog para analisarmos e corrigirmos!

Att.

**Comment by wsteixeira** [comment]
olá @CSimoesJr,

 Creio que a versão 16.13.0 resolveu o assunto!
![image](https://github.com/po-ui/po-angular/assets/36740857/95cca9b0-5f66-4cd7-8b7f-d08792dc1cb9)

**Comment by anliben** [comment]
Bom Dia @wsteixeira, tudo bem?

Liberamos a correção desta issue na versão: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#16130-2024-01-29

Attr.
