### ISSUE TITLE
Upload: Componente incompatível com o Fluig

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1825]
#### Descrição da melhoria
O componente não é compatível com a API de [Upload do Fluig](https://api.fluig.com/latest/content-management/swagger-ui/#/Documents/documentUploadAndPublish), pois é necessário ajustar a URL para cada arquivo no momento do upload. O evento (p-upload) não permite a substituição da URL, provavelmente ela está armazenada em uma variável local no momento do upload. Eu fiz alguns ajustes e consegui realizar o upload, mas esta alternativa não é possível para uploads múltiplos.

#### Caso de uso
Ajustar o evento `(p-upload)`para que permita sobrescrever a `URL`.

#### Informações adicionais
Segue um print da API de upload do Fluig.
![image](https://github.com/po-ui/po-angular/assets/36740857/c1fd6ffb-2ed7-4845-af29-d3b8550cc1c8)

**Comment by felipepetuco** [comment]
Bom Dia @wsteixeira , obrigado por reportar essa necessidade e pela contribuição, iremos analisar e retornar uma resposta.

Attr.
