### ISSUE TITLE
Page Default: O atributo `visible` da propriedade `actions` não está funciona como função

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1836]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-fbfcra?file=src%2Fapp%2Fapp.component.ts) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Execute o stackblitz enviado para sinulação;
2. Alterne o componente `switch` entre falso e verdadeiro;
3. Observe que o `visible` não funciona com o `disabled`;

#### Qual o comportamento atual?
O `visible` fica sempre `true`, ou seja, não tem o comportamento como função conforme documentado. 

#### Que comportamento você esperava ver?
O comportamento do `visible` deveria ser como o `disabled` já que ambos aceitam `boolean | Function`.

#### Ambiente

- PO UI: 15.1.0
- Angular: 15.0.5
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by anliben** [comment]
Bom Dia @wsteixeira, tudo bem?

Obrigado por reportar, em breve iremos analisar e retornar uma resposta.

Attr.
