### ISSUE TITLE
po-popover : instabilidade no funcionamento

### ISSUE THREAD

**Issue by GuilhermeMesquita** [po-ui/po-angular#1854]
Seguindo as etapas da documentação, ao realizar um simples teste, me deparei com os erros abaixo:

![image](https://github.com/po-ui/po-angular/assets/19232571/141ee354-21bc-4ded-95dc-8f797a590ee4)

![image](https://github.com/po-ui/po-angular/assets/19232571/37544022-8f68-46f5-a207-be0590c7743e)

Porém, o seguinte erro é disparado:
![image](https://github.com/po-ui/po-angular/assets/19232571/a4ee6901-7f63-470d-ac11-8d4cf0d7ffe6)

Infelizmente não encontrei o erro, visto que é uma reprodução básica do exemplo da documentação.

**Comment by jkozima** [comment]
Boa Tarde @GuilhermeMesquita 
Tudo bem?
Para que possamos apoia-lo precisaremos de mais detalhes para entender a situação
Utilize o Stackblitz para reproduzir o problema;
https://stackblitz.com/edit/po-ui
Detalhe passo a passo a reprodução da ocorrência, inclua evidências utilizando imagens, vídeos ou gifs:
Passo 1...
Passo 2...
Detalhe o comportamento atual;
Detalhe o comportamento que você espera ver;
Informe a versão dos ambientes:
PO UI: Ex. v15.8.0
Angular: Ex. 15
Informe o Browser:
 Chrome
Firefox
Edge
Safari
 IE 11
 Outros
Informe e o Sistema Operacional:
Windows
macOS
Ubuntu
Outros

No aguardo.

**Comment by GuilhermeMesquita** [comment]
Bom dia, me desculpem o atraso extrema para dar continuidade à esse tópico. Na época contornei a situação utilizando  outro componente. Mesmo assim, muito obrigado.
