### ISSUE TITLE
Totvs-po-theme: Erro na versão 16.4.0

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#1857]
#### Reprodução
Eu instalei o `"@totvs/po-theme": "^16.3.0"` e não existe a pasta `CSS`.

![image](https://github.com/po-ui/po-angular/assets/36740857/fb0247e1-ae6a-4983-89e0-5bee22662ddc)

Passos para reproduzir:
1. Instalar o "@totvs/po-theme": "^16.3.0",
2. executar o `ng serve`,
3. Verifique que ele não encontro a pasta de `css`

#### Qual o comportamento atual?
Execução com erro:
![image](https://github.com/po-ui/po-angular/assets/36740857/56693fd6-5e99-438b-a26f-43382fec6ade)

#### Que comportamento você esperava ver?
Execução sem erro:
![image](https://github.com/po-ui/po-angular/assets/36740857/19452507-0a27-40da-9e55-9f0878a4b53b)

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by jkozima** [comment]
Bom dia!
@wsteixeira Tudo bem?
Obrigada por reportar.
Liberamos no fim da tarde de ontem uma release corretiva 16.4.1 para tratar essa questão.
Por gentileza validar.
Abraço
