### ISSUE TITLE
Cancelar requisição ao fechar modal do lookup

### ISSUE THREAD

**Issue by LuanPonick** [po-ui/po-angular#1880]
#### Descrição da melhoria
   Fazer a modal do lookup toda vez que for fechada cancelar as requisições pendentes e também caso o usuário tenha uma requisição pendente ao tente gerar uma nova requisição primeiro cancelar a requisição pendente para somente depois criar uma nova

#### Caso de uso
   A modal do lookup pode acabar causando certas estranhezas principalmente caso esteja atuando em ambientes com baixa velocidade de internet ou caso o lookup tenha que trabalhar com requisições muito pesadas que por serem maiores podem acabar demandando mais para serem finalizadas.
Esse problema pode ocorrer caso tenha 2 ou mais requisições rodando ao mesmo tempo, por exemplo caso tenha 2 requisições pendentes e a primeira requisição terminar a tela que esta presa com o carregamento ira liberar a tela para o usuário mexer porem ainda tem mais uma requisição que ainda não terminou, e quando essa requisição terminar ira atualizar todos os dados do lookup dando um """suto""" no usuário porque ele está lendo ou selecionando as opções que desejaria até que de repente as informações mudam.
Exemplo de como e onde podem acontecer: 
   ao entrar em um lookup que necessita fazer uma requisição que demora consideravelmente você clica para abrir a sua modal, e ao entrar será feito uma requisição padrão que irá buscar os 10 primeiros resultados, porém você já sabe o que quer e sem a primeira requisição terminar você já faz uma outra em seguida usando aquele buscado que fica no canto superior direito da modal colocando 123 quando é feito essa requisição do 123 logo é terminada a requisição do começo e por conta disso o loading da tela sai por ter "acabado a requisição" 
   Vídeo demonstrativo da situação citada acima https://app.screencast.com/nyLgG1K2tP6Mp
Também pode acontecer em casos mais específicos de uma requisição anular a outra porque caso a primeira requisição acabe depois da segunda requisição a segunda será sobrescrita pela primeira, mas são casos mais raros de acontecer.

#### Informações adicionais
   Esse problema pode ser solucionado usando o "X-PO-Screen-Lock" no cabeçalho da requisição porem fica visualmente estranho por ter 2loading na tela e também acaba perdendo muita usabilidade do componente porque por exemplo caso tenha uma tela com muito lookups pode ser que o usuário abra um sem querer e acabe tendo que esperar todo o carregamento da requisição para só daí conseguir voltar para a tela padra.

**Comment by anliben** [comment]
Bom Dia @LuanPonick, tudo bem?

Obrigado por reportar, em breve iremos analisar e voltar respota!

Attr.
