### ISSUE TITLE
po-combo: Erro ao usar o método 'setInputValue' 

### ISSUE THREAD

**Issue by jean-medes-totvs** [po-ui/po-angular#1892]
#### Reprodução
Selecionei a opção 'sp' no combo
![image](https://github.com/po-ui/po-angular/assets/152443840/7def4092-9229-44d6-ac1c-27f0a0801074)
Selecionando o switch, ele limpa o combo
![image](https://github.com/po-ui/po-angular/assets/152443840/b7c13549-a7b8-4898-a7dd-dcd32e6caee5)
Voltando o switch pra false, para liberar o acesso ao combo novamente:
![image](https://github.com/po-ui/po-angular/assets/152443840/32b3c07e-3b68-452e-b752-1e329739685f)
Seleciono a mesma opção 'sp' novamente, a pré-visualização não é carregada;
![image](https://github.com/po-ui/po-angular/assets/152443840/33263b1b-39d9-4230-bdee-847f7cc70775)

Nos prints, eu seleciono a opção '**sp**' e carrega a 'pré-visualização' logo abaixo do combo, a pré-visualização carrega na primeira vez por que que evento 'p-change' é acionado, e depois eu clico no switch que usa o método 'setInputValue(null)', o campo é limpo visualmente, se eu for e selecionar a opção '**sp**' novamente, a pré-visualização não carrega, por que o 'p-change' não é acionado. Porem se eu digitar outra opção, ele cai no 'p-change' por que o '**selectedValue**' e '**selectedOption**' foi alterado;

Passos para reproduzir:
1. Digitar um valor e selecionar uma opção X no combo;
2. Limpar o valor do combo com o 'setInputValue(null)' com a ação em um botão, por exemplo;
3. O campo visualmente é limpo;
4. Porem se acessar as propriedades do combo no console do navegador, vai ver que o 'selectedValue' e o 'selectedOption' estão com o último valor selecionado mesmo visualmente não mostrando valor;
5. Dai digitando e selecionando a opção X novamente, o evento de 'p-change' não é disparado;

#### Qual o comportamento atual?
Não tem ação no 'p-change' após usar o método do combo: 'setInputValue(null)';

#### Que comportamento você esperava ver?
Ao limpar o combo utilizando o método, 'setInputValue(null)', selecionar novamente a mesma opção, o evento do 'p-change' dispararia o valor que foi selecionado antes de limpar;

#### Ambiente

- PO UI: 15.12.1
- Angular: 15.12.1
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by anliben** [comment]
Boa Tarde @jean-medes-totvs , tudo bem?

Para podermos apoiá-lo precisaremos de mais detalhes para entender a situação

- Utilize o Stackblitz para reproduzir o problema: https://stackblitz.com/edit/po-ui

### Detalhe passo a passo a reprodução da ocorrência, inclua evidências utilizando imagens, vídeos ou gifs:

- Passo 1...*
- Passo 2...
- Detalhe o comportamento atual:
- Detalhe o comportamento que você espera ver:

### Informe a versão dos ambientes:
- PO UI: Ex. v15.8.0
- Angular: Ex. 15
- Node: Ex. 15

### Informe o Browser:
- [ ] Chrome
- [ ]  Firefox
- [ ] Edge
- [ ]  Safari
 - [ ] IE 11
- [ ] Outros

### Informe e o Sistema Operacional:
- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Outros

### Aguardamos seu retorno!

**Comment by jean-medes-totvs** [comment]
Boa tarde, 

Vou resumir aqui pra ficar mais facil.. 

o metodo de vocês, 'setInputValue(null)', não limpa o 'selectedValue' e 'selectedOption' do po-combo, mas na interface ele limpa, dai se selecionar o mesmo valor que antes de usar o 'setInputValue(null)', nao tem ação no (p-change)
