### ISSUE TITLE
Sugestão de menu horizontal

### ISSUE THREAD

**Issue by fernandodeabreupereira** [po-ui/po-angular#190]
#### Descrição da melhoria
Ao meu ver um componente bacana a ser inserido seria um menu horizontal, onde a montagem desse seria através de um JSON.

#### Caso de uso
Hoje o PrimeNG tem um componente bem bacana similar a minha sugestão, segue o link: https://www.primefaces.org/primeng/#/megamenu

#### Informações adicionais
Algo que eu acho muito bacana nesse componente do PrimeNG é a propriedade "visible", essa responsável pela exibição do item no menu, muito útil para trabalhar com permissões de acesso.

**Comment by jhosefmarks** [comment]
Ótima sugestão, vamos mantes em nosso backlog.

Hoje, você já pode contar com o menu e o navbar.

**Comment by fernandodeabreupereira** [comment]
> Ótima sugestão, vamos mantes em nosso backlog.
> 
> Hoje, você já pode contar com o menu e o navbar.

Fico feliz que tenha sido uma ótima sugestão, realmente é um componente bem legal e útil.

Sim, hoje em meus testes utilizo o menu aliado ao navbar. Estou e estarei atento as atualizações, muito boa a iniciativa de vocês. Obrigado!

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
