### ISSUE TITLE
Incompatibilidade da biblioteca rxjs do  @po-ui/ng-components@16.8.0 com @angular-devkit/build-angular@"16.2.10"

### ISSUE THREAD

**Issue by Gabriel7fs** [po-ui/po-angular#1900]
Olá, pessoal! Estou realizando a atualização de um projeto para o Angular 16 e PO-UI 16, porém está ocorrendo erro de incompatibilidade entre a biblioteca rxjs.

Segue erro do console:

17:28:31 [ERROR] npm ERR! Found: rxjs@7.8.1
17:28:31 [ERROR] npm ERR! node_modules/rxjs
17:28:31 [ERROR] npm ERR!   rxjs@"^7.4.0" from the root project
17:28:31 [ERROR] npm ERR!   rxjs@"7.8.1" from @angular-devkit/build-angular@16.2.10
17:28:31 [ERROR] npm ERR!   node_modules/@angular-devkit/build-angular
17:28:31 [ERROR] npm ERR!     dev @angular-devkit/build-angular@"16.2.10" from the root project
17:28:31 [ERROR] npm ERR!   4 more (@angular/core, @angular/common, @angular/forms, @angular/router)
17:28:31 [ERROR] npm ERR! 
17:28:31 [ERROR] npm ERR! Could not resolve dependency:
17:28:31 [ERROR] npm ERR! @po-ui/ng-components@"16.8.0" from the root project
17:28:31 [ERROR] npm ERR! 
17:28:31 [ERROR] npm ERR! Conflicting peer dependency: rxjs@7.5.7
17:28:31 [ERROR] npm ERR! node_modules/rxjs
17:28:31 [ERROR] npm ERR!   peer rxjs@"~7.5.5" from @po-ui/ng-components@16.8.0
17:28:31 [ERROR] npm ERR!   node_modules/@po-ui/ng-components
17:28:31 [ERROR] npm ERR!     @po-ui/ng-components@"16.8.0" from the root project

Já atualizei o rxjs para outras e versões inclusive para o que o erro me informa que devo atualizar, porém o po-ui/ng-component requer a 7.5.5 e o angular-devkit/build-angular requer a versão 7.8.1 do rxjs.

Agradeço a atenção e fico no aguardo!

**Comment by anliben** [comment]
Boa Tarde @Gabriel7fs, tudo bem?

Segue o link da nossa doc onde ensina a instalar o `po-ui` com as versões corretas do angular

https://po-ui.io/guides/getting-started

Attr.

**Comment by anliben** [comment]
Boa Tarde @Gabriel7fs, tudo bem?

Iremos incluir esta correção do rxjs na versão 7.8.x a partir da versão 17.x do `po-ui`
Attr.
