### ISSUE TITLE
Melhoria no 'PoDynamicView' para Exibição Personalizada de Valores Booleanos

### ISSUE THREAD

**Issue by carlosdiego** [po-ui/po-angular#1913]
#### Descrição da melhoria
Para campos do tipo booleano no PoDynamicView, seria benéfico se o método setFieldValue pudesse automaticamente apresentar valores customizados definidos nas propriedades booleanTrue e booleanFalse. Atualmente, assume-se somente o valor padrão booleano (true/false). A melhoria proposta permitiria uma apresentação mais amigável e customizável desses valores.

#### Caso de uso
Em formulários dinâmicos onde campos booleanos frequentemente representam uma escolha binária como 'Sim'/'Não', 'Ativo'/'Inativo', 'Aceito'/'Rejeitado', etc., esta melhoria possibilitaria aos desenvolvedores definir explicitamente o texto que deve ser exibido para cada valor. Isso melhoraria a legibilidade do formulário para o usuário final, permitindo que as escolhas booleanas sejam apresentadas de maneira mais clara e intuitiva.

Por exemplo, ao invés de simplesmente mostrar **true** ou **false**, o PoDynamicView poderia mostrar '**Ativo**' ou '**Inativo**', conforme definido nas propriedades **booleanTrue** e **booleanFalse** do campo.

#### Informações adicionais
Essa melhoria é particularmente útil em contextos onde o formulário dinâmico é usado para exibir dados em uma maneira mais humanamente legível. Valores booleanos brutos podem ser confusos para usuários finais que não estão acostumados a trabalhar com dados nesse formato. A capacidade de definir apresentações customizadas para esses valores ajudaria a alinhar a experiência do usuário com as expectativas e o design do sistema.

**Comment by alinelariguet** [comment]
concluído e disponível na v16.11.0
