### ISSUE TITLE
Erro ao rodar o Portinari-Ui após adicionar ao Angular

### ISSUE THREAD

**Issue by welintonauerbach** [po-ui/po-angular#192]
Olá,

Gostaria apenas de reportar uma situação que encontrei ao instalar o Portinari-Ui seguindo os passos da página https://portinari.io/guides/getting-started.

Modifiquei o arquivo package.json conforme descrito, modificando para "~8.0.0" e apliquei os os passos subsequentes.

Quando executei NG SERVE ou NG BUILD recebi a exception: **An unhandled exception occurred: Object prototype may only be an Object or null: undefined**

Realizei um pesquisa sobre o problema e uma das soluções que encontrei que funcionou para meu projeto foi fazer a seguinte modificação no package.json.

Modifiquei: "@angular/compiler": "**~8.0.0**"
Para: "@angular/compiler": "**~8.2.0**"

#### Ambiente

- Portinari: "@portinari/portinari-ui": "^1.19.0"
- Angular version:

Angular CLI: 8.3.20
Node: 10.16.3
OS: win32 x64
Angular: 8.0.3
... animations, common, core, forms, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.20
@angular-devkit/build-angular     0.803.20
@angular-devkit/build-optimizer   0.803.20
@angular-devkit/build-webpack     0.803.20
@angular-devkit/core              8.3.20
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@angular/compiler                 8.2.14
@angular/compiler-cli             8.2.14
@angular/language-service         8.2.14
@ngtools/webpack                  8.3.20
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2 

- Arquivo package.json completo:

{
    "name": "tc-po-cli",
    "version": "0.0.0",
    "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "build": "ng build",
        "test": "ng test",
        "lint": "ng lint",
        "e2e": "ng e2e"
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "~8.0.0",
        "@angular/common": "~8.0.0",
        "@angular/compiler": "~8.2.0",
        "@angular/core": "~8.0.0",
        "@angular/forms": "~8.0.0",
        "@angular/platform-browser": "~8.0.0",
        "@angular/platform-browser-dynamic": "~8.0.0",
        "@angular/platform-server": "~8.0.0",
        "@angular/router": "~8.0.0",
        "@portinari/portinari-ui": "^1.19.0",
        "rxjs": "~6.4.0",
        "tslib": "^1.10.0",
        "zone.js": "~0.9.1"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~0.803.20",
        "@angular/cli": "~8.3.20",
        "@angular/compiler-cli": "~8.2.14",
        "@angular/language-service": "~8.2.14",
        "@types/node": "~8.9.4",
        "@types/jasmine": "~3.3.8",
        "@types/jasminewd2": "~2.0.3",
        "codelyzer": "^5.0.0",
        "jasmine-core": "~3.4.0",
        "jasmine-spec-reporter": "~4.2.1",
        "karma": "~4.1.0",
        "karma-chrome-launcher": "~2.2.0",
        "karma-coverage-istanbul-reporter": "~2.0.1",
        "karma-jasmine": "~2.0.1",
        "karma-jasmine-html-reporter": "^1.4.0",
        "protractor": "~5.4.0",
        "ts-node": "~7.0.0",
        "tslint": "~5.15.0",
        "typescript": "~3.5.3"
    }
}
- Log do erro gerado:
[error] TypeError: Object prototype may only be an Object or null: undefined
    at setPrototypeOf (<anonymous>)
    at Object.__extends (F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\tslib\tslib.js:65:9)
    at F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:115:17
    at F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:314:6
    at F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:3:17
    at Object.<anonymous> (F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\template.js:9:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:20:22
    at F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:10:17
    at Object.<anonymous> (F:\Welinton\VSProjects\TecniCAD.ProjectManagerPortal\tc-customer-angular\tc-po-cli\node_modules\@angular\compiler-cli\src\ngtsc\indexer\src\transform.js:16:3)

**Comment by welintonauerbach** [comment]
Verifiquei que no Github diverge a instalação do @angular/cli.

Github
npm i -g **@angular/cli@8.0.0**

No portal: portinari.io
npm i -g **@angular/cli**

Entendo que é simples a solução, mas p/ quem estiver começando com angular/portinari acredito que poderá ser uma dificuldade caso não compreenda sobre as versões.

**Comment by jhosefmarks** [comment]
@welintonauerbach vamos rever nossa documentação para que está iniciando com o Portinari.

**Comment by jhosefmarks** [comment]
Doc atualizada: https://po-ui.io/guides/getting-started
