### ISSUE TITLE
Navegação por teclado no componente po-page-dynamic-table

### ISSUE THREAD

**Issue by brodao2** [po-ui/po-angular#1921]
#### Descrição da melhoria
Navegação por teclado no componente po-page-dynamic-table.

#### Caso de uso

Melhor acessibilidade e fluidez no uso do componente.

#### Informações adicionais

Nada a adicionar.

**Comment by felipepetuco** [comment]
Obrigado pela sugestão, vamos incluir em nosso backlog, mas caso você deseje dar celeridade você pode realizar uma contribuição no projeto.
