### ISSUE TITLE
 Inclusão da Propriedade `params` no Componente `po-dynamic-view`

### ISSUE THREAD

**Issue by carlosdiego** [po-ui/po-angular#1933]
#### Descrição da melhoria
Sugere-se adicionar a propriedade params ao po-dynamic-view, semelhante aos componentes lookup e combo do PO UI, permitindo parâmetros adicionais em requisições de serviços.

#### Caso de uso
Essa melhoria facilitaria o uso de informações contextuais, como o ID do cliente, ao carregar campos de seleção, garantindo a exibição de dados relevantes e personalizados.

#### Informações adicionais
A falta dessa funcionalidade requer abordagens menos eficientes, como pré-processamento ou criação de componentes personalizados. A propriedade params harmonizaria o po-dynamic-view com outros componentes do PO UI como o po-dynamic-view, padronizando o desenvolvimento e a experiência do usuário.

**Comment by felipepetuco** [comment]
Obrigado pelo contato e pela contribuição na PR acima, vamos analisar e lhe daremos retorno o mais breve possível.

**Comment by anliben** [comment]
Boa Tarde @carlosdiego, tudo bem?

Subimos sua contribuição em nossa versão 16.14.0

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#16130-2024-01-29
Attr.
