### ISSUE TITLE
Inclusão das propriedades `optionsService` e  `optionsMulti` no componente po-dynamic-view

### ISSUE THREAD

**Issue by carlosdiego** [po-ui/po-angular#1939]
#### Descrição da melhoria
Incluir as propriedades `optionsService` e `optionsMulti` no componente po-dynamic-view. Atualmente, o po-dynamic-view carrega informações para campos que utilizam a propriedade **searchService**. Contudo, seria bom ampliar essa funcionalidade para incluir os campos que empregam `optionsService` e `optionsMulti`. Estas propriedades são essenciais para carregar dados em componentes de seleção e múltipla seleção (como combo e multi-select), um comportamento já existente no po-dynamic-edit e semelhante ao oferecido para campos com **searchService**. A adoção dessa melhoria possibilitaria a execução automática dos serviços associados a essas propriedades, aprimorando a consistência dos dados do componente.

#### Caso de uso
Essa melhoria permitiria aos desenvolvedores utilizar o componente po-dynamic-view de forma mais eficaz em aplicações que exigem a exibição dinâmica de dados. Por exemplo, em um formulário de edição de usuário, onde campos como 'departamento' ou 'habilidades' podem ser preenchidos por meio de seleção múltipla ou combo, a melhoria permitiria carregar automaticamente as opções disponíveis para esses campos sem a necessidade de implementações adicionais.

#### Informações adicionais
A incorporação dessas propriedades alinha o po-dynamic-view mais estreitamente com o po-dynamic-edit, oferecendo uma experiência de desenvolvimento mais coesa e reduzindo a quantidade de código necessário para manipular dados dinâmicos. Além disso, essa melhoria aumenta a flexibilidade do componente, permitindo que ele seja usado em uma gama mais ampla de cenários.
A integração dessas propriedades também pode contribuir para reduzir erros e inconsistências na manipulação de dados entre diferentes componentes.

**Comment by felipepetuco** [comment]
Obrigado pelo contato, vamos analisar e dar retorno o mais breve possível.

**Comment by anliben** [comment]
Boa Tarde @carlosdiego, tudo bem?

Subimos sua contribuição em nossa versão 16.14.0

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#16140-2024-02-05
Attr.
