### ISSUE TITLE
Sugestão: Filtro por coluna no componente po-table

### ISSUE THREAD

**Issue by jotamauro** [po-ui/po-angular#195]
#### Descrição da melhoria
Descreva a melhoria que você gostaria de ver.
 - No cabeçalho de cada coluna do componente po-table, habilita uma campo para que o usuário preencha o que deseja filtra na tabela.

#### Caso de uso
Descreva os casos de uso que a melhoria permitiria.
- Imagina que uma tabela possui diversos registros, realizando paginação do itens. Vamos supor que uma dessas colunas da tabela seja o CNPJ do fornecedor. Se existisse, na coluna de CNPJ, um campo para eu digitar o CNPJ que eu desejo filtrar, ajudaria na localização de itens.

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

**Comment by jhosefmarks** [comment]
Estamos avaliando esse funcionalidade.

**Comment by hugocarreiracosta** [comment]
Seria perfeito ! Única coisa que me impede de usar este componente.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
