### ISSUE TITLE
PoPageDynamicEdit: Otimização de Validação de Campos e Redução de Requisições GET em Lookups.

### ISSUE THREAD

**Issue by carlosdiego** [po-ui/po-angular#1950]
#### Descrição da melhoria
Atualmente, o componente PoPageDynamicEdit valida seus campos obrigatórios (required: true) antes de gravar as informações. Entretanto, identificou-se um comportamento ineficiente em campos do tipo lookup. Mesmo quando esses campos já estão preenchidos (sendo obrigatórios ou não), o ato de gravar desencadeia uma alteração no model que, por sua vez, dispara o método writeValue do lookup. Esse método executa um GET no serviço para preencher o componente, recarregando informações de forma desnecessária e gerando custos adicionais ao servidor. Esse problema pode se tornar crítico em telas com um número significativo de componentes lookup, onde, por exemplo, ao gravar e validar o formulário, seriam enviadas múltiplas requisições GET ao servidor sem necessidade.

#### Caso de uso
A melhoria permitiria uma otimização significativa em telas que utilizam o PoPageDynamicEdit com múltiplos campos de lookup. Ao evitar requisições GET desnecessárias, reduzir-se-ia a carga sobre o servidor, melhorando a eficiência e a performance da aplicação. Isso seria especialmente útil em cenários com formularios extensos que contêm muitos campos lookup, otimizando tanto o uso de banda de rede quanto a carga de trabalho do servidor.

#### Informações adicionais
A sugestão é que as alterações no model sejam realizadas apenas quando estritamente necessárias. Atualmente, existem recursos como beforeSave e beforeSaveNew que permitem ao desenvolvedor realizar ações ou alterar o model antes de salvar. Se, durante essas ações, o model é alterado e isso desencadeia o método updateModel, os dados na tela são atualizados, incluindo a execução desnecessária de GETs para componentes lookup. Esse comportamento é relevante apenas quando há uma mudança real no model. Portanto, seria benéfico revisar e ajustar o mecanismo de atualização do model para que evite requisições GET desnecessárias, otimizando o processo de validação e gravação em telas com componentes lookup.

![aZj7kEGgbw](https://github.com/po-ui/po-angular/assets/12103080/b6c070d1-302f-4a0e-be37-b5b5965c1e2e)

Essa melhoria contribuiria significativamente para a eficiência de aplicações que utilizam o PoPageDynamicEdit, especialmente aquelas com alta demanda de interações com o servidor, garantindo uma experiência de usuário mais fluida e reduzindo custos operacionais.

**Comment by anliben** [comment]
Boa Tarde @carlosdiego, tudo bem?

Subimos sua contribuição em nossa versão 16.14.0

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#16140-2024-02-05
Attr.
