### ISSUE TITLE
Instalação de dependência 

### ISSUE THREAD

**Issue by willdev-crypto** [po-ui/po-angular#1958]
Olá, estou muito interessado em desenvolvedor um projeto(para estudos) usando os componentes do Po Ui, e estou enfrentando dificuldades na instalação dos mesmos, já busquei diversas soluções e não consegui instalar em um projeto só zero Angular, utilizando os componentes, venho seguindo o guia disponível no site, conferindo versões das dependências para compatibilidade conforme descrito no guia, versões do NodeJs,Angular Cli. Cheguei até a verificar e alterar as dependências do Windows para caso haver alguma incompatibilidade com as dependências mínimas exigidas . E mesmo assim não consegui , há alguma versão mais recente dos componentes para instalação no projeto?? Estou bem interessado em desenvolver algo conjunto a Po Ui e vim até aqui solicitar algum tipo de orientação para melhor fazer. O único momento que consegui fazer a instalação dos componentes ,templates. Foi ao instalar em um projeto angular já feito por eu. E este já era um outro projeto aí após conseguir instalar as dependências ele rodou mas em cima de um projeto já existente o que eu acredito não ser o ideal aí então não quis editá-lo para poder começar um projeto do zero diretamente com o Po. Muito Obrigado Complementando ao e-mail anterior eu consegui baixar pelo github o repositório Po Angular, resultando também em erros de app.module.ts ao fazer o ng serve por exemplo.Porém eu quero iniciar um projeto totalmente do zero utilizando esses componentes para poder compartilhar com a equipe

**Comment by willdev-crypto** [comment]
![20240219_140017](https://github.com/po-ui/po-angular/assets/120841470/bd56f29c-2873-48d7-b900-25686b88b196)

**Comment by anliben** [comment]
Boa Tarde @willdev-crypto, tudo bem?

Siga nosso passo a passo para instalação correta da biblioteca!
https://po-ui.io/guides/getting-started

Attr.

**Comment by willdev-crypto** [comment]
@anliben Olá, estou seguindo e conferindo as dependências mínimas exigidas e mesmo assim chego a esse resultado do terminal

**Comment by anliben** [comment]
@willdev-crypto a versão mínima e 16.x.x você esta claramente pelo print usando uma versão superior!
