### ISSUE TITLE
<po-table>: <po-table não abre após migrar para o Angular 17>

### ISSUE THREAD

**Issue by tapiarona** [po-ui/po-angular#1973]
Bom dia, Pessoal, estamos fazendo alguns testes para migração do po-ui e Angular 17. Pegamos um problema ao utilizar o po-table. Se puderem validar, agradeço. 
Error: Cannot read properties of undefined (reading 'some')

Segue link para repdo: 
https://stackblitz.com/edit/po-ui-cvstzt?file=src%2Fapp%2Fapp.component.html

#### Ambiente
  | "@angular/animations": "^17.2.3",
  | "@angular/common": "^17.2.3",
  | "@angular/compiler": "^17.2.3",
  | "@angular/core": "^17.2.3",
  | "@angular/forms": "^17.2.3",
  | "@angular/platform-browser": "^17.2.3",
  | "@angular/platform-browser-dynamic": "^17.2.3",
  | "@angular/platform-server": "^17.2.3",
  | "@angular/router": "^17.2.3",
  | "@po-ui/ng-components": "^17.0.0-rc.0",
  | "@po-ui/ng-templates": "^17.0.0-rc.0",
  | "@po-ui/style": "^17.0.0-rc.0",
  | "@totvs/po-theme": "^17.0.0-rc.0",
  | "@totvs/protheus-lib-core": "^15.1.0",

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by likid** [comment]
Acho que você tem que seguir esta tabela aqui

https://github.com/po-ui/po-angular/discussions/735

O po-ui atualmente não é compatível com o Angular 17.

**Comment by tapiarona** [comment]
Bom dia.
Estamos tentando fazer a migração para o Angular 17 e po-ui 17. Independente do po-ui estar na versão 16 ou 17, o erro acontece em ambos os casos.
Estamos mapeando os dados antes de fazer a migração oficial, conforme orientando para todo o time da TOTVS.

**Comment by anliben** [comment]
Boa Tarde @tapiarona, tudo bem?

O `po-ui` ainda não suporta a versão 17.2.x, somente a versão 17.0.4! Por favor, voltar a versão está como especificado em: https://github.com/po-ui/po-angular/commit/48ee18bbbae06c03d7aaa9c6d8c3acd9ef05f602#diff-cfabf1cf40f1208bf2a9e4198f0fa64a0fb3de07c1e2a005a3965e1a699a9e37

Attr.
