### ISSUE TITLE
Aumentar paleta de cores padrão 

### ISSUE THREAD

**Issue by aksilvaa** [po-ui/po-angular#198]
#### Descrição da melhoria

- Hoje as opções de cores disponíveis na paleta de cores são limitadas, por isso penso que seria importante aumentar a quantidade de cores disponíveis para a personalização dos temas e além disso a sua aplicação em componentes, como o Po-Table. 

#### Caso de uso

- Um exemplo prático de sua aplicação seria a personalização de temas voltados para pessoas com daltonismo, sendo assim seria mais fácil a utilização dos recursos por parte deste nicho.

- Outro caso que pode ser citado é a personalização dos **labels** e **subtitles**, pois conforme imagens abaixo pode-se observar que as cores existentes já se assemelham, porém a inserção de cores pelo padrão RGB para a otimização do uso das propriedades.

#### Informações adicionais:

Protheus
![image](https://user-images.githubusercontent.com/50679891/70806233-97129280-1d99-11ea-9329-bc661d3eb23a.png)

Portinari
![image](https://user-images.githubusercontent.com/50679891/70806417-07b9af00-1d9a-11ea-9ebc-af86fea0e9ff.png)

**Comment by jhosefmarks** [comment]
Você consegue customizar as cores de acordo com esses documentos:

- [Customizando cores do tema padrão](https://portinari.io/guides/colors-customization)
- [Criando um tema para o Portinari](https://portinari.io/guides/create-theme-customization)

#ficadica: você não deve se basear apenas em cores para diferenciar seus registros, você deve usar labels que expressem isso para facilitar a visualização e o entendimento do usuário.

Temos em nosso backlog um item para que possibilite a passagem de valores hexadecimais.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
