### ISSUE TITLE
Ajuda com a instalação do PO-UI

### ISSUE THREAD

**Issue by ivancasaof** [po-ui/po-angular#1985]
Boa noite. Poderiam me ajudar a entender esse erro de dependência durante a instalação?

Estou seguindo o passo a passo mas está apresentando esse erro.
Uma das dúvidas é, eu preciso instalar as mesmas versões de dependência que estão descritas no tutorial ou posso utilizar uma versão superior?

Segue versão:
Node - v20.11.1
NPM - 10.2.4
Angular - @angular/cli@17.2.3

![Screenshot_2](https://github.com/po-ui/po-angular/assets/107046154/c952e203-5e78-4790-8d64-2890ffb25af3)

 
Obrigado.

**Comment by pedrodominguesp** [comment]
Bom dia, @ivancasaof .
Atualmente, o PO UI é compatível com a versão ~17.0 do Angular, o que pode ser a causa do erro de dependências durante a instalação.

Com base nas informações compartilhadas, percebi que a versão do Angular instalada foi a 
>  "@angular/cli@17.2.3"

Para resolver esse problema e assegurar a compatibilidade do seu projeto com o PO UI, recomendo:

**Instalar a Versão Compatível do Angular CLI:**
`npm install -g @angular/cli@17.0`

**Verificar e Ajustar Dependências Conforme Documentação**: 

https://po-ui.io/guides/getting-started 
[Passo 1.1 - Instalando as dependências]

Espero que essas orientações ajudem no sucesso da instalação.
Caso tenha mais dúvidas, por favor, não hesite em nos contactar novamente.

**Comment by ivancasaof** [comment]
Bom dia Pedro.
Fiz o recomendado agora sobre a versão -> @angular/cli@17.0.9

Veja se estou fazendo algo de errado no processo de instalação:
1 - Crio um novo projeto com 
ng new nome_do_projeto --skip-install

2 - Abro esse projeto no VSCode, depois abro o package.json e ajusto manualmente o arquivo de acordo com o recomendado.
Exemplo:
"dependencies": {
    "@angular/animations": "^17.0.0",
Altero para
"dependencies": {
    "@angular/animations": "^17.0.9",

3 - Executo o npm install para instalar as dependências.

4 - Adiciono o POUI com "ng add @po-ui/ng-components"
Nessa parte está apresentando o erro conforme anexo.
[2024-03-07T11_49_50_428Z-eresolve-report.txt](https://github.com/po-ui/po-angular/files/14523631/2024-03-07T11_49_50_428Z-eresolve-report.txt)
Obrigado.

**Comment by pedrodominguesp** [comment]
> > Bom dia, @ivancasaof . Atualmente, o PO UI é compatível com a versão ~17.0 do Angular, o que pode ser a causa do erro de dependências durante a instalação.
> > Com base nas informações compartilhadas, percebi que a versão do Angular instalada foi a
> > > "@angular/cli@17.2.3"
> > 
> > 
> > Para resolver esse problema e assegurar a compatibilidade do seu projeto com o PO UI, recomendo:
> > **Instalar a Versão Compatível do Angular CLI:** `npm install -g @angular/cli@17.0`
> > **Verificar e Ajustar Dependências Conforme Documentação**:
> > https://po-ui.io/guides/getting-started [Passo 1.1 - Instalando as dependências]
> > Espero que essas orientações ajudem no sucesso da instalação. Caso tenha mais dúvidas, por favor, não hesite em nos contactar novamente.
> 
> Bom dia Pedro. Fiz o recomendado agora sobre a versão -> @angular/cli@17.0.9
> 
> Veja se estou fazendo algo de errado no processo de instalação: 1 - Crio um novo projeto com ng new nome_do_projeto --skip-install
> 
> 2 - Abro esse projeto no VSCode, depois abro o package.json e ajusto manualmente o arquivo de acordo com o recomendado. Exemplo: "dependencies": { "@angular/animations": "^17.0.0", Altero para "dependencies": { "@angular/animations": "^17.0.9",
> 
> 3 - Executo o npm install para instalar as dependências.
> 
> 4 - Adiciono o POUI com "ng add @po-ui/ng-components" Nessa parte está apresentando o erro conforme anexo. [2024-03-07T11_49_50_428Z-eresolve-report.txt](https://github.com/po-ui/po-angular/files/14523631/2024-03-07T11_49_50_428Z-eresolve-report.txt) Obrigado.

@ivancasaof 
Experimente os seguintes passos:
1- Remova os diretórios node_modules, .angular (caso exista) e o arquivo package-lock.json
2- verificar a versão do Angular CLI instalado com o comando ng version
    Nesse momento espera-se que as versões estejam nesse formato: 
![image](https://github.com/po-ui/po-angular/assets/15203261/353ed15f-8102-4be3-96e1-847010c101e2)

Caso as versões estejam definidas com `^` realize as seguintes ações:

Altere para `~`, conforme exemplo da documentação

Execute o comando npm install --force

**Comment by ivancasaof** [comment]
> npm install --force

Agora sim!!!!!!!
Muito Obrigado Pedro.

**Comment by pedrodominguesp** [comment]
Show!! Bons códigos @ivancasaof
