### ISSUE TITLE
Ajuda App Tela Branca  - Debug

### ISSUE THREAD

**Issue by ivancasaof** [po-ui/po-angular#1987]
Bom dia. 
Montei um App utilizando POUI e ele funciona perfeitamente fora do Protheus.
Quando importo para o Protheus e tento abri-lo, fica apenas uma tela branca e eu fico sem entender o que pode ser que esteja errado.
Teria como debugar essa aplicação?

Detalhe.. se eu crio um app sem adicionar POUI e somente com uma tela HelloWorld.. funciona..

Poderiam me ajudar com isso?

Obrigado.

**Comment by anliben** [comment]
Boa Tarde @ivancasaof, tudo bem?

Não temos uma forma de debugar dentro do protheus infelizmente, todos os projetos que conheço passam por revisões antes de compilar no protheus.

Attr.
