### ISSUE TITLE
PoPageDynamicTable: Tabela não respeita a propriedade order da coluna.

### ISSUE THREAD

**Issue by carlosdiego** [po-ui/po-angular#1998]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

**Passos para reproduzir:**
StackBlitz: https://stackblitz.com/edit/po-ui-ruuyem
1. Navegue até o componente `PoPageDynamicTable`.
2. Configure o componente com a propriedade `p-fields` definida como um array de objetos. Alguns objetos devem ter a propriedade `order` definida com números inteiros positivos e outros objetos não devem ter a propriedade `order` ou devem tê-la com valores inválidos (como strings ou números negativos).
3. Inicie a aplicação e observe a ordem das colunas geradas na tabela.

#### Qual o comportamento atual?

As colunas que não possuem a propriedade `order` definida, ou que têm valores inválidos para `order`, não estão sendo consistentemente posicionadas no final da tabela. A ordem destas colunas segue a sequencia da lista de colunas, o que pode levar a uma experiência de usuário inconsistente.

#### Que comportamento você esperava ver?

Esperava-se que as colunas com a propriedade `order` definida e com valores válidos fossem ordenadas de acordo com esses valores, do menor para o maior. Colunas sem a propriedade `order` ou com valores inválidos deveriam ser posicionadas no final da tabela, mantendo a ordem relativa original entre si.

#### Ambiente

- PO UI: `v17.1.0`
- Angular: `17`
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Este comportamento afeta significativamente a usabilidade da tabela, especialmente em aplicações que dependem da ordem correta das colunas para a apresentação dos dados.

---

**Tempo de Resposta PO UI:** Em até 7 dias úteis.  
**Tempo de Retorno do Solicitante:** 35 dias corridos.  
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by anliben** [comment]
Boa Tarde @carlosdiego, tudo bem?

Obrigado pela contribuição, iremos analisar e seguir com o fluxo da issue. 
#1999 

Attr.

**Comment by jkozima** [comment]
Carlos, boa tarde!

Entrega publicada na versão 17.1.1 do PO UI em 18/03/24.
Obrigada pela contribuição.
Abraço.
