### ISSUE TITLE
Seletor de idiomas

### ISSUE THREAD

**Issue by andredealmei** [po-ui/po-angular#200]
#### Descrição da melhoria
possibilidade de remover o seletor de linguagem da po-page-login.

#### Caso de uso
Aplicações que não são multi idiomas não precisam do seletor.

**Comment by jhosefmarks** [comment]
Duplicate of #120 and #127

**Comment by jhosefmarks** [comment]
Feito! PR #607 

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#360-2020-09-14
