### ISSUE TITLE
PoDynamicView: Comportamento incorreto na exibição de valores com opções

### ISSUE THREAD

**Issue by carlosdiego** [po-ui/po-angular#2006]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Versão PO-UI **16.4.1**: [Exemplo do erro](https://stackblitz.com/edit/po-ui-zozpvv-pun8qv)
Versão PO-UI **16.3.0**: [Exemplo com a versão anterior do PO-UI sem o erro](https://stackblitz.com/edit/po-ui-zozpvv-dmk6m7)

Passos para reproduzir:
1. Criar um campo com múltiplas opções no PoDynamicView, utilizando a propriedade options com optionsMulti definido como true, fieldLabel, fieldValue e uma propriedade específica, conforme exemplo abaixo:

```
<po-page-default p-title="Employee">
    <po-dynamic-view [p-fields]="fields" [p-value]="employee"> </po-dynamic-view>
</po-page-default>
```

```
fields: Array<any> = [
    {
      options: [
        {
          id: "INIC",
          description: "Iniciação"
        },
        {
          id: "CRESC",
          description: "Crescimento"
        },
        {
          id: "MAT",
          description: "Maturidade"
        },
        {
          id: "RENOV",
          description: "Renovação"
        },
        {
          id: "DECL",
          description: "Declínio"
        }
      ],      
      optionsMulti: true,
      fieldLabel: 'description',
      fieldValue: 'id',
      property: "faseDoCicloDeNegocios",
      label: "Fase do Ciclo de Negócios"
    }
  ];

  employee = {
    faseDoCicloDeNegocios: ['RENOV'],
  };
```

#### Qual o comportamento atual?
O dynamic-view apresenta um comportamento incorreto ao tentar exibir valores baseados em campos com opções, especialmente quando há uma tentativa de utilizar a descrição (description) correspondente ao valor de id especificado. Em vez de buscar o valor correto, o sistema erroneamente tenta definir o valor de uma propriedade com base no fieldLabel, o que não faz sentido no contexto de campos dinâmicos.

#### Que comportamento você esperava ver?
Esperava-se que o dynamic-view exibisse a descrição correspondente ao id especificado na propriedade faseDoCicloDeNegocios, de acordo com as opções definidas no campo. Especificamente, para o valor 'DECL', a descrição esperada seria "Declínio".

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações
A falha na lógica de _transformFieldLabel_ impacta diretamente a usabilidade do dynamic-view em cenários onde a exibição correta de valores dinâmicos é crucial. É importante revisar a implementação para garantir que valores sejam atribuídos e exibidos corretamente, respeitando a intenção original de uso de fieldLabel e fieldValue, sem recorrer a atribuições inadequadas que comprometem a lógica e a clareza do código.

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by likid** [comment]
Encontrei um problema em meu projeto onde o valor não é exibido quando as opções vêm de um serviço.

[https://stackblitz.com/edit/po-ui-gacb9g?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fmain.ts](url)

**Comment by carlosdiego** [comment]
> Encontrei um problema em meu projeto onde o valor não é exibido quando as opções vêm de um serviço.
> 
> [https://stackblitz.com/edit/po-ui-gacb9g?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fmain.ts](url)

O erro que você está enfrentando pode ser devido à ausência das configurações de **fieldLabel** e **fieldValue** no seu código. 
Portanto, certifique-se de incluir:
```
 campos: any = [
    {
      property: 'id',
      label: 'Nome',
      fieldLabel: 'name',
      fieldValue: 'id',
      optionsService: 'https://po-sample-api.onrender.com/v1/people',
    },
  ];
```

**Comment by likid** [comment]
> > Encontrei um problema em meu projeto onde o valor não é exibido quando as opções vêm de um serviço.
> > [https://stackblitz.com/edit/po-ui-gacb9g?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.ts,src%2Fapp%2Fapp.component.html,src%2Fmain.ts](url)
> 
> O erro que você está enfrentando pode ser devido à ausência das configurações de **fieldLabel** e **fieldValue** no seu código. Portanto, certifique-se de incluir:
> 
> ```
>  campos: any = [
>     {
>       property: 'id',
>       label: 'Nome',
>       fieldLabel: 'name',
>       fieldValue: 'id',
>       optionsService: 'https://po-sample-api.onrender.com/v1/people',
>     },
>   ];
> ```

Carlos, realmente neste stackblitz usando a api de exemplo eu acabei esquecendo destes campos e quando eu alterei funcionou. Porém eu tenho um caso em um desenvolvimento meu onde os campos vêm do backend e com optionsService e depois de carregar eles eu busco os valores. Neste caso específico que eu não consegui reproduzir no stackblitz, os valores não são mostrados. No meu caso, eu uso os campos label e value mesmo e não nomes diferentes.

**Comment by renanarosario** [comment]
Por falta de retorno essa ISSUE será finalizada.
