### ISSUE TITLE
Protheus-lib-core: Não funcionando em componente principal standalone(Angular 17)

### ISSUE THREAD

**Issue by andrelanzieri** [po-ui/po-angular#2009]
#### Qual o comportamento atual?

import { ProtheusLibCoreModule } from '@totvs/protheus-lib-core';

Quando importado o módulo em um componente que não é standalone, o direcionamento das API`s dentro do Protheus ocorre corretamente.

#### Que comportamento você esperava ver?
Dentro do Protheus, quando utilizado o módulo citado dentro do componente principal standalone, não está sendo executado o direcionamento correto das APIs conforme o endereço rest da porta multiprotocolo.

Vídeo em anexo, onde o mesmo projeto, utilizando um componente que não é standalone(com módulo), funciona normalmente.

[2024-03-18 17-19-59.zip](https://github.com/po-ui/po-angular/files/14652753/2024-03-18.17-19-59.zip)

#### Ambiente

- PO UI: 17.1.0
- Angular: ~17.2.4
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by jnrpalma** [comment]
@andrelanzieri  Obrigado pelo seu contato e pela informação fornecida. Estamos analisando a questão apresentada e trabalharemos para lhe dar um retorno o mais breve possível.

**Comment by jnrpalma** [comment]
Olá, @andrelanzieri Tudo bem!? 

Percebi que sua dúvida não especificou exatamente com qual componente do PO UI você está enfrentando dificuldades. Além disso, notei que você mencionou a importação do `ProtheusLibCoreModule`, o qual não é parte direta da biblioteca PO UI, possivelmente desviando do foco da nossa equipe core. 

Poderia fornecer mais detalhes sobre o problema? Assim, poderemos oferecer uma orientação mais precisa. 

Aguardo seu retorno para podermos ajudá-lo da melhor forma possível.

**Comment by andrelanzieri** [comment]
Olá, tudo bem.
O problema não é em componente do PO UI, é no módulo fornecido pela TOTVS, onde não efetua o direcionamento correto das API`s:
https://tdn.totvs.com.br/pages/releaseview.action?pageId=827321473

Conforme mencionado e evidenciado no video.

**Comment by jnrpalma** [comment]
Ah, compreendi! A questão que você está enfrentando não se relaciona diretamente com os componentes do PO UI. Portanto, seria ideal procurar assistência diretamente junto ao canal de produto TOTVS para esclarecer seu problema e buscar uma solução.
