### ISSUE TITLE
NPM Install:  configuaração do package.json  17

### ISSUE THREAD

**Issue by JCTG-Jorge** [po-ui/po-angular#2013]
Bom dia!
Fiz a instalação do angular desta forma: npm i -g @angular/cli@17

![image](https://github.com/po-ui/po-angular/assets/160171828/e73b48c7-86af-4dec-8e0f-0e71b60f2a2c)
Fiz a alteração no arquivo package.json conforme o recomendado:
![image](https://github.com/po-ui/po-angular/assets/160171828/c44eafcc-1cf0-48f6-972a-d7358865e703)

Dai quando dou o comando npm install, apresenta o erro abaixo:

![image](https://github.com/po-ui/po-angular/assets/160171828/d36843e2-a5da-4805-b0fb-3c41b69523db)

#### Qual o comportamento atual?
Não consigo fazer o npm install com esta configuração do arquivo package.json

#### Que comportamento você esperava ver?
Que o comando npm install funcione normal.

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by jnrpalma** [comment]
@JCTG-Jorge Totvs Obrigado pelo seu contato e pela informação fornecida. Estamos analisando a questão apresentada e trabalharemos para lhe dar um retorno o mais breve possível.

**Comment by jnrpalma** [comment]
Oi @JCTG-Jorge, tenta usar `npm install --legacy-peer-deps` Esse comando ajuda a evitar problemas de incompatibilidade entre as versões das dependências, permitindo que o npm prossiga com a instalação usando regras mais flexíveis. Isso pode ser uma solução rápida para o conflito de versões que você está enfrentando, sem a necessidade de ajustes manuais detalhados nas suas dependências.

**Comment by JCTG-Jorge** [comment]
@jnrpalma, obrigado deu certo esta parte npm instalou com sucesso consegui adiciona o po-ui/ng-components, mais no ao executar ng serve ele apresentou estes erros:
![image](https://github.com/po-ui/po-angular/assets/160171828/754c9ad7-6cc3-443e-8a94-ee06a8293525)

**Comment by JCTG-Jorge** [comment]
@jnrpalma, boa tarde!
Desta forma funcionou corrertamente, muito obrigado pelo apoio.

**Comment by DiegoKenko** [comment]
> Sr. @JCTG-Jorge, durante a configuração do projeto, lembra-se de ter respondido "sim" à questão `Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? (y/N)`. Realizei um teste optando por "não" (N) na mesma questão, referente ao SSR e SSG. Prosseguindo com os demais passos, o projeto foi construído com sucesso e iniciado sem problemas. Realize o mesmo e verifique , fico no aguardo.

uma vez ja configurado e aceito, como redifinir essa configuração e alterar para 'Não'?
