### ISSUE TITLE
po-page-dynamic-table: Erro no uso da propriedade p-service-api

### ISSUE THREAD

**Issue by JCTG-Jorge** [po-ui/po-angular#2015]
Bom dia!

Estou usando o po-pag-dynamic-table e quando passo a api no p-service-api não está passando pelo interceptor.
lembrando que como estou usando a versão  17 do angular o interceptor teve mudanças.
Quando faço uma requisicao ser ser pela propriedade p-service-api ele passa no interceptor normal.

#### Ambiente

- PO UI: 17.1.1
- Angular: 17
- Browser(s):
  - [ x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by jnrpalma** [comment]
@JCTG-Jorge Obrigado pelo seu contato e pela informação fornecida. Estamos analisando a questão apresentada e trabalharemos para lhe dar um retorno o mais breve possível.

**Comment by JCTG-Jorge** [comment]
@jnrpalma, entao mais pelo stackbliz é a versão  15.0.3 do angular o problema so ocorre no angular 17 e PO-UI 17.1.1
no angular 16.2 e po-ui 16.16.0 está ok

**Comment by JCTG-Jorge** [comment]
@jnrpalma ,
consegui acessar este link vi que vc colocou 17 mais está com modulo o como estou fazendo é o novo jeito sem modeulo:
![image](https://github.com/po-ui/po-angular/assets/160171828/0d65afee-fccb-42de-acc4-ab6c84be6931)

onde agora coloca o interceptor dentro appConfig.
![image](https://github.com/po-ui/po-angular/assets/160171828/43ba7747-8a99-49f7-bd68-ba12c59e6a17)
e standalone: true

desta forma não vai apresentar o erro.

**Comment by JCTG-Jorge** [comment]
@jnrpalma, bom dia!
Fiz um gravação, pra melhorar o entendimento do que esta ocorrendo.
https://youtu.be/DxxSXPh_ayw

**Comment by jnrpalma** [comment]
Ola @JCTG-Jorge passa pra mim seu app por gentileza !
Fico no aguardo.

**Comment by JCTG-Jorge** [comment]
Oi @jnrpalma 
segui o app
https://github.com/JCTG-Jorge/DEVPOUI17

**Comment by jnrpalma** [comment]
Olá @JCTG-Jorge realizei algumas mudanças nos fontes fornecidos 
```
export class AuthInterceptor implements HttpInterceptor {

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    console.log("Passou no Interceptor");

    const headers = new HttpHeaders({
      'Content-Type': 'application/json',
      'Authorization': 'Basic ' + btoa('jorge:pedrinho@123')
    });

    // Clonando a requisição para adicionar os novos cabeçalhos
    req = req.clone({ headers });

    // Utilizando o método `handle` do `HttpHandler` para passar a requisição adiante
    return next.handle(req);
  }
}
```
```
export const appConfig: ApplicationConfig = {
  providers: [
    provideRouter(routes),
    provideHttpClient(),
    {
      provide: HTTP_INTERCEPTORS,
      useClass: AuthInterceptor,
      multi: true,
    },
    importProvidersFrom([BrowserAnimationsModule, HttpClientModule, PoHttpRequestModule]),
  ],
};
```
```
<po-page-dynamic-table
  #cadastroTable
  [p-auto-router]="true"
  [p-concat-filters]="true"
  [p-keep-filters]="true"
  p-title="Users"
  [p-fields]="fields"
  p-service-api="https://po-sample-api.onrender.com/v1/people">
</po-page-dynamic-table>
```
Dessa forma não mais necessária o uso do `ngOninit`

Realize testes e me retorne fico no aguardo !

**Comment by JCTG-Jorge** [comment]
@jnrpalma, 
funcionou muito obrigado pela explicação e o apoio...
entao com o PO-UI tem que continuar usando HttpInterceptor ... e não o que eu estava tentando usar  "HttpInterceptorFn"
correto?

**Comment by jnrpalma** [comment]
A interface HttpInterceptor fornece o método intercept, que você precisa sobrescrever para adicionar a lógica do seu interceptor...

**Comment by jnrpalma** [comment]
Core Team PO UI à Disposição.
