### ISSUE TITLE
Page Dynamic Edit:  Não exibe mensagem de erro 500 - regra de negocio

### ISSUE THREAD

**Issue by JCTG-Jorge** [po-ui/po-angular#2039]
Boa tarde!

Estou fazendo o uso da Page Dynamic Edit, porém quando é retorno erro 500 da api não está sendo exibido.
![image](https://github.com/po-ui/po-angular/assets/160171828/484459b9-be1e-483c-bc28-b9f2cb29be44)

![image](https://github.com/po-ui/po-angular/assets/160171828/9064a361-ec6c-48c0-8b83-d062e7059e59)

#### Qual o comportamento atual?
Não exibe mensagem de erro somente de sucesso 

#### Que comportamento você esperava ver?
que apresente a mensagem de erro 500 da regra de negocio.

#### Ambiente

- PO UI: 17.5
- Angular: 17
- Browser(s):
  - [ x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by anliben** [comment]
Boa Tarde.

Seguindo o guia de implementação de API localizado em: https://po-ui.io/guides/api

Entendemos que a propriedade `code` deveria ser preenchida por um código de http que se estende entre 4xx e 5xx.

Para o seu caso seria.
```
{
  code: "500",
  detailedMessage: "",
  message: "",
  type: "error"
}
```

Lembrando que detailedMessage e a mensagem detalhada, uma mensagem curta ou titulo seria message.

Attr.

**Comment by anliben** [comment]
Poderia incluir aqui o seu código?

**Comment by JCTG-Jorge** [comment]
Html:

<po-page-dynamic-edit
[p-auto-router]="true"
[p-service-api]="service.apiService()"
[p-actions]="actions"
[p-fields]="fields"
[p-breadcrumb]="breadcrumb">
</po-page-dynamic-edit>


component....................
<po-page-dynamic-edit
[p-auto-router]="true"
[p-service-api]="service.apiService()"
[p-actions]="actions"
[p-fields]="fields"
[p-breadcrumb]="breadcrumb">
</po-page-dynamic-edit>

service:
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { environment } from '../../environments/environment';

@Injectable({
  providedIn: 'root'
})
export class Esws0109Service {

  private API = environment.apiUrl
  constructor(private http: HttpClient) { }


  apiService(){
    let url = this.API +  'cie/v1/esws0109ws'
    return url
  }

  apiServiceSetor(){
    let url = this.API +  'cie/v1/esws0108ws'
    return url
  }

}

**Comment by JCTG-Jorge** [comment]
Bom dia!
Consegui fazer as notificações voltarem a ser exibidas automatica,
Solução: Como estou usando a versão 17 do angular, como "standalone"  e 17.5 do PO-UI, tive que fazer a importação do PoModule no app.config.ts, dai tudo voltou a funcionar normalmente.
