### ISSUE TITLE
Loading nos botões do PageHeaderActions

### ISSUE THREAD

**Issue by SalatielBairros** [po-ui/po-angular#208]
#### Descrição da melhoria
Confirme a documentação do portinari no PoButton, existe a possibilidade de informar quando o botão está ou não em loading, fazendo com que ele fique desabilitado e um gif apareça no canto esquerdo do botão. No entanto, não é possível utilizar esta propriedade nos botões das actions de uma page, ainda que ela use PoButtons para exibir na tela, essa propriedade não está exposta na interface PoPageAction.

#### Caso de uso
Preciso realizar a chamada de um paciente, conforme imagem abaixo: 

![image](https://user-images.githubusercontent.com/10634531/71476928-3423f100-27c6-11ea-93dd-9b19db482663.png)

Ao chamar, é necessário bloquear o botão até que a chamada seja realizada, exibindo o gif já existente como funcionalidade no PoButton.

#### Informações adicionais
Caso a inclusão dessa propriedade for quebrar outros projetos que já estão utilizando essa interface, talvez dê para criá-la em na propriedade page ou uma diretiva no page header ou nos botões.

**Comment by jhosefmarks** [comment]
Boa tarde @SalatielBairros, hoje não é possível pois as ações da página podem ser exibidas através de botões e/ou em uma lista (quando atingido o número máximo de ações que podem ser exibidas), como as ações em lista não tem essa opção não foi feito a exposição dessa propriedade usado apenas no button.

Vamos avaliar melhor sua demanda para adicionar o loading também nas ações exibidas na lista.

**Comment by SalatielBairros** [comment]
Ok! Me disponho a, inclusive, trabalhar em par com alguém do projeto, seja sobre esta demanda ou seja pela outra que comentei, para pensarmos soluções para isso. Como o projeto é Open Source, seria muito interessante para mim estar mais ambientado com o código e padrões de desenvolvimento do Portinari para que eu consiga contribuir melhor na ferramenta e ser mais preciso nas necessidades que temos e a relevância delas para o Portinari.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
