### ISSUE TITLE
Evento keyPress no PoInput

### ISSUE THREAD

**Issue by jeterson** [po-ui/po-angular#211]
#### Descrição da melhoria
Notei que o `PoInput` não possui um evento `KeyPress` configurado.
Caso realmente nao tenha uma maneira de fazer isso, ou uma maneira simpes de fazer isso, é uma feature interessante.

#### Caso de uso
Campo de pesquisa de registros em uma tabela. Usuário digita sua pesquisa, tecla enter, e o evento é disparado realizando a consulta.

#### Informações adicionais
-

**Comment by jhosefmarks** [comment]
Boa tarde @jeterson, você pode usar dessa forma:

```
<po-input
  p-label="Pesquisa"
  [(ngModel)]="search"
  (keydown.enter)="startSearch($event)">
</po-input>
```

Veja se isso atende sua necessidade.
