### ISSUE TITLE
Selector de colunas do PoTable

### ISSUE THREAD

**Issue by jeterson** [po-ui/po-angular#212]
#### Descrição da melhoria
1 -  Permitir que a configuração do recente seletor de colunas possa ser salvo localmente (no localstorage ou cookies).

2 -  Outra feature interessante, é que o usuário possa trocar a posição das colunas dentro do PoTable

#### Caso de uso
1 - O usuário realiza uma configuração das colunas que ele julgue ser melhor para sua legibilidade, e ao fechar o navegador, sair da rota, fechar a aba, quando voltar aquela tela, as colunas estejam do jeito que deixou pela ultima vez.

2 - Usuário muda a posição da ultima coluna para a primeira coluna, e que isso também fiquei salvo no navegador.

**Comment by jhosefmarks** [comment]
Sugestão anotada e adicionada ao nosso backlog.

**Comment by tiago-arrosi** [comment]
Alguns clientes do produto Totvs Saúde Planos - Datasul também pediram para salvarmos a configuração das colunas por usuário. Não sei se apenas salvar no front seria o ideal. Acredito que precisaríamos salvar em banco essas configurações.

Para isso, entendo que seria necessário implementar as seguintes regras:

- Ter acesso ao model com as colunas visíveis/ocultas;
- Evento quando uma coluna for apresentada ou escondida;
- Conseguirmos selecionar dinamicamente as colunas que devem estar visíveis.

**Comment by ricardo-mello** [comment]
Acredito que esse seja o caminho mesmo @tiago-arrosi 

Assim, atenderia quem quer salvar no front, nos casos mais simples em que a configuração do usuário não precise persistir. E ao mesmo tempo abriria um leque de possibilidades para que possamos persistir essas preferências do usuário na base.

**Comment by jhonyeduardo** [comment]
Bom dia Pessoal

Lançamos no PoTable o evento _p-change-visible-columns_, o qual será disparado ao selecionar as colunas que serão visíveis ao usuário, por parâmetro é enviado a lista de colunas visíveis.

**Comment by alinelariguet** [comment]
Boa tarde @jeterson, conforme comentário anterior já disponibilizamos o evento p-change-visible-columns e também já está disponível a funcionalidade de poder reordenar as colunas através do gerenciador. Já temos exemplo disso no nosso portal, inclusive persistindo essas informações. Essa última funcionalidade foi liberada na v6.13.0.
Att.
