### ISSUE TITLE
Documentação de filter-service para componentes Lookup, combo, etc..

### ISSUE THREAD

**Issue by nicocelli** [po-ui/po-angular#214]
#### Descrição da melhoria
Descreva a melhoria que você gostaria de ver.

O padrão de response das APIS para utilização dos componentes com o filter-service não está claro na documentação. Minha sugestão é que deveria estar explícito na documentação de cada componente que a API deverá obrigatoriamente responder com as propriedades **Label** e **Value** do backend.

#### Caso de uso
Descreva os casos de uso que a melhoria permitiria.

Melhor entendimento para novos usuários do framework portinari.

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

**Comment by jhosefmarks** [comment]
Boa tarde @nicocelli, não é obrigatório que o seu objeto venha com `label` e `value`, você pode usar as propriedades `p-field-label` e `p-field-label` para que o componente faça o de-para por você.

Ficou mais alguma dúvida sobre o uso das propriedades?
