### ISSUE TITLE
Dúvida: Componente de múltipla seleção com opção de pesquisa(lookup)

### ISSUE THREAD

**Issue by nicocelli** [po-ui/po-angular#215]
#### Descrição da melhoria
Descreva a melhoria que você gostaria de ver.

Gostaria de saber se existe algum componente além do **po-combo** onde permite a visualização dos registros em tabela, pesquisa com filtros avançados e a múltipla seleção.

Basicamente é um Lookup com seleção múltipla, onde o componente devolve a lista dos IDs selecionados.

#### Caso de uso
Descreva os casos de uso que a melhoria permitiria.

- Casos onde a lista de registros é extensa e possui vários campos que podem ser filtrados e selecionados.

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

Veja nas imagens abaixo o contexto da utilização desse componente.

**Considerando esse cadastro onde preciso adicionar produtos:**
![image](https://user-images.githubusercontent.com/1651988/71669051-2c29fb00-2d4a-11ea-9ebf-5a962760b653.png)

**Utilizo o componente para filtrar e selecionar vários registros:**
![image](https://user-images.githubusercontent.com/1651988/71669206-a78bac80-2d4a-11ea-933e-6e63b5c88de5.png)

**Os itens selecionados são devolvidos para o componente que chamou:**
![image](https://user-images.githubusercontent.com/1651988/71669091-51b70480-2d4a-11ea-94ce-f4768fb6d981.png)

**Comment by jhosefmarks** [comment]
Boa tarde @nicocelli, nós temos o [multiselect](https://portinari.io/documentation/po-multiselect), mas o mesmo não faz requisições para um endpoint como o lookup hoje.  

Já temos em nosso backlog itens para fazer essa melhoria em nosso componente.

**Comment by tiago-arrosi** [comment]
Pessoal, temos uma previsão para essa melhoria? 
No Totvs Saúde Planos - Linha Datasul temos a necessidade de seleção múltipla utilizando um serviço do backend, para isso precisaríamos desse melhoria ou então a opção de seleção múltipla no Lookup.

**Comment by jhonyeduardo** [comment]
Bom dia @tiago-arrosi 

Vamos avaliar a possibilidade de entrega para o 2021Q1, qualquer novidade serão avisados, obrigado.

**Comment by tiago-arrosi** [comment]
Boa tarde. @jhonyeduardo .

Alguma novidade sobre esse item?

Obrigado.

**Comment by jhonyeduardo** [comment]
Boa tarde @tiago-arrosi 

Estamos planejando para entregar neste Q3, tivemos perda de devs e afetou nossas entregas, mas estamos trabalhando para entregar final de julho ou meio de agosto.

**Comment by tiago-arrosi** [comment]
Legal. Obrigado pelo retorno @jhonyeduardo

**Comment by jhonyeduardo** [comment]
@nicocelli Sobre o PoLookup com múltipla seleção estamos planejando para entregar este ano.

**Comment by alinelariguet** [comment]
Foi finalizado e entregue na versão 5.18.0.
