### ISSUE TITLE
<po-multiselect>: Cor diferente da flexinha

### ISSUE THREAD

**Issue by eduardodallmann** [po-ui/po-angular#2154]
#### Reprodução
https://codesandbox.io/p/devbox/disable-options-select-ff8v79

Passos para reproduzir:
1. Abrir o link do codesandbox
2. Observar que a cor da flexinha do po-select é diferente do po-multiselect

#### Que comportamento você esperava ver?
As duas flexinhas deveriam ter a mesma cor. Quando usadas na mesma tela, pode parecer discrepante.

#### Ambiente

- PO UI: 17.20.0
- Angular: 17.3.0

#### Observações
![image](https://github.com/user-attachments/assets/feb27ebd-2a25-4986-bdec-c0b0d1751f91)

**Comment by bruno-severino** [comment]
Olá, @eduardodallmann 

Agradecemos por nos informar. Nossa equipe já está analisando a situação e entraremos em contato com mais informações em breve. Agradecemos pela sua compreensão.

Atenciosamente,
Time PO-UI [(doc)](https://po-ui.io/documentation)

**Comment by bruno-severino** [comment]
OLA @eduardodallmann , foi aberto uma task no nosso backlog **DTHHFUI-9679** par corrigir as cores do chevron-down dos componentes.

Assim que finalizarmos a task, entraremos em contato com a versão do po-ui corrigida.

Atenciosamente,
Time PO-UI [(doc)](https://po-ui.io/documentation)
