### ISSUE TITLE
Interface PoDynamicFormField

### ISSUE THREAD

**Issue by JCTG-Jorge** [po-ui/po-angular#2170]
#### Descrição da melhoria
Duvida na interafec PoDynamicFormField, não tem como setar um valor inicial para uma propriedade tipo ngModel ?

#### Caso de uso
Poder infromar um valor incial em input usando a interafec PoDynamicFormField.

**Comment by felipepetuco** [comment]
Olá @JCTG-Jorge obrigado por entrar em contato conosco. 

As interfaces são utilizadas para descrever a estrutura do objeto em questão por exemplo, quais propriedades e tipos de valores elas esperam receber. O local mais adequado para definir um valor inicial seria no ngOnInit 

Atenciosamente,
Time PO-UI
