### ISSUE TITLE
<po-toolbar>: o popup da notificação esta ficando no lugar errado

### ISSUE THREAD

**Issue by rafameureer** [po-ui/po-angular#2172]
#### Reprodução
No propria documentação do toolbar o problema acontece, ao usar toolbar action type como notification

Passos para reproduzir:
1. Criar um po-toolbar utilizando o p-notification-actions e o p-notification-number depois disso somente clickar na notificação
2. Também é possivel ir pela documentação do po-toolbar nos exemplos da parte de PO Toolbar Labs e cadastrar uma toolbar action type notification

#### Qual o comportamento atual?
O popup abre proximo ao meio da tela com a seta apontado para o nada

#### Que comportamento você esperava ver?
Espera que fosse aberto logo abaixo do ícone de notificação e com a seta apontando para o mesmo

#### Ambiente

- PO UI: 18.1.0
- Angular: 18.1.2
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações
![image](https://github.com/user-attachments/assets/106d6433-0542-432b-b3cb-c10de1ce94bd)

**Comment by wsteixeira** [comment]
Olá @jkozima,

Eu também estou com este problema, porém além de abrir deslocado, não fecha depois de clicar!

**Comment by bruno-severino** [comment]
Olá, @rafameureer 

Identificamos onde está o problema e vamos abrir uma task no nosso Jira para resolvê-lo. Assim que tivermos mais informações, postarei uma atualização aqui.

Atenciosamente,
Time PO-UI [(doc)](https://po-ui.io/documentation)

**Comment by wsteixeira** [comment]
Olá @bruno-severino, isso depois de corrigido será publicado na V18 ou na V17 ou em ambas, pergunto porque foi informado anteriormente que as versões impares teriam suporte estendido! 

Atenciosamente,

**Comment by bruno-severino** [comment]
Olá, @wsteixeira

Sim, após a correção, ela será publicada tanto na V18 quanto na V17.

Atenciosamente,
Time PO-UI [(doc)](https://po-ui.io/documentation)

**Comment by bruno-severino** [comment]
Olá @rafameureer  e @wsteixeira 
A correção da issue foi já realizada. subimos nas versões:

 • v17.26.0.
https://github.com/po-ui/po-angular/blob/17.x.x/CHANGELOG.md

  • v18.6.0.
https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md

Qualquer dúvida, estou a disposição.

Atenciosamente,
Time PO-UI [(doc)](https://po-ui.io/documentation)
