### ISSUE TITLE
Método de Empty para o PoCombo

### ISSUE THREAD

**Issue by SalatielBairros** [po-ui/po-angular#220]
#### Descrição da melhoria
Dependendo da regra onde o combo é utilizado, se torna necessário limpar o seu conteúdo para novas alterações. No entanto, devido aos vínculos com eventos, a única forma de alterar limpar o registro é dentro de um `setTimeout`. 

#### Caso de uso
Conforme a imagem abaixo, o combo é utilizado para inserir itens dinamicamente em uma lista. Para cada item adicionado, o combo deve ser limpo outra vez:

![image](https://user-images.githubusercontent.com/10634531/71922309-786da480-3169-11ea-80d8-de362dc6500b.png)

O código atual utilizado para limpar o PoCombo é:
```
  private _resetCombo() {
    setTimeout(() => {
      // propriedade associada ao componente no ngModel
      this.current = '';
      this.combo.focus();
    }, 0);
  }
```

O ideal seria poder chamar algo como `this.combo.empty()`.

#### Informações adicionais
Já foi realizada uma chamada com o @jhosefmarks sobre a situação.

**Comment by jhosefmarks** [comment]
Sugestão adicionada ao nosso backlog.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
