### ISSUE TITLE
Navbar gerando scrollbar vertical

### ISSUE THREAD

**Issue by Rezoppei** [po-ui/po-angular#221]
#### Qual o comportamento atual?
Ao adicionar a NavBar, aparece um scrollbar vertical que pega toda a extensão da página.

#### Que comportamento você esperava ver?
Esperava que a Navbar se incorporasse ao layout da mesma maneira que antes de adicioná-la.

#### Ambiente

Segue app.component.html

```
<po-navbar
    p-logo="../../assets/img/Logo-Azul-01.png"
    p-menu="userMenu"
    p-shadow="true" >
</po-navbar>

<div class="po-wrapper">

  <po-menu #userMenu [p-menus]="menus"></po-menu>

  <po-page-default p-title="Nordy">
    <p> AppName page </p>
  </po-page-default>
</div>
```
Alguém teve esse problema ou sabe como resolver?

![Webp net-resizeimage](https://user-images.githubusercontent.com/51380599/71994050-dc9a7200-3216-11ea-86b3-6998ab5592d8.png)

Obs: Uma maneira de contornar o problema e colocar a tag "po-navbar" dentro da "po-wrapper", mas isso gera um outro problema, o menu lateral fica atrás da Navbar.

Ambiente
Angular CLI: 8.3.21
Node: 12.13.0
OS: win32 x64
Angular: 8.2.14
Portinari: 1.22.1
Browser(s): Edge, Chrome

**Comment by jhosefmarks** [comment]
Favor informar os dados abaixo:

#### Ambiente

- Portinari:
- Angular:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by Rezoppei** [comment]
> Favor informar os dados abaixo:
> 
> #### Ambiente
> * Portinari:
> * Angular:
> * Browser(s):
> * Operating System (e.g. Windows, macOS, Ubuntu):

Obrigado pela correção. Fiz o update no post original.

**Comment by Rezoppei** [comment]
Será que é possível alguém me ajudar? Baixei a versão 1.23.0 do PO, mas, também não tive sucesso com meu problema.

**Comment by Rezoppei** [comment]
Eu ouvi vocês no Hypsters. Acreditei em vocês e no nome da Totvs.
Todo mundo da minha equipe disse que vocês não estavam preparados pra um projeto Open Source, só queriam o apoio da comunidade pra trabalharem de graça pra vocês.
Eu duvidei. E fiz uma aposta simples. Eu teria 3 semanas pra postar um problema simples porém real e esperar um prazo pra que isto fosse solucionado com o apoio de vocês.
Infelizmente hoje o prazo se encerrou e e eu perdi essa aposta. Não iremos utilizar o Portinari em Produção. 
De qualquer maneira, desejo sucesso à iniciativa e sigo acreditando.
Forte abraço à todos.

**Comment by jhosefmarks** [comment]
Bom dia @Rezoppei, lamento que o seu problema não tenha sido resolvido da forma e na velocidade que você esperava.

Faltou da minha parte informar aqui na issue que nós colocamos sua issue no nosso planejamento mas que infelizmente estamos bastante atarefados e precisamos de um tempo a mais para resolver o problema, estamos revisitando TODOS OS NOSSOS COMPONENTES para que eles fiquem acessíveis para que todos possam aproveitar o máximo possível da biblioteca sem restringir nenhum usuário que possa se beneficiar do seu/nossos projetos que venham a usar o Portinari UI, o Navbar é o 3º componente (se pensar que os fields são considerados um) que está sendo avaliado pela equipe de UX.

Além das 46 issues abertas (47 com essa) aqui no github, ainda temos mais de 300 issues no nosso backlog interno (e isso não é nada perto de outros projetos, veja os números do Angular), e não estou falando de bugs, estamos falando de sugestões de melhorias, ideias nossas e de outros desenvolvedores que querem ver o projeto dar certo.

Estamos vendo uma forma de expor nosso roadmap para a comunidade e numa forma de informar a comunidade em que estamos trabalhando no momento buscando ser o mais transparente possível.

Nossa equipe é pequena comparada a outros projetos open source de destaque e conta com a colaboração de outros devs dentro da Totvs quando os mesmo tem disponibilidade e gostam de colaborar, e quando possível com devs que tem interesse em participar que não tem vínculo algum com a Totvs. A Totvs não quer desenvolvedores trabalhando de graça, a Totvs quer que a comunidade colabore quando achar viável e se achar que deve, o Portinari UI não é um produto da Totvs, a Totvs entregou o projeto para a comunidade (licença MIT) para que a comunidade se beneficiasse com o mesmo, eu por exemplo estou fora do meu expediente de trabalho e estou aqui respondendo sua issue e tentando ajudar por que acredito que esse é um projeto que pode ajudar muitos devs/projetos.

Talvez seu time tenha razão, talvez a Totvs ainda não esteja 100% preparada para um projeto Open Source, mas talvez esteja sim e é o que eu acredito, mas precisa que a comunidade abrace o projeto também, afinal o sucesso de qualquer projeto Open Source depende da comunidade de desenvolvedores e não apenas de uma empresa, esse é o nosso primeiro projeto, estamos aprendendo bastante e contamos com o feedback de vocês para melhorar, eu gostaria de receber mais feedbacks desse tipo, mas também gostaria de saber com o que vocês gostariam de colaborar para melhorar ainda mais o projeto, por exemplo, qual a sugestão que vocês dariam para que esse tipo de situação não voltasse a acontecer?

Vocês poderiam fazer um fork do projeto e trabalhar nas correções e melhorias que vocês acham interessante e guardar para vocês e o trabalho de vocês não seria de graça ou vocês poderiam colaborar ajudando a corrigir o problema que você relatou e ajudar outras pessoas que podem ter tido o mesmo problema que você.

Espero ter respondido e explicado o motivo de não termos resolvido o seu problema da maneira que você esperava, mas espero também que compreenda que esse é um projeto de todos, onde todos são bem vindos a colaborar também, já deve ter ouvido isso, mas se cada um ajudar um pouco não fica pesado para ninguém e todo mundo se beneficia.

Conto com sua participação e espero que o Portinari UI volte a atender as suas expectativas.

Obs: vou reabrir a issue já que o problema persiste e outros podem sofrer com o mesmo problema.

**Comment by Rezoppei** [comment]
Agradeço DEMAIS a resposta. Eu tenho um projeto pessoal e vou seguir com o Portinari. Não é um projeto grande, mas, estou colocando todo meu tempo e dinheiro nele.
Será que seria possível você disponibilizar um app.component.html que você já tenham utilizado? Eu vejo que o site do portinari.io não tem esse problema. Acredito que é ali que não estou acertando.
Muito obrigado novamente.

**Comment by jhosefmarks** [comment]
Boa tarde @Rezoppei, como medida paleativa, tente adicionar no seu arquivo CSS o seguinte código:

```
po-navbar~.po-wrapper {
  padding-top: 56px;
  height: 100%;
  margin-top: unset;
}
```

Deve resolver seu problema até que consigamos revisar o Navbar para acertar esse problema.

**Comment by Rezoppei** [comment]
Resolveu mesmo!!! Muito obrigado!!!

**Comment by jhosefmarks** [comment]
Item resolvido: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#340-2020-08-31
