### ISSUE TITLE
po-icon: manter a descrição de ícones antigos do po-ui

### ISSUE THREAD

**Issue by thiagogoncalves** [po-ui/po-angular#2225]
#### Qual o comportamento atual?
Eu ainda possuo um projeto numa versão antiga do PO-UI, e não tenho planos de migrar de versão por agora. Preciso colocar alguns ícones(da versão antiga) e não tenho mais os códigos.

#### Que comportamento você esperava ver?
Uma página informando os códigos dos ícones na versão antiga devido a compatibilidade de versões de produtos na versão antiga.

**Comment by anabye** [comment]
Bom dia @thiagogoncalves,

Você pode estar consultando a biblioteca de ícones anterior neste link:
https://github.com/po-ui/po-style/blob/17.x.x/docs/guides/icons.md

**Comment by kaironferreira** [comment]
Esta precisando, também. Valeu @anabye

**Comment by joaohdib** [comment]
ajudou bastante, também tava precisando
