### ISSUE TITLE
Inserção de Imagem nas linhas da Tabela

### ISSUE THREAD

**Issue by aksilvaa** [po-ui/po-angular#224]
#### Descrição da melhoria

- Possibilitar a inserção de imagem nas linhas da tabela.

#### Caso de uso

- Essa funcionalidade permite que o usuário realize a visualização prévias das imagens antes de acessar um outro componente, modal ou outro.

#### Informações adicionais

- Um exemplo prático da sua usabilidade seria o exemplo abaixo no qual seria possível visualizar um produto ou serviço anteriormente. 

![image](https://user-images.githubusercontent.com/50679891/72173437-4bfa9800-33b6-11ea-90bc-c4d69ab9c44f.png)

**Comment by jhosefmarks** [comment]
Sugestão adicionada ao nosso backlog.

**Comment by jhonyeduardo** [comment]
Boa noite @aksilvaa 

Com a funcionalidade [PoTableColumnTemplate](https://po-ui.io/documentation/po-table-column-template), que foi lançada na versão [2.8.0](
https://po-ui.io/documentation/po-table-column-template), ainda necessitaria da funcionalidade solicitada nesta issue?

Com ela você tem mais liberdade para exibir informações.

Pode observar um exemplo no nosso portal: [SamplePoTableFieldComponents](https://po-ui.io/documentation/po-table?view=web)

**Comment by jhonyeduardo** [comment]
Olá @aksilvaa 

Resolveu o seu problema?

**Comment by CarlosEReis** [comment]
Acredito que sim:
![image](https://user-images.githubusercontent.com/12797559/100520553-0e912b80-317d-11eb-8e7b-c775b7980370.png)

**Comment by aksilvaa** [comment]
Bom dia, desculpe a demora, acabei não recebendo as primeiras notificações, mas resolveu sim o meu problema.

Obrigado!
