### ISSUE TITLE
Datepicker Range (dúvida)

### ISSUE THREAD

**Issue by danielsilvalima1996** [po-ui/po-angular#225]
#### Qual o comportamento atual?
O Datepicker Range recebe duas datas, porém ele não abre um calendário para auxilar na escolha das datas.

#### Que comportamento você esperava ver?
Ele deveria abrir um calendário para auxiliar na escolha das datas.

Exemplo: Site para compra de passagens aéreas.

#### Ambiente

- Portinari: 1.22.1
- Angular: 8
- Browser(s): Google Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 18.04

A dúvida seria se o componente abre um calendário para auxiliar na escolha da data?

Caso não, poderia ser uma melhoria?

Desde já agradeço!

**Comment by jhosefmarks** [comment]
Boa tarde @danielsilvalima1996, atualmente ele não tem esse comportamento mas já temos um item relacionado a essa necessidade.

Conforme nosso planejamento vamos fazer a entrega do mesmo.

**Comment by jhonyeduardo** [comment]
Issue resolvida na versão [5.2.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#520-2021-06-21)
