### ISSUE TITLE
Dynamic-view: Erro na exibição do componente multiselect com múltiplas opções

### ISSUE THREAD

**Issue by wsteixeira** [po-ui/po-angular#2308]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui-vvdrsy?file=src%2Fapp%2Fapp.component.ts) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Criar uma pagina com o componente `po-dynamic-view`;  
2. Em `p-fields` informe para o primeiro campo `property: 'teste'`;
3. Ainda em `p-fields` informe para o primeiro campo `optionsMulti: true`;
4. Ainda em `p-fields` informe para o primeiro campo `options` com as opções possíveis;
5. Em `p-value` informe as opções marcadas, por exemplo `{ teste: [1, 2] }`
6. O componente `multiselect` não será renderizado com as opções selecionadas 

#### Qual o comportamento atual?
Na simulação enviada foi simulado a mesma situação no `dynamic-form` e no `dynamic-view`, porem no `dynamic-view` o componente não foi renderizado corretamente!

#### Que comportamento você esperava ver?
Que o componente `dynamic-view` fosse renderizado corretamente e de forma semelhante ao `dynamic-form`.

#### Ambiente

- PO UI: 18.15.0
- Angular: 18.0.1
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

#### Observações

![image](https://github.com/user-attachments/assets/cb12824c-54bc-4be8-b836-5f2eb1b50169)

Tempo de Resposta PO UI --> Em até 7 dias úteis.
Tempo de Retorno Solicitante --> 35 dias corridos
Issues sem retorno do solicitante por mais de 35 dias corridos serão encerradas.

**Comment by anabye** [comment]
Bom dia @wsteixeira 

Obrigada por reportar. Ajuste sendo tratado na PR de contribuição https://github.com/po-ui/po-angular/pull/2310 

Atenciosamente.
