### ISSUE TITLE
Possibilidade de ocultar o botão "Show more" da PoTable

### ISSUE THREAD

**Issue by meyer20** [po-ui/po-angular#232]
#### Descrição da melhoria
Implementar uma propriedade para esconder/remover o botão de "Load more" do componente PoTable.

#### Caso de uso
Essa funcionalidade permite ocultar/remover o botão de "Load more", tendo em vista que o botão bloqueado quando todos os dados já forem carregados não agrega muito valor funcional a tela, além de consumir espaço na tela.

#### Informações adicionais
Caso seja necessário, podem entrar em contato comigo através do email: 
rodrigo.meyer@fluig.com

**Comment by jhosefmarks** [comment]
Boa tarde @meyer20, essa é uma definição de UX, o botão permanece pois indica ao usuário que houve paginação e o mesmo não tem mais dados para serem carregados.

Caso tenha mais alguma dúvida, favor nos informar.
