### ISSUE TITLE
Implementar função disable para reactive form

### ISSUE THREAD

**Issue by fernando-alencar** [po-ui/po-angular#238]
Utilizando Reactive Form, quando desabilito o FormGroup ou o FormControl programaticamente no controle de angular, os componentes de interface do portinari vinculados não desabilitam, me forçando a usar a diretiva [disabled]="form.get('nome').disabled" por exemplo.

**Comment by jhosefmarks** [comment]
Bom dia @fernando-alencar, você pode reproduzir o problema para a gente?

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

**Comment by fernando-alencar** [comment]
Exemplo reproduzido em https://github.com/portinariui/portinari-angular/issues/238

**Comment by fernando-alencar** [comment]
> Exemplo reproduzido em #238
> 
> Mesmo desabilitando o FormControl o campo po-input continua editável.

**Comment by jhosefmarks** [comment]
@fernando-alencar o link que você postou é da própria issue aqui no Github, você pode fazer a reprodução no https://stackblitz.com/fork/portinariui e compartilhar o link do seu exemplo?

**Comment by fernando-alencar** [comment]
Olá @jhosefmarks , falha minha, segue exemplo correto: https://stackblitz.com/edit/portinariui-8p5nen

**Comment by jhosefmarks** [comment]
Boa tarde @fernando-alencar, vamos avaliar a situação.

**Comment by jhosefmarks** [comment]
Item adicionado ao backlog.

**Comment by jhonyeduardo** [comment]
Olá,

Nossos componentes de entrada estão aceitando serem desabilitados via ReactiveForm, liberado na versão 4.1.0, 
Obrigado!
