### ISSUE TITLE
Permitir remover o gerenciador de colunas do po-table

### ISSUE THREAD

**Issue by AlexandreWeber** [po-ui/po-angular#240]
Permitir remover o gerenciador de colunas do po-table

Em alguns casos trabalhamos com colunas com poucos campos e seria importante ter a opção de não exibir o gerenciador de colunas.

**Comment by jhosefmarks** [comment]
Vamos avaliar sua PR assim que possível.

**Comment by jhosefmarks** [comment]
Item finalizado pela PR #458
