### ISSUE TITLE
po-table - Coluna Fixa com Rolagem Scroll Lateral

### ISSUE THREAD

**Issue by dovalgomes** [po-ui/po-angular#245]
#### Descrição da melhoria
Gostaria de uma melhoria no componente de tabela onde eu consiga deixar uma ou mais colunas fixas enquanto as demais são dinâmicas e rolam de acordo com a barra de rolagem.

#### Caso de uso
Possuímos um portal de gerenciamento de recursos e gostaríamos de exibir o calendário em formato de grid. 

________________________________________
Recurso | Dia 02/01 | Dia 03/01 ...  
________________________________________
Doval.... | Cliente x | Cliente Y
________________________________________ 

Conforme o scroll rola para a direita para o eixo x a coluna recuso permanece fixa enquanto as demais colunas são dinâmicas.

#### Informações adicionais
Exemplo: https://codepen.io/paulobrien/pen/gWoVzN

**Comment by jhosefmarks** [comment]
Sugestão anotada!!

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
