### ISSUE TITLE
Header da página do Portinari UI não marca opção selecionada corretamente

### ISSUE THREAD

**Issue by dowglasbarros** [po-ui/po-angular#248]
#### Reprodução

Não se aplica.

#### Qual o comportamento atual?

Na página do Portinari UI, algumas opções quando selecionadas no Header não ficam sublinhadas ou é
preciso clicar duas vezes. Por exemplo: A aba **Iniciar** só fica sublinhada se for
clicada duas vezes, a aba **Guias** não fica sublinhada.

#### Que comportamento você esperava ver?

Ao clicar em uma opção ela deve ficar sublinhada.

#### Ambiente

- Portinari: Não se aplica
- Angular: Não se aplica
- Browser(s): Google Chrome Version 79.0.3945.117
- Operating System (e.g. Windows, macOS, Ubuntu): macOS

**Comment by jhosefmarks** [comment]
Bom dia @dowglasbarros esse item já foi reportado, está em nosso backlog para correção.

Obrigado pela contribuição!

**Comment by jhonyeduardo** [comment]
Boa noite @dowglasbarros 

Liberamos a correção desta item na versão 3.9.2, https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md

Obrigado!!
