### ISSUE TITLE
Impressão po-dynamic-view

### ISSUE THREAD

**Issue by Smmartinez** [po-ui/po-angular#258]
Galera, estou precisando de uma ajuda. Tenho um po-dynamic-view e preciso gerar um PDF desta view, pensei em usar o ctrl+P e mandar imprimir em PDF, mas quando eu faço isso ele imprime somente a primeira parte, ou seja, a parte visível da tela e tenho mais informações.
Existe alguma maneira, ou outro componente que eu possa usar para fazer isso?

**Comment by jhosefmarks** [comment]
@Smmartinez você pode enviar alguma imagem ou algo para que possamos reproduzir o problema?

**Comment by Smmartinez** [comment]
Jhosef,

No pdf é a impressão pela com o CTRL+P e o PNG é o restante da tela, perceba que ainda tem dados e informações para baixo de onde ele parou de imprimir.


Att.
Sergio Martinez Martinez
 
 



De: "Jhosef Marks" <notifications@github.com>
Enviada: 2020/01/28 17:03:15
Para: portinari-angular@noreply.github.com
Cc:  mm_sa@uol.com.br, mention@noreply.github.com
Assunto:  Re: [portinariui/portinari-angular] Impressão po-dynamic-view (#258)
 

@Smmartinez você pode enviar alguma imagem ou algo para que possamos reproduzir o problema?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/portinariui/portinari-angular/issues/258?email_source=notifications\u0026email_token=ABCSU54KP6UYLCBZRNIPPWDRACFP7A5CNFSM4KMSO65KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKEWJLI#issuecomment-579429549", "url": "https://github.com/portinariui/portinari-angular/issues/258?email_source=notifications\u0026email_token=ABCSU54KP6UYLCBZRNIPPWDRACFP7A5CNFSM4KMSO65KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKEWJLI#issuecomment-579429549", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url&qu
 ot;: &qu
 ot;https://github.com" } } ]

**Comment by Smmartinez** [comment]
@jhosefmarks fiz um exemplo https://portinariui-sbvdnl.stackblitz.io/  perceba que a tela tem mais campos na tela, mas se você der o CTRL+P e madar imprmir em PDF não aparece todos os campos.

**Comment by jhosefmarks** [comment]
Bom dia @Smmartinez, consegui fazer a impressão corretamente, verifique se o seu gerador de PDF não está configurado para apenas imprimir a primeira página, ou tente usar outro browser.

[portinariui-sbvdnl.stackblitz.io.pdf](https://github.com/portinariui/portinari-angular/files/4128388/portinariui-sbvdnl.stackblitz.io.pdf)

**Comment by Smmartinez** [comment]
Já tentei em todos os tipos de navegador.
Você esta usando algum software para gerar o PDF, ou esta usando a impressora do windows de PDF?


Att.
Sergio Martinez Martinez
 
 



De: "Jhosef Marks" <notifications@github.com>
Enviada: 2020/01/29 10:58:08
Para: portinari-angular@noreply.github.com
Cc:  mm_sa@uol.com.br, mention@noreply.github.com
Assunto:  Re: [portinariui/portinari-angular] Impressão po-dynamic-view (#258)
 

Bom dia @Smmartinez, consegui fazer a impressão corretamente, verifique se o seu gerador de PDF não está configurado para apenas imprimir a primeira página, ou tente usar outro browser.

portinariui-sbvdnl.stackblitz.io.pdf

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/portinariui/portinari-angular/issues/258?email_source=notifications\u0026email_token=ABCSU56EILGUEQ7NZ5MCD6LRAGDO3A5CNFSM4KMSO65KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKHIVLA#issuecomment-579766956", "url": "https://github.com/portinariui/portinari-angular/issues/258?email_source=notifications\u0026email_token=ABCSU56EILGUEQ7NZ5MCD6LRAGDO3A5CNFSM4KMSO65KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKHIVLA#issuecomment-579766956", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url&qu
 ot;: &qu
 ot;https://github.com" } } ]

**Comment by jhosefmarks** [comment]
Consegui simular o erro no IE e no Firefox numa máquina Windows, vou adicionar a issue para nossa próxima Sprint.

**Comment by Smmartinez** [comment]
Ufa... é faltou eu mencionar isso, estou com WINDOWS 10, tentei no Firefox, Chrome e o Edge e todos ocorre o mesmo problema.
Obrigado pela ajuda.


Att.
Sergio Martinez Martinez
 
 



De: "Jhosef Marks" <notifications@github.com>
Enviada: 2020/01/29 12:06:02
Para: portinari-angular@noreply.github.com
Cc:  mm_sa@uol.com.br, mention@noreply.github.com
Assunto:  Re: [portinariui/portinari-angular] Impressão po-dynamic-view (#258)
 

Consegui simular o erro no IE e no Firefox numa máquina Windows, vou adicionar a issue para nossa próxima Sprint.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.

[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/portinariui/portinari-angular/issues/258?email_source=notifications\u0026email_token=ABCSU5Z3GUUOITOTJX5JFGTRAGLMZA5CNFSM4KMSO65KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKHQDKA#issuecomment-579797416", "url": "https://github.com/portinariui/portinari-angular/issues/258?email_source=notifications\u0026email_token=ABCSU5Z3GUUOITOTJX5JFGTRAGLMZA5CNFSM4KMSO65KYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEKHQDKA#issuecomment-579797416", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url&qu
 ot;: &qu
 ot;https://github.com" } } ]

**Comment by nicoleoliveira** [comment]
Será liberado no próximo release :)

**Comment by Smmartinez** [comment]
Acabei de testar com a release 26 e mesmo assim não consigo imprimir todos os dados do dynamic-view,

**Comment by jhosefmarks** [comment]
Favor tentar fazer a impressão usando essa url: https://portinariui-ureclz.stackblitz.io/

Atualizei as dependências do Portinari UI e corrigi as dependências do Angular, o código do exemplo, continua sendo o seu.

**Comment by jhosefmarks** [comment]
@Smmartinez conseguiu testar com as últimas versões?
