### ISSUE TITLE
po-page-dynamic-table não popula dados, gerenciador de colunas não funciona

### ISSUE THREAD

**Issue by LucianoRex** [po-ui/po-angular#260]
Componente po-page-dynamic-table não está populando os dados da API,  e o gerenciaddor de colunas não está funcionando como esperado

**Comment by jhosefmarks** [comment]
Olá @LucianoRex,

#### Reprodução

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

Passos para reproduzir:
1. 
2. 

#### Qual o comportamento atual?


#### Que comportamento você esperava ver?


#### Ambiente

- Portinari:
- Angular:
- Browser(s):
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jhosefmarks** [comment]
Os samples foram corrigidos e estão sendo populados, o gerenciador de colunas será visto em nossa próxima sprint.
