### ISSUE TITLE
Gráfico de Colunas, Linhas e Colunas x Linhas

### ISSUE THREAD

**Issue by silverio27** [po-ui/po-angular#261]
Eu gostaria que fosse criado o type column para o componente po-chart.

Em diversos relatórios os clientes gostam de ver resultados relacionados ao tempo. E a forma mais simples pra sintetizar isso é com o gráfico de colunas ou linhas, em alguns casos precisamos comparar esses valores com metas estipuladas, exemplo:

Valores realizados em colunas.
Metas em linha.
Visualmente fica claro o momento que as metas foram alcançadas ou não e o quanto se passou ou o quanto ficou abaixo.

**Comment by jhosefmarks** [comment]
@silverio27 dentro do nosso roadmap, esses e outros gráficos estão planejados para o terceiro e quarto trimestre, hoje essa é a previsão.

Para sair antes desse prazo, dependemos da colaboração de outros desenvolvedores.

**Comment by silverio27** [comment]
@jhosefmarks  valeu, ainda não consigo contribuir, mas em breve quero fazer contribuições ao portinari.

**Comment by jhosefmarks** [comment]
@silverio27 vamos manter a issue aberta para que fique no nosso histórico a necessidade da criação do componente, e caso alguém tenha interesse possa contribuir.

**Comment by silverio27** [comment]
blz!

**Comment by jhosefmarks** [comment]
Issue adicionada ao nosso backlog.

**Comment by jhosefmarks** [comment]
Gráficos liberados, segue documentação: https://po-ui.io/documentation/po-chart?view=web

Versões que os mesmos foram liberados:
- Coluna - [3.14.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#3140-2020-11-23)
- Linha - [3.12.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#3120-2020-11-09)
