### ISSUE TITLE
ícones em SVG 

### ISSUE THREAD

**Issue by ux-lead** [po-ui/po-angular#264]
#### Descrição da melhoria
Olá, Pessoal! Primeiro gostaria de dar os parabéns. Portinari é show, minha sugestão de melhoria é a disponibilização da biblioteca de ícones do PO em svg, 

#### Caso de uso
Estou desenhando uma biblioteca de componentes do PO para o Adobe XD, e estou tentando ser 100% fiel aos componentes do Design System, mas estou levando um tempo muito grande para escrever a biblioteca, hora por causa do processo de pesquisa para achar um ícone compatível, hora desenhando o ícone. 

#### Informações adicionais
Estou escrevendo a biblioteca para facilitar o dia-a-dia o UX Designer, na hora de prototipar e desenhar wireframes, acelerando assim processo de desenvolvimento.

**Comment by jhosefmarks** [comment]
Bom dia @ux-lead, nós não temos os ícones separados ainda, pretendemos fazer isso no futuro para facilitar o uso em outros projetos e da forma que as pessoas acharem melhor, mas ainda não conseguimos fazer isso.

Não sei se é possível fazer a "engenharia reversa" em cima do arquivo de fonts que disponibilizamos para vocês e se isso ajudaria por enquanto, mas segue o link dos [ícones](https://github.com/portinariui/portinari-style/tree/master/src/assets/icons).

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
