### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by andredealmei** [po-ui/po-angular#267]
#### Descrição da melhoria
Criar um roadmap publico;

#### Caso de uso
Ajudaria a todos os devs que hoje utilizam o Portinari a saber a melhorias que estão planejadas;

#### Informações adicionais
Ao ler as issues , já foi citado varias vezes o roadmap , inclusive com possíveis datas, seria interessante expor algumas dessas informações para o publico;

**Comment by jhosefmarks** [comment]
Olá @andredealmei, estamos discutindo internamente como faremos para adicionar um documento com nosso Roadmap para todos os interessados. Nós entendemos que a exposição trás mais transparência para o projeto, mas entendemos que um roadmap também está vinculado a um compromisso de entrega.

Em breve teremos novidades sobre esse tópico.

**Comment by andredealmei** [comment]
Show, obrigado pela resposta @jhosefmarks , aguardo novidades!

**Comment by afucher** [comment]
@jhosefmarks alguma novidade em relação a isso?

**Comment by jhonyeduardo** [comment]
Olá Pessoal

Criamos nosso Roadmap público, fiquem atentos ao comunicado no documento.

https://github.com/po-ui/po-angular/wiki/Roadmap-2021

Qualquer dúvida, estamos a disposição.
