### ISSUE TITLE
Atualizar para angular 9

### ISSUE THREAD

**Issue by andredealmei** [po-ui/po-angular#272]
Atualizar para versão estável atual

**Comment by jhosefmarks** [comment]
Assim que possível estaremos fazendo a atualização.

**Comment by jhosefmarks** [comment]
Assim que possível estaremos fazendo a atualização.

**Comment by jhosefmarks** [comment]
Atualizado!

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#200-2020-04-17

#317
