### ISSUE TITLE
Implementar componente de paginação

### ISSUE THREAD

**Issue by joaopedromoraez** [po-ui/po-angular#279]
#### Descrição da melhoria
Implementar um widget genérico para exibir o conteúdo em formato paginado.

#### Caso de uso
Uma tabela que apresenta os dados de forma paginada, conforme a resposta da API, para seguir para as próximas paginas, se faz necessário um componente de paginação.

#### Informações adicionais
Um exemplo para esse componente seria os componentes de paginação existentes em outras bibliotecas como a do [PrimeNG](https://www.primefaces.org/primeng/#/paginator) e do [Bootstrap Angular](https://ng-bootstrap.github.io/#/components/pagination/)

**Comment by JoaoPedroMoraes** [comment]
Tenho interesse em implementar este componente.

**Comment by jhosefmarks** [comment]
Olá @JoaoPedroMoraes, qual a sugestão de uso desse componente?
Como ficaria a estrutura dele? Ou seja, como o usuário usaria esse seu componente?

Acho válida sua ideia, mas a implementação precisaria ser separada do table atual, para ser uma segunda opção para o desenvolvedor.

**Comment by eriklesbr** [comment]
Senti a falta dessa opção no componente table também!

@jhosefmarks, nesse caso o usuário enxergaria a tabela com a opção das páginas abaixo, ex: 1,2,3,..., 40. Com isso o usuário teria a opção de chegar a página 5 sem a necessidade de ficar clicando em carregar mais ate chegar ao componente específico!

**Comment by alinelariguet** [comment]
Olá! Este componente de paginação será desenvolvido pelo Animalia Design System, desta forma para evitarmos trabalhos duplicados, decidimos aguardar para sua implementação o que deve ocorrer em breve :)

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
