### ISSUE TITLE
Criar componente de "Page Slide"

### ISSUE THREAD

**Issue by rubinhos** [po-ui/po-angular#283]
**Descrição da melhoria**
Criar componente visual no estilo "Page Slide" - consiste em uma página lateral exibida programaticamente.

**Caso de uso**
Este componente é útil para exibir elementos avançados ou secundários conforme solicitação do usuário, sem que o mesmo saia da página atual. Possui um comportamento semelhante ao de uma modal.

**Informações adicionais**
Componente solicitado pelos desenvolvedores dos apps de logística da TOTVS e desenhado pelo UX dos mesmos.

Mais sobre o componente: [Page Slide: Stay on the page pattern](http://designingwebinterfaces.com/page-slide-stay-on-the-page-pattern)

[Protótipo PoPageSlide](https://ibb.co/nRxfHrP)

**Comment by jhosefmarks** [comment]
Bom dia @rubinhos, o uso do modal atual já não atenderia a necessidade?

**Comment by rubinhos** [comment]
Boa tarde @jhosefmarks, o comportamento é um pouco semelhante, mas a solicitação é de uma página fixa nas laterais, dando impressão que o conteúdo exibido é secundário (avançado) ao conteúdo da página principal e não como um conteúdo extra.

Aproveitando, como a equipe de UX já desenhou o componente eu fiz o PR do mesmo em: https://github.com/portinariui/portinari-angular/pull/285.

**Comment by silverio27** [comment]
Tô de olho nesse lançamento ai

**Comment by jhonyeduardo** [comment]
Componente disponível na biblioteca.

https://po-ui.io/documentation/po-page-slide
