### ISSUE TITLE
POCombo aceitando HTML/Script Injection

### ISSUE THREAD

**Issue by SalatielBairros** [po-ui/po-angular#294]
#### Reprodução

Passos para reproduzir:
1. Incluir um PO Combo.
2. Incluir no Combo uma option cuja label contém HTML, conforme imagem abaixo: 

![image](https://user-images.githubusercontent.com/10634531/75040767-08597a80-549a-11ea-8ca1-4d452b57582e.png)

3. O combo aceita o HTML formatado, ou seja, permite a injeção de HTML

![image](https://user-images.githubusercontent.com/10634531/75040821-23c48580-549a-11ea-87d1-5e1c22a07b4d.png)

#### Qual o comportamento atual?
POCombo permite HTML Injection. O bug pode ser reproduzido no próprio site da documentação do componente.

#### Que comportamento você esperava ver?
Tudo o que for informado como label do combo deveria ser tratado como texto e não ser renderizado, como é hoje no POMultiselect

#### Ambiente:
https://portinari.io/documentation/po-combo

- Portinari: V1.26.0
- Angular: 8
- Browser(s): Chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jhosefmarks** [comment]
@SalatielBairros vamos verificar essa situação, mas o certo é não ter esse comportamento, pois se você quiser criar seu próprio template você deveria usar a diretiva [PoComboOptionTemplateDirective](https://portinari.io/documentation/po-combo-option-template).

**Comment by jhosefmarks** [comment]
Corrigido na versão 2.0.0. #375
