### ISSUE TITLE
Page Actions

### ISSUE THREAD

**Issue by danielsilvalima1996** [po-ui/po-angular#309]
#### Qual o comportamento atual?
Quando há mais duas ou mais ações no mobile ou mais de três no desktop, o po-page-default colocar as demais ações em um botão com o label "outras ações".

![Captura de tela de 2020-03-02 15-18-51](https://user-images.githubusercontent.com/48965860/75705472-33ae4780-5c9a-11ea-92a3-00977cfff06e.png)

#### Que comportamento você esperava ver?
Gostaria de saber como mudar o label do botão "outras ações", pois estou utilizando o I18N para adicionar o inglês e espanhol no projeto, e o mesmo se mantém em português.

Sei que na tabela é possível personalizar o component através do literals. no po-page-default há algo parecido?

#### Ambiente

- Portinari: 1.25.0
- Angular: 8.0.0
- Browser(s): Google Chrome 80.0.3987.116
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu 18.04.3

**Comment by jhosefmarks** [comment]
Atualmente o label muda de acordo com o idioma do browser, estamos fazendo a alteração dos componentes para que os mesmos passem a fazer a tradução baseado no serviço i18n também, mas ainda não fizemos a alteração no page default.

Em breve vocês terão essa funcionalidade.

**Comment by jhonyeduardo** [comment]
Boa tarde @danielsilvalima1996 

Na versão 3.10.0 lançamos essa funcionalidade.

Agora, por padrão traduzimos ela corretamente conforme o PoI18n, porém você também pode alterar a literal através do p-literals implementado no PoPageDefault.


https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md
https://po-ui.io/documentation/po-page-default

**Comment by danielsilvalima1996** [comment]
Bom dia @jhonyeduardo !

Obrigado pelo retorno, eu atualizei o projeto semana passada da versão 1.28.0 para a 3.10.0, vou implementar a funcionalidade nos outras ações pelo p-literals.

E novamente, muito obrigado a você e toda a equipe.
