### ISSUE TITLE
Literais da lib sendo sobrescritas pelas literais da aplicação

### ISSUE THREAD

**Issue by rubinhos** [po-ui/po-angular#321]
#### Reprodução:

Github disponível em: https://github.com/rubinhos/po-lib-18n-sample
Por se tratar de uma biblioteca, não foi possível incluir o projeto no Stackblitz

Passos para reproduzir:
1. Criar uma lib Angular e utilizar o módulo de i18n do Portinari
2. Adicionar a biblioteca à uma aplicação que também utilize o módulo i18n do Portinari

#### Qual o comportamento atual?

As literais dos componentes da bilbioteca estão sendo sobrescritas pelas literais da aplicação.

#### Que comportamento você esperava ver?

As literais dos componentes da biblioteca devem funcionar de forma independente das literais da aplicação.

#### Ambiente

- Portinari: 1.28.0
- Angular: 8.2.14
- Browser(s): Chrome, Firefox
- Operating System (e.g. Windows, macOS, Ubuntu): Ubuntu

**Comment by guiebitt** [comment]
Olá, apenas enfatizando que este item é bem importante para a organização em uma aplicação maior na qual seja feita a divisão em módulos dentro de libraries e cada library contenha sua própria configuração de internacionalização.
Atualmente não é possível manter a configuração específica em cada library, pois quando utilizada na aplicação, as configurações se sobrescreverem.

**Comment by thiagoasw** [comment]
Pelo que vi, o `I18nService` é um _singleton_.

Seria possível, manter ele como um _singleton_, mas permitir que um módulo (aka. lib: `NgModule -> CUSTOM_ELEMENTS_SCHEMA`) possa adicionar contextos quando o módulo for carregado via _lazy load_?

Algo do tipo: `PoI18nModule.addContext({ libModule: { ... } })`

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
