### ISSUE TITLE
https://portinari.io/ 404 Web Site not found. [LINK PROVISÓRIO: https://wa-po-ui.azurewebsites.net/]

### ISSUE THREAD

**Issue by eriklesbr** [po-ui/po-angular#336]
#### Site Offline?

O site https://portinari.io/ não está disponível!

#### 404 Web Site not found.
You may be seeing this error due to one of the reasons listed below :

Custom domain has not been configured inside Azure. See how to map an existing domain to resolve this.
Client cache is still pointing the domain to old IP address. Clear the cache by running the command ipconfig/flushdns.
Checkout App Service Domain FAQ for more questions.

**Comment by jhonyeduardo** [comment]
Olá Erikles,

Desculpe o incomodo, mas estamos com um problema de domínio.

Pode acessar este link provisoriamente: https://wa-po-ui.azurewebsites.net/

**Comment by andredealmei** [comment]
Foram removidas todas as referências ao nome Portinari ?

**Comment by rezendeweb** [comment]
Estou usando o comando ng add @po/po-ui e está me retornandoo erro 404, tem alguma outra solução para adicionar o portinari na minha aplicação?

**Comment by jhonyeduardo** [comment]
Olá, você pode utilizar ```ng add @portinari/portinari-ui``` no momento.

**Comment by po-ui-dev** [comment]
URL oficial: https://po-ui.io/

O domínio anterior irá fazer o redirect.
