### ISSUE TITLE
Corrigir comando no portal PO-UI

### ISSUE THREAD

**Issue by dovalgomes** [po-ui/po-angular#356]
Fala Galera!

Na aba getting-start do portal PO-UI: https://po-ui.io/guides/getting-started

No titulo Passo 2: Passo 2 - Adiconando o pacote @po/po-ui

Favor corrigir o comando ng add @po/po-ui, pois o mesmo está retornando 404- not found na url que tenta buscar os componentes do PO.

**Comment by jhosefmarks** [comment]
Corrigido, só lembrando que estamos fazendo a migração da doc para a nova versão do PO UI e o Angular v9.

Agradecemos a compreensão.
