### ISSUE TITLE
Configurar seleção por item no p-table (p-selectable)

### ISSUE THREAD

**Issue by SalatielBairros** [po-ui/po-angular#360]
#### Descrição da melhoria
Atualmente, ao utilizar a opção _p-selectable_ do componente _po-table_, todos os itens da lista recebem um _checkbox_ habilitado. Necessito, como usuário do componente, impedir que o usuário selecione alguma linha de acordo com regra de negócio estabelecida, para que o ao usuário final fique claro quais itens estão disponíveis para a ação ao ser executada nos selecionados.

#### Caso de uso
Um exemplo da necessidade dessa funcionalidade pode ser visto na imagem abaixo:
![image](https://user-images.githubusercontent.com/10634531/78174381-890f7d00-742f-11ea-9c1e-a8cc2a14b27c.png)
Apenas os itens **Finalizados** podem ser selecionados, enquanto os ainda em modo de rascunho devem estar bloqueados para a seleção (inclusive o selecionar todos).

#### Informações adicionais
Para manter a consistência visual da tela , sugiro que o checkbox seja apenas desabilitado, permanecendo visível.
Uma possível sugestão de desenvolvimento seria desenvolver uma interface que seria implementada na classe do objeto listado contendo uma propriedade que permite ou não ser habilitado. Caso a propriedade não exista, o _default_ seria exibir.

**Comment by jhosefmarks** [comment]
Item adicionado ao backlog.

**Comment by rabraganca** [comment]
Também estou precisando dessa funcionalidade.

**Comment by adrielov** [comment]
Precisando disso tbm :(

**Comment by HermesDS2U** [comment]
Também preciso dessa mesma regra. Por enquanto para tentar validar/"não deixar" selecionado, fiz um  tratamento, onde ao selecionar um item e ele não poderia ser marcado, exibo a msg que não pode e na sequência executo  "poTable.unselectRowItem()" / também tentei com "row.$selected = false" para desmarcar. Na primeira vez que clico nessa linha que não poderia ser marcada,  isso funciona, desmarca corretamente, porém ao clicar novamente na mesma linha para marcar, já não funciona mais, deixa selecionado. 

Atualizei a versão do angular (global e local) e atualizei o PO-UI/Components, mesmo assim continua selecionado.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.

**Comment by LeonardoZ** [comment]
Consigo ter alguma alternativa para esse caso?
