### ISSUE TITLE
PoTable não considera o idioma configurado no serviço i18n

### ISSUE THREAD

**Issue by raphasoares** [po-ui/po-angular#364]
#### Reprodução

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

Passos para reproduzir:
1. Acesse https://portinariui-akevq3.stackblitz.io utilizando o browser com idioma em português
2. Verifique que o idioma setado no serviço i18n ´no construtor da aplicação é 'en-us'
3. Verifique que as literais da table estão exibidas em portugês, idioma do navegador.

#### Qual o comportamento atual?
O componente não considera o idioma setado no serviço i18n

#### Que comportamento você esperava ver?
O idioma setado no serviço i18n deverá ser preferêncial

#### Ambiente

- PO UI: 2.0.0-beta.1
- Angular: 9.0.4
- Browser(s): Chrome Versão 80.0.3987.149 (Versão oficial) 64 bits
- Operating System (e.g. Windows, macOS, Ubuntu): Windows 10

**Comment by jhosefmarks** [comment]
Resolvido na PR #564
