### ISSUE TITLE
Botão fechar(close) nas abas(tabs).

### ISSUE THREAD

**Issue by mykaelandrade** [po-ui/po-angular#365]
#### Descrição da melhoria
Opção de adicionar uma **propriedade** _close (x)_ no **componente** das abas.

#### Caso de uso
Estamos em um projeto onde trabalhamos com varias abas internas, numa unica pagina abre-se vários cadastros, onde posteriormente os usuários precisarão fechar a aba e voltar a anterior.
Assim como é no google chrome por exemplo.

Fizemos uma gambiarra, onde colocamos um botão fechar na unha, já que o componente não possui essa opção.

#### Informações adicionais
Segue abaixo a imagem de demonstração:

![close](https://user-images.githubusercontent.com/55408649/78370208-592dba00-7594-11ea-9b18-531cd7140e12.png)

Nossa sugestão é adicionar essa _propriedade_  fechar nas abas.
Ex: `(p-close)`.

**Comment by andredealmei** [comment]
Fiz uma gambiarra parecida
tavezz p-action seja ate melhor, para costomizar uma action;
tenho caso de uso que precisa ser um fechar e tenho caso de uso que preciso de um botao adionar por exemplo

**Comment by rabraganca** [comment]
Seria interessante também se nós pudéssemos escolher o ícone que seria exibido, podendo trocar o 'x' pelo ícone de uma lixeira ou por um '+', por exemplo.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
