### ISSUE TITLE
Erro: Documentação - po-lookup

### ISSUE THREAD

**Issue by jotamauro** [po-ui/po-angular#376]
#### Reprodução

Utilize StackBlitz para reproduzir a sua issue: https://stackblitz.com/fork/portinariui

Passos para reproduzir:
1. Acesse o link do componente po-lookup.
2. No último exemplo, ao clicar na lupa para listar os registros, um erro é apresentado no console e não lista os itens.

#### Qual o comportamento atual?
Erro ao listar os itens buscados.

#### Que comportamento você esperava ver?
Uma lista de itens dentro do modal.

#### Ambiente

- PO UI:
- Angular:
- Browser(s): 
- Operating System (e.g. Windows, macOS, Ubuntu):

**Comment by jhosefmarks** [comment]
A API (https://swapi.co/api/films/) que estamos usando no exemplo está fora do ar, estamos convertendo nossos exemplos para apis nossas para não ter mais esse tipo de problema, em breve vamos atualizar o exemplo.
