### ISSUE TITLE
Feature - Componente - po-toolbar

### ISSUE THREAD

**Issue by jotamauro** [po-ui/po-angular#377]
#### Descrição da melhoria
Descreva a melhoria que você gostaria de ver.
Seria interessante criar um scroll para o componente po-toolbar quando o array de  p-notification-actions for muito grande, hoje, caso o usuário possua muitas notificações a usabilidade não fica agradável. Percebi também que ao possuir mais de um determinado número de notificações, a lista é exibida pra cima, impossibilitando o usuário de navegar. 

![Issue-Toolbar - 2](https://user-images.githubusercontent.com/40409817/78898967-1152db00-7a4b-11ea-804f-ac30f985eca4.png)

![Issue-Toolbar](https://user-images.githubusercontent.com/40409817/78898614-778b2e00-7a4a-11ea-9459-e169f0ef93f8.png)

#### Caso de uso
Ao possuir muitas notificações, o componente não gera scroll da lista de notificações.

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

**Comment by jhosefmarks** [comment]
Sugestão anotada, vamos deixar em nosso backlog para análise junto com o time de UX.

**Comment by jhonyeduardo** [comment]
Olá @jotamauro 

Na [release](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#370-2020-09-21), resolvemos este problema.
Pode testar no nosso sample também: https://po-ui.io/documentation/po-toolbar

Obrigado!
