### ISSUE TITLE
Erro na comando "ng serve" após migrar para o Angular 9 e Versão 2.0

### ISSUE THREAD

**Issue by caiadofelipe** [po-ui/po-angular#389]
Boa tarde.

Segue erro que está acontecendo depois de migrar o projeto para a versão 2.0 seguindo os passos conforme documentação.

ERROR in node_modules/@po-ui/ng-storage/lib/services/po-storage.service.d.ts:252:22 - error TS2304: Cannot find name 'LocalForage'.

252     ready(): Promise<LocalForage>;

**Comment by jhonyeduardo** [comment]
Olá Caiado, pedimos desculpa pelo ocorrido.

Identificamos o problema e liberaremos a correção no próximo release, prevista para o dia 24/04.

Manteremos a issue aberta até a liberação da correção, qualquer dúvida estamos a disposição.

**Comment by caiadofelipe** [comment]
Obrigado @jhonyeduardo

**Comment by jhonyeduardo** [comment]
Olá,

Pacote 2.1.0 publicado com a correção.

Qualquer dúvida estamos a disposição.
