### ISSUE TITLE
PoMultiselect não exibe pesquisa e dispara erro a selecionar item

### ISSUE THREAD

**Issue by leonardosimoura** [po-ui/po-angular#392]
#### Reprodução

Passos para reproduzir:
1. Utilizar um PoMultiselect 
2. Abrir o componente e selecionar qualquer item

#### Qual o comportamento atual?
Ao abrir o PoMultiselect pela primeira vez ele fica sem o campo de pesquisa e dispara erros no console ao selecionar qualquer item.

![1](https://user-images.githubusercontent.com/20740973/80209047-b6eb7a00-8607-11ea-8ed0-c3daefe40493.png)

![2](https://user-images.githubusercontent.com/20740973/80209054-b8b53d80-8607-11ea-8779-089638d0f2f7.png)

Fechando e abrindo novamente esse comportamento para de ocorrer.

![3](https://user-images.githubusercontent.com/20740973/80209061-bbb02e00-8607-11ea-8c37-73f72c265500.png)

Aparentemente o componente continua funcionando (atualizando o Model, disparando eventos).

#### Que comportamento você esperava ver?
Não disparar erros ao realizar essa ação

#### Ambiente

Pode ser reproduzido no portal de documentação

[https://po-ui.io/documentation/po-multiselect](https://po-ui.io/documentation/po-multiselect)

**Comment by jhosefmarks** [comment]
Vamos adicionar esse item em nossa próxima Sprint, obrigado por nos informar.

**Comment by jhosefmarks** [comment]
Corrigido na release 2.3.0:

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#230-2020-05-15

#412
