### ISSUE TITLE
Indicador selecionado

### ISSUE THREAD

**Issue by andredealmei** [po-ui/po-angular#397]
#### Descrição da melhoria
Possibilidade de setar programaticamente o item selecionado em no componente po-menu

#### Caso de uso
Uma listagem de categoria, ao selecionar uma categoria indicar que esta selecioanda

**Comment by jhosefmarks** [comment]
O menu destaca um item baseado na rota.

**Comment by andredealmei** [comment]
Sua resposta da a entender que ignorou complemente oque escrevi.

**Comment by jhosefmarks** [comment]
Desculpe @andredealmei, não foi a intenção, hoje os itens do Menu ficam selecionados de acordo com a rota ativa, não existe essa opção.

**Comment by andredealmei** [comment]
Tudo bem, sem problemas, obrigado pela resposta =)
