### ISSUE TITLE
Placeholder em PoMultiSelect  diferente do PoSelect

### ISSUE THREAD

**Issue by andredealmei** [po-ui/po-angular#399]
#### Reprodução

https://stackblitz.com/edit/portinariui-vtgeub

Passos para reproduzir:
1.  Criar  um PoSelect com placeholder
2. Criar um PoMultiSelect com placeholder 

#### Qual o comportamento atual?
placeholder no PoMultiSelect é diferente do PoSelect.

#### Que comportamento você esperava ver?
Ambos sejam iguais para manter consistência da ui.

**Comment by jhonyeduardo** [comment]
Bom dia @andredealmei, item adicionado ao backlog, obrigado.

**Comment by leonardotdleal** [comment]
Opa @jhonyeduardo, gostaria de contribuir com essa correção se possível. Qual é o placeholder correto para ambos os casos?

**Comment by jhonyeduardo** [comment]
Boa noite @leonardotdleal 

Muito obrigado pela futura contribuição.

O correto é o PoMultiselect ficar com a aparencia do PoSelect

![image](https://user-images.githubusercontent.com/6907801/96933369-ad4bad80-1496-11eb-877f-2a073f90760b.png)

**Comment by jhonyeduardo** [comment]
Issue resolvida, liberada na próxima versão, obrigado.
