### ISSUE TITLE
[Bugs/Suggestions] PO-UI page

### ISSUE THREAD

**Issue by ftonato** [po-ui/po-angular#408]
Hello, tudo bem?
Conforme falado em um [tweet](https://twitter.com/ftonato/status/1258928099003113473?s=19), encontrei alguns pequenos detalhes que podem out não serem considerados bugs e gostaria de sugerir correções.

Deixo abaixo a lista de issues com os reports:

- [x] Página de exemplos sem estado de loading
- [x] Página de documentação (lista de componentes) não converte o _markdown_ para HTML
- [x] Página de documentação (cards podiam adicionar um padding ao texto da descrição para não ficar tão colado o texto com as bordas)

Se houver quaisquer dúvidas sobre às issues é só avisar ;)

**Comment by jhosefmarks** [comment]
Fiz uma alteração rápida pois temos em nosso backlog a reestruturação do nosso portal de documentação, favor verificar se a usabilidade ficou um pouco melhor e já atende.

https://po-ui.io/documentation

**Comment by ftonato** [comment]
Acabei de ver, comentei na issues que achei que influenciaram em algo :)
