### ISSUE TITLE
Cards de componentes não converte o markdown para HTML

### ISSUE THREAD

**Issue by ftonato** [po-ui/po-angular#410]
REF: #408 

#### Reprodução
Go to página de documentação e veja algum card que tenha um markdown na descrição ou olhe o screenshot abaixo (nos componentes Switch e Sync):

![Screenshot_2020-05-09-12-02-56-244_com android chrome](https://user-images.githubusercontent.com/5417662/81472000-1ee7b600-91ed-11ea-8ce4-72ea5a61e519.jpg)

#### Qual o comportamento atual?
A página não está convertendo o conteúdo de markdown para HTML. 

#### Que comportamento você esperava ver?
O HTML convertido.

**Comment by jhosefmarks** [comment]
Fiz uma alteração rápida pois temos em nosso backlog a reestruturação do nosso portal de documentação, favor verificar se a usabilidade ficou um pouco melhor e já atende.

https://po-ui.io/documentation
