### ISSUE TITLE
Adicionar espacamento na descrição do card de componentes

### ISSUE THREAD

**Issue by ftonato** [po-ui/po-angular#411]
REF: #408 

#### Descrição da melhoria
Página de documentação (cards podiam adicionar um padding ao texto da descrição para não ficar tão colado o texto com as bordas)

#### Caso de uso
Acessibilidade na hora da leitura? 

#### Informações adicionais
Como é feito para o título de cada card (há  um espaçamento), talvez faria sentido também para o texto (descrição) que houvesse o mesmo, facilitando a leitura. 

A imagem abaixo representa bem o "problema":
![Screenshot_2020-05-09-12-02-56-244_com android chrome](https://user-images.githubusercontent.com/5417662/81472094-93225980-91ed-11ea-8565-deab35da9d43.jpg)

**Comment by jhosefmarks** [comment]
Fiz uma alteração rápida pois temos em nosso backlog a reestruturação do nosso portal de documentação, favor verificar se a usabilidade ficou um pouco melhor e já atende.

https://po-ui.io/documentation

**Comment by ftonato** [comment]
Boas, achei o espaçamento legal, agora no lado direito não está cortando a palavra e adicionando os três pontinhos, achas que faz sentido mante-los ou deixar assim já que vocês querem recriar o portal de documentação todo?

**Comment by jhosefmarks** [comment]
O próprio componente de markdown que faz isso, não tenho controle, e como você mesmo citou vamos rever com mais calma quando reestruturar o portal.

**Comment by andredealmei** [comment]
Agora está cortando a descrição

![image](https://user-images.githubusercontent.com/33403972/81683941-ee8e5a80-942c-11ea-9750-f21719fa5b68.png)

**Comment by jhosefmarks** [comment]
Corrigido!
