### ISSUE TITLE
po-rich-text em formulário reativo

### ISSUE THREAD

**Issue by dgo-angelo** [po-ui/po-angular#417]
**Reprodução**
https://stackblitz.com/edit/portinariui-dvc9el

**Passos para reproduzir:** Clicar no botão de teste

**Qual o comportamento atual?**
Ao utilizarmos o componente po-rich-text em um formulário reativo, identificamos que:
- Ao forçarmos a atualiação do campo via patchValue/setValue, o valor foi atualizado no form porém não foi atualizado na tela.

**Que comportamento você esperava ver?**
- Que o form apresentasse o novo valor informado.

**Ambiente**
**PO UI:** 2.0.0
**Angular:** 9.1.0

**Browser(s):** Chrome

**Operating System (e.g. Windows, macOS, Ubuntu):** Windows

**Comment by jhosefmarks** [comment]
Corrigido na versão 3.4.0: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#340-2020-08-31

PR #583
