### ISSUE TITLE
Opção de acrescentar header no po-upload

### ISSUE THREAD

**Issue by cetenorio** [po-ui/po-angular#422]
Sugiro que o po-upload nos permita acrescentar header nas suas opções;
Esta melhoria permitiria uma flexibilidade para conexões com API's diversas, como por exemplo o acréscimo de um header Authorization com o valor do token a ser passado.

**Comment by jhosefmarks** [comment]
Bom dia @cetenorio você pode usar um interceptor para isso, na verdade é até o mais indicado.

**Comment by tccspringsecurity** [comment]
Realmente o Interceptor parece ser a melhor opção para esse caso, nesse caso não há mais necessidade de implementar essa sugestão. Ainda assim deixo uma outra sugestão de um possível indicador quanto a essa informação na documentação do Portinari, vi que o interceptor pode ser utilizado pra mais coisas do que consta na página. Agradeço a você @jhosefmarks pelo esclarecimento.
