### ISSUE TITLE
String pesquisar esta fixo na barra de pesquisa do MENU

### ISSUE THREAD

**Issue by eternauta123** [po-ui/po-angular#434]
String pesquisar esta fixo na barra de pesquisa do MENU, por favor extrair para o i18n

**Comment by jhosefmarks** [comment]
@eternauta123 já temos em nosso backlog um épico para revisão das literais de todos os  componentes, inclusive observando as configurações do serviço i18n que já tem dentro do pacote.

Assim que pudermos trabalharemos nesse item.

**Comment by eternauta123** [comment]
Obrigado Joseph... Sei que não é o foro, mas poderia me dar uma pequena ajuda para usar o pipe, vi este exemplo na documentacao: {{ literals?.people | poI18n:[120] }}
mas nao consigo usar dentro do componente, não estou entendendo se necesio importar algum componente. Poderia me dar um exemplo, incluindo o import necessario e o que devo adicionar no constructor (ou não)

**Comment by jhosefmarks** [comment]
O ideal é você abrir outra issue então para as pessoas poderem te ajudar.

**Comment by jhosefmarks** [comment]
Finalizado na PR #493.

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#300-2020-08-03
