### ISSUE TITLE
Propriedade p-icon não funciona no po-number.

### ISSUE THREAD

**Issue by FelipeGatti** [po-ui/po-angular#437]
#### Reprodução

Utilize StackBlitz para reproduzir a sua issue:  https://portinariui-ny2auw.stackblitz.io

Passos para reproduzir:
1. Criar um Po-number
2. Inserir a propriedade p-icon

#### Qual o comportamento atual?
O Icone nao aparece.

#### Que comportamento você esperava ver?
O Icone deveria aparecer

#### Ambiente

- PO UI: 2.0.0
- Angular: 9.1.2
- Browser(s): chrome
- Operating System (e.g. Windows, macOS, Ubuntu): Windows

**Comment by jhosefmarks** [comment]
Existe um erro em nossa documentação, onde não deveria ser exibida essa propriedade, mas como algumas pessoas já tentaram usar, talvez faça sentido implementar a mesma, vou adicionar como uma melhoria em nosso backlog.

**Comment by RafaellyG** [comment]
Fala pessoal! Vou fazer esta contribuição e criar uma PR! Assim o core team pode avaliar se faz sentido a inclusão desta funcionalidade 😸
