### ISSUE TITLE
Propriedade value da interface PoTableColumnLabel

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#441]
#### Descrição da melhoria
A adição do tipo number na propriedade value da interface PoTableColumnLabel

#### Caso de uso
Caso não tivesse essa dinâmica do labels, muito provavelmente nós usaríamos condições para definir a cor/nome do label usando enumeráveis.

Nós criamos enumeráveis para fazer essas condições de dados que vem do banco com o tipo number, portanto, quando usamos o labels, é preciso mapear a propriedade do objeto usando toString, pois o labels: [{values, ..., ...}], só aceita o tipo string.

**Comment by jhosefmarks** [comment]
Olá @guiworks, Item anotado em nosso backlog, assim que tivermos disponibilidade trataremos o item.

**Comment by jhosefmarks** [comment]
Item entregue: #452
