### ISSUE TITLE
Disparar evento ao selecionar as colunas no column manager - poTable

### ISSUE THREAD

**Issue by jeangrahl** [po-ui/po-angular#466]
#### Descrição da melhoria
Incluir um eventEmitter que retorne as colunas marcadas como visíveis no column manager do componente po-table.

#### Informações adicionais
Salvar as colunas marcadas como visíveis para que quando usuário entrar novamente na mesma tela, permaneça visivel apenas as colunas configuradas.

**Comment by jhosefmarks** [comment]
@jeangrahl sugestão anotada, vai estar em nosso backlog para futura implementação.

**Comment by orkanmeister** [comment]
Estou precisando da mesma funcionalidade. Seria muito interessante.
Estou utilizando a princípio o ngDoCheck para verificar a mudança do `PoTableComponent.columns`

**Comment by jhonyeduardo** [comment]
Boa tarde Pessoal

Na versão [3.10.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md) disponibilizamos o evento (p-change-visible-columns) no [po-table](https://po-ui.io/documentation/po-table).

O evento será disparado ao fechar o gerenciador de colunas após alterar as colunas visíveis.
