### ISSUE TITLE
A carga dos literais dos objetos (poTable, Lookup, etc.) nao respeita o poLocale definido e sempre pega do browser

### ISSUE THREAD

**Issue by eternauta123** [po-ui/po-angular#468]
A carga dos literais dos objetos (poTable, Lookup, etc.) nao respeita o poLocale definido e sempre pegar o idioma do Browser.
No meu caso, a aplicacao esta implementada respeitando o PO-LOCALE, tendo implementadas todas os meus literais em russo.
Quando uso em `RU` mostra tudo corretamente em russo (inclusive alguns componentes padroes) com excecao (o que descobri ate agora) dos literiais dos objetos de lookup ae POTABLE que estao enm russo.
Percebi que tem uma metodo no Util que retora o idioma em uso, mas pega o idioma do Browser.

![image](https://user-images.githubusercontent.com/34449118/86227257-6e1ae900-bb95-11ea-931b-8fe44665848c.png)

**Comment by jhosefmarks** [comment]
@eternauta123 você está usando a propriedade p-literals do componente?

**Comment by eternauta123** [comment]
Não, mas não deveria ser necessário, pois os literals já estão em Russo no padrão, só se eu carregar os padrões em russo para os  custom.
Tem alguma forma de eu carregar os literals padrão do componente em russo para o literals custom de cada componente?

    	
    	

    	Get Outlook for iOS
    
  




On Thu, Jul 2, 2020 at 1:05 AM +0300, "Jhosef Marks" <notifications@github.com> wrote:
















@eternauta123 você está usando a propriedade p-literals do componente?

**Comment by jhosefmarks** [comment]
@eternauta123 hoje os componentes buscam o idioma do browser, ainda vamos trabalhar melhorar o comportamento das literais usando o serviço i18n, mas isso está no nosso backlog e vai levar um tempo para implementar.

**Comment by eternauta123** [comment]
Ok. faz sentido ter o idioma no login se pega do browser?
Tem alguma previsão para melhorar o i18n?
    	
    	

    	Get Outlook for iOS
    
  




On Thu, Jul 2, 2020 at 4:08 PM +0300, "Jhosef Marks" <notifications@github.com> wrote:
















@eternauta123 hoje os componentes buscam o idioma do browser, ainda vamos trabalhar melhorar o comportamento das literais usando o serviço i18n, mas isso está no nosso backlog e vai levar um tempo para implementar.

**Comment by jhosefmarks** [comment]
Faz por que você pode modificar as literais hoje também, o login veio depois de já implementado a parte de literais usando o idioma do browser.

Depois de implementado o login que veio a necessidade de olhar para o serviço do i18n também.

Não temos previsão ainda para essa alteração, faz aceitamos PRs!!! 😃😃

**Comment by jhosefmarks** [comment]
Atualmente os componentes já usam o serviço i18n e o template de login também já tem as funções para troca idioma. Item já  finalizado!!!!
