### ISSUE TITLE
Doc do po-menu está alterando o título da página

### ISSUE THREAD

**Issue by afucher** [po-ui/po-angular#475]
Ao acessar a documentação do https://po-ui.io/documentation/po-menu, o título da página muda para PO - Human Resources e não volta mais mesmo navegando para outras páginas.

<img width="580" alt="image" src="https://user-images.githubusercontent.com/3756185/86521247-966c4700-be24-11ea-9c1c-6d1d1a13be5e.png">

**Comment by jhosefmarks** [comment]
@afucher isso ocorre por que o tollbar muda o nome da página e não o menu, como temos mais de um exemplo rodando com o tollbar acaba tendo esse reflexo, isso não vai ocorrer na sua aplicação.

**Comment by afucher** [comment]
@jhosefmarks imaginei que isso não ocorria na aplicação e somente na doc, mas a ideia da issue era pra arrumar a doc mesmo.
