### ISSUE TITLE
Po-Slide [Invalid keyframe value for property transform: translateX(-NaNpx)]

### ISSUE THREAD

**Issue by silverio27** [po-ui/po-angular#479]
Estou utilizando o PoSlide :
`<po-slide *ngIf="banners.length > 0" [p-slides]="banners" [p-height]="500"> </po-slide>`

E estou obtendo o erro no console:
Invalid keyframe value for property transform: translateX(-NaNpx)
ERROR
core.js:6189
DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.

E o slide só começa a animar quando eu clico a primeira vez em um botão de avançar ou voltar.

**Comment by jhosefmarks** [comment]
@silverio27 mude seu código para:

`<po-slide *ngIf="banners.length > 0" [p-slides]="banners" p-height="500"> </po-slide>`

Da forma que você está fazendo ele está fazendo um bind com a variável 500 e não atribuindo o valor 500 a propriedade.

**Comment by silverio27** [comment]
Oi Joseph, sim eu coloquei [p-height]="500" antes de colar aqui, mas eu estava usando sem mesmo. acho que o problema foi no *ngif. Eu alterei para *ngIf="banners", ele estava checando a contagem do banners antes dele ser iniciado. Pode fechar essa issue. Obrigado!
