### ISSUE TITLE
Usar componentes PO-UI com React

### ISSUE THREAD

**Issue by andreamador** [po-ui/po-angular#489]
#### Descrição da melhoria
Gostaria de saber se é possível usar o PO-UI junto com REACT?

se sim, qual a estrategia?

imaginando que PO-UI seja agnóstico a framework

**Comment by jhosefmarks** [comment]
@andreamador hoje não é possível usar os componentes do PO UI com React, apenas com o Angular.

Quem sabe no futuro possamos fazer essa implementação, mas por enquanto sem prazo definido.

Você pode usar os estilos que estão separados no repositório https://github.com/po-ui/po-style, onde você vai encontrar os arquivos CSS e os HTML que usamos como base para os componentes.

O pacote é publicado separadamente como `@po-ui/style` e pode ser usado no seu projeto React.
