### ISSUE TITLE
Erro ao usar PoNotificationService em aplicação Angular 9 com Ivy desabilitado.

### ISSUE THREAD

**Issue by fabiomirandaa** [po-ui/po-angular#492]
#### Reprodução
Quando eu desabilitei o Ivy de uma aplicação, o PoNotificationService não funciona. Exemplo pode ser visto aqui => https://stackblitz.com/edit/angular-ivy-tz2a7s

Passos para reproduzir:
1. Criar aplicação com Angular 9 e desabilitar o Ivy 
2. Importar o módulo de PoNotification e tentar usar o PoNotificationService

#### Qual o comportamento atual?

Atualmente, ele exibe um erro no console:
```
ERROR
Error: No component factory found for PoToasterComponent. Did you add it to @NgModule.entryComponents?
```
#### Que comportamento você esperava ver?
Não acontecer o erro.

#### Ambiente

- PO UI: 2.6 e 2.9
- Angular: 9.1
- Browser(s): Chrome, Firefox e Opera
- Operating System (e.g. Windows, macOS, Ubuntu): MacOS, Windows e Ubuntu

**Comment by jhosefmarks** [comment]
Vamos avaliar o item.

**Comment by jhosefmarks** [comment]
@fabiomirandaa analisamos o problema relatado e isso acontece por conta do entryComponents que nós usávamos e com a migração para o Angular 9 foi removido, pois foi depreciado.

https://angular.io/api/core/NgModule#entryComponents

Como na próxima versão isso será um breaking change, decidimos que não faz sentido fazer esse "rollback", e como adotamos sempre as boas práticas sugeridas pelo time do Angular, sugerimos que ative o Ivy para poder usar nossa biblioteca.
