### ISSUE TITLE
Combo: Alterando o FormControl para dirty no form.patchValue

### ISSUE THREAD

**Issue by leonardosimoura** [po-ui/po-angular#515]
#### Reprodução
Utilizar o combo e outros componentes( input / select / checkbox / etc) com reactive forms e realizar o form.patchValue

https://stackblitz.com/edit/po-ui-4eudxe

Passos para reproduzir:
1. Utilizar o combo e outros componentes( input / select/ checkbox) com reactive forms e realizar o form.patchValue
2. Verificar que o combo seta o formControl como dirty e os demais componentes não.

#### Qual o comportamento atual?
Ao utilizar o componente de combo com reactiveForms e realizar o patchValue o formControl é setado como dirty.
Outros componentes como o input / checkbox / select não fazem isso.

#### Que comportamento você esperava ver?
O combo deveria ter o mesmo resultado que os demais componentes.

#### Ambiente
- PO UI: 2.10
- Angular: 9
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
Olá @leonardosimoura, vamos agendar essa correção para nossas próximas sprints.

**Comment by jhosefmarks** [comment]
Item finalizado: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#330-2020-08-24
