### ISSUE TITLE
PoTable: p-sort com problemas quando existe valor nulo

### ISSUE THREAD

**Issue by ezequielgandolfi** [po-ui/po-angular#525]
#### Reprodução
https://stackblitz.com/edit/po-ui-bug-tablesortdate

Passos para reproduzir:
1. Criar um po-table, com o atributo p-sort, e nos itens ter valores nulos misturado com valores preenchidos
2. Na tela, tentar ordenar pela coluna.

#### Qual o comportamento atual?
Quando tentado ordenar os valores, a linha que possui um valor nulo não muda corretamente de posição.

#### Que comportamento você esperava ver?
Que todas linhas fiquem ordenadas, mesmo que possua algum valor nulo na coluna em questão

#### Ambiente

- PO UI: 2.10.0
- Angular: 9
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
Issue será tratada na próxima sprint.

**Comment by jhosefmarks** [comment]
Issue finalizada: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#330-2020-08-24
