### ISSUE TITLE
Erro ao incluir o Tema da TOTVS

### ISSUE THREAD

**Issue by caiadofelipe** [po-ui/po-angular#532]
Passos para reproduzir:
1. Ao seguir os passos da pagina do THF para inclusão do tema da TOTVS em um projeto novo do PO-UI, ao rodar o "ng serve" ele mostra erro
Passos para instalação segundo a página do THF 
1) npm i --save @totvs/po-theme
2) Alterar o angular.json
"styles": [
  "node_modules/@totvs/po-theme/css/po-theme-default.min.css"
]

- PO UI: V3.0.0 RC1
- Angular: 10
- Browser(s):
  - [X] Chrome
- Operating System:
  - [X ] Windows

**Comment by jhonyeduardo** [comment]
Boa tarde, a abertura de issue relacionado ao @totvs/po-theme, deve ser no github do projeto: https://github.com/totvs/po-theme-totvs

Porém, aproveitando para responder, concluímos uma issue semelhante, veja se resolve seu problema:
https://github.com/totvs/po-theme-totvs/issues/51

Verifique se não foi instalado a versão **2.10.0** do **@totvs/po-theme**, no qual foi publicado com problemas.

A versão **2.10.1** e demais, como **3.0.0-rc.1**, não possuem este problema.

E novamente, solicito que as proximas issues seja aberta pelo projeto po-theme, https://github.com/totvs/po-theme-totvs.

Obrigado.

**Comment by alvarocamillont** [comment]
Apenas para complementar oque o @jhonyeduardo  falou
Temos um exemplo e um tutorial nesse link https://tdn.totvs.com/pages/viewpage.action?pageId=556388451
