### ISSUE TITLE
PoNumber: valor divergente ao utilizar sinal de negativo no meio do número

### ISSUE THREAD

**Issue by ezequielgandolfi** [po-ui/po-angular#537]
#### Reprodução
![uaggOADNn5](https://user-images.githubusercontent.com/20089116/89321111-dbb8aa00-d658-11ea-82cb-ccc91b5722f2.gif)
Reproduzido no labs.

#### Qual o comportamento atual?
Ao utilizar um sinal de negativo no po-number (não sendo o primeiro digito), o valor do model fica nulo, porém o texto exibido contém um valor, deixando o resultado divergente.

#### Que comportamento você esperava ver?
Ao sair do campo (on-blur) caso o valor do model seja nulo, o texto do input deveria ser apagado para não gerar divergência na visualização da informação.

#### Ambiente

- PO UI: 3.0.0
- Angular: 10
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
Vamos validar o valor na saída do campo e mostrar para o usuário que o valor está inválido dessa forma o usuário tem um feedback e sabe que o mesmo está inválido e pode tomar alguma ação.

Vamos programar a correção para a próxima sprint.

**Comment by jhosefmarks** [comment]
Issue finalizada: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#330-2020-08-24
