### ISSUE TITLE
<po-select>: <quando label é grande não funciona em celulares>

### ISSUE THREAD

**Issue by glaubergad** [po-ui/po-angular#542]
#### Reprodução
Usando po-select, se a label extrapolar a largura do campo, simplesmente não abre em telas de celulares. Testado em equipamentos Android e iOS.

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Usando array no padrão {label: 'ESTE É UM TESTE COM UMA LABEL UM POUCO GRANDE PARA CELULAR', value: 1} , causa o componente não responder em telas de telefones celulares. Este problema já foi verificado em pelo menos 3 projetos que requeriam um label maior no campo po-select. Para resolver, tive que usar um <select><option> html5 e aplicar as classes po-input, po-input-title para não descaracterizar o formulário.
#### Qual o comportamento atual?
O po-select não responde ao toque no sistema operacional Android e iOS

#### Que comportamento você esperava ver?
Que o componente operasse como os outros no mesmo formulário.

#### Ambiente

- PO UI: release mais atual para Angular 9
- Angular: 8 e 9
- Browser(s):
  - [x ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [x ] Outros

**Comment by jhosefmarks** [comment]
@glaubergad como você está passando os valores para a propriedade `p-options`?

Fiz um teste no nosso Sample Labs do select e tive esse problema pois nosso exemplo não estava usando imutabilidade, a referência das opções não estava sendo atualizada corretamente.

Veja se a seguinte alteração resolve o seu problema:

De
```
this.options.push({label: 'ESTE É UM TESTE COM UMA LABEL UM POUCO GRANDE PARA CELULAR', value: 1});
```
Para
```
this.options = [...this.options, {label: 'ESTE É UM TESTE COM UMA LABEL UM POUCO GRANDE PARA CELULAR', value: 1}];
```

Com isso as opções passam a ser atualizadas exibindo a lista de opções corretamente.

![image](https://user-images.githubusercontent.com/11772148/90033623-0d072a80-dc96-11ea-822e-4e4cca4dcd43.png)
