### ISSUE TITLE
Duvidas P.O

### ISSUE THREAD

**Issue by maximinocastro** [po-ui/po-angular#548]
Boa tarde Prezados,

Aqui na empresa estão querendo desenvolver algumas telas no Portinari porém surgiu algumas dúvidas.

1 - Como Eu chamo uma função ADVPL do Portinari ?

2 - Como Eu fecho a tela do P.O depois de aberto dentro do Protheus ?

3 - Como compila dentro do RPO do Protheus?

Essa execução será feito dentro do Protheus.

**Comment by alvarocamillont** [comment]
Boa Tarde!

O Po-ui é uma biblioteca para front-end independente de back-end. Para tirar essas dúvidas você pode entrar em contato com a equipe de suporte do Framework/Tec Protheus.

Obrigado desde já!
