### ISSUE TITLE
PO Table: Ordenação não funciona em colunas do time datetime

### ISSUE THREAD

**Issue by leonardosimoura** [po-ui/po-angular#557]
#### Reprodução

Exemplo do "PO Table - Transport"  no https://po-ui.io/documentation/po-table

Ao tentar ordenar a coluna do tipo datetime "Exit forecast" não é feita a ordenação.

Passos para reproduzir:
1. Acessar https://po-ui.io/documentation/po-table e ir no exemplo "PO Table - Transport"
2. Ordenar a coluna do tipo datetime  Exit forecast
3. Verificar que nada acontece

#### Qual o comportamento atual?
Ao tentar ordenar a coluna do tipo datetime  Exit forecast  não é feita a ordenação.

#### Que comportamento você esperava ver?
Que seja feita a ordenação corretamente

#### Ambiente

- PO UI: 3.1.0
- Angular: 10
- Browser(s):
  - [ X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
Issue será tratada na próxima sprint.

**Comment by jhosefmarks** [comment]
Issue finalizada: https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#330-2020-08-24
