### ISSUE TITLE
Melhoria para filtro avançado no Page Dynamic Table

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#560]
#### Descrição da melhoria
Definir a possibilidade de utilizar filtro De/Até com um determinado campo.

#### Caso de uso
Muitas vezes utilizamos a Page Dynamic Table para exibir uma lista de registros de uma tabela. Em alguns casos em que utilizei, eu adiciono campo de data por exemplo e marco ele para aparecer na pesquisa avançada, porém, ao enviar para o backend, a pesquisa avançada me permite pesquisar apenas pelo valor que eu informar do campo, mas em datas muitas vezes é necessário pesquisar por um período. Seria interessante haver uma opção nos campos quando informamos (filterRange por exemplo), para que na pesquisa avançada o campo apareça duas vezes para que possibilite o usuário informar um período de datas para serem filtradas no backend.

#### Informações adicionais
Citei como exemplo o campo de data, mas isso pode ser estendido para outros tipos de campos também.

A ideia é ficar como na imagem em anexo.
![chrome_2020-08-13_08-49-37](https://user-images.githubusercontent.com/10984007/90131141-07671e80-dd42-11ea-9d69-1100da6f0705.png)

**Comment by jhosefmarks** [comment]
Item adicionado ao backlog.

**Comment by jhosefmarks** [comment]
Hoje é possível adicionar itens na busca avançada sem exibir na tabela, você teria o mesmo resultado que espera, para isso use a seguinte configuração para os campos que quer usar:

```
 { property: 'filterX', filter: true, visible: false }
```

**Comment by likid** [comment]
> Hoje é possível adicionar itens na busca avançada sem exibir na tabela, você teria o mesmo resultado que espera, para isso use a seguinte configuração para os campos que quer usar:
> 
> ```
>  { property: 'filterX', filter: true, visible: false }
> ```

Jhosef, a partir de qual versão isso é possível, pois na versão que estava quando eu abri a issue, eu tentei fazer exatamente isso que você sugeriu, mas o campo não apareceu na pesquisa.

**Comment by likid** [comment]
@jhosefmarks atualizei para a versão 3.6.0 e funcionou da forma que você sugeriu.
