### ISSUE TITLE
Po-Lookup: Valor com /

### ISSUE THREAD

**Issue by likid** [po-ui/po-angular#571]
#### Reprodução
Passos para reproduzir:
1. Incluir um po-lookup chamando um serviço rest
2. Digitar um valor no campo (sem buscar pela lupa) onde este valor contenha uma "/".

#### Qual o comportamento atual?
Ao chamar o serviço rest, a "/" acaba agindo como se fosse parte do Path e retorna o erro 404 do serviço

#### Que comportamento você esperava ver?
O valor deve receber o tratamento de encoding da função encodeURIComponent para que tenha o valor com codificação de url e assim passar o valor corretamente para o endpoint sem parecer ser um path. Este encoding deve ocorrer para outros caracteres também. Ver https://tools.ietf.org/html/rfc3986

#### Ambiente

- PO UI: 3.2.0
- Angular: 10.0.0.9
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros

- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by likid** [comment]
Apesar de eu achar válido a transformação dos dados conforme mencionei na abertura da issue, pois isso está na especificação do RFC, o problema encontrado na verdade é do server REST do Protheus que ao ser definido os PATHs e enviado um parametro com "/", faz com que ele não enxergue o parametro como dados e sim como uma rota, fazendo com que o processamento se perca, por esse motivo estou fechando a issue.
Se os devs do PO acharem interessante fazer este tratamento nos dados, é só reabrir a issue.

**Comment by jhosefmarks** [comment]
Nós estamos avaliando a situação.

**Comment by jhosefmarks** [comment]
Item programado para próxima sprint.

**Comment by jhonyeduardo** [comment]
Issue resolvida na versão 3.7.0

[Changelog](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md)
