### ISSUE TITLE
Como popular um multiselect com "estado" diferente?

### ISSUE THREAD

**Issue by lemissel** [po-ui/po-angular#581]
Oi pessoas!

Eu não sabia onde encaixar, então abrir uma issue em branco, caso precise abrir com um template específico é só me avisar por favor.

Eu tenho um componente "po-multiselect" em um form e funciona perfeitamente para fazer o cadastro, mas não consegui, de forma alguma popular esse componente com o estado de "selecionado" com os dados já existentes no BD no caso da função de alteração.

Olhando a interface PoMultiselectOption não tem nenhum campo que faça isso.

```
export interface PoMultiselectOption {
    /** Label exibido nos itens da lista. */
    label: string;
    /** Valor do objeto que será atribuído ao model. */
    value: string | number;
}
```

Existe essa opção nesse componente?

Desde já agradeço!

**Comment by jhosefmarks** [comment]
**Para saber onde encontrar as informações que você precisa, saber onde postar uma dúvida ou achar outros devs que usam o  PO UI, veja a issue https://github.com/po-ui/po-angular/issues/439.**

@lemissel o multiselect é um campo de múltiplos valores, então você precisa passar para o model do componente um array só com os valores que você quer que sejam preenchidos.

Se você tem um multiselect com os seguintes valores listados (options):

```
readonly peopleList: Array<PoMultiselectOption> = [
  { value: '412341', label: 'Alfred' },
  { value: '518734', label: 'Alice' },
  { value: '986237', label: 'Bradley' },
  { value: '941278', label: 'Jackie' },
  { value: '423837', label: 'Robert' }
];
```

E você deseja que o mesmo já venha selecionado com 2 valores, basta passar para o model um array com os valores desejados (propriedade value dos itens listados):

```
people = ['518734', '423837'];
```

Importante: os valores do array devem fazer parte da lista de objetos disponíveis para o usuário selecionar.

> **Você pode postar suas dúvidas no Stackoverflow usando a hashtag [#po-ui](https://pt.stackoverflow.com/questions/tagged/po-ui).**

**Comment by lemissel** [comment]
Entendido!

Muito obrigado @jhosefmarks !
