### ISSUE TITLE
Erro de cyclic dependency ao atualizar Angular 9.x e PO UI 2.x

### ISSUE THREAD

**Issue by jvaleskasilva** [po-ui/po-angular#584]
#### Qual o comportamento atual?
Mesmo o projeto funcionando, no teste unitário acusa esse erro de cyclic dependency.

![image](https://user-images.githubusercontent.com/12084638/91094409-1fd41480-e631-11ea-985e-582d883b3b2b.png)

#### Ambiente

- PO UI: 2.10.0
- Angular: 9.1.12
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
Bom dia, estamos analisando o caso, assim que possível responderemos sua issue com uma possível solução.

**Comment by jhosefmarks** [comment]
Corrigido!!!

https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#350-2020-09-08
