### ISSUE TITLE
po-upload: componente não possuí headers necessários para comunicação em https

### ISSUE THREAD

**Issue by BIEMAX** [po-ui/po-angular#593]
#### Problema/Reprodução

Hoje, o componente po-upload permite a seleção do arquivo e efetua o upload do arquivo de acordo com o endereço configurado (configurado através da propriedade [p-url]='http://......').

Hoje, possuo dois endereços de endpoints/api (desenvolvidos em nodejs) hospedados em um servidor linux:
-um endpoint em http
-um endpoint em https

Quando configurado para fazer o upload no endpoint em http, o po-upload faz corretamente, mas, quando configurado para o endpoint em https, ele acusa o seguint erro:

*Access to XMLHttpRequest at 'https://localhost:3000/upload' from origin 'https://localhost:4200' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.*

> **Observação:** No seu servidor *node.js*, você precisa adicionar o seguinte componente:
>
> https://www.npmjs.com/package/cors

Após instalar o componente em seu node server, você precisa adicionar o componente na inicialização (abaixo segue um exemplo de como adicionar a política CORS dentro do seu node server):
```javascript

const express = require('express')
const cors = require('cors')
const app = express()

app.use(cors())
app.options('*', cors())

app.listen(config.api.portServer || 3000, function () {
  console.log('Servidor da API iniciado na porta ' + (config.api.portServer || 3000) + ' em ' + Date())
  console.log('--------------------------------------------------')
})

```

Passos para reproduzir:
1. Adicione um component po-upload
2. Na propriedade '[p-url]' adicione um endereço de API que possua certificado (que inicie em HTTPS)
3. Faça o upload do arquivo e verifique o console de seu navegador
4. Deverá apresentar um erro similar ao da imagem abaixo:

![erro_po_upload](https://user-images.githubusercontent.com/47108057/91724184-4f27db80-eb73-11ea-921c-2c520afab620.png)

#### Qual o comportamento atual?
Apresenta erro, informando de que um dos endpoints (front-end ou back-end) não permitiu a chamada devido a falta de segurança  

#### Que comportamento você esperava ver?
Efetuar o upload.

- PO UI: 3.3.0
- Angular: 10.0.10
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [X] Edge
  - [x] Safari
  - [ ] IE 11
  - [X] Outros (Opera também é reproduzível)
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [X] Ubuntu
  - [X] Outros (CentOS também é reproduzível)

**Comment by jhosefmarks** [comment]
@BIEMAX em nossos exemplos usamos HTTPS também e não temos esse problema (https://po-ui.io/documentation/po-upload), verifique se a instância que você está usando o https está configurada corretamente para liberar o acesso.

No seu exemplo as portas dos serviços são diferentes, para isso seu CORS precisa estar configurado corretamente.

**Comment by kassinho13** [comment]
Boa tarde!
Tambem estou com a Mesmoa duvida, preciso passar no header alguns dados como acesstoken etc e no UPLOAD nao tem essa opcao, nem nos exemplos!
alguem sabe me dizer como posso fazer para preencher o header antes de enviar o arquivo?

**Comment by kassinho13** [comment]
Pra correção do meu problema acabei alterando umas funcoes do PO-UI acredito que sirva para voces  @jhosefmarks @devtotvs  colocarem na nova relase, segue um breve procedimento do que foi feito e funcionou

Alteramos a função UPLOAD dentro do **po-ui-ng-components.js** 
Inserindo um novo parametro do **headers** na função **this.sendfile**
Exemplo:
upload(url, files, tOnUpload, uploadCallback, successCallback, errorCallback) {
        const filesLength = files.length;
        const uploadEvent = {
            data: {},
            file: null
        };
        for (let i = 0; i < filesLength; i++) {
            const formData = new FormData();
            const file = files[i];
            const fileName = file.rawFile.name;
            formData.append(this.formField, file.rawFile, fileName);
            // Função upload, onde o desenvolvedor pode enviar dados para a requisição.
            if (tOnUpload) {
                uploadEvent['file'] = file;
                tOnUpload.emit(uploadEvent);
                formData.append('data', JSON.stringify(uploadEvent.data));
            }
            this.sendFile(url, file, formData, uploadCallback, successCallback, errorCallback, uploadEvent.header);
        }
    }
 
Criamos uma nova função **this. getRequestUpload** contendo um parametro **header** e adicionamos na propriedade da variável **_req_** a tag **_headers: header_**
Exemplo:
**_getRequestUpload(url, formData, header) {
        const req = new HttpRequest('POST', url, formData, {
            reportProgress: true,
            headers: header
        });
        return this.http.request(req);
    }_**

Trocamos a função **this.getRequest** que encontra-se dentro da funcao sendFile para a nova função **this.getRequestUpload.**
Exemplo:
sendFile(url, file, formData, uploadCallback, successCallback, errorCallback, header) {
        const request = this.getRequestUpload(url, formData, header).subscribe(event => {
            if (event.type === HttpEventType.UploadProgress) {
                this.addRequest(file, request);
                const percentDone = Math.round((100 * event.loaded) / event.total);
                uploadCallback(file, percentDone);
            }
            else if (event instanceof HttpResponse) {
                // Sucesso, arquivos enviados.
                successCallback(file, event);
            }
        }, (err) => {
            errorCallback(file, err);
        });
    } 

Em nosso componente.html na função p-upload criamos uma função **sendFIle($event)**


 

Dentro desta função inserimos o nosso header evend.header 
Exemplo
 **_sendFile(event) {
   

    let headerCustom =  new HttpHeaders({
      'X-API-Key': apiKey,
      'tipo': tipo,
      'empresa': empresa,
      'matricula': matricula,
    })
    event.header = headerCustom
    event.data = {id_tabela_externa: this.cIDTabela};
    console.log(event);
  }_**
