### ISSUE TITLE
po-page-login: Possibilidade de alterar texto padrão do tooltip fixo.

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#594]
#### Descrição da melhoria
o componente po-page-login vem com o info tooltip fixo e não está sendo útil no projeto que estou trabalhando, preciso retirar este icone com a informação padrão.

#### Caso de uso
Customizar o tooltip ou retirá-lo da página de login, isto permitiria retirar ou adicionar informações. Atualmente só é possível alterar o e-mail que aparece neste campo.
![po_page_login](https://user-images.githubusercontent.com/58361652/91729010-48509700-eb7a-11ea-99d5-5121ca58f38c.png)

**Comment by jhosefmarks** [comment]
@EduardaDalmas você pode fazer a customização da mensagem através das literais.

```
<po-page-login [p-literals]="{loginHint: 'Nova dica de login'}"></po-page-login>
```

![image](https://user-images.githubusercontent.com/11772148/91872805-aa7acc00-ec4e-11ea-9786-84b6f0f2981e.png)
