### ISSUE TITLE
po-menu: Pesquisa ignora itens com subItems vazio

### ISSUE THREAD

**Issue by rubinhos** [po-ui/po-angular#595]
#### Reprodução

Passos para reproduzir:
* Acesse https://po-ui-cshxdj.stackblitz.io/
* Pesquise no filtro do menu pela palavra "Item"

#### Qual o comportamento atual?

O filtro ignora o item que tem um `subItems` vazio - `subItems: []`, sendo que o mesmo visualmente é considerado um item de menu normal.

#### Que comportamento você esperava ver?

O filtro deve considerar os itens com `subItems` vazio também.

#### Ambiente

- PO UI: V3.4.0
- Angular: 10
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [x] macOS
  - [x] Ubuntu
  - [ ] Outros

**Comment by jhosefmarks** [comment]
Programado para a próxima sprint.

**Comment by jhonyeduardo** [comment]
Item liberado na versão 3.7.0

Changelog: https://github.com/po-ui/po-angular/pull/612
