### ISSUE TITLE
Bibliotecas de Ícones não está aparecendo no Portal https://po-ui.io/

### ISSUE THREAD

**Issue by juni0rsi** [po-ui/po-angular#626]
#### Descrição da melhoria
Notei hoje que a página de ícones não estão mais aparecendo no portal   

https://po-ui.io/
https://po-ui.io/guides/icons

#### Caso de uso
Fico no Aguardo.

**Comment by alvarocamillont** [comment]
Olá Junior fizemos os ajuste na publicação. Poderia conferir novamente e confirmar se está ok?

**Comment by juni0rsi** [comment]
Agora Está OK.

**Comment by juni0rsi** [comment]
Obrigado.
