### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by dycorrales** [po-ui/po-angular#639]
#### Descrição da melhoria
Gostaria de saber se tem como adicionar um novo valor que não este na lista do Multiselect. 

#### Caso de uso
Se usuário procura um valor no multiselect e esse valor não esta que permita inserir ele dentro da lista

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.

**Comment by jhonyeduardo** [comment]
Bom dia @dycorrales 

Anotada sua sugestão, este issue entrará em nosso backlog, obrigado.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
