### ISSUE TITLE
Utilizando eventos de tecla nos componentes po-input e po-password

### ISSUE THREAD

**Issue by BIEMAX** [po-ui/po-angular#650]
Olá,

Eu estou implementando o componente **po-input** e gostaria de adicionar eventos do teclado nos componentes, como por exemplo, executar uma determinada ação quando o usuário pressionar a tecla *enter* do teclado.

Estive revisando a documentação e não encontrei uma propriedade com essa finalidade. Isso é possível? Se sim, teria algum exemplo?

**A minha finalidade é a seguinte:** gostaria que quando o usuário pressionasse a tecla enter, que eu pudesse executar uma função para validar os valores em um banco de dados, para me certificar de que de fato essa informação existe, caso não existisse, cadastraria esse novo valor no banco de dados.

Grato pela atenção.

**Comment by jhonyeduardo** [comment]
Bom dia @BIEMAX 

Veja um exemplo que fiz no stackblitz: https://stackblitz.com/edit/po-ui-nurdtb

**Comment by BIEMAX** [comment]
Bom dia @jhonyeduardo 

Era exatamente isso que eu estava procurando.

Eu fiz um teste com seu exemplo e pra minha funcionalidade não funcionou, eu tive que trocar esse trecho de código dentro do **app.component.html**:

**De:**
```html
<po-input name="input" [(ngModel)]="input" (keyup.enter)="onenter(input)">
```

**Para:**
```html
<po-input name="input" [(ngModel)]="input" (keydown.enter)="onenter(input)">
```

Obrigado pela ajuda.
