### ISSUE TITLE
po-lookup Scroll infinito

### ISSUE THREAD

**Issue by izacsc** [po-ui/po-angular#653]
#### Descrição da melhoria
Ao utilizar um componente de lookup que retorne muitos dados o resultado é paginado. O único modo de mudar de página é clicando no botão 'Carregar Mais resultado'

![image](https://user-images.githubusercontent.com/423449/97721760-9ca7c280-1aa8-11eb-90da-de481d29b739.png)

Gostaria que ao chegar no fim da página ( ou próximo ao fim )  fosse disparado automaticamente a requisição, para que a nova página fosse carregada automaticamente.

#### Caso de uso
A melhoria vai permitir um uso mais fluído e com menos cliques do usuário.

**Comment by jhosefmarks** [comment]
Como funcionaria a parte de acessibilidade com essa funcionalidade de scroll infinito?

**Comment by izacsc** [comment]
Como funciona hoje? 

Eu imagino que ao carregar mais registros a acessibilidade poderia notificar o usuário.

**Comment by jhonyeduardo** [comment]
Boa tarde @izacsc 

vamos avaliar com equipe de UX sobre esta sugestão, obrigado.

**Comment by jhonyeduardo** [comment]
Bom dia,

Item será adicionado em nosso backlog, e passará ser opcional no Lookup/Table.
