### ISSUE TITLE
Po-Dialog não aceita quebra de linha

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#656]
Precisava adicionar uma quebra de linha no Po-Dialog porém ele não aceita nenhuma propriedade que faça isso. Seria muito bacana disponibilizar essa opção.

**Comment by jhonyeduardo** [comment]
Boa tarde @EduardaDalmas 

vamos adicionar este item em nosso backlog, obrigado!

**Comment by EduardaDalmas** [comment]
Agradeço muito, será de grande utilidade. Bom trabalho!

**Comment by jhonyeduardo** [comment]
Boa noite, feature esta na master, na proxima release será liberada!
