### ISSUE TITLE
[Dúvida] Page Dynamic Table

### ISSUE THREAD

**Issue by danilocgraciano** [po-ui/po-angular#658]
Olá,

Sobre o componente Page Dynamic Table, quando utilizado via rotas:

serviceApi: 'http://localhost:3000/v1/people', // endpoint dos dados
serviceMetadataApi: 'http://localhost:3000/v1/metadata', // endpoint dos metadados utilizando o método HTTP Get
serviceLoadApi: 'http://localhost:3000/load-metadata' // endpoint de customizações dos metadados utilizando o método 

Poderiam me explicar a diferença de uso de serviceMetadataApi e serviceLoadApi?

Se serviceMetadataApi busca os metadados para montagem da tabela, porque outro método (serviceLoadApi)?

Dei uma olhada na issue #456, mas ainda não consegui compreender quando e como usá-los.

Obrigado.

**Comment by jhosefmarks** [comment]
@danilocgraciano, caso você tenha uma tela que você usa o metadados para construção da mesma no seu produto padrão você vai usar o serviceMetadataApi, e caso queira disponibilizar uma maneira para o seu cliente customizar essa tela, você aponta o serviceLoadApi para o endpoint onde contem a customização, dessa forma você consegue ter pontos separados e isolados.

Imagine um cenário mais real onde você tem o metadados padrão no seu servidor/cloud, você sempre vai atualizar sua aplicação (ou parte da mesma) apenas atualizando o metadados sem precisar "compilar" a aplicação do cliente e o cliente pode ter um servidor a parte com os metadados deles (incluindo um campo a mais, alterando labels, mudando a ordem de exibição do campo, escondendo campos, aplicando validações próprias, etc...), para esse cenário você vai usar o metadados (carrega o metadados que for devolvido) e o load (merge do seu metadados + metadados de customização).

Agora se você tem tudo sob controle, não tem necessidade de isolar os dados dos metadados e nem customização só o serviceApi já é suficiente, basta seguir o padrão chamado pelo template.

Talvez a informação sobre o load não ficou clara na documentação, faltou informar que o load faz o MERGE do metadados.

**Comment by danilocgraciano** [comment]
Olá @jhosefmarks, entendi.

Muito obrigado pela informação.
