### ISSUE TITLE
<po-number>: <quando possui máscara, não permite deletar os números digitados e aceita somente 6 dígitos mesmo sem ter adicionado o p-maxlength>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#665]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.
https://po-ui-aymkq8.stackblitz.io/

Passos para reproduzir:
1. Com o po-number e uma p-mask, tento digitar no campo;
2. Ao digitar, não consigo apagar o que digitei;
3. Também aceita somente 6 dígitos, mesmo sem ter sido colocado maxlenght;

#### Qual o comportamento atual?
Quando vou digitar os números, ele não permite apagar e só aceita até 6 dígitos, ocorre quando é utilizado p-mask 

#### Que comportamento você esperava ver?
Que ele deletasse os números corretamente e não aceitasse somente 6 dígitos, além de obedecer a máscara quando adicionada

#### Ambiente
Aplicação web empresarial

- PO UI:  3.3.0  
- Angular:  10.1.0
- Browser(s):
  - [x ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros
![ProblemPoUi](https://user-images.githubusercontent.com/58361652/98938468-b264b100-24c6-11eb-8006-2201448c79d7.png)

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

Atualmente temos um problema de documentação em certos componentes.

O Po Number não aceita o p-mask, para isso você pode utilizar o [po-input](https://po-ui.io/documentation/po-input)
