### ISSUE TITLE
<po-input>: <campo não tem propriedade para aceitar somente letras>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#666]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.
https://po-ui-tyq7t8.stackblitz.io

Passos para reproduzir:
1. não possui configuração para campo aceitar somente letras;
2.  alguns usuários digitam números e dá problema na aplicação;

#### Qual o comportamento atual?
Aceita números e letras, sem permitir configuração;

#### Que comportamento você esperava ver?
Uma propriedade que permitisse definir se deseja aceitar somente letras;

#### Ambiente

- PO UI:  3.3.0
- Angular:  10.1.0
- Browser(s):
  - [ x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros
![inputIssue](https://user-images.githubusercontent.com/58361652/98940128-46377c80-24c9-11eb-828c-0900ce8bc854.png)

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

Caso houver um tamanho limitado, você pode utilizar o p-mask, ex: ```p-mask="@@@@@@@"```

Já se for algo dinâmico, você pode utilizar o p-pattern e p-error-pattern, ex: 
``` 
  <po-input ... p-pattern="^[a-zA-Z]+$" p-error-pattern="Digite apenas letras"></po-input>
```
