### ISSUE TITLE
table: loading está ficando "esticado" no componente

### ISSUE THREAD

**Issue by jhosefmarks** [po-ui/po-angular#667]
#### Reprodução

Passos para reproduzir:
1. Acessar o link https://po-ui.io/documentation/po-table?view=web e ir até o Sample Labs
2. Adicionar alguns registros
3. Setar a propriedade LOADING

#### Qual o comportamento atual?

O elemento do loading está ficando esticado na tela.

![image](https://user-images.githubusercontent.com/11772148/99108125-a9a6d480-25c5-11eb-93f3-f564c1bc983f.png)

Esse problema afeta o componente lookup também e só tem acontecido no Chrome.

#### Que comportamento você esperava ver?

Que ele tenha o visual da versões anteriores.

![image](https://user-images.githubusercontent.com/11772148/99108298-e70b6200-25c5-11eb-84bf-4774837985ba.png)

#### Ambiente

- PO UI: 3.12.0
- Angular: 10
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [x] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @jhosefmarks 

Adicionamos este item em nosso backlog, obrigado!

**Comment by jhonyeduardo** [comment]
Bom dia

Issue resolvida na versão 3.14.0
