### ISSUE TITLE
page-dynamic-table: mockar dados no front-end

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#669]
#### Descrição da melhoria
Mockar itens através de um [p-options] da mesma forma como funciona em outros lugares enquanto o back-end ainda não está configurado para receber no padrão que o componente obriga a ser.
#### Caso de uso
[p-options]="[{ hasNext: false, items: [{ ... }]"

#### Informações adicionais
Se não usarmos o p-service-api, não conseguimos mockar dados de outra forma direto no componente page-dynamic-table.

**Comment by jhonyeduardo** [comment]
Bom dia @guiworks 

O componente foi desenvolvido para funcionar com serviço e realizar o trabalho pesado, portanto todas as ações, Excluir, Detalhar, Editar, Pesquisar, dependem do serviço de dados.

Caso retirarmos essa inteligência dele seria como utilizar os componentes isolados, tendo que passar funções, itens e fazer a logica dele.

**Comment by guiworks** [comment]
Entendido. Obrigado
