### ISSUE TITLE
po-dynamic-table: acessar o objeto de um atributo retornado no p-service-api

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#675]
#### Descrição da melhoria
Criar uma feature no po-dynamic-table onde eu possa acessar o array de um atributo que é retornado pelo endpoint no 'property'. 
#### Caso de uso

Por exemplo, eu preciso acessar o dado que está no tel1, porém eu não consigo colocar no property 'phones.tel1' hoje com o po-dynamic-table. Esse property seria um dos objetos do [p-fields].

`
[
   {
      "hasNext":false,
      "items":[
         {
            "username":"teste",
            "password":123,
            "phones":{
               "tel1":"2222",
               "tel2":33333
            }
         }
      ]
   }
]
`

**Comment by jhosefmarks** [comment]
@guiworks hoje não é possível fazer isso diretamente nem usando o table, mas você poderia criar um interceptor para deixar os seus items mais flat caso você não consiga acertar isso do lado do servidor.

A ideia de uso desse template é já ter os dados tratados apenas para a apresentação e tomada de decisão (editar, duplicar, remover, etc...).

**Comment by guiworks** [comment]
Ok, estava tentando achar uma solução mais simples do que interceptor (já temos muito hehe), algo como "beforeLoad", mas entendi, obrigado pela atenção.
