### ISSUE TITLE
Seleção da linha da Tabela pelo combo

### ISSUE THREAD

**Issue by maiconputton** [po-ui/po-angular#678]
#### Descrição da melhoria
Fazer uma opção em que somente pelo combo selecione a linha da tabela, e não em qualquer local da linha. 

#### Caso de uso
Ao fazer alguma customização nas células ou colunas que tenham o evento de click, ele acaba fazendo duas ações selecionando a linha e executando a ação da célula

#### Informações adicionais
![imagem](https://user-images.githubusercontent.com/20648863/99569364-4a730680-29af-11eb-9b4a-b323c98bcf57.PNG)

**Comment by jhonyeduardo** [comment]
Boa tarde @maiconputton 

Você poderia dar um exemplo de código para ficar um pouco mais claro?

Você esta utilizando a tabela com columnTemplate e adicionando um combo dentro desse template?

Obrigado.

**Comment by maiconputton** [comment]
`<po-table #tablepedidos p-height="540" 
        p-sort="true" 
                            p-hide-text-overflow 
                           [p-actions]="tableActions" p-striped="true"
                           [p-loading]="loading" 
                           [p-literals]="customLiteralsTable" 
                           p-hide-columns-manager="false" 
                           [p-columns]="pedidoColumns"
                           [p-items]="pedidos"
                          p-selectable 
                          (p-show-more)="listaPedidos()" 
                           [p-show-more-disabled]="validacao.showmore">

    <ng-template p-table-cell-template let-column="column" let-row="row">
      <div id='reagendar' *ngIf="column.property === 'dt_entrega' && row.reagenda === true">
        <span  (click)="onClickReagendar(row)">{{ row.dt_entrega | date: 'dd/MM/yy' }}</span><br>
      </div>
      <div *ngIf="column.property === 'dt_entrega' && row.reagenda === false">
        <span>{{ row.dt_entrega | date: 'dd/MM/yy' }}</span>
      </div>
    </ng-template>

  </po-table>`

**Tenho uma tabela com uma customização em uma célula que contem um evento, se é efetuado o click na célula além de executar a ação da célula ele seleciona a linha.**

**Comment by jhonyeduardo** [comment]
Certo @maiconputton 

No click já tentou utilizar event.stopPropagation?

Ex:
```
<span  (click)="onClickReagendar(row, $event)">{{ row.dt_entrega | date: 'dd/MM/yy' }}</span>

....

onClickReagendar(row, event) {

  event.preventDefault();
  event.stopPropagation();
}
```

**Comment by maiconputton** [comment]
Funcionou @jhonyeduardo Muito obrigado.
