### ISSUE TITLE
Limitação modal (po-modal) de largura max 768px, remover

### ISSUE THREAD

**Issue by charlesreitz** [po-ui/po-angular#680]
Bom Dia caros, pq existe uma limitação do modal? 

É possível remover tal restrição?

https://po-ui.io/documentation/po-modal

![image](https://user-images.githubusercontent.com/1248135/99692903-908ca080-2a69-11eb-8ab0-71376421ffbd.png)

**Comment by jhosefmarks** [comment]
@charlesreitz use `p-size='auto'`.

**Comment by charlesreitz** [comment]
Com "auto" funcionou
