### ISSUE TITLE
po-page-dynamic-table: permitir ajuste de posição do po-notification-service 

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#692]
#### Descrição da melhoria
Posição de bottom and top do notification service ao disparar algum feedback. Hoje o padrão é no bottom e todas as aplicações do nosso repositório estão com o feedback na parte do topo.

#### Caso de uso
p-notification-position=top/bottom
ou p-position

**Comment by jhonyeduardo** [comment]
Olá @guiworks 

Faz sentido criamos um método que seja possível informar a orientação padrão para a aplicação toda? semelhante ao setDefaultDuration, https://po-ui.io/documentation/po-notification

**Comment by guiworks** [comment]
Pode ser sim. Em nossos projetos da TOTVS utilizamos a "orientation top" das notifications. Para deixar 100% a posição no topo, isso seria útil.

**Comment by guiworks** [comment]
Terá então uma configuração para o po-page-dynamic-table para alterar a orientação?

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
