### ISSUE TITLE
po-multiselect - p-literals: Alterar componente ou a propriedade para permitir apresentar uma mensagem enquanto estiver sem dados, e outra enquanto estiver carregando

### ISSUE THREAD

**Issue by nicholaswgd** [po-ui/po-angular#695]
#### Descrição da melhoria
Atualmente no componente PoMultiselectLiterals\po-multiselect, a propriedade **p-literals** mostra uma mensagem personalizada para quando não houver dados. No entanto, gostaríamos de adaptá-lo para mostrar também a mensagem quando está carregando, e caso não haja, continua no padrão do exemplo abaixo, mas quando houver dados e estiver buscando, tenha outra mensagem.

 const customLiterals: PoMultiselectLiterals = {
  noData: 'Sem dados'
};

#### Caso de uso
Neste exemplo abaixo, podemos verificar que é necessário aparecer uma mensagem de quando não há dados, e outra de quando estiver carregando.
![image](https://user-images.githubusercontent.com/21965230/100478532-3ecbc200-30ca-11eb-9837-b4a874f85a14.png)

#### Informações adicionais
N/A

**Comment by jhosefmarks** [comment]
@nicholaswgd atualmente não existe o estado de carregando no componente pois o mesmo não lida com serviço.

Em que momento você teria isso hoje?

**Comment by nicholaswgd** [comment]
@jhosefmarks , obrigado pelo retorno.

No momento em que eu vou selecionar algum item, de início a mensagem que obtenho é essa daqui:
![image](https://user-images.githubusercontent.com/21965230/100480515-42fade00-30d0-11eb-98be-64a2bc210810.png)


Então uso o p-literals para apresentar uma mensagem melhor quando não houver dados. No entanto, enquanto carrega as mensagens também aparece a mesma mensagem do print acima, e acabei utilizando-a para outro propósito.

![image](https://user-images.githubusercontent.com/21965230/100480253-80ab3700-30cf-11eb-96af-e9839e78ecfd.png)

**Comment by jhosefmarks** [comment]
Entendi seu ponto, o ideal então é quando não tiver itens na lista para o usuário, o componente apresentar uma informação diferente, por exemplo "sem itens configurados", ai vc pode configurar essa msg também.

Vamos esperar o PO do projeto analisar e ver se aprova a sugestão e adiciona no backlog.

**Comment by nicholaswgd** [comment]
Então @jhosefmarks, só pra alinhar que passei a necessidade da maneira certa; enquanto está buscando as informações para carregar, ele fica com status de mensagem não encontrada, então eu meio que utilizei o p-literals para customizar uma mensagem de carregando.

Neste caso citado, necessitava de uma mensagem também para enquanto estiver buscando os dados. Não sei se acrescentar mais um parâmetro no p-literals, ou outra forma.

Muito obrigado @jhosefmarks

**Comment by jhonyeduardo** [comment]
Bom dia @nicholaswgd 

Você consegue simular a situação que deseja, obviamente sem a nova mensagem ainda, no stackbliz? https://stackblitz.com/edit/po-ui

Pois o po-multiselect não tem serviço e gostaria de saber como está fazendo, obrigado!

**Comment by jhonyeduardo** [comment]
Bom dia @nicholaswgd, alguma novidade?

**Comment by jhonyeduardo** [comment]
@nicholaswgd Agora com o Multiselect permitindo buscar registros por API, você acredita que há essa necessidade?

Já observou a propriedade `p-filter-service`, que permite este filtros diretamente na API? com isso a experiência fica mais agradável.

**Comment by jhonyeduardo** [comment]
Bom dia @nicholaswgd 

É que antes não tínhamos essa funcionalidade, e para atender a sua  sugestão, teríamos que abrir alguma propriedade para saber se esta carregando os dados, para então apresentar a sua nova literal.

Utilizando o p-filter-service, ele vai funcionar conforme o padrão que adotamos para a biblioteca.

Obrigado, qualquer dúvida estou a disposição.
Att,
