### ISSUE TITLE
Filtros Dinamicos aplicados nos Graficos 

### ISSUE THREAD

**Issue by CassioMenabueLima** [po-ui/po-angular#715]
#### Descrição da melhoria
Poderíamos ter filtros dinâmicos dentro dos gráficos igual o google charts permite, segue URL https://developers.google.com/chart/interactive/docs/gallery/controls
Assim conseguiríamos expandir mais ainda esses graficos 
#### Caso de uso
 Segue exemplo de filtros aplicados dentro dos graficos
![image](https://user-images.githubusercontent.com/26257379/101364987-f8245780-3881-11eb-8220-859b1e779e30.png)

**Comment by jhonyeduardo** [comment]
Bom dia @kassinho13 

Primeiramente obrigado pela sugestão, mas vamos avaliar com calma, pelas seguintes situações:

1. Da pra fazer o filtro na mão e repassar os valores para o gráfico.
2. Estamos avaliando até onde vamos com os gráficos.

**Comment by kassinho13** [comment]
Maravilha Vamos que vamos

**Comment by jhonyeduardo** [comment]
Bom dia, obrigado pela sugestão porém neste momento não temos a intenção de construir filtros para os gráficos.

Caso preciso, é possível fazer por conta própria.

Qualquer dúvida estou a disposição.
