### ISSUE TITLE
onVisibleColumnsChange no po-table não altera os campos do gerenciador de colunas

### ISSUE THREAD

**Issue by maiconputton** [po-ui/po-angular#722]
#### Descrição da melhoria
Ao utilizar a função onVisible ColumnsChange no po-table passando um novo array com colunas não visíveis('visible'), o gerenciador de colunas fica ainda com as colunas selecionadas como se estivessem visíveis. 

#### Caso de uso
Alterar Visibilidade de colunas dependendo de alguma escolha(filtro, ação).

#### Informações adicionais
exemplo: Filtros('primeiro' = colunas 1,2) Filtros('segundo' = colunas 1,4)

**Comment by jhonyeduardo** [comment]
Boa tarde @maiconputton 

Não possuímos uma função para atualizar as colunas visíveis, temos um event emiter (p-change-visible-columns) que é disparada ao alterar via componente, mas não temos algo que você consiga atualizar, a não ser passar as colunas com as novas definições.

Qual seria a necessidade? pois pode passar no inicio essa informação dentro das columns e depois o próprio componente fazer a alteração conforme a demanda do usuário.

**Comment by maiconputton** [comment]
Vou tentar descrever o Requisito:
Preciso fazer uma Tabela de 'Pedidos' que tenha 20 colunas, porem não fica viável deixar todas as colunas em tela por causa da visibilidade, deixando assim visível somente as colunas mais utilizadas possibilitando a escolha de alguma coluna pelo gerenciador. ate ai tudo tranquilo funcionamento normal.

Só que foi desenvolvido Filtros que mostram situações(visões). EX: 'pedidos faturados' onde  quero predeterminar colunas diferentes da visualização original, nessa escolha quero que apareça por exemplo a coluna 'Nota fiscal'. Se selecionar 'Pedidos em Aberto' não faz sentido ter a coluna 'Nota Fiscal'. 
Tentando ter uma situação dinâmica em que dependendo dos filtros selecionados a tabela vai visualizar ou não as colunas necessárias. Porem deixando a possibilidade do usuário marcar as demais colunas se achar necessário.

Para tentar fazer isso com uma única tabela eu estou alterando a visibilidade das colunas do PoTableColumn e utilizando o metodo onVisibleColumnsChange onde consigo ter esse comportamento, porem o gerenciador de colunas fica com a seleção das colunas inicial.

**Comment by jhonyeduardo** [comment]
Bom dia @maiconputton 

Fizemos a correção do item https://github.com/po-ui/po-angular/issues/783 que também tem relação com o seu problema.

Você passa nova definições de colunas, com a propriedade *visible* alterada conforme a necessidade.

Qualquer dúvida estou a disposição.
