### ISSUE TITLE
po-page-dynamic-table: p-table-custom-actions não funciona se usada sem p-actions

### ISSUE THREAD

**Issue by afucher** [po-ui/po-angular#732]
#### Reprodução
Aparentemente não é possível mais utilizar apenas a propriedade `p-table-custom-actions` sem definir a propriedade `p-action`, não vi nada sobre isso no doc de atualização. No link para reprodução do stackblitz abaixo, copiei as ações do exemplo da documentação para validar isso. Para fazer funcionar basta adicionar no `app.component.html` o seguinte código:
```html
[p-actions]="actions" 
```

[Reprodução](https://stackblitz.com/edit/po-ui-ued1sn?file=src%2Fapp%2Fapp.component.html)

Passos para reproduzir:
1. Aplicação `po-ui`versão 3
2. Utilizar o componente `po-page-dynamic-table` com `p-table-custom-actions` e sem `p-actions`
3. Ao atualizar para versão 4 do `po-ui`a aplicação quebra.

O repositório da aplicação que estou fazendo é este [aqui](https://github.com/afucher/aera-core/), apenas atualizei o angular e o `po-ui`.

#### Qual o comportamento atual?
Não consegue renderizar o componente corretamente, e da vários erros no console
<img width="641" alt="Captura de Tela 2020-12-10 às 23 03 16" src="https://user-images.githubusercontent.com/3756185/101852222-e79f0600-3b3b-11eb-92aa-8eaa9cfdcd7e.png">

#### Que comportamento você esperava ver?
Renderizar a tabela com a ação customizada que foi passada.

#### Ambiente

- PO UI: "@po-ui/ng-components": "4.0.0",
- Angular: "@angular/core": "~11.0.4",
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [x] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @afucher 

Vamos adicionar este item em nosso backlog, obrigado!

**Comment by afucher** [comment]
🎉
