### ISSUE TITLE
Terceiro botão (Action) no componente po-modal

### ISSUE THREAD

**Issue by tiago-arrosi** [po-ui/po-angular#733]
#### Descrição da melhoria
Gostaríamos de avaliar a possibilidade de inclusão de uma terceira ação no componente po-modal.

#### Caso de uso
Hoje temos algumas buscas avançadas que possuem diversos campos de filtros. Alguns clientes solicitam que o filtro seja aparece preenchido com a última pesquisa realizada e outros preferem que estejam em branco. Assim gostaríamos de incluir uma opção para limpar o filtro, dessa forma atenderíamos as duas necessidades.

Na busca avançada teríamos então os botões de "Aplicar Filtro",  "Limpar Filtro" e "Fechar".

Caso essa não seja uma possibilidade, existe alguma recomendação do padrão a ser utilizado atendendo essa necessidade?

#### Informações adicionais
Exemplo de uma tela onde temos diversos filtros para o usuário.

![image](https://user-images.githubusercontent.com/18600662/102083101-cd8e4d80-3df1-11eb-95a3-6473589116ec.png)

**Comment by jhonyeduardo** [comment]
Bom dia @tiago-arrosi 

Vamos adicionar este item em nosso backlog e avaliar a implementação, obrigado.

**Comment by rafaellmarques** [comment]
Bom dia @tiago-arrosi , tudo bem?
Estou revisitando nossas issues e gostaria de saber se esse tópico pode ser encerrado?
Na versão 5.20.0 implementamos ao modal o modal-footer, componente que permite ao desenvolvedor utilizar botões de ação personalizados de acordo com suas necessidades.
Fico no aguardo.

Att.

**Comment by tiago-arrosi** [comment]
Boa tarde, @rafaellmarques .

Com essa implementação podemos encerrar esse tópico.

Obrigado.
