### ISSUE TITLE
PO-DECIMAL - Entrada númerica

### ISSUE THREAD

**Issue by danilosalve** [po-ui/po-angular#741]
#### Descrição da melhoria
Ao utilizar o componente **po-decimal**, o teclado do celular não fica formatado para a entrada do tipo numérico.

**Comment by jhonyeduardo** [comment]
Bom dia @danilosalve 

Vamos incluir em nosso backlog, obrigado!

**Comment by jhonyeduardo** [comment]
Bom dia @danilosalve 

Item implementado na PR https://github.com/po-ui/po-angular/pull/749

Será liberado na próxima release, obrigado!
