### ISSUE TITLE
Ícone de acessibilidade

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#744]
A biblioteca de ícones do PO-UI não tem ícones de acessibilidade, como por exemplo para cadeirantes, gestantes, idosos. 
é de muita importância que esses ícones estejam inclusos na biblioteca, como o exemplo.
![cadeirante](https://user-images.githubusercontent.com/58361652/102616150-dfcffa80-4115-11eb-9e68-c67ed2ee2f16.png)

**Comment by peixeh** [comment]
Olá @EduardaDalmas, tudo bom?
Ótimo ponto de vista. Concordamos e vamos incluir em uma de nossas próximas atividades para o PO UI.
Assim que tivermos notícia avisaremos.

Muito obrigado!

**Comment by peixeh** [comment]
Olá @EduardaDalmas 
Na próxima release teremos disponível 3 ícones referentes a acessibilidade, que são: cadeirante, gestante e idoso. Planejaremos outros estilos de ícones para próximas releases, pois entendemos a importância do assunto.

Muito obrigado,

**Comment by EduardaDalmas** [comment]
Muito obrigada pelo empenho. Ótimo trabalho.

**Comment by peixeh** [comment]
Os ícones se encontram disponíveis:
. a11y-elderly
. a11y-pregnant
. a11y-wheelchair

**Comment by jhonyeduardo** [comment]
ícones liberados na versão [4.5.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#450-2021-02-08)
