### ISSUE TITLE
Permitir trabalhar com templates dentro do po-multiselect

### ISSUE THREAD

**Issue by yantotvs** [po-ui/po-angular#750]
#### Descrição da melhoria
Seria útil de ter a opção de utilizar templates como o po-combo disponibiliza([https://po-ui.io/documentation/po-combo]()), onde é utilizado algumas diretivas e então é possível ter um nível de customização maior dentro do componente.

#### Caso de uso
Em um dos projetos que estou participando existe um cadastro de motoristas e um cadastro de prestadores de serviços, um motorista pode ter vínculo com 1 ou mais prestadores de serviços, no processo de cadastro esse vínculo é feito por meio de um <po-multiselect/>, foi alinhado com dois designers que o usuário deveria saber se o prestador de serviço que ele está vinculando ao motorista está com o status "ATIVO" ou "INATIVO". Depois de realizar uma pesquisa encontramos o seguinte modelo: [https://imgur.com/BnjgMbR]()
Para implementar apenas a tag indicando se o cadastro está "ATIVO" ou "INATIVO" atualmente meu time e eu não conseguimos encontrar nenhuma maneira viável que não envolva gambiarras enormes.
Temporariamente foi optado por apenas concatenar a situação ao label de cada opção: [https://imgur.com/a/TItsuII]()

#### Informações adicionais
O template poderia substituir o "label" de cada opção gerada, assim o mecanismo de marcação de opções não seria afetado.

**Comment by jhonyeduardo** [comment]
Boa tarde @yantotvs 

Adicionamos este item em nosso backlog para implementação futura, obrigado!

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
