### ISSUE TITLE
po-input: setErros não funciona quando p-mask é dinâmico

### ISSUE THREAD

**Issue by felipexmantovani** [po-ui/po-angular#751]
#### Reprodução
https://po-ui-x4vtwx.stackblitz.io
https://stackblitz.com/edit/po-ui-x4vtwx?

Passos para reproduzir:
1. Alterar o tipo de pessoa (PF / PJ)

#### Qual o comportamento atual?
Ao alterar o tipo de pessoa o método setErros não funciona.

#### Que comportamento você esperava ver?
Ao alterar o tipo de pessoa deveria setar o erro "{ documentoIdentificacao: true }" no control do component po-input.

#### Ambiente
- PO UI: 3.9.1
- Angular: ~10.1.6
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [x] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @felipexmantovani 

Este item será adicionado em nosso backlog para corrigirmos assim que possível.

**Comment by jhonyeduardo** [comment]
Boa noite @felipexmantovani 

Problema resolvido na versão [4.8.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md), obrigado!

**Comment by felipexmantovani** [comment]
Bom dia @jhonyeduardo, show!!!
Obrigado!
