### ISSUE TITLE
po-combo

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#758]
Boa tarde.

Eu preciso trazer a informação que já foi selecionada no po-combo anteriormente para a edição de beneficiários, porém o componente não carrega a tela com a opção antiga selecionada, mesmo ela vindo no array. As opções apresentadas na documentação não solucionaram. Teria como ajudarem?

![Captura de Tela 2021-01-04 às 16 24 41](https://user-images.githubusercontent.com/58361652/103571507-bfd85f00-4ea9-11eb-8bd3-157544521840.png)

**Comment by alvarocamillont** [comment]
Olá! Poderia mandar como você está fazendo e quando você quer esse campo atualizado (assim que entra na tela, depois de alguma ação)

Obrigado

**Comment by alvarocamillont** [comment]
Você pode usar o stackblitz (https://stackblitz.com/edit/po-ui) para montar seu exemplo

**Comment by alvarocamillont** [comment]
Excelente! Mas faltou como que você configurou os inputs. Não precisa conectar ao ser servidor, o serviço pode voltar um json fixo com alguma categorias no exemplo, pq o problema pode ser no retorno da API, para isolar isso vc pode para teste colocar o json fixo no service

**Comment by EduardaDalmas** [comment]
Os exemlos que iniciam já com um valor no combo são do po-select. Então não há exemplos na documentação de como inicializar com um valor selecionado no combo. Se puderem ajudar nisso.

**Comment by alvarocamillont** [comment]
Tudo bem tranquilo! Vamos analisar

Obrigado

**Comment by EduardaDalmas** [comment]
Aguardo seu retorno.

Obrigada!

**Comment by jhonyeduardo** [comment]
Boa tarde @EduardaDalmas 

Alterei o fonte e funcionou, anteriormente estava passando pro ngModel a referencia da função "getMedicalSpecialty" no link abaixo fiz a alteração passando o valor correto "medicalSpecialty".
 
https://stackblitz.com/edit/po-ui-qzrwdn?file=src%2Fapp%2Fapp.component.html

**Comment by EduardaDalmas** [comment]
Obrigada pelo suporte, iremos testar desta forma.

**Comment by EduardaDalmas** [comment]
Resolvemos o problema com sua ajuda. Obrigada pela atenção e dedicação. Bom trabalho!

**Comment by jhonyeduardo** [comment]
Que bom que ajudou,

Ficamos a disposição!
