### ISSUE TITLE
Criar o componente Timeline

### ISSUE THREAD

**Issue by leonardosimoura** [po-ui/po-angular#759]
#### Descrição da melhoria
Criar o componente Timeline.

#### Caso de uso
Exibição de conteúdo em formato sequencial / timeline.

#### Informações adicionais
PR:
#709 
[#178](https://github.com/po-ui/po-style/pull/178)

**Comment by EduardaDalmas** [comment]
Iria ser ótimo mesmo, o stepper ás vezes não funciona tão bem para timelines.

**Comment by jhonyeduardo** [comment]
Obrigado pela contribuição e solicitação.

Estamos desenvolvendo no momento o [Animalia Design System](https://github.com/animaliads), que contemplará os componentes bases de quais faremos o uso.

Repassamos a necessidade do componente a equipe responsável, acreditamos que ano que vem possamos ter a disposição este componente.

Qualquer dúvida estamos a disposição.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
