### ISSUE TITLE
page-dynamic-table: newUrl do beforeRemove repetindo a key no final da url

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#761]
#### Reprodução

implementação do beforeRemove nas actions e criação de método para retornar a nova 'newUrl' com 
newUrl: `item/${variavelA}/{variavelB}

#### Qual o comportamento atual?

Quando eu tento passar a nova URL passando as variáveis que quero no beforeRemove, ele acaba colocando o campo 'key' no final da url por padrão que esteja definido la no p-fields.

na url fica: ...item/teste/teste/key

obs.: 

#### Que comportamento você esperava ver?

o esperado: ...item/teste/teste

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [ ] Chrome
  - [ ] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @guiworks 

Consegue simular o problema neste ambiente? 

https://stackblitz.com/edit/po-ui

**Comment by guiworks** [comment]
Opa, coloquei só o componente e fiz alguns comentários pra sinalizar

https://po-ui-3d4j9l.stackblitz.io/

**Comment by guiworks** [comment]
.

**Comment by guiworks** [comment]
up

**Comment by jhonyeduardo** [comment]
Boa tarde @guiworks 

Desculpe-nos a demora, será analisado de fato se é problema, se concretizando vamos adicionar nas próximas sprints.

Qualquer dúvida a disposição.

**Comment by jhonyeduardo** [comment]
Bom dia @guiworks 

Issue resolvida na versão 4.16.1, já publicada para uso.

Qualquer dúvida estou a disposição.
