### ISSUE TITLE
<Po-Modal>: <Modal não limpa o valor quando fechada>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#762]
#### Boa tarde. O portal da empresa em que trabalho é totalmente feito em Po-ui. Somos uma operadora de planos de saúde,  tem uma modal que abre quando um usuário quer transferir usuários para outro contrato, nessa modal há um po-select para a seleção de contratos e 2 botões de upload. Quando o transferência é realizada ou cancelada, quando abre a modal novamente, o contrato continua selecionado como anteriormente e o upload também. Utilizei os exemplos de 'restore' que apresentam na documentação porém não funcionou.

https://po-ui-wcmkgd.stackblitz.io

Passos para reproduzir:
1. Seleciono o contrato;
2. Faço os uploads;
3. Fecho a modal;
4. Ao abrir novamente, os dados continuam ali mesmo quando coloquei o restore na action da modal .

#### Qual o comportamento atual?
Os dados permanecem na modal mesmo após fechada. 

#### Que comportamento você esperava ver?
Que a modal limpasse os dados quando fechada, assim como no exemplo apresentado na documentação.

#### Ambiente

- PO UI: 3.3
- Angular: 10.1
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @EduardaDalmas 

Não encontrei o po-modal na reprodução que nos passou, poderia verificar?

Porém, o po-modal é um componente que mantém os valores, pois ele não é removido do DOM ao fechar, 
para limpar os dados ao fechar a modal, você precisa limpar o formulário na "mão", podendo utilizar o form.reset() por exemplo.

**Comment by jhonyeduardo** [comment]
Olá @EduardaDalmas, alguma novidade?

**Comment by EduardaDalmas** [comment]
Boa tarde. Utilizei o recurso do form.reset() porém não funcionou.

**Comment by jhonyeduardo** [comment]
Você consegue nos enviar um exemplo deste seu cenário neste ambiente https://stackblitz.com/edit/po-ui ?

**Comment by EduardaDalmas** [comment]
Bom dia. Desculpe a demora. Estamos com alta demanda. Aqui está a simulação do problema. Agradeço a atenção e dedicação. segue o link: https://po-ui-7xvmqu.stackblitz.io

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

segue link de demonstração: https://stackblitz.com/edit/po-ui-savrtz

Deve-se utilizar ngModel ou ReactiveForm nos campos, e recuperar o <form> responsável por eles, após isso realizar o form.reset() tanto na confirmação como no cancelamento da modal.

Qualquer dúvida estou a disposição.

**Comment by jhonyeduardo** [comment]
Alguma novidade?

**Comment by EduardaDalmas** [comment]
Boa tarde, desculpa a demora para responder, estamos com muita demanda. 
Boas notícias, o problema foi resolvido. Obrigada por toda atenção e suporte. Bom trabalho.

**Comment by marcioA** [comment]
Boa noite Eduarda, como resolveram o problema ?
