### ISSUE TITLE
po-dynamic-form: campo do tipo time atualiza valor sem o caracter ":"

### ISSUE THREAD

**Issue by afucher** [po-ui/po-angular#766]
#### Reprodução

[reprodução](https://stackblitz.com/edit/po-ui-gowhxv)

Passos para reproduzir:
1. Crie um formulário com campo do tipo time
2. Atualize o valor do campo para 16:30 (por exemplo)
3. Verifique o valor da propriedade ligada ao campo

#### Qual o comportamento atual?
O valor que fica na propriedade não contém o caracter `:`, caso digite `16:30` fica `1630`.

#### Que comportamento você esperava ver?
Esperava que o valor se mantivesse com o caracter `:`

#### Ambiente

- PO UI: 4.0.0
- Angular: 11.0.4
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ ] Windows
  - [x] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @afucher 

Vamos incluir este item em nosso backlog, obrigado.

**Comment by jhonyeduardo** [comment]
Boa tarde 

Issue resolvida, será liberada na versão 4.10.0, obrigado.
