### ISSUE TITLE
Suporte ao Angular Universal

### ISSUE THREAD

**Issue by siegklenes** [po-ui/po-angular#769]
#### Descrição da melhoria
Suporte a https://angular.io/guide/universal

#### Caso de uso
Permite utilizar a pattern https://samnewman.io/patterns/architectural/bff/ sem a necessidade de um serviço extra.
Permite que requisições com dados sensiveis sejam feitas apenas pelo backend do front-end.

**Comment by afucher** [comment]
@siegklenes hoje já é possível usar BFF independente de SSR (server-side rendering).

**Comment by jhonyeduardo** [comment]
Boa tarde @siegklenes 

Vamos avaliar esta situação.

Mas para saber mais detalhes, você tentou utilizar o po-ui em uma aplicação ssr e ocorreu algum erro?
