### ISSUE TITLE
po-combo: Zoom no iOS

### ISSUE THREAD

**Issue by deboraconstantino** [po-ui/po-angular#770]
Passos para reproduzir:
1. Abrir uma tela que possua um campo po-combo;
2. Clicar no campo do combo para apresentar as informações;

#### Qual o comportamento atual?
Ao clicar no campo que é po-combo, o zoom está cortando parte da tela, não sendo possível visualizar todas as opções disponíveis. Comportamento percebido apenas em iOS.

#### Que comportamento você esperava ver?
Que o zoom aplicado no campo não cortasse a tela e fosse possível visualizar todas as opções disponíveis no combo.

#### Ambiente

- PO UI: 3.1.0
- Angular: 10
- Browser(s):
  - [ ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari - PWA
  - [ ] IE 11
  - [x] Outros: PWA em iOS

**Comment by jhonyeduardo** [comment]
Bom dia @deboraconstantino 

Vamos adicionar este item em nosso backlog, obrigado.
