### ISSUE TITLE
PoPageSlideComponent : Erro no console log, impossibilitando navegação: Uncaught RangeError: Maximum call stack size exceeded. 

### ISSUE THREAD

**Issue by wgcostta** [po-ui/po-angular#772]
Ao utilizar o po-page-slide, e colocar um polookup dentro dele, o mesmo estoura erro no console depois de abrir o modal do lookup para selecionar os registros e clicar nos itens da grid. Isso ocorre também quando utilizando um modal com vários inputs de edição que são chamados dentro do po-page-slide.

Reprodução:
https://stackblitz.com/edit/po-ui-7ggwzr?file=src/app/app.component.html

Github:
https://github.com/wgcostta/po-ui-page-slide

Passos para reproduzir:
O StackBlitz não reconhece o lookup mesmo atualizando a versão do Angular e Po-UI, portanto adicionei o mesmo, mas para reprodução do erro usar o modal colocado: 
1 - Abrir o page-slide 
2 - Abrir o modal, 
3 - em seguida abrir o console do navegador e tentar utilizar os inputs, será exibido os erros e não será possível utilizar os inputs e navegação.

#### Qual o comportamento atual?
É apresentado erros no console e fica impossibilitado de outros componentes dentro de um po-page-slide.

#### Que comportamento você esperava ver?
Que fosse possível abrir outros componentes e selecionar registros, fazer edições, sendo chamado por dentro do po-page-slide. Nossa necessidade visa atender o design de UX do SupplyAgro. Issue: DTHFUI-4666

![erro](https://user-images.githubusercontent.com/39952575/105065742-f2af5500-5a5c-11eb-93b5-d4f8060a6aeb.png)
![possivel problema](https://user-images.githubusercontent.com/39952575/105065746-f4791880-5a5c-11eb-82ea-e4f5f02c246b.png)

#### Ambiente

- PO UI: 4.3.0
- Angular: 11.0.5
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @wgcostta 

Vamos avaliar este problema e liberar a correção assim que possível, obrigado.

**Comment by jhonyeduardo** [comment]
Boa tarde,
Correção liberada na versão [4.7.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md), obrigado!
