### ISSUE TITLE
Adicionar soma/total de uma coluna

### ISSUE THREAD

**Issue by RBalconi** [po-ui/po-angular#777]
#### Descrição da melhoria
Possibilidade de adicionar no final de uma coluna, cujo valores sejam números, a soma/total da mesma, como é geralmente feito em planilhas do Excel.

#### Caso de uso
Quando temos uma GRID cuja alguma coluna refere-se a valores, é comum que o cliente/usuário espere que ao final exista uma Soma/Totalização dessa coluna, pois isso facilita muito a identificação desses valores e evita que o mesmo precisa fazer somas manualmente, ou até gerar um relatório em alguns casos. É uma informação prática e rápida que está a disposição do cliente.

#### Informações adicionais
![exemplo](https://user-images.githubusercontent.com/18688446/106193168-88e12a80-6183-11eb-9e35-516fcc62091d.png)
Exemplo de como poderia ser uma grid exibindo o total dos valores da coluna "Currency"

**Comment by jhonyeduardo** [comment]
Bom dia @RBalconi 

Obrigado pela issue, vamos adicionar este item em nosso backlog, obrigado.
