### ISSUE TITLE
po-code-editor permitir informar o atributo ignoreCase na criação de nova linguagem.

### ISSUE THREAD

**Issue by dgo-angelo** [po-ui/po-angular#778]
#### Descrição da melhoria
Incluir a propriedade ignoreCase na interface do PoCodeEditorRegisterableOptions, permitindo definir se a nova linguagem é case sensitive ou não
(Isto já é permitido no Monato Editor)

#### Caso de uso
Definir se a nova linguagem será case sensitive ou não.

**Comment by jhonyeduardo** [comment]
Boa tarde @dgo-angelo 

Que tal contribuir conosco? temos este (guia)[https://po-ui.io/guides/development-flow] que pode te ajudar :)

Se não puder, entenderemos, vamos adicionar este item em nosso backlog.
