### ISSUE TITLE
<po-email>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#782]
![image](https://user-images.githubusercontent.com/58361652/107080259-c707cb00-67cf-11eb-92e4-17058df5b01b.png)
  
No po-email não há tratativa para emails com letras maiúsculas, gerando um erro.

**Comment by jhonyeduardo** [comment]
Olá @EduardaDalmas 

Que tal fazer sua primeira contribuição? Você pode seguir este documento https://po-ui.io/guides/development-flow e qualquer dúvida me chamar :)

Caso não puder, entenderemos e vamos adicionar este item em nosso backlog.

**Comment by jhonyeduardo** [comment]
Issue resolvida, será liberado na versão 4.10.0.
