### ISSUE TITLE
PoTableComponent : columns-manager não fica condizente quando atualizado o elemento columns.

### ISSUE THREAD

**Issue by wgcostta** [po-ui/po-angular#783]
#### Reprodução

Reproduzido em: https://stackblitz.com/edit/po-ui-ozvpgw?file=src/app/save-columns.directive.ts

Passos para reproduzir:
1. Editar as colunas em exibição.
2. Atualizar a pagina, o localstorage será recarregado juntos com as colunas.
3. Problema -> Mesmo chamando as duas funções abaixo o Gerenciador de Colunas não atualiza com as colunas
      Correspondentes que estão de fato em exibição;

      this.table.onVisibleColumnsChange(colunasVisiveis);
      this.table.onChangeVisibleColumns(columns);

#### Qual o comportamento atual?
No Gerenciador de Colunas exibe colunas que não estão em exibição.

#### Que comportamento você esperava ver?
Que ao atualizar as columns seja diretamente ou por meio das funções:
      this.table.onVisibleColumnsChange(colunasVisiveis);
      this.table.onChangeVisibleColumns(columns);
Que o gerenciador de colunas respeite os mesmos.

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [X] Ubuntu
  - [ ] Outros
![erro-gerenciador-colunas](https://user-images.githubusercontent.com/39952575/107081199-169ac680-67d1-11eb-9bdc-931bb06c722c.png)

**Comment by jhonyeduardo** [comment]
Boa tarde @wgcostta 

Estes métodos não estão documentados para utilização, são públicos por causa da sua estrutura internamente.

Você atribuir as novas colunas normalmente não funciona?

**Comment by wgcostta** [comment]
Se eu atribuir diretamente nas colunas, ele atualiza as mesmas porém o ColumnsManager não é atualizado. 
Como pode ver na imagem abaixo, passando direto pra columns ele atualiza a grid mas no gerenciador de colunas não fica condizendo com o que esta sendo exibido. Isso ocorre também sem usar diretiva como no meu exemplo. se fizesse diretamente no component, os dados de exemplo são da documentação do po-ui;

https://stackblitz.com/edit/po-ui-wbmjq6?file=src/app/save-columns.directive.ts

![image](https://user-images.githubusercontent.com/39952575/108749904-27f90800-751f-11eb-9794-eeb21d986e2a.png)

**Comment by jhonyeduardo** [comment]
Bom dia, item adicionado em nosso backlog, obrigado

**Comment by jhonyeduardo** [comment]
Bom dia @wgcostta 

Na versão 4.16.0 corrigimos esta situação.

Qualquer dúvida estou a disposição, obrigado!
