### ISSUE TITLE
Stepper > PoStepperItem: Não respeita o valor de PoStepperStatus

### ISSUE THREAD

**Issue by CarlosEReis** [po-ui/po-angular#790]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. https://stackblitz.com/github/yqnimyqkg?file=src/app/app.component.ts
2. https://github.com/CarlosEReis/po-ui-stepper

#### Qual o comportamento atual?
O **status** não muda independentemente da configuração que é passada nos objetos dentro do array de **PoStepperItem** através do enum **PoStepperStatus** 

![image](https://user-images.githubusercontent.com/12797559/107979728-d7713000-6f9d-11eb-8761-0c969bfe4767.png)

![image](https://user-images.githubusercontent.com/12797559/107979402-426e3700-6f9d-11eb-8b8b-db45c5652ba6.png)

#### Que comportamento você esperava ver?
Estava que o status ficasse de acordo com o que é especificado na documentação:
![image](https://user-images.githubusercontent.com/12797559/107980141-8150bc80-6f9e-11eb-8a49-ff5d5dd684ed.png)

#### Ambiente

- PO UI: 4.4.0
- Angular: 11.0.7
- Browser(s):
  - [✔️ ] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [✔️ ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @CarlosEReis 

Para o mesmo respeitar o status, você deve utilizar o p-steps, conforme documentado no ENUM, e você deve construir o mecanismo de troca de steps.

**Comment by alinelariguet** [comment]
Boa noite @CarlosEReis, tudo bem?
Alguma novidade? Podemos fechar a issue?
