### ISSUE TITLE
Error: src/app/app.component.html:5:3 - error TS2322: Type 'string' is not assignable to type 'boolean'.

### ISSUE THREAD

**Issue by Evertonpx** [po-ui/po-angular#792]
Bom dia, estou com esse erro quando incluo P-FILTER

√ Browser application bundle generation complete.

5 unchanged chunks

Build at: 2021-02-19T11:37:07.945Z - Hash: e1f5dfcf9e284141474c - Time: 624ms

Error: src/app/app.component.html:5:3 - error TS2322: Type 'string' is not assignable to type 'boolean'.

5   p-filter
    ~~~~~~~~

  src/app/app.component.ts:9:16
    9   templateUrl: './app.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component AppComponent.

**Comment by jhonyeduardo** [comment]
Bom dia, Preciso de mais informações.

- Qual versão esta utilizando?
- Este erro acontece no ng serve ou ng build --prod?
- Você criou o projeto no modo strict?

**Comment by Evertonpx** [comment]
Versão angular cli 11
ng serve
criei conforme https://po-ui.io/guides/getting-started

**Comment by jhonyeduardo** [comment]
Obrigado pelo retorno.

Após a verificar, foi observado que quando criar uma aplicação via `ng new <name>`, ele questiona se quer iniciar no modo `strict`, com isso ele faz essas validação de templates, pois `p-filter` é um atributo booleano, fazendo apenas `p-filter` é como estivesse passando string, que é a raiz do erro mencionado.

Portanto para resolver, informe um valor boolean, ex: `[p-filter]="true"`

Fico no aguardo para avaliar se funcionou.

**Comment by Evertonpx** [comment]
Bom dia Jhony, agora funcionou sim ... muito obrigado

**Comment by jhonyeduardo** [comment]
De nada, qualquer dúvida estamos a disposição.
