### ISSUE TITLE
po-slide: falha de apresentação ao redimencionar janela

### ISSUE THREAD

**Issue by JoseCamilo** [po-ui/po-angular#795]
#### Reprodução
No próprio portal do POUI o problema acontece: https://po-ui.io/documentation/po-slide

Passos para reproduzir:
Modo A:
1. Com a janela do navegador em seu tamanho máximo, abra o portal POUI: https://po-ui.io/documentation/po-slide
2. Acesse a aba exemplos
3. Diminua o tamanho da janela do Navegador (ao ponto do slide ter seu tamanho alterado)
4. Restaure o tamanho original do Navegador
5. Utilizar os Po-Slides que contem na página

Modo B:
1. Com a janela do navegador em tamanho reduzido (ao ponto do slide ter seu tamanho alterado), abra o portal POUI: https://po-ui.io/documentation/po-slide
2. Acesse a aba exemplos
3. Maximize a janela do navegador na sua totalidade
4. Utilizar os Po-Slides que contem na página

#### Qual o comportamento atual?
Quando a janela do Browse é reduzida, o Slide calcula o tamanho que deve ser apresentado as imagens porém, quando a janela retorna ao seu valor original (expandida), esse calculo não refeito corretamente.

#### Que comportamento você esperava ver?
Ao reduzir e ao expandir a janela do navegador, as imagens do Slide, devem ser enquadradas corretamente nos slides.

#### Ambiente

- PO UI: 4.7.0
- Angular: 11
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge (no Edge Funciona corretamente)
  - [ ] Safari
  - [ ] IE 11
  - [] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @JoseCamilo 

Obrigado pela issue, vamos adicionar ao nosso backlog e corrigir assim que possível.

Qualquer dúvida, estou a disposição.
