### ISSUE TITLE
po-login: p-background não redimensiona imagem proporcionalmente conforme tamanho de tela

### ISSUE THREAD

**Issue by sganzerla** [po-ui/po-angular#808]
#### Descrição da melhoria
Ao utilizar uma imagem para ser exibida junto com o login em telas maiores que 768px de largura ela é exibida. Mas conforme aumenta-se a largura da tela a imagem não acompanha a proporção do espaço lateral fazendo com que ela fique parcialmente visível. 

Sugiro, se possível, adicionar uma opção para que a imagem fique centralizada no espaço, e o seu tamanho seja redimensionado de acordo com o tamanho disponível.

Para não quebrar quem já utiliza esse componente, pode-se adicionar outra Input property OPCIONAL para mudar o comportamento da imagem, por exemplo:

<po-page-login  [p-background]="image"  p-background-resize="proporcional">   <po-page-login/>

O p-background-resize alteraria o comportamento atual do componente se fosse passado um parâmetro  "proporcional".

#### Caso de uso
Ao gerar um PWA com a aplicação rodando numa tela 21', a imagem fica recortada pela metade perdendo parte da informação.

#### Passos para reproduzir 

Colocar uma imagem de background no componente <po-page-login> e utilizando-se as ferramentas de desenvolvedor (F12) do navegador ir aumentando e diminuindo a tela na página de login da aplicação. 

#### Ambiente

* PO-UI: 4.7.0
* Angular: 11
* @po-ui/ng-templates: "^4.8.0"

Temas: 
   * @totvs/po-theme: "^4.7.0"
   * @totvs/po-bemacash-theme : "^2.0.0-beta.1"

Browser(s):
  * Chrome
  * Firefox

SO:
  * Windows
  * Ubuntu

Imagem renderizada corretamente:

![image](https://user-images.githubusercontent.com/22710963/110633069-1488a680-8187-11eb-88ac-f28b02c44aa0.png)

Imagem com tela reduzida:

![image](https://user-images.githubusercontent.com/22710963/110633258-50237080-8187-11eb-9908-b79b42c46b81.png)

**Comment by jhonyeduardo** [comment]
Bom dia @sganzerla 

Obrigado pela sugestão, vamos avaliar e adicionarmos em nosso backlog.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
