### ISSUE TITLE
po-table: p-show-more-disabled não aceita valor boolean com modo strict ativado

### ISSUE THREAD

**Issue by lucasbmeister** [po-ui/po-angular#810]
#### Reprodução

Código para reprodução do problema: https://stackblitz.com/edit/po-ui-sm7pf2

Não foi possível encontrar o mesmo comportamento no stackblitz, talvez pela forma que a ferramenta faz a checagem dos erros. Foi tentado aplicar as configurações dos arquivos tsconfig e angular.json mas não surtiram efeito para simular o problema.

Passos para reproduzir:
1. Iniciar um novo projeto seguindo os passos do guia: https://po-ui.io/guides/getting-started, ativando a checagem estrita de tipos no passo de instalação dos pacotes:
![image](https://user-images.githubusercontent.com/28509411/110841252-6d8a3480-8284-11eb-8c39-5385540180cf.png)
2. Instalar os templates: **ng add @po-ui/ng-templates**
3. Gerar um componente com o seguinte schematic: **ng generate @po-ui/ng-components:po-page-list** com o componente de listagem **po-table**.
4. No template do componente recém criado, no po-table, adicionar o atributo [p-show-more-disabled]="true"
5. **[EDIT]** No meu ambiente do vscode possuo a extensão https://marketplace.visualstudio.com/items?itemName=Angular.ng-template que utiliza o LS oficial do Angular para checagem de erros. Percebi (após abrir a issue) que o erro só é identificado em tempo de edição ativando os recursos de checagem baseados no Angular Ivy:

![image](https://user-images.githubusercontent.com/28509411/110847263-792d2980-828b-11eb-9eb5-5c876ef0dc63.png)

6. Tentar realizar o build ou executar ng serve. Será apresentado o erro abaixo:

![image](https://user-images.githubusercontent.com/28509411/110844526-46cdfd00-8288-11eb-8371-27271ca83d64.png)

#### Qual o comportamento atual?
Ao tentar realizar o bind de uma variável ou um valor boolean ao atributo **p-show-more-disabled**, a checagem de tipos entende que existe um erro pois está sendo atribuído um valor boolean quando é esperado uma string:

![image](https://user-images.githubusercontent.com/28509411/110843359-f4401100-8286-11eb-9941-3acfe294b139.png)

A checagem de tipos está correta em apresentar o erro pois, o método set deste atributo espera apenas valores do tipo string:

![image](https://user-images.githubusercontent.com/28509411/110843520-25b8dc80-8287-11eb-9b02-125418f4cd79.png)

#### Que comportamento você esperava ver?
Espera-se que seja possível a atribuição valores boolean da mesma forma que o atributo **p-selectable**:

![image](https://user-images.githubusercontent.com/28509411/110843767-6c0e3b80-8287-11eb-80c9-b2e247b1088d.png)

É importante salientar que olhando a origem deste erro, foi notado que mais parâmetros do po-table podem sofrer do mesmo problema.

#### Ambiente

- PO UI: ^4.9.0
- Angular: ~11.2.5
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa dia @lucasbmeister 

Obrigado por reportar esta situação, vamos avaliar para resolver assim que possível, obrigado.

**Comment by CaioKretzer** [comment]
Eu estou passando pela mesma situação. Vi que a Issue foi fechada.
