### ISSUE TITLE
class SharedModule Appears in the NgModule.imports of CustomersModule, but itself has errors(-996002)

### ISSUE THREAD

**Issue by erivaltonoliveira** [po-ui/po-angular#812]
#### Reprodução
![image](https://user-images.githubusercontent.com/56845297/110857793-06767b00-8298-11eb-8e22-b86a1755b4bc.png)

#####shared.module.ts#####
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { PoModule } from '@po-ui/ng-components';
import { PoTemplatesModule } from '@po-ui/ng-templates';

@NgModule({
  imports: [
    CommonModule,
    FormsModule,
    PoModule,
    PoTemplatesModule
  ],
  exports: [
    CommonModule,
    FormsModule,
    PoModule,
    PoTemplatesModule
  ]
})
export class SharedModule { }

#################################################################

#### Ambiente

- PO UI: 4.9.0
- Angular: 11.2.5
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @erivaltonoliveira 

Este não é um problema do PO UI, e sim do seu projeto ANGULAR.

Qualquer dúvida estou a disposição.
