### ISSUE TITLE
Drag and Drop no CheckBox Group / Columns Mangaer - Gerenciador de Colunas Permitir ordenação.

### ISSUE THREAD

**Issue by wgcostta** [po-ui/po-angular#817]
#### Descrição da melhoria
Ser possível que o usuário reordene as colunas pelo Gerenciador de Colunas. No componente: po-table-column-manager, sendo implementado no po-checkbox-group, sendo assim seria reaproveita nos dois componentes e disponibilizando um campo com o index de posição, para que seja possível passar tanto via storage como via columns a ordem padrão e o usuário reordenar e podermos gravar a ordenação realizada via diretiva.

#### Caso de uso
Diferentes clientes, e até mesmo diferentes usuários dentro de um mesmo cliente (TOTVS), possuem preferências diferentes de visualização das consultas.
Com base nisso, verificar a possibilidade de evoluir o gerenciador de colunas para permitir alterar não somente quais campos serão visíveis, mas também a ordenação dos mesmos.

#### Informações adicionais
No angular existe o Drag and Drop, conforme mostra no link da DevMedia: 
https://www.devmedia.com.br/novidades-do-angular-7/40194

Verificar possibilidade de aplicar o mesmo nos componentes citados para que o usuário TOTVS/Agro possa utilizar.

![image-2021-03-16-09-39-11-056](https://user-images.githubusercontent.com/39952575/111467087-cf262500-8702-11eb-908b-ffc377627f0d.png)

**Comment by jhonyeduardo** [comment]
Boa noite @wgcostta 

Obrigado pela sugestão, anotamos aqui e vamos incluir em nosso backlog.

**Comment by saravando** [comment]
Bom dia!

Jhony, 

Tudo bem?

Sou PO da controladoria e estamos desenvolvendo uma ferramenta muito importante que se chama conciliador contábil e precisamos desta feature no produto, temos um prazo previsto para essa liberação?

Atenciosamente, 
Diogo Vieira

**Comment by alinelariguet** [comment]
Boa tarde @wgcostta, a funcionalidade de ordenação de colunas pelo gerenciador já está disponível a partir da v6.13.0.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
