### ISSUE TITLE
Po-Select: não inicia com valor de variável, apenas com valor fixo

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#824]
#### Descrição da melhoria
Bom dia. Utilizamos o Po-Select em nossa aplicação para a seleção de contratos de empresas. Quando há somente 1 contrato, tentamos fazer ele inicializar já marcado no combo, porém ele não consegue iniciar com valor de variável. Fizemos o teste e com variáveis fixas funciona. 

#### Caso de uso
Permitiria iniciar já o select com valor marcado para facilitar a usabilidade e gerar praticidade.

#### Informações adicionais
Trazer este campo preenchido por variável.
![image](https://user-images.githubusercontent.com/58361652/112465944-08cedf80-8d44-11eb-8c3d-66454e022a4c.png)

O detalhe é que ele não apresenta o contrato que foi setado para inicializar no select, mas ele está com valor do contrato atribuído e faz a pesquisacorretamente.

**Comment by jhonyeduardo** [comment]
Boa tarde @EduardaDalmas 

Consegue nos passar um ambiente do que esta tentando fazer? https://stackblitz.com/edit/po-ui

Veja se você esta carregando a lista de opções antes de atribuir o valor.

Obrigado.

**Comment by EduardaDalmas** [comment]
Oi, coloquei a lógica que estou fazendo, claro que não conectei minha API então não funciona. Não há nenhum exemplo na documentação de vocês com valores que não sejam fixos. O select consegue pegar o valor mas não apresenta o label dentro do select ao iniciar.

https://po-ui-aobw8p.stackblitz.io

**Comment by jhonyeduardo** [comment]
Olá,

O exemplo não esta funcionando.

Faça um teste atribuindo o valor para o PoSelect após carregar as opções.

**Comment by EduardaDalmas** [comment]
Oi, sim não funciona pois eu expliquei que não conectei a minha API. O valor fixo eu sei que funciona, lhe enviei meu código pra ver o lógica que fiz...

**Comment by EduardaDalmas** [comment]
Bom dia. Aqui está a url do modelo padrão funcionando. Eu preciso saber como fazer para pegar um valor variável, que não esteja fixo no código fonte.

https://stackblitz.com/edit/po-ui-m2t7wm?file=src/app/app.component.ts
https://po-ui-m2t7wm.stackblitz.io
https://po-ui-m2t7wm.stackblitz.io

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

Pelo que entendi, você quer definir o valor no PoSelect após sua API retornar os dados para o p-options.

Para isso, você terá que atribuir os valores para o p-options e depois atribuir o valor para o PoSelect.

ex: 
```
opcaoSelecionada: any;
options: Array<PoSelectOption>;

  ngOnInit() {
     this.api.subscribe(response => {
         this.options = reponse.items;
    
    
        this.opcaoSelecionada = this.options[0].value;
    }
  }



```

**Comment by EduardaDalmas** [comment]
Vou testar isso, obrigada pelo auxílio.

**Comment by jhonyeduardo** [comment]
Certo, neste caso @EduardaDalmas vamos precisar de um cenário com o problema ocorrendo para verificar.

Você pode usar no API para exemplo, http://po-sample-api.herokuapp.com/v1/heroes.

Ficamos no aguardo.

**Comment by EduardaDalmas** [comment]
https://stackblitz.com/edit/po-ui-m2t7wm?file=src/app/app.component.html
tentei reproduzir aproximadamente o que eu fiz. Não vem com a seleção aparecendo e este é o problema que está ocorrendo

**Comment by jhonyeduardo** [comment]
Boa noite @EduardaDalmas 

Segue um exemplo com os dados que me passou, https://stackblitz.com/edit/po-ui-uvxfp2

Aparentemente é algum problema que você tenha relacionado ao Angular e não ao componente, caso precise de mais suporte, pode utilizar https://github.com/po-ui/po-angular/discussions ou até mesmo entrar em alguma comunidade e solicitar apoio, https://github.com/po-ui/po-angular/issues/439.
