### ISSUE TITLE
PO Page List: Ao realizar uma busca rápida pelo PO Page List e remover o po-disclaimer do filtro o campo de texto de busca ainda fica preenchido.

### ISSUE THREAD

**Issue by leonardosimoura** [po-ui/po-angular#827]
#### Reprodução
Ao realizar uma busca rápida pelo PO Page List e remover o po-disclaimer do filtro  o campo de texto de busca ainda fica preenchido.

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.
**É possível reproduzir pelo próprio portal** 

Passos para reproduzir:
1. Acessar: https://po-ui.io/documentation/po-page-list
2. No sample: PO Page List - Hiring Processes
3. Realize uma busca pelo campo de texto (busca rápida)
4. Remova o filtro aplicado
5. Com isso o campo de texto ainda fica com o valor informado dando uma falsa impressão de filtro.

#### Qual o comportamento atual?
Ao realizar uma busca rápida pelo PO Page List e remover po-disclaimer do filtro  o campo de texto de busca ainda fica preenchido.

#### Que comportamento você esperava ver?
Após remover o disclaimer do filtro o campo de texto ser limpo.

#### Ambiente

- PO UI: 4.10.1
- Angular: 11
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [x] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Olá @leonardosimoura, 
vamos analisar e adicionar este item em nosso backlog, obrigado.

**Comment by jhonyeduardo** [comment]
Bom dia @leonardosimoura 
Na versão 4.16.0 liberamos o método *clearInputSearch*, responsável por limpar o campo de busca.

Agora é possível limpar o campo, conforme a necessidade, qualquer dúvida estou a disposição, obrigado!
