### ISSUE TITLE
<po-page-dynamic-table>: removeAll duplicando opção de Excluir

### ISSUE THREAD

**Issue by EdrianGolob** [po-ui/po-angular#832]
#### Reprodução
![image](https://user-images.githubusercontent.com/53577431/113298117-da1bb080-92d1-11eb-9f3c-820a511b246a.png)
![image](https://user-images.githubusercontent.com/53577431/113298194-f1f33480-92d1-11eb-9fa5-16cb8050bcd7.png)

Passos para reproduzir:
1. Criar uma po-page-dynamic-table
2. Acrescentar os actions do componente [p-actions]="actions"
3. definir e acrescentar o action Padrão removeAll
4.  actions:PoPageDynamicTableActions = {
      removeAll: true,
    };

#### Qual o comportamento atual?
Quando a API REST retorna dados corretamente alimentando a tela, aparecem 2 botões "Excluir"  com as mesmas funções. Quando ocorre algum erro na API-REST e não é retornado nenhuma informação, a tela apresenta apenas 1 botão Excluir.

#### Que comportamento você esperava ver?
Apenas 1 botão de excluir criado na tela.

#### Ambiente

- PO UI: 4.8.0
- Angular: 11.0.9
- Browser(s):
  - [X ] Chrome
  - [ X] Firefox
  - [ X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [ X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @EdrianGolob 

Vamos avaliar o item e adicionar em nosso backlog, obrigado.

**Comment by jhonyeduardo** [comment]
@EdrianGolob consegue simular este problema no ambiente https://stackblitz.com/edit/po-ui-cuf1oo?

Ficamos no aguardo, obrigado.

**Comment by jhonyeduardo** [comment]
Issue fechada por falta de reprodução.
