### ISSUE TITLE
Botão reenviar do po-upload

### ISSUE THREAD

**Issue by seijibr** [po-ui/po-angular#848]
Não é possível ter controle sobre o botão reenviar do arquivo para remover por exemplo.

![Screenshot_6](https://user-images.githubusercontent.com/57536220/115074638-5ddbbc80-9ed0-11eb-92a9-0b92fa54310f.png)

**Comment by jhonyeduardo** [comment]
Bom dia,
Por favor, nos  passar mais informações.

Como você está utilizando?
Para que você precisa desta funcionalidade?
Qual controle você deseja?

**Comment by seijibr** [comment]
Quero utilizar junto com o po-progress só que quando ocorre um erro em algum upload e tento reenviar não tenho como saber apenas quais arquivos deram erro e com isso para não quebrar a progress o ideal seria remover o envio unitário. 
O currentFiles sempre retorna tudo que está em exibição e não encontrei alguma documentação também para remover da lista tudo que já fez o upload com sucesso. 

Então precisaria ajustar de um dos dois lados, ou recuperar apenas os arquivos que falharam ou remover o botão de renviar unitário.
