### ISSUE TITLE
BarChart: Ordenamento das Categories por tamanho de string e não em ordem alfabetica

### ISSUE THREAD

**Issue by dycorrales** [po-ui/po-angular#851]
#### Reprodução

https://stackblitz.com/edit/po-ui-zktybd?file=src/app/app.component.ts
https://po-ui-zktybd.stackblitz.io

Passos para reproduzir:
1. Criar um Chart de tipo Bar
2. Inserir as Categories em Ordem alfabetica

#### Qual o comportamento atual?
Mesmo criando um array string das categories em ordem alfabetico, no momento de visualizar o chart na tela ele as reordena de maior tamanho de carateres para menor tamanho de caracteres o que traz como consequencia que se temos os dados ordenamos junto com as categories, os dados não batam com a categoria no momento da visualização.

#### Que comportamento você esperava ver?
Ordenar categories alfabeticamente e não por tamanho de string

#### Ambiente

- PO UI: 4.14.0
- Angular: 11.1.1
- Browser(s):
  - [X] Chrome
  - [X] Firefox
  - [X] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Olá @dycorrales 

Obrigado pela abertura da issue, vamos avaliar a situação e adicionar em nosso backlog, obrigado.

**Comment by jhonyeduardo** [comment]
Bom dia @dycorrales 

Correção realizada na versão [5.10](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#5100-2021-08-23),
Qualquer dúvida estamos a disposição.
