### ISSUE TITLE
po-menu: Mapeamento de acordo com a rota

### ISSUE THREAD

**Issue by seijibr** [po-ui/po-angular#852]
#### Reprodução
1 - Instalar versão 4.8.0
![Screenshot_1](https://user-images.githubusercontent.com/57536220/115759831-142f1e00-a377-11eb-923e-c284e4bffc17.png)

2 - Subir o server e verificar que o menu é posicionado no item de menu de acordo com a rota
![Screenshot_3](https://user-images.githubusercontent.com/57536220/115759934-3163ec80-a377-11eb-8ba9-282223101acf.png)

3 - Apagar a node_modules e instalar a versão 4.13.0
![Screenshot_2](https://user-images.githubusercontent.com/57536220/115760021-4771ad00-a377-11eb-8193-5c534fd13bb0.png)

4 - Subir o server e verificar que o menu **não** é posicionado no item de menu de acordo com a rota
![Screenshot_4](https://user-images.githubusercontent.com/57536220/115760125-5e180400-a377-11eb-8a97-a986bc01fc72.png)

#### Qual o comportamento atual?
Na versão mais recente não posiciona no item do menu de acordo com a rota

#### Que comportamento você esperava ver?
Posicionar no item do menu de acordo com a rota

#### Ambiente

- PO UI: 4.13.0
- Angular: 11.2.5
- Browser(s):
  - [ x] Chrome
  - [x ] Firefox
  - [ x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Olá Seijibr,

Você consegue nos passar como esta a estrutura do seu projeto, de forma básica, para que possamos simular o problema?

Caso preferir pode utiliazar o stackblitz para isso, 
ficamos no aguardo, obrigado!

**Comment by seijibr** [comment]
Segue a estrutura de execução da navegação: 

![Screenshot_9](https://user-images.githubusercontent.com/57536220/116105274-89f0fd80-a687-11eb-89ce-84b0eac84645.png)

![Screenshot_10](https://user-images.githubusercontent.com/57536220/116105288-8d848480-a687-11eb-8904-c18a7ff8e296.png)

![Screenshot_11](https://user-images.githubusercontent.com/57536220/116105302-91180b80-a687-11eb-8703-e0c5c475e9de.png)
