### ISSUE TITLE
ng add @po-ui/ng-components  :  Package Installation failed

### ISSUE THREAD

**Issue by enakamatu** [po-ui/po-angular#856]
Windows 10 
Node 16

O comando de instalação gera o erro da imagem em anexo, consegui continuar apenas após instalar versão anterior do node.
npm i -g npm@6

![image](https://user-images.githubusercontent.com/6952231/115968655-44112980-a50f-11eb-881e-295e7ffde11a.png)

**Comment by jhonyeduardo** [comment]
Bom dia @enakamatu 

Obrigado pela abertura desta issue, vamos avaliar para corrigir a situação.

**Comment by jhonyeduardo** [comment]
Bom dia @enakamatu 

Problema resolvido, dependências atualizadas com a v12 do Angular

Obrigado!
