### ISSUE TITLE
po-page-slide: Hide Close Button

### ISSUE THREAD

**Issue by seijibr** [po-ui/po-angular#858]
Passos para reproduzir:
1. Deixar o p-hide-close="false"
![Screenshot_5](https://user-images.githubusercontent.com/57536220/116104058-86a94200-a686-11eb-9870-ab3ffd0895fd.png)

2. Abrir o pageSlide
![Screenshot_6](https://user-images.githubusercontent.com/57536220/116104126-945ec780-a686-11eb-821b-fe5e5c127e17.png)

3. Deixar o p-hide-close="true"
![Screenshot_7](https://user-images.githubusercontent.com/57536220/116104187-a0e32000-a686-11eb-8c3c-310902f0632e.png)

4. Abrir o pageSlide
![Screenshot_8](https://user-images.githubusercontent.com/57536220/116104246-aa6c8800-a686-11eb-907b-6af1f7d9b1f8.png)

#### Qual o comportamento atual?
Utiliando a propriedade p-hide-close="boolean" tanto true como false não tem efeito no componente

#### Que comportamento você esperava ver?
Utilizar o p-hide-close="true" para remover o botão fechar do pageSlide

#### Ambiente

- PO UI: Site e versão 4.8.0
- Angular:  Site e 11
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Olá @seijibr 

Neste exemplo não funcionou, porque o "Click out" deve estar selecionado, conforme explica a documentação do "p-hide-close-button".

Qualquer dúvida estou a disposição.
