### ISSUE TITLE
Data inicial Po-calendar

### ISSUE THREAD

**Issue by knoonrx** [po-ui/po-angular#859]
Na aplicação que estou desenvolvento eu defino a max-date e min-date e funciona muito bem. A minha sugestão é que ao selecionar o min e max-date, o calendário exibisse em foco a primeira data disponível e não a data atual.

Quando o usuário seleciona um range de dates, o calendário deve ir para a primeira data disponível (dia/mês) e não a data atual.

Obrigado :)

**Comment by jhonyeduardo** [comment]
Olá @knoonrx 

Obrigado pela sugestão, vamos anotar e incluir em nosso backlog, obrigado!

**Comment by jhonyeduardo** [comment]
Olá @knoonrx 

Melhoria lançada na versão [5.11.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md#5110-2021-08-30), obrigado!
