### ISSUE TITLE
Virtual scroll no componente po-table

### ISSUE THREAD

**Issue by victorcmps** [po-ui/po-angular#861]
#### Descrição da melhoria
Quando o componente po-table é utilizado com uma grande massa de dados, o navegador acaba consumindo bastante memória RAM e CPU por conta da quantidade de elementos que ele precisa renderizar no scroll da tabela. Adicionando um virtual scroll nesse componente, o navegador só vai renderizar o que estiver no viewport da tabela. 

#### Caso de uso
Essa melhoria permite trabalhar com qualquer quantidade de linhas na tabela, auxiliando bastante na performance dos produtos. Ela também remove uma limitação que temos hoje para desenvolver alguns produtos dentro da TOTVS que utilizem uma grande quantidade de dados.

#### Informações adicionais
Acredito que seja possível utilizar o virtual scroll também em outros componentes que tenham scroll infinito, por exemplo o po-lookup.

**Comment by jhonyeduardo** [comment]
Olá @victorcmps 

Muito obrigado pela sugestão, realmente o Virtual Scrolling é uma feature muito importante, vamos adicionar com carinho em nosso backlog, para que quando possível implementa-la.

Lembrando contribuição é sempre bem vindo, estamos com uma equipe enxuta e roadmap desafiador, fica a dica ;)
https://po-ui.io/guides/development-flow

Obrigado

**Comment by victorcmps** [comment]
Bom dia!

Bacana @jhonyeduardo, assim que as coisas ficarem mais tranquilas por aqui, com certeza espero poder colaborar com a biblioteca.

Obrigado!

**Comment by alinelariguet** [comment]
Boa tarde @victorcmps, esta funcionalidade já foi implementada e está disponível a partir da v6.12.0.
Att.
