### ISSUE TITLE
Formatação BRL padrão no input do tipo currency - Dynamic Form

### ISSUE THREAD

**Issue by mauromattos00** [po-ui/po-angular#862]
#### Descrição da melhoria
Um dos tipos de input do [Po Dynamic Form](https://po-ui.io/documentation/po-dynamic-form) é o `currency`. A formatação padrão do campo é a americana, mostrada abaixo. Para que sejam adicionados centavos, o usuário deve digitar manualmente (inserindo vírgula e os valores em seguida).

![po-dynamic-form-currency](https://user-images.githubusercontent.com/13375865/117018392-d4e3c400-acca-11eb-818b-3375d3cc7835.gif)

Acredito que a maioria das implementações que utilizam o PO UI devem utilizar o padrão BRL, e acredito que possa ser uma boa melhoria a implementação da formatação BRL __por padrão__ (inserção dos centavos sem a necessidade de digitar vírgula).

**Comment by jhonyeduardo** [comment]
Bom dia @mauromattos00 

A questão de inserir a virgula para informar o centavos é um comportamento do componente e não relacionado a moeda.

a moeda padrão é recebida da linguagem browser.

Neste caso, qual seria sua sugestão para a virgula?

https://po-ui.io/documentation/po-decimal

Obrigado.

**Comment by mauromattos00** [comment]
Olá @jhonyeduardo

Eu pensei em um comportamento onde, no caso do locale pt-BR, a inserção da vírgula nos centavos fosse inserida automaticamente, assim como nos casos dos milhares.
 
Pelo que pude perceber, apenas o ponto nos milhares são inseridos automaticamente e a vírgula para os centavos deve ser inserida manualmente.

**Comment by alinelariguet** [comment]
Boa tarde @mauromattos00
No caso, verifique o po-input, nele é possível colocar uma máscara. Veja se isso resolve para você.
Atenciosamente.
