### ISSUE TITLE
<po-table>: <p-striped não funciona em linhas específicas>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#868]
#### Reprodução

https://stackblitz.com/edit/po-ui-cr8vtz?file=src/app/app.component.html

Passos para reproduzir:
1. Ao acessar a tabela, o p-striped não está funcionando quando configuro para apenas algumas linhas;
2. Tentei utilizar os componentes adicionais como o table-cell-template, o table-row-template e o table-column-template para aplicar uma lógica que sendo verdadeira, deixa uma linha específica de outra cor, porém não funciona. 

#### Qual o comportamento atual?
O po-striped não está funcionando se configurado para apenas algumas linhas.

#### Que comportamento você esperava ver?
Que ao aplicar a lógica e o parâmetro ficasse verdadeiro, o stripped alterasse a cor da linha

#### Ambiente

- PO UI: 4.10.1
- Angular: 10.1
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

O link enviado de reprodução não esta com erro.

O striped é "automático" não é possível aplicar quando desejar, ele faz striped em uma linha sim, outra não.

Qualquer dúvida estou a disposição.

**Comment by EduardaDalmas** [comment]
Obrigada pela atenção e pelo esclarecimento.

Ótima semana.
