### ISSUE TITLE
PoPageDynamicEditComponent: Duvida de como carregar valor default em um input

### ISSUE THREAD

**Issue by PauloPenalva** [po-ui/po-angular#870]
Olá, sou iniciante em Angular e na PO UI
Estou iniciando um formulário a partir de um metadata e gostaria de saber como carregar input com valor default ?

#### Ambiente

- PO UI: 4.15
- Angular: 11.2.10
- Browser(s):
  - [X] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [X] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @PauloPenalva 

Atualmente não temos esta funcionalidade no componente, vamos adicionar esse item em nosso backlog, obrigado.

**Comment by PauloPenalva** [comment]
Obrigado pelo retorno @jhonyeduardo

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
