### ISSUE TITLE
po-widget com po-page-dynamic-search

### ISSUE THREAD

**Issue by Evertonpx** [po-ui/po-angular#871]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. Estou utilizando po-widget com po-page-dynamic-search e as informações do po-widget não ficam posicionadas corretamente na tela.
2. 

#### Qual o comportamento atual?
https://prnt.sc/12ubpab
https://prnt.sc/12ubzcx

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @Evertonpx 

você tem exemplo do fonte que esta utilizando?

Veja um exemplo que criei, bem simples com po-widget dentro do page-dynamic-search, https://stackblitz.com/edit/po-ui-xpahsf

**Comment by Evertonpx** [comment]
Bom dia, segue exemplo

<div class="po-wrapper">
  <po-toolbar p-title="Menu"></po-toolbar>

  <po-menu [p-menus]="menus"></po-menu>

  <po-widget class="po-lg-3 po-mt-2" p-height="200" p-primary="true" p-primary-label="Details" p-title="Total savings">
    <div class="po-font-subtitle po-text-center">$5.000,00</div>
    <div class="po-text-center">Last updated at 18:34</div>
  </po-widget>

  <po-page-dynamic-search p-title="Po Page Dynamic search" [p-filters]="[{ property: 'name' }]">
  </po-page-dynamic-search>

</div>

**Comment by Evertonpx** [comment]
Segue exemplo do fonte

https://prnt.sc/131f4fv

**Comment by jhonyeduardo** [comment]
@Evertonpx 

O po-widget tem que ficar dentro do PoPageDynamicSearch

**Comment by jhonyeduardo** [comment]
Qualquer dúvida estou a disposição
