### ISSUE TITLE
po-upload: Não abre a caixa de diálogo sem um ngModel

### ISSUE THREAD

**Issue by jota-oliveira** [po-ui/po-angular#872]
#### Reprodução

Usar o po-upload com form reativo. Sem o ngModel ele não funciona.
Verificar o comportamento no próprio portal, alguns casos estão funcionando outros não.

- PO UI: 4.15
- Angular: 11.2.12
- Browser(s):
  - [ x] Chrome
  - [ x] Firefox
- Operating System:
  - [ x] Windows
  - [x ] Ubuntu

**Comment by jhonyeduardo** [comment]
Bom dia @jota-oliveira 

Você quer dizer, que não abre a caixa de dialogo porque esta desabilitado, certo?
O botão "Selecionar arquivo" ele é habilitado ao possuir a propriedade "p-url".

Sobre casos semelhantes no portal que você comentou, sabe me dizer qual exemplo para a gente verificar?

Obs: Nós estamos com um problema que é o sucesso de envio dos arquivos, por que não migramos a API usada no exemplo do upload ainda.

**Comment by frnndluc** [comment]
O mesmo erro está acontecendo comigo, onde o gerenciador de arquivos não está sendo aberto para o usuário quando `ngModel` não está informado no componente `po-upload`.

Observei que o erro descrito também ocorre no portal do PO-UI, conforme imagem abaixo:

![Imagem de erro exibido no console após click no componente po-upload](https://i.ibb.co/JzVRDKr/erro-versao-4-17.png)

Acredito que o erro esteja associado a última alteração do componente, que pode ser observada [nesse commit](https://github.com/po-ui/po-angular/commit/f7d6a00c#diff-7080dc0e559dffbb7d7489c3de98e0d6c80b605ddf837623a99c2e30d0253065). 

Fico à disposição para mais informações.

**Comment by jhonyeduardo** [comment]
Muito obrigado @frnndluc , realmente consegui simular o problema.

Vamos corrigi-lo assim que possível @jota-oliveira @frnndluc, obrigado!

**Comment by jhonyeduardo** [comment]
Bom dia,

item resolvido na v5.0.0,

Obrigado
