### ISSUE TITLE
po-chart: Chart não é exibido dentro de um accordion

### ISSUE THREAD

**Issue by JuAintablian** [po-ui/po-angular#874]
Reprodução:
https://po-ui-eofjvg.stackblitz.io

#### Qual o comportamento atual?
Tendo o po-chart dentro de um po-accordion, ao abrir o accordion, os dados do chart não são carregados.
No stackblitz, ao aumentar/diminuir a aba do navegador, os dados são exibidos.
No meu projeto, o accordion fica em branco e ao passar o mouse em algum popover, o chart com os dados são exibidos.

#### Que comportamento você esperava ver?
Ao abrir o accordion, o chart ser exibido com os dados automaticamente

#### Ambiente

- PO UI: 4.16.0
- Angular: 11.2.13
- Browser(s):
  - [ ] Chrome
  - [x] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @JuAintablian 

Vamos adicionar esse item em nosso backlog e avaliar assim que possível, obrigado!

**Comment by jhonyeduardo** [comment]
Bom dia,

item resolvido na  v5.0.0,

Obrigado
