### ISSUE TITLE
po-upload: Problema Drag Drop

### ISSUE THREAD

**Issue by cmregazzo** [po-ui/po-angular#879]
#### Qual o comportamento atual?
Ao tentar usar o Drag Drop do po-upload, arrastando diretamente uma mensagem (.msg) do Outlook para a area de upload de arquivos, o arquivo não é carregado e a pagina fica "congelada".

#### Que comportamento você esperava ver?

O arquivo deveria aparecer disponível para upload.

Segue link para download do video demonstrando o problema citado acima:

https://1drv.ms/v/s!AiJ2ao8amUNvgiFH4MrNxW296dTu?e=lGgKCy

#### Ambiente

- PO UI:  V4.16.1
- Angular: 12.0.1
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros

- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom tarde @cmregazzo 

O componente não tem esta funcionalidade habilitada, você precisa fazer o download do arquivo.

**Comment by cmregazzo** [comment]
Boa Tarde @jhonyeduardo ,

Obrigado pelo feedback.

Se vocês fizeram um teste do Outlook para o OneDrive, funciona perfeitamente.

Obrigado.

**Comment by jhonyeduardo** [comment]
Mas neste caso são ambientes que estão "interligados", são da Microsoft, neste caso não temos tratamento, não esta homologado pra tal função.

Para funcionar corretamente será necessário baixar o arquivo e arrasta-lo.

Qualquer dúvida estou a disposição.

**Comment by cmregazzo** [comment]
Boa Tarde @jhonyeduardo,

Obrigado pelo feedback.

Quando citei o OneDrive seria a interface Web via navegador.

Mas tem um site que usa Angular, e funciona o drag and drog diretamente do Outlook (.msg) para a página.

Segue link do mesmo:

https://angular-drag-n-drop-directive.stackblitz.io

Obrigado

**Comment by alinelariguet** [comment]
Essa issue será analisada e assim que possível retornaremos o contato.

**Comment by rafaellmarques** [comment]
Bom dia @cmregazzo , tudo bem?
Estamos analisando essa issue mas antes de prosseguir precisamos saber se essa questão ainda se faz necessária.
Ficamos no aguardo.

Att.

**Comment by alinelariguet** [comment]
Por falta de interação estamos fechando esta issue. Caso necessário abrir uma nova issue.
