### ISSUE TITLE
notification-service: atributo duration é ignorado caso exista o actionLabel no método 

### ISSUE THREAD

**Issue by guiworks** [po-ui/po-angular#884]
Demo:
```
this.poNotificationService.information({
          action: () => this.accountLogModal.open(),
          actionLabel: translate('common.seeMore'),
          duration: 20000,
          message: translate('account.errorLogImport'),
        });
```

Qual o comportamento atual?
Caso eu insira o atributo actionLabel dentro desse objeto, o 'duration' é ignorado e a notificação só é fechada caso eu clique na mensagem.

Que comportamento você esperava ver?
A duração funcionando corretamente ao configurar no método warning/info/danger, etc.
E se possível ter um ícone (X) depois da action sendo habilitado por input true/false a ser exibido para leigos. (sugestão)

Ambiente
PO UI: 4.10.0
Angular: 11.2.00
Browser(s):
 Chrome
 Firefox
 Edge
 Safari
 IE 11
 Outros
Operating System:
 Windows
 macOS
 Ubuntu
 Outros

**Comment by jhonyeduardo** [comment]
Bom dia @guiworks 

Atualmente o PoNotificationService respeita a duração, caso não possuir uma ação, portanto é um comportamento do componente mesmo.

Vou adicionar em backlog para avaliar em conjunto com a equipe de UX para avaliar esta sugestão, obrigado!

**Comment by alinelariguet** [comment]
Foi avaliado em conjunto com a equipe de UX e o comportamento foi mantido.
