### ISSUE TITLE
po-loockup / po-page-dynamic-search: disclaimers sem formatação

### ISSUE THREAD

**Issue by caiosantosf** [po-ui/po-angular#890]
#### Reprodução

https://stackblitz.com/edit/po-ui-ehezfw

Passos para reproduzir:

1. Abra o Loockup e escolha os dois filtros avançados
2. Abra os filtros avançados do dynamic search e escolha os dois filtros.
3. Observar na lista de disclaimers a formatação

#### Qual o comportamento atual?

Precisei utilizar em num projeto o Loockup e o Page Dynamic Search, observei que a lista de disclaimers dos dois apresentam um erro e uma diferença.

Quando uso um filtro do tipo currency ele aparece no disclaimer como um numero sem formatação, isso tanto no Loockup quanto no Page Dynamic Search.

Quando uso um filtro de options (select) mostra no disclaimer do Loockup o value da opção escolhida, já no Page Dynamic Search aparece o label.

No Loockup tambem não mostra no disclaimer o titulo do filtro utilizado.

![image](https://user-images.githubusercontent.com/14207713/119881865-22d39c80-bf04-11eb-8937-1f5ae3a829ad.png)

![image](https://user-images.githubusercontent.com/14207713/119881972-4565b580-bf04-11eb-93f4-464d648c7276.png)

#### Que comportamento você esperava ver?

Filtros do tipo currency mostrar formatados no disclaimer e filtro do tipo options mostrar o label no disclaimer.

Outra questão é que no dynamic search eu consigo colocar um initValue para o filtro já trazer um valor default na lista de disclaimers usando a interface PoPageDynamicSearchFilters, já no Loockup essa opção não funciona.

https://stackblitz.com/edit/po-ui-gmf4bu

#### Ambiente

- PO UI: 4.4.0
- Angular: 11.1.1
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [ ] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by caiosantosf** [comment]
Outra questão é que no dynamic search eu consigo colocar um initValue para o filtro já trazer um valor default na lista de disclaimers, já no Loockup essa opção não funciona.

https://stackblitz.com/edit/po-ui-gmf4bu

**Comment by jhonyeduardo** [comment]
Bom dia @caiosantosf 

Obrigado pela issue, vamos adicionar este item em nosso backlog, obrigado.
