### ISSUE TITLE
Page-login: propriedade "p-recovery" sem definição de código de retorno para erro

### ISSUE THREAD

**Issue by joaojorge891** [po-ui/po-angular#892]
boa tarde,

Estou usando a modal pronta de recuperação de senha através da propriedade p-recovery. Em caso de envio de endereço de e-mail válido para o backend retorna ok, pois inseri o código de retorno 204. O problema seria se o usuário inserir um e-mail inválido e enviar para o backend, não está tendo nenhuma ação, pois não sei ao certo qual código de erro devo mandar o backend retornar. Já tentei vários (400, 401, 500) sem sucesso. Procurei na documentação consta somente o caso de sucesso (204), o caso de erro não consta (se há, não consegui encontrar). Peço apoio de vocês.

html:

<po-page-login

    (p-login-submit)="onLogin($event)" 
    p-register-url="new-register" 
    p-logo="./assets/oi-logo-a3.png"
    p-product-name="Portal de Operações B2B" 
    [p-literals]="customLiterals" 
    [p-recovery]="pwdRecovery">
    
</po-page-login>

.ts:

pwdRecovery: PoPageLoginRecovery = {
    url: 'http://localhost:8081/api/users/resetPwd',
    contactMail: 'ld-portalB2B@oi.net.br',
    type: PoModalPasswordRecoveryType.Email
  }

user.route:

resetPwd: function (req, res) {
        var document = controller.findByMail(req.body.email)
        document.then(result => {
            if (result.status === 'ok') {
                res.sendStatus(204)
            } else {
                res.sendStatus(400)
            }

        })
    }

user.controller:

exports.findByMail = async function (email) {

    let filter = {}
    filter['email'] = { '$eq': email }
    var user = await userSchema.find(filter)
    if (user != null && user != undefined && user != '') {
        sendMail.sendMailPwdRecovery(user)
        return { status: 'ok' }

    } else {
        return { status: 'error' }
    }

}

**Comment by jhonyeduardo** [comment]
Boa tarde @joaojorge891 

Assim que possível vamos avaliar esta situação, obrigado.

**Comment by alinelariguet** [comment]
Boa tarde @joaojorge891,
Nesse caso como você usa o recovery integrado ao po-page-login, seria interessante você utilizar o po-http-interceptor para dar um feedback ao usuário, caso você queira também pode implementar os componentes separadamente, nesse caso o componente po-modal-password-recovery.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
