### ISSUE TITLE
Melhoria na visualização do po-dynamic-view

### ISSUE THREAD

**Issue by NixonAzeredo** [po-ui/po-angular#898]
#### Reprodução

Apresentação do po-dynamic-view.

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

https://stackblitz.com/edit/po-ui-z3uptv?file=src%2Fapp%2Fapp.component.html

Passos para reproduzir:
1. Usar o po-dynamic-view

#### Qual o comportamento atual?

Os itens que são carregados sem valor aparecem, mas o valor fica em branco.

#### Que comportamento você esperava ver?

Os itens que não tivessem valor válido, não deveriam aparecer na tela.

#### Ambiente

- PO UI: 3.10
- Angular: 10.2
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @NixonAzeredo 

Obrigado pela sugestão, o Item será incluido em nosso backlog como melhoria.

**Comment by jhosefmarks** [comment]
@NixonAzeredo se você não definir os fields e usar a propriedade p-show-all-value você vai ter o resultado que você deseja. Use a propriedade p-show-all-value e passe o objeto no p-value só com as propriedades que você quer que sejam exibidas.

Outra alternativa é você usar a propriedade visible do field, no evento p-load você pode fazer uma rotina para validar os campos e mudar a propriedade de acordo com o valor.

Não vejo motivo para mudar o comportamento do componente para esconder o campo por que o mesmo está vazio.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
