### ISSUE TITLE
Adicionar a propriedade de alinhamento para o componente po-avatar

### ISSUE THREAD

**Issue by thiagogoncalves** [po-ui/po-angular#901]
#### Descrição da melhoria
O componente "po-avatar" não tem uma propriedade de alinhamento(left, center, right) da imagem. Quando colocamos numa tela um pouco maior, a imagem fica alinhada somente no lado esquerdo deixando um espaço em branco no lado direito conforme o exemplo no [stackblitz](https://po-ui-ipias7.stackblitz.io).

#### Caso de uso
Com isso conseguiríamos centralizar a imagem.

#### Informações adicionais
N/A

**Comment by jhonyeduardo** [comment]
Bom dia @thiagogoncalves 

o po-avatar é um componente isolado, você consegue posiciona-lo do jeito que precisar, veja o seu exemplo com ele centralizado.

https://stackblitz.com/edit/po-ui-hhqeuv


Qualquer dúvida estou a disposição.

**Comment by thiagogoncalves** [comment]
Jhonny, resolveu o meu problemas. Muito obrigado.
