### ISSUE TITLE
Multiselect: Não fecha as opções ao clicar fora

### ISSUE THREAD

**Issue by jota-oliveira** [po-ui/po-angular#921]
#### Qual o comportamento atual?
Ao abrir as opções do multiselect, geralmente ao clicar fora a caixinha de seleção é recolhida, mas em alguns casos isso não acontece, ainda que a configuração seja igual.

#### Ambiente

- PO UI: 4.17.0
- Angular: 11
- Browser(s):
  - [x ] Chrome
  - [x] Firefox
- Operating System:
  - [x ] Windows
  - [x ] Ubuntu

**Comment by jhonyeduardo** [comment]
boa noite @jota-oliveira 

Consegue nos passar como reproduzir a situação?

Realizei alguns testes no Firefox e não consegui reproduzir.

Fico no aguardo :)

**Comment by jota-oliveira** [comment]
Oi Jhony, teria prints para mostrar a implementação... Porque realmente, acontece em uns, e outros não e nos parece que a implementação é a mesma... serviria para você?

**Comment by jhonyeduardo** [comment]
Seria interessante um GIF para tentar entender como ocorre o problema

**Comment by alinelariguet** [comment]
Boa noite @jota-oliveira , tudo bem?

Você conseguiu simular o problema? Será que podemos encerrar essa issue?

**Comment by alinelariguet** [comment]
Entrei em contato com o Autor por outros canais de comunicação e o problema foi resolvido.
