### ISSUE TITLE
Possibilidade de desabilitar features do po-page-login

### ISSUE THREAD

**Issue by afucher** [po-ui/po-angular#925]
#### Descrição da melhoria
Gostaria de poder desabilitar algumas funcionalidades do template `po-page-login`, como por exemplo a caixa de escolha de idiomas e a dica do login (`loginHint`)

#### Caso de uso
Contextos que não precisam dessas features na tela poderiam não utilizá-las.

#### Informações adicionais
Pensei que para não ficar crescendo o número de propriedades no template, poderia ser um objeto de configuração. Outra questão é que hoje se passar a lista de idiomas parece que não mostra o dropdown de idiomas, porém isso não fica explícito no código, dificultando entendimento e leitura.

**Comment by jhonyeduardo** [comment]
Boa tarde @afucher 

A opções de idiomas, pode ser desabilitado conforme indica a propriedade `p-languages` informando um array vazio `[]`.

Já loginHint, será feito um tratamento para que caso informar valor vazio no `p-literals: { loginHint: '' }` não seja exibido o ícone.
isso se estenderá ao `rememberUserHint`.

Obrigado pela sugestão, este item será incluído em nosso backlog.

**Comment by afucher** [comment]
Olá @jhonyeduardo obrigado pela resposta.
Não existe a possibilidade de ter uma config para isso? Não me parece intuitivo passar uma string fazia no literals para desabilitar uma funcionalidade do componente. Deixar explícito no código que estou habilitando ou desabilitando uma feature me parece mais lógico.

**Comment by jhonyeduardo** [comment]
Geralmente temos essas configurações para habilitar/desabilitar, porém neste caso existem propriedades sobre as mesmas no componente, acredito que seria atributos a mais como você mesmo comentou, sendo que poderíamos apenas informar que não tem valor e com isso não exibir o dado.

De qualquer forma vou levar para o time e decidirmos em conjunto.

Obrigado pela sugestão.

**Comment by jhonyeduardo** [comment]
Bom dia
Melhoria liberada na versão [5.13.0](https://github.com/po-ui/po-angular/blob/master/CHANGELOG.md)
