### ISSUE TITLE
Quebra do breadcrumb afetando layout da página

### ISSUE THREAD

**Issue by yanric2000** [po-ui/po-angular#931]
#### Descrição da melhoria
O breadcrumb do componente PoPageDefaultComponent, quando recebe itens com um texto muito grande, acaba realizando uma quebra de linha e afetando tanto o título quanto as ações da página, vide print: [https://imgur.com/a/RIkpWeM](https://imgur.com/a/RIkpWeM)

#### Caso de uso
O componente é fundamental para um sistema que utilize a biblioteca como base.

#### Informações adicionais
Uma possível solução seria adicionar reticências quando o texto estiver muito grande, essa necessidade poderia ser determinada ao iniciar o componente, já que(pelo menos na minha visão) não é esperado que o usuário fique redimensionando a tela, vide print da ideia: [https://imgur.com/a/Hvjd42n](https://imgur.com/a/Hvjd42n)

**Comment by jhonyeduardo** [comment]
Bom dia @yanric2000 

Vamos adicionar esse item em nosso backlog, obrigado!
