### ISSUE TITLE
po-lookup - Envio de headers HTTP

### ISSUE THREAD

**Issue by matheus-newtech** [po-ui/po-angular#932]
#### Descrição da melhoria
Possibilidade de envio de headers HTTP na chamada do serviço informado em p-filter-service

#### Caso de uso
Para cenários onde o desenvolvimento e/ou execução da aplicação acontece em ambiente diferente daquele onde os serviços estão sendo executados, a impossibilidade de enviar os headers impede processos como a autenticação.

O problema pode ser contornado com a criação de uma classe que extende PoLookupFilter, mas isso obriga a criação de código desnecessário.

**Comment by jhonyeduardo** [comment]
Boa tarde @matheus-newtech 

Para adicionar headers de autenticação, geralmente é utilizado Interceptors, já realizou este teste?

**Comment by mantonelli** [comment]
Com interceptors o problema foi resolvido. Obrigado!
