### ISSUE TITLE
Instalação PO-UI : Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by everson-almeida** [po-ui/po-angular#935]
#### Qual o comportamento atual?
Durante o passo a passo de instalação/configuração do PO-UI, para o passo 2, adicionando pacote de componentes, ocorre o seguinte erro:

>   _"PS F:\workspace\TOTVS\Portinari\PO-Protheus\po-protheus> ng add @po-ui/ng-components
>   Skipping installation: Package already installed
>   ? Would you like to configure Sidemenu? Yes
>   Cannot read property 'kind' of undefined"_

#### Ambiente
{
  "name": "po-protheus",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "watch": "ng build --watch --configuration development",
    "test": "ng test"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~12.0.1",
    "@angular/common": "~12.0.1",
    "@angular/compiler": "~12.0.1",
    "@angular/core": "~12.0.1",
    "@angular/forms": "~12.0.1",
    "@angular/platform-browser": "~12.0.1",
    "@angular/platform-browser-dynamic": "~12.0.1",
    "@angular/router": "~12.0.1",
    "@po-ui/ng-components": "^5.4.0",
    "rxjs": "~6.6.0",
    "tslib": "^2.1.0",
    "zone.js": "~0.11.4"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~12.1.1",
    "@angular/cli": "~12.1.1",
    "@angular/compiler-cli": "~12.1.1",
    "@types/jasmine": "~3.6.0",
    "@types/node": "^12.11.1",
    "jasmine-core": "~3.7.0",
    "karma": "~6.3.0",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage": "~2.0.3",
    "karma-jasmine": "~4.0.0",
    "karma-jasmine-html-reporter": "^1.5.0",
    "typescript": "~4.2.4"
  }
}
- Operating System:
  - [ x ] Windows
  - [ ] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Boa tarde @everson-almeida 

Qual é a versão do Angular CLI?

Você pode ver através do comando `ng version`

**Comment by jhonyeduardo** [comment]
Não conseguimos simular o problema, Att.

**Comment by everson-almeida** [comment]
Boa tarde pessoal,
Perdão, eu não tinha observado a movimentação dessa issue.
Apenas para dar um retorno, eu resolvi essa questão, realizando a instalação padrão, sem seguir a "receita de bolo" presente na documentação do framework.

Abraço a todos.
