### ISSUE TITLE
<cache>: <armazenando cache indesejado>

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#937]
#### Reprodução

Utilize StackBlitz (https://stackblitz.com/edit/po-ui) para reproduzir o bug relatado na issue.

Passos para reproduzir:
1. 
2. 
3. 

#### Qual o comportamento atual?
O projeto em po-ui está armazenando cache e não atualiza a aplicação quando aplicamos a atualização, causando assim diversos problemas no nosso sistema.

#### Que comportamento você esperava ver?
Que não armazenasse as páginas e dados em cache e que atualizasse quando necessário

#### Ambiente

- PO UI: 
- Angular: 
- Browser(s):
  - [x] Chrome
  - [x] Firefox
  - [x] Edge
  - [x] Safari
  - [x] IE 11
  - [x] Outros
- Operating System:
  - [x] Windows
  - [ ] macOS
  - [x] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

O `@po-ui/ng-components` não tem tratamento para isso, o browser muitas vezes faz automático.

Verifique configurações do seu projeto para desabilitar caso precise.
