### ISSUE TITLE
PoPageLoginComponent: Notificação não customizável

### ISSUE THREAD

**Issue by leticiatomasio** [po-ui/po-angular#942]
No PO Page Login, quando trabalhamos a autenticação integrada com o back através do (p-login-submit) e há um erro na requisição, o componente PoPageLoginComponent automaticamente imprime o erro em uma notificação do tipo error, direção bottom, como a seguir:

![Captura de tela de 2021-07-22 11-26-59](https://user-images.githubusercontent.com/69875352/126656541-f243c696-c36a-4041-b023-c1e32cc9cdc2.png)

Sugiro que a lib dê autonomia ao desenvolvedor de customizar a notificação como bem entender, desde a mensagem em exibição até a direção bottom ou top e a função de uso success, warning, error, information.. Sugiro também que o desenvolvedor tenha a opção de não exibir a notificação, caso não queira. Acredito que essas possibilidades tornariam o componente mais conveniente.

#### Caso de uso
Customizar a notificação facilitaria manter o padrão estético do projeto.

**Comment by jhonyeduardo** [comment]
Olá @leticiatomasio 

Possuímos um Interceptor que faz este trabalho para nós, veja a documentação: [PoHttpInterceptor](https://po-ui.io/documentation/po-http-interceptor)

Tem como informar a mensagem de erro que deseja retornar, até como detalhes deste erro, veja `Mensagens de erro 4xx ou 5xx` 
Também tem como fazer o Interceptor ignorar este erro, através do Header `PO-X-No-Error`.

Possuímos a issue #692 para permitir posicionar de forma global a posição da notificação, que está em backlog.

Qualquer dúvida estou a disposição.

**Comment by leticiatomasio** [comment]
Muito obrigado, @jhonyeduardo! Não estava familiarizada com o PoHttpInterceptor. O X-PO-No-Message funcionou bem aqui. :smile:
