### ISSUE TITLE
Trilha PO UI

### ISSUE THREAD

**Issue by paulomarcelo** [po-ui/po-angular#945]
Eu encontrei estas duas trilhas no Alura nomeadas como PO UI:
https://cursos.alura.com.br/meu-plano-de-estudos-danilo-gomes0-1596466610077-p59468

https://cursos.alura.com.br/totvs-angular-po-ui-thiago-andrrade-1611788657590-p113863

Gostaria da sua opinião sobre as trilhas, se realmente pode me ajudar a desenvolver aplicações em PO UI para integrar com o nosso ERP que é o Protheus

**Comment by jhonyeduardo** [comment]
Boa tarde @paulomarcelo 

São ótimas trilhas, após finaliza-las você com certeza estará apto a construir aplicações e utilizar a biblioteca PO UI.

**Comment by paulomarcelo** [comment]
Obrigado @jhonyeduardo pela pronta resposta.
