### ISSUE TITLE
PO Page Login: Permitir que os inputs sofram customizações programaticamente

### ISSUE THREAD

**Issue by fabiomirandaa** [po-ui/po-angular#951]
#### Descrição da melhoria
Gostaria que no componente de template da página de login os inputs fossem expostos publicamente, permitindo que fosse possível passar qualquer que seja a configuração para eles quando houver necessidade.

#### Caso de uso
Caso de exemplo: O template de login, contempla por padrão o uso de email para login. Porém, caso seja necessária outra forma de login, não é possível adicionar uma máscara no input de login como, por exemplo, uma máscara de CPF. Isso poderia ser facilmente modificado programaticamente se ao usar o viewChild no componente do template de login, houvesse entre as propriedades do componente um viewChild de cada input. 

Se houver essa exposição dos inputs com viewChild, esse caso poderia ser feito mais ou menos assim:
```typescript
...
@ViewChild(PoPageLoginComponent, { static: true }) poPageLogin: PoPageLoginComponent;
...

private setCPFMaskInLoginInput() {
  this.poPageLogin.poLoginComponent.mask = this.cpfMask;
  this.poPageLogin.poLoginComponent.maskFormatModel = true;
}
 
```   

#### Informações adicionais
A ideia é dar a facilidade de um template já pré-configurado pros usuários da Lib e ao mesmo tempo a liberdade de adaptação para os casos onde o cenário padrão não atende. Se possível, posso ajudar com essa demanda em um pull request.

**Comment by jhonyeduardo** [comment]
Bom dia @fabiomirandaa 

Obrigado pela sugestão de melhoria, vamos adicionar em nosso backlog.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
