### ISSUE TITLE
Uma sugestão -Gantt

### ISSUE THREAD

**Issue by ammarcossbo** [po-ui/po-angular#955]
#### Descrição da melhoria
Para nós que trabalhamos com Protheus  é muito difícil encontrar uma ferramenta de Gantt interativa.

#### Caso de uso
Gerenciamento de Projetos, Planejamento e Controle de Produção, e uma infinidade de possibilidades que absorvem esse tipo de gráfico, além dos próprios softwares da Totvs. 

#### Informações adicionais
Adicione um outro contexto ou imagens sobre a melhoria.
![image](https://user-images.githubusercontent.com/73861707/127714511-28d97f17-6eab-4421-81df-9218d38a0d98.png)
https://support.monday.com/hc/article_attachments/360020536899/image_2.png

**Comment by jhonyeduardo** [comment]
Bom dia @ammarcossbo 

Vamos adicionar em nosso backlog e avaliar a criação deste componente, obrigado.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
