### ISSUE TITLE
Novas Cores

### ISSUE THREAD

**Issue by ghost** [po-ui/po-angular#959]
Bom dia pessoal.

É possível adicionar mais opções de cores no PO-UI ?
Hoje temos 12 cores, 01..12 mas necessitamos de 16 (00..15) semelhantes ao que utilizamos no Datasul.
Quando tentamos adicionar uma cor na "PoTableColumn" (Ex : { property: 'col1', label: 'Like', type: 'string', color: 'color-14' }) que não existe, ele troca por 'color-01'.

Vocês poderiam manter as cores que hoje são padrões e colocar para as novas uma cor default (#000000 - preto);
Ai cada um pode definir nas variáveis do tema quais seriam as cores adotadas.

Muito obrigado!

#### Caso de uso
Padronizacao das cores com o que é utilizado no Datasul. O usuário continuaria vendo as mesmas cores na versão PO-UI.

#### Informações adicionais
Cores do Datasul
![image](https://user-images.githubusercontent.com/87096759/128196840-89dfdf6e-28d2-4f3d-91dc-e23d036d2f9a.png)

Lista das cores Datasul
:root {
    --color-00: #000000;
    --color-01: #000083;
    --color-02: #047e01;
    --color-03: #00827d;
    --color-04: #7e0105;
    --color-05: #800080;
    --color-06: #7f8001;
    --color-07: #808080;
    --color-08: #c0c0c0;
    --color-09: #0000fe;
    --color-10: #00ff01;
    --color-11: #01ffff;
    --color-12: #fe0000;
    --color-13: #ff00fd;
    --color-14: #ffff01;
    --color-15: #ffffff;
}

**Comment by jhonyeduardo** [comment]
Boa tarde @jose-castro-gs 

Vamos adicionar no backlog e avaliar a melhor forma para tratar essas cores, obrigado pela sugestão.

**Comment by alinelariguet** [comment]
Serão definidas as cores utilizadas na tabela no estudo do AnimaliaDS.
