### ISSUE TITLE
table: nova propriedade PoTableColumn.sortable

### ISSUE THREAD

**Issue by jose-castro-gs** [po-ui/po-angular#960]
Bom dia pessoal.

Na interface "PoTableColumn" é possivel colocar uma propriedade "notSort: boolean = false (opcional)" para que a coluna não tenha opção de ordenação quando "p-sort = true" e "notSort = true".

Muito obrigado!

#### Caso de uso
Ajudaria em muito quando temos varias colunas e algumas delas são colunas "calculadas" que não são ordenáveis. 
Isso evitaria de chamar o evento "p-sort-by" para colunas que não tem ordenação server-side (chamadas de api's externas).
O usuário não teria a false impressão que pode ordenar a coluna, mesmo ela não sendo ordenável.

#### Informações adicionais
![image](https://user-images.githubusercontent.com/87096759/128200245-b7fcd8ad-aa88-4d93-8edd-bb42ee9160b6.png)

Neste caso teríamos  Status/Estabelecimento/Serie como "notSort=true" na PoTableColumn
Ex: { property: 'status', label: 'Status', type: 'label', notSort: true, ... }

**Comment by jhonyeduardo** [comment]
Boa tarde @jose-castro-gs 

Obrigado pela sugestão, é  uma ótima oportunidade de contribuição, fica nossa dica: https://po-ui.io/guides/development-flow

De qualquer forma, adicionaremos a mesma em nosso backlog, obrigado.

**Comment by jose-castro-gs** [comment]
Bom dia @jhonyeduardo 

Implementação realizada com sucesso. Iremos subir em breve um PR :)
Nova propriedade "sortable : false" (default = true) faz com que a coluna não seja ordenável.

![image](https://user-images.githubusercontent.com/87096759/128866676-e0da8f63-15c6-4dfb-98b9-fdff9ee695fd.png)
![image](https://user-images.githubusercontent.com/87096759/128866717-17670b4b-dfe5-4174-8bcd-7e8a0ff93014.png)

**Comment by jhonyeduardo** [comment]
Obrigado pela contribuição, será liberada na release 5.13.0
