### ISSUE TITLE
Page List - nova propriedade 

### ISSUE THREAD

**Issue by ghost** [po-ui/po-angular#966]
Bom tarde pessoal.

No componente Page List podemos ter mais que 3 botões ativos, sendo determinado pela nova propriedade
p-max-visible-action-buttons="number", aonde o default continua sendo 3, mas podendo variar de 2 a 10 botões visíveis. Depois do máximo alcançado, é feito o dropdown das actions.
Caso o numero seja < 2 ou > 10, será assumido os limites (2 a 10).

Caso de uso
Podemos ter mais que 3 botões visíveis, ajudando em muito a interação do usuário com a aplicação.

Informações adicionais
![image](https://user-images.githubusercontent.com/87096759/128762762-832946bb-be12-4c82-a1f9-9da315bff04c.png)

Na pagina de exemplos (Lab)
![image](https://user-images.githubusercontent.com/87096759/128762945-6a265cca-a8a0-486f-99ce-4665b2cdab5c.png)
![image](https://user-images.githubusercontent.com/87096759/128763042-799f59af-0298-415a-ae44-e3abc07b4814.png)

Configurado com 10
![image](https://user-images.githubusercontent.com/87096759/128763208-a8873d27-4240-4331-803e-8b3a6a0bf687.png)
![image](https://user-images.githubusercontent.com/87096759/128763289-89f41561-9eb3-4185-a5e3-c064f01b3ee1.png)

O exemplo de lab como também os testes já foram alterados para suportar as mudanças.
Em breve subiremos para um PR :)
Abraços

**Comment by jhonyeduardo** [comment]
Boa noite Jose, vamos analisar sua solicitação em conjunto com equipe de UX para avaliar esta adesão, pois também precisamos manter os componentes com usabilidade.

A parte de desenvolvimento, como implementar podemos verificar após a conclusão da melhoria proposta.

Obrigado pela sugestão.

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
