### ISSUE TITLE
table column - color

### ISSUE THREAD

**Issue by danielsilvalima1996** [po-ui/po-angular#97]
### Boa tarde!

é possível adicionar mais opções de cores no **component po-table**, na propriedade **color**?

hoje o mesmo conta com 12 cores, mas eu necessitava de opções semelhantes ao que utilizo no Protheus como preto, branco e cinza.

**obrigado!**

**Comment by jhonyeduardo** [comment]
Bom dia Daniel

Atualmente não é possível definir outras cores,

Vamos adicionar este item em nosso backlog e o PO irá avaliar sua sugestão,
qualquer dúvida estou a disposição!

**Comment by jhosefmarks** [comment]
@danielsilvalima1996 obrigado pela sugestão, vamos incluir em nosso backlog.

**Comment by aksilvaa** [comment]
Boa Tarde @jhonyeduardo e @jhosefmarks !

Estou enfrentando a mesma  situação do colega acima, houve algum avanço em relação a esse caso?

Pois estou adaptando algumas tela do Protheus para o Portinari e preciso inserir alertas na tabela, segue abaixo imagem demonstrando um exemplo da utilização das cores :

![Pedidos-venda-list-legenda](https://user-images.githubusercontent.com/50679891/67028522-d4340e80-f0e1-11e9-900b-543ea11167b0.PNG)

**Comment by ricardo-mello** [comment]
Galera, eu abri um PR que permite a customização das colunas da tabela utilizando templates. Acredito que isso resolve o problema das cores já que vocês vão poder adicionar qualquer conteúdo, sem precisar mexer no guideline do Portinari.

**Comment by jhosefmarks** [comment]
É possível customizar suas colunas, veja a PR #454
