### ISSUE TITLE
Ícone de outros tipos de arquivo

### ISSUE THREAD

**Issue by EduardaDalmas** [po-ui/po-angular#976]
#### Descrição da melhoria
Atualmente temos na galeria do po-ui o icone de  documento PDF, seria muito útil se tivesse também o ícone de txt e de csv.

#### Caso de uso
usuários teriam fácil identificação de outros tipos de documento

#### Informações adicionais
![image](https://user-images.githubusercontent.com/58361652/129962353-a77055c2-fe32-4038-9787-d44a28eb8f1e.png)
Seria muito útil para quando temos um tipo de documento em mais de um formato.

**Comment by jhonyeduardo** [comment]
Bom dia @EduardaDalmas 

Vou solicitar a equipe a criação destes ícones, mas o PoTable agora permite informar ícones de outras fontes caso necessário.

**Comment by EquipeFB** [comment]
@jhonyeduardo  boa tarde, estou precisando usar icones de outras fontes conforme vc citou acima, teria algum exemplo de como usar?

**Comment by renanarosario** [comment]
Após uma análise mais detalhada e considerando as recentes mudanças na nossa estratégia, decidimos encerrar esta issue. Agradecemos a todos que contribuíram com suas análises e sugestões. 
Caso seja necessário, uma nova ISSUE será aberta conforme a evolução das nossas necessidades.

Agradecemos pela compreensão.
