### ISSUE TITLE
po-chart: gráfico com mais de 12 itens desaparece da tela

### ISSUE THREAD

**Issue by camposmichel** [po-ui/po-angular#986]
#### Reprodução

Evidência:
<img width="1004" alt="Captura de Tela 2021-08-25 às 11 18 47" src="https://user-images.githubusercontent.com/9743905/130818078-cce4b172-b737-4a60-a384-612eb01792d1.png">

StackBlitz:
https://stackblitz.com/edit/angular-ivy-cyffd8?file=src%2Fapp%2Fapp.component.ts

Passos para reproduzir:
1. Utilizar o po-chart
2. O array de dados deve conter mais de 13 itens

#### Qual o comportamento atual?
O gráfico está desaparecendo.

#### Que comportamento você esperava ver?

Algo semelhante ao chart.js
<img width="654" alt="Captura de Tela 2021-08-25 às 12 23 35" src="https://user-images.githubusercontent.com/9743905/130818870-13864a32-417c-4309-91d4-b2172fe04d30.png">

#### Ambiente

- PO UI: 5.9.0
- Angular: 12.1.0
- Browser(s):
  - [x] Chrome
  - [ ] Firefox
  - [x] Edge
  - [ ] Safari
  - [ ] IE 11
  - [ ] Outros
- Operating System:
  - [x] Windows
  - [x] macOS
  - [ ] Ubuntu
  - [ ] Outros

**Comment by jhonyeduardo** [comment]
Bom dia @camposmichel 

Os gráficos atualmente tem suporte para 12 series, vamos ajustar para permitir, porém poderá ser duplicado as cores. Para utilizar corretamente será preciso definir a cor via PoChatSerie.color.

Esta issue será adicionado no backlog.

**Comment by rogelho** [comment]
> Bom dia @camposmichel
> 
> Os gráficos atualmente tem suporte para 12 series, vamos ajustar para permitir, porém não terá definição de cores. Para utilizar corretamente será preciso definir a cor via PoChatSerie.color.
> 
> Esta issue será adicionado no backlog.

A limitação hoje ocorre devido ao "PoDefaultColors" ter apenas 12 cores, não? https://github.com/po-ui/po-angular/blob/master/projects/ui/src/lib/services/po-color/po-colors.constant.ts

Nesse caso o mais correto ao meu ver é permitir ao usuário passar uma colorPalette e usar essa paleta ao invés do PoDefaultColors

**Comment by jhonyeduardo** [comment]
Olá @rogelho 

É uma opção também, vamos avaliar a implementação e quando possível liberar na biblioteca, obrigado!

**Comment by rogelho** [comment]
> Olá @rogelho
> 
> É uma opção também, vamos avaliar a implementação e quando possível liberar na biblioteca, obrigado!

Beleza Jhony, eu fiz essa correção localmente, vi a que a issue DTHFUI-5314 ainda está no backlog lá no Jira, se for o caso avise que faço o PR aqui, valeu

**Comment by jhonyeduardo** [comment]
Fique a vontade @rogelho, contribuições são muito bem vindas :)

**Comment by wsteixeira** [comment]
Olá @alinelariguet,

Esta issue já foi resolvida na PR fix(chart): exibe grafico após a 12 série #1232

**Comment by alinelariguet** [comment]
Essa correção foi feita e entregue a na versão 6.7.0
