### ISSUE TITLE
PoPageDynamicTable: Objetos do tipo PoPageDynamicTableCustomAction deveriam aceitar ícone

### ISSUE THREAD

**Issue by luizmariz** [po-ui/po-angular#987]
#### Descrição
Deveria ser possível definir ícones para as custom actions do PoPageDynamicTable, definidas pela interface PoPageDynamicTableCustomAction, o PoPageDynamicSearch já permite isso e essa limitação acaba gerando inconsistências de layout.

#### Caso de uso

.ts
```
readonly customActions: PoPageDynamicTableCustomAction[] = [
    {
      label: 'Home',
      action: () => console.log('Você clicou na home'),
      icon: 'po-icon-home',
    }
];
```

.html
```
<po-page-dynamic-table
    [p-page-custom-actions]="customActions"
></po-page-dynamic-table>
```

#### Informações adicionais
Atualmente fica impossível manter o padrão determinado pelo ux, com ícones nos botões, entre as telas que utilizam o `po-page-dynamic-search` e as que utilizam o `po-page-dynamic-table`  😭

Ps.: Existem outras propriedades do `po-table` e `po-page-dynamic-search` que o `po-page-dynamic-table` não extende ou reflete (Apesar de ser uma composição desses componentes). Seria legal poder ter as mesmas funcionalidades desses componentes inseridas no dynamic table.

**Comment by jhonyeduardo** [comment]
Bom dia @luizmariz 
Vamos adicionar sua solicitação ao nosso backlog.

Este é um item muito bacana para contribuição, pois é simples de ser implementado, veja nosso [guia de contribuição](https://po-ui.io/guides/development-flow), fica a dica :D
